### ISSUE TITLE
How to download video in MongoTv

### ISSUE THREAD

**Issue by neciszhang** [iawia002/annie#105]
下载芒果TV在报错
annie -f default https://www.mgtv.com/b/322865/4352046.html
错误提示：
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/iawia002/annie/extractors.mgtvM3u8(0xc42054a000, 0x21b, 0x2c0, 0x1295040, 0xc4202e2080, 0x0)
	/private/tmp/annie-20180412-3232-9fqw6g/annie-0.6.5/src/github.com/iawia002/annie/extractors/mgtv.go:53 +0x2b4
github.com/iawia002/annie/extractors.Mgtv(0x7ffeefbffc79, 0x2a, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/private/tmp/annie-20180412-3232-9fqw6g/annie-0.6.5/src/github.com/iawia002/annie/extractors/mgtv.go:92 +0x6fb
main.main()
	/private/tmp/annie-20180412-3232-9fqw6g/annie-0.6.5/src/github.com/iawia002/annie/main.go:71 +0x28d

**Comment by iawia002** [comment]
@neciszhang 0.6.6，注意一下 https://github.com/iawia002/annie#multi-thread

> Use too many threads in mgtv download will cause HTTP 403 error, we recommend setting the number of threads to 1.

最好 `annie -n 1 ...`

**Comment by neciszhang** [comment]
@iawia002 Thanks you!
