### ISSUE TITLE
It is recommended to support configurable download threads

### ISSUE THREAD

**Issue by luny217** [iawia002/annie#108]
类似#82，线程过多会导致下载失败，建议改成可配置线程数。大概改了下，测了下爱奇艺可以
`	var wg sync.WaitGroup
	ParallelNum := 0
	// multiple fragments
	parts := []string{}
	for index, url := range data.URLs {
		partFileName := fmt.Sprintf("%s[%d]", title, index)
		partFilePath := utils.FilePath(partFileName, url.Ext, false)
		parts = append(parts, partFilePath)		

		if(ParallelNum + 1 > config.ParallelNum){			
			wg.Wait()
			ParallelNum = 0
		}

		ParallelNum = ParallelNum + 1		
		wg.Add(1)
		go func(url URLData, refer, fileName string, bar *pb.ProgressBar) {
			defer wg.Done()
			data.urlSave(url, refer, fileName, bar)
		}(url, refer, partFileName, bar)			
	}
	wg.Wait()
	bar.Finish()
`

**Comment by iawia002** [comment]
确实，`goroutine` 过多也不好，这个我会限制一下，改成可配置。

但是现在只有芒果 TV 会对过多的线程同时下载报 403，#82 的爱奇艺报错应该不是因为这个

**Comment by luny217** [comment]
实测爱奇艺的出错确实是跟线程数有关，开多了，下的过程中，很大概率会被踢掉

**Comment by iawia002** [comment]
那我尽快把这个改了，爱奇艺的视频分得太细了，线程开得太多了

**Comment by iawia002** [comment]
我下爱奇艺倒是没遇到过这种问题

**Comment by luny217** [comment]
如果开了几百上千个线程，服务器不做限制，倒也奇怪了不是，小视频文件还好，几百兆上G的，基本下不完

**Comment by luny217** [comment]
另外，做好能把视频列表下载也加上，下个剧集还是方便不少，简单用递归做了下，另外出错处理要改下，尽量不要panic和exit
`
html := request.Get(url, iqiyiReferer)
	doc := parser.GetDoc(html)
	doc.Find("ul.album-numlist").Find("li").Each(func(i int, sel *goquery.Selection) {
		href, _ := sel.Find("a").Attr("href")
		if href != "" {
			fmt.Printf("--------%d %s\n",i ,href)
			Iqiyi(href)
		}		
	})
`

**Comment by iawia002** [comment]
列表下载空了再做吧，循环就行了，没必要递归

**Comment by iawia002** [comment]
> 另外出错处理要改下，尽量不要panic和exit

关于这个，有什么更好的建议吗，下载错了直接重试？有些情况，不退出逻辑会乱的

**Comment by luny217** [comment]
重试就可以，最多限制一下重试次数，可能会浪费一些下载流量（删掉当前下载的临时文件重来），但是总比断了，还需要人工干预强。

**Comment by iawia002** [comment]
自动重试这个我也前也想过，只是还没想到好的实现方法，我先提个 issue 备忘
