### ISSUE TITLE
可以支持腾讯视频么？

### ISSUE THREAD

**Issue by xkser** [iawia002/annie#112]
希望能支持腾讯视频

**Comment by iawia002** [comment]
#99 
#101

**Comment by iawia002** [comment]
0.7.4

**Comment by xkser** [comment]
试了一下。第一下下载200k。然后暂停下载。速度就快起来了。抓包发现refer变了，不知道是不是这个原因。不过还是很感谢作者第一时间通知以及辛苦的劳作。我手机上没有go。只有python器。我尝试改了you-get的qq那部分。保证了下载分段视频的url和header一致。结果还是限速。好奇怪哦。看上去没啥区别。目前看来只能用电脑的annie下载了。
还想说两个问题
1.vip加cookie。好像是可以直接加cookie的。之前Lulu限速下载。我家来cookie可以下载。当然速度还是狗屎
2.有可能使用-i指令得到m3u8播放链接么
