### ISSUE TITLE
download error

### ISSUE THREAD

**Issue by fyzzy1943** [iawia002/annie#115]
if i use cookie file:

panic: Get https://www.bilibili.com/bangumi/play/ep202005: net/http: invalid header field value "sid=123;\n" for key Cookie

--
if I use annie -c "sid=ihhj4p7k;" -i ep202005, it can work well

**Comment by iawia002** [comment]
try to remove the '\n' from the cookie file

**Comment by fyzzy1943** [comment]
no '\n' in cookie file. just 'sid=123;'

but if I wrote `annie -c "sid=ihhj4p7k;\n" -i ep202005`, It can work;

**Comment by iawia002** [comment]
> no '\n' in cookie file. just 'sid=123;'

you sure? No `\n` means only one line in the entire file

**Comment by iawia002** [comment]
@fyzzy1943 any response? I'm gonna close this issue

**Comment by fyzzy1943** [comment]
sorry to late, too many things these days.

**Comment by iawia002** [comment]
That's strange, can you upload the cookie file that reproduces this bug? I wanna take a look.

**Comment by fyzzy1943** [comment]
yes,
https://github.com/fyzzy1943/temp/blob/master/bilibili.cookie this is file.

**Comment by iawia002** [comment]
@fyzzy1943 you are really kidding with me. There are two lines in your cookie file. Open it in other editors, you will see this:

![](https://user-images.githubusercontent.com/9134003/39393125-fbf06e40-4af3-11e8-9e46-d5f1705316a8.png)

**Comment by fyzzy1943** [comment]
so sorry, I don't know why vim can not see the last "\n". It work now, thank you. :P
