### ISSUE TITLE
最新版本1.x兆的exe，都是zip又打一次包的？？

### ISSUE THREAD

**Issue by Justsoos** [iawia002/annie#119]
win 10下载下来zip打开后，再
```
File .\annie.exe
.\annie.exe: Zip archive data, at least v2.0 to extract
```
压缩率97%
这是啥高科技？ 还得再解压这 annie.exe  文件一次，能用。

ubuntu下更奇怪，
```
file ./annie
./annie: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, stripped
```
不能用
https://github.com/iawia002/annie/releases/tag/0.6.8

**Comment by iawia002** [comment]
一个叫 upx 的工具，我测过 mac 的，没问题

**Comment by iawia002** [comment]
我下个版本先不用这个工具

**Comment by iawia002** [comment]
@Justsoos 能帮忙试一下这两个新包吗

[annie_0.6.9_Windows_64-bit.zip](https://github.com/iawia002/annie/files/1949539/annie_0.6.9_Windows_64-bit.zip)
[annie_0.6.9_Linux_64-bit.tar.gz](https://github.com/iawia002/annie/files/1949541/annie_0.6.9_Linux_64-bit.tar.gz)

**Comment by iawia002** [comment]
下面的是未压缩版本的

[annie_0.6.9_Linux_64-bit.tar.gz](https://github.com/iawia002/annie/files/1949545/annie_0.6.9_Linux_64-bit.tar.gz)
[annie_0.6.9_Windows_64-bit.zip](https://github.com/iawia002/annie/files/1949546/annie_0.6.9_Windows_64-bit.zip)

**Comment by Justsoos** [comment]
annie_0.6.9_Windows_64-bit.zip 可用，0.6.8
```
file annie.exe
annie.exe: PE32+ executable (console) x86-64 (stripped to external PDB), for MS Windows

.\annie.exe -v
annie: version 0.6.8, A fast, simple and clean video downloader.
```
annie_0.6.9_Linux_64-bit.tar.gz  **ubuntu不可用** sha1sum: 7246310fdafe75c54b395c97b8fee3fe7a81349f
```
# file annie
annie: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, stripped
# ./annie
-bash: ./annie: cannot execute binary file: Exec format error
```

**Comment by Justsoos** [comment]
未压缩版 annie_0.6.9_Linux_64-bit.tar.gz 
ubuntu 可用，
sha1sum: 609d746ac1382b402ee41650407bf08847116b02
win 那个未压缩也可用

**Comment by Justsoos** [comment]
补充下，sha1 都是对最原始的 annie 文件进行。压缩包用 winrar 测，没有发现错误。

**Comment by iawia002** [comment]
@Justsoos 感谢测试

看来是 upx 压缩的 bug，或者我们用的姿势不对

**Comment by Justsoos** [comment]
https://github.com/Microsoft/WSL/issues/330
找到了，是 upx 和 wsl 兼容问题bug
