### ISSUE TITLE
能支持断点续传吗

### ISSUE THREAD

**Issue by dxsweet** [iawia002/annie#121]
希望能修改下，写个判断，如果某个文件已经下载完了
如果中间网路断开后，重新开始任务时
不要再重新下载了
这个应该很简单了
希望能给个支持

**Comment by iawia002** [comment]
这个是支持的

https://github.com/iawia002/annie#resume-a-download

如果一个文件已经下载完或者下载到一半之类的，只要那个文件还在你执行 `annie ...` 的目录下，就不会再重新下载

**Comment by aohanhongzhi** [comment]
> 这个是支持的
> 
> https://github.com/iawia002/annie#resume-a-download
> 
> 如果一个文件已经下载完或者下载到一半之类的，只要那个文件还在你执行 `annie ...` 的目录下，就不会再重新下载

有些不是ctrl + c 停止的，可能是网络原因。
