### ISSUE TITLE
希望有跳过错误的功能，下载不了的跳过，接着下载下一个，主要在list里面用。

### ISSUE THREAD

**Issue by heavengod** [iawia002/annie#123]
谢谢。

**Comment by iawia002** [comment]
这和现在的逻辑有点冲突，现在为了方便，下载报错的直接退出了。目前只能你手动重新下载一下，我再看看有没有什么解决方法

#109

**Comment by heavengod** [comment]
能否加一个选项，比如说--skip-error，这样就可以跳过报错，继续下去，因为这个问题主要是发生在下载list里面，重新下载还是没法跳过就中断了。

谢谢。

**Comment by iawia002** [comment]
> 重新下载还是没法跳过就中断了。

这是什么意思，一个列表里面有一个怎么都下不了的视频？

**Comment by heavengod** [comment]
对，比如说Youtube的列表里面经常有无法下载的，可能是版权问题，也有可能是解析的不对等等。

**Comment by iawia002** [comment]
有没有这种列表，给我一个用来测试

**Comment by heavengod** [comment]
https://www.youtube.com/watch?v=mmM68zFnNvM&list=UUCkJ9ZToTIET2XCunyUiSzg <https://www.youtube.com/watch?v=mmM68zFnNvM&list=UUCkJ9ZToTIET2XCunyUiSzg>

**Comment by iawia002** [comment]
> 对，比如说Youtube的列表里面经常有无法下载的，可能是版权问题，也有可能是解析的不对等等。

遇到这种你说的什么版权问题的视频的时候，URL 和报错信息贴上来看看
