### ISSUE TITLE
爱奇艺 -i 为什么会出现多个质量大小不同的720p？

### ISSUE THREAD

**Issue by misaka123456** [iawia002/annie#124]
> annie -i http://www.iqiyi.com/v_19rrcm0h0w.html?vfm=2008_aldbd

 Site:      爱奇艺 iqiyi.com
 Title:     高能少年团第2季：王俊凯弹唱《告白气球》 张一山杨紫牵手合唱
 Type:      video
 Streams:   # All available quality

     [default]  -------------------
     Quality:         1280x720
     Size:            600.91 MiB (630098732 Bytes)
     # download with: annie -f default "URL"

     [1]  -------------------
     Quality:         640x360
     Size:            258.04 MiB (270575992 Bytes)
     # download with: annie -f 1 "URL"

     [21]  -------------------
     Quality:         896x504
     Size:            437.09 MiB (458324260 Bytes)
     # download with: annie -f 21 "URL"

     [96]  -------------------
     Quality:         384x216
     Size:            110.50 MiB (115871544 Bytes)
     # download with: annie -f 96 "URL"

     [14]  -------------------
     Quality:         1280x720
     Size:            1143.43 MiB (1198977520 Bytes)
     # download with: annie -f 14 "URL"

     [4]  -------------------
     Quality:         1280x720
     Size:            997.09 MiB (1045522332 Bytes)
     # download with: annie -f 4 "URL"

     [2]  -------------------
     Quality:         896x504
     Size:            540.65 MiB (566911932 Bytes)
     # download with: annie -f 2 "URL"

**Comment by iawia002** [comment]
这是爱奇艺接口返的，具体有什么差别我也不清楚
