### ISSUE TITLE
爱奇艺综艺视频720p合并时出现问题

### ISSUE THREAD

**Issue by misaka123456** [iawia002/annie#125]
Merging video parts into 高能少年团第2季：王俊凯弹唱《告白气球》 张一山杨紫牵手合唱.mp4
2018/04/29 12:38:56 exit status 1
ffmpeg version 3.4.2 Copyright (c) 2000-2018 the FFmpeg developers
  built with gcc 7.3.0 (GCC)
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-bzlib --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libmfx --enable-cuda --enable-cuvid --enable-d3d11va --enable-nvenc --enable-dxva2 --enable-avisynth
  libavutil      55. 78.100 / 55. 78.100
  libavcodec     57.107.100 / 57.107.100
  libavformat    57. 83.100 / 57. 83.100
  libavdevice    57. 10.100 / 57. 10.100
  libavfilter     6.107.100 /  6.107.100
  libswscale      4.  8.100 /  4.  8.100
  libswresample   2.  9.100 /  2.  9.100
  libpostproc    54.  7.100 / 54.  7.100
Input #0, concat, from '高能少年团第2季：王俊凯弹唱《告白气球》 张一山杨紫牵手合唱.txt':
  Duration: N/A, start: 0.000000, bitrate: 256 kb/s
    Stream #0:0: Video: h264 (High) ([27][0][0][0] / 0x001B), yuv420p(tv, bt709, progressive), 1280x720, 25 fps, 25 tbr, 90k tbn, 50 tbc
    Stream #0:1(und): Audio: eac3 ([135][0][0][0] / 0x0087), 48000 Hz, 5.1(side), fltp, 256 kb/s
[AVBSFContext @ 0000027b46bcbfa0] Codec 'eac3' (86057) is not supported by the bitstream filter 'aac_adtstoasc'. Supported codecs are: aac (86018)
Error initializing bitstream filter: aac_adtstoasc
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (copy)
    Last message repeated 1 times

**Comment by iawia002** [comment]
你不要删那些已经下载的片段文件，试一下下面这条命令会不会报错：

```
ffmpeg -y -f concat -safe -1 -i '高能少年团第2季：王俊凯弹唱《告白气球》 张一山杨紫牵手合唱.txt' -c:a copy -bsf:a aac_adtstoasc '高能少年团第2季：王俊凯弹唱《告白气球》 张一山杨紫牵手合唱.mp4'
```

**Comment by misaka123456** [comment]
对不起   我错了   目前只是这一个有问题  下载的别的视频都正常  
博主还是关闭这个问题吧  
我怕误导别人
