### ISSUE TITLE
能不能加个开关跳过已经下载且合并好的视频？

### ISSUE THREAD

**Issue by iwzoo** [iawia002/annie#127]
现在下载列表视频如果中途退出， 再下载的时候会全部重新下载， 能不能加个开关跳过已经下载完成的文件？ 

谢谢

**Comment by iawia002** [comment]
Annie 支持断点续传的，如果一个文件已经下载完或者下载到一半之类的，只要那个文件还在你执行 annie ... 的目录下，就不会再重新下载

**Comment by iawia002** [comment]
你两次下的不一样清晰度的？
还有，下次把图贴到 Github 上来

**Comment by iawia002** [comment]
我好像知道是什么情况了，我检查一下代码

**Comment by iwzoo** [comment]
@iawia002 清晰度一样的， 参数如下
annie -n 1  -p -f default https://www.bilibili.com/bangumi/play/ss20114

谢谢🙏
