### ISSUE TITLE
下载b站视频时，从下载了大概5MB往后，速度逐渐从5mb/s减小到30kb/s

### ISSUE THREAD

**Issue by modyuan** [iawia002/annie#128]

**Comment by iawia002** [comment]
ctrl c 重新下载试试

**Comment by yuansushow** [comment]
总体趋势是开始贼快。。然后之后就越来越慢，然后稳当到一个速度。下载youtube也是一样，不过最终收敛的速度不一样

**Comment by fyzzy1943** [comment]
我下B站视频也是这样
不过一般是出现在 80%-90% 这样，有时候要 Ctrl-C 好几次

**Comment by SteveYung** [comment]
B站下载列表收敛的最终速度只有100K，从10M一直降下来

**Comment by yiny0liuyin** [comment]
即使是提升线程数 依旧是稳定在1MB/s左右 
![image](https://user-images.githubusercontent.com/41265413/44852151-178cad00-ac95-11e8-8d06-bf81330c0ac1.png)

**Comment by LIUYOU2015** [comment]
差不多是同样的问题，B站会不会对于这种请求限速？

**Comment by iawia002** [comment]
我也不清楚 B 站是不是有什么机制，如果有 B 站登录过的或者大会员的 Cookie 最好都带上吧
