### ISSUE TITLE
IQIYI does not work

### ISSUE THREAD

**Issue by misaka123456** [iawia002/annie#129]
annie http://www.iqiyi.com/v_19rrcpkbdc.html

 Site:      爱奇艺 iqiyi.com
 Title:     湖南脚斗士：二胎妈妈为啥扎堆月子会所
 Type:      video
 Stream:
     [default]  -------------------
     Quality:         1280x720
     Size:            10.29 MiB (10788756 Bytes)
     # download with: annie -f default "URL"

 0 B / 10.29 MiB [--------------------------------------------------------------------------------------------]   0.00%2018/05/05 19:17:17 http://dx.data.video.qiyi.com/videos/v0/20180504/dc/ea/612a3a84ee6a30555e6e64e89b6848e3.265ts?qdv=1&qypid=1034037500_04022000001000000000_17&start=581860&end=1265616&contentlength=683756&sd=4840&qd_uid=&qd_vip=0&qd_src=3_31_312&qd_tm=1525519006884&qd_ip=718c0b78&qd_p=718c0b78&qd_k=64f69cb7c8221ea83cae494a47cc1b04&sgti=&dfp=&qd_sc=504d26d741926b4578ebbdaac1ed9ccb
2018/05/05 19:17:17 [31mHTTP error: 504[0m

**Comment by iawia002** [comment]
504 Gateway Timeout

网络问题，重试一下

**Comment by misaka123456** [comment]
我发现就爱奇艺不行   别的比如哔哩哔哩都可以 
you-get插件也是同样的问题  
我怀疑是我我前两天在学校的机房配了一下大数据服务器，动了一下设置（也就改了一下自己电脑的ip），配完之后改了回来，相关的软件全部都已经卸载，也不知道是不是这里出了什么问题

**Comment by iawia002** [comment]
那我空了调试一下

**Comment by iawia002** [comment]
爱奇艺接口返回的文件链接地址没响应，不知道是他们加了什么防护机制还是改接口了

**Comment by misaka123456** [comment]
乖巧地等着博主大大解决
