### ISSUE TITLE
[功能建议]希望列表功能能够手动选定下载哪一个视频

### ISSUE THREAD

**Issue by rocknamx8** [iawia002/annie#136]
1. 有时候想两台机器在两个地方下载，一个下载前半段，一个下载后半段
2. 经常是看了几p，然后就想把后面的下载完，但是只能全部一次下

_(:з」∠)_
总之希望能够手动选择要下的列表视频

**Comment by iawia002** [comment]
youtube-dl 那种 playlist-start/end/items 吗

**Comment by rocknamx8** [comment]
应该是

**Comment by iawia002** [comment]
0.7.2
https://github.com/iawia002/annie#download-playlist
