### ISSUE TITLE
ubuntn18.04无法打开application该文件(annie_0.6.11_Linux_64-bit.tar.gz)

### ISSUE THREAD

**Issue by Whiood** [iawia002/annie#139]

**Comment by iawia002** [comment]
你怎么打开的，具体报什么错

**Comment by Whiood** [comment]
解压，然后运行发现没反应，于是我用sudo nautilus，结果还是没反应，输入annie提示找不到Annie命令

whiood@whiood-CP17S:~$ sudo nautilus
[sudo] whiood 的密码：

(nautilus:26341): IBUS-WARNING **: 17:45:23.674: The owner of
/home/whiood/.config/ibus/bus is not root!
Nautilus-Share-Message: 17:45:24.079: Called "net usershare info" but it
failed: Failed to execute child process “net” (No such file or directory)
Too few arguments
Usage: annie [args] URLs...
  -F string
    URLs file
  -O string
    Specify the output file name
  -c string
    Cookie
  -d Debug mode
  -f string
    Select specific format to download
  -i Information only
  -j Print extracted data
  -n int
    The number of download thread (default 10)
  -o string
    Specify the output path
  -p Download playlist
  -r string
    Use specified Referrer
  -s string
    SOCKS5 proxy
  -v Show version
  -x string
    HTTP proxy


2018-05-11 17:13 GMT+08:00 L <notifications@github.com>:

**Comment by iawia002** [comment]
😢 这是命令行程序
