### ISSUE TITLE
请问cookie怎么使用？

### ISSUE THREAD

**Issue by shiping998** [iawia002/annie#141]
我看了文档annie -c "cookie" url
但是cookie怎么提取，我是爱奇艺的会员，直接从f12控制台里复制head里面的cookie用不了。想问一下怎么获取正确的cookie用于下载？谢谢

**Comment by iawia002** [comment]
看一下 #37，这个问题在那里回答得比较详细了

还有，爱奇艺需要做单独的 VIP 下载适配，现在有 cookie 也下不了 VIP 视频
