### ISSUE TITLE
这个警告信息是什么意思？

### ISSUE THREAD

**Issue by jyuan15** [iawia002/annie#142]
如何去除？

root@localhost:~/go/bin # ./annie -o /sdcard1/movies -f 3gphd https://v.youku.com/v_show/id_XMTU3NzY2NjM5Ng.html
WARNING: linker: ./annie: unused DT entry: type 0x6ffffef5 arg 0x4c4

 Site:      优酷 youku.com
 Title:     秒速5厘米 日文版 秒速5厘米 日文版
 Type:      video
 Stream:
     [3gphd]  -------------------
     Quality:         3gphd 640x360
     Size:            135.13 MiB (141694109 Bytes)
     # download with: annie -f 3gphd "URL"

 135.13 MiB / 135.13 MiB [=====] 100.00% 3.35 MiB/s 40s

**Comment by iawia002** [comment]
影响下载吗？

你什么系统，这可能是编译的二进制的问题，不影响正常使用就不管了

**Comment by Justsoos** [comment]
呵呵，高级啊，安卓上装的 linux 吧。能用就用着，一般来说，像 annie 这样简单调用的，不会出大问题。android的arm跨平台lib版本不匹配，这个错误经常出。

**Comment by jyuan15** [comment]
@iawia002 @Justsoos 谢谢解答，了解了，暂时未发现其他影响。
