### ISSUE TITLE
B站下载列表的时候特别严重，从10M下降到100K

### ISSUE THREAD

**Issue by SteveYung** [iawia002/annie#143]
B站下载列表的时候特别严重，从10M下降到100K，ctrl + c 之后，速度有所改善，无法持久，如果下载单个的话也是从10M开始下降，但是可以维持在1-2M每秒，大体可以接受，列表就不行了

**Comment by SteveYung** [comment]
嗯，差不多，网络是200M光纤

**Comment by Chigogo** [comment]
Same issue.
