### ISSUE TITLE
Add input option for overwriting the file with the same name or not

### ISSUE THREAD

**Issue by iawia002** [iawia002/annie#15]
files with the same file name but different file size

**Comment by tonyxyl** [comment]
据我所知，you-get解析b站出错了。lulu是fork了you-get，合并了一个解决b站解析的pr，但lulu存在一个问题就是一个播放列表，有多集的情况下，下载了其中任何一集，其他的因为同名问题而不能下载，需要手动改已经下载的那个名字。

**Comment by iawia002** [comment]
@tonyxyl B 站的播放列表页面结构变了，lulu 还没有更新，annie 已经更新了

**Comment by tonyxyl** [comment]
卧槽，你就是lulu啊

**Comment by iawia002** [comment]
@tonyxyl 这个头像，这个 ID，不是很明显的吗，你才发现啊哈哈哈哈哈哈
