### ISSUE TITLE
[bilibili]有部分来于第三方网站如何解析

### ISSUE THREAD

**Issue by luhy118** [iawia002/annie#154]
如https://www.bilibili.com/video/av20855552?from=search&seid=5931780740456339832
目前是解析失败，看播放界面是来自腾讯的视频，如何解析？或者找到原视频地址也行。

**Comment by iawia002** [comment]
确实没考虑过这种情况，应该获取原视频地址，然后用对应的来解析

**Comment by luhy118** [comment]
@iawia002 我分析了下，不太好找到原视频地址

**Comment by iawia002** [comment]
`vid=g0026zhrtga`

这个，腾讯视频
