### ISSUE TITLE
爱奇艺 api

### ISSUE THREAD

**Issue by selewu** [iawia002/annie#159]
下载的片段只有音频 没有视频，导致合成的也没有

**Comment by selewu** [comment]
我的是win环境，测试貌似都不行哦
http://www.iqiyi.com/v_19rr0rxt0o.html

**Comment by selewu** [comment]
就是暂停了，播放ts文件播放不了，ts文件平均600kb一个，ffmpeg用4.0和20180602-9827bb8都测试过了

**Comment by selewu** [comment]
ts文件用qq播放器播放只有音频，没有视频

**Comment by iawia002** [comment]
试一下 mpv 播放器

**Comment by selewu** [comment]
一样，只有音频

**Comment by selewu** [comment]
我用mac测试了也是一样，只有音频没有视频

**Comment by selewu** [comment]
[download_files.zip](https://github.com/iawia002/annie/files/2064994/download_files.zip)

**Comment by selewu** [comment]
Headers:     URL:         http.Header{
    "User-Agent":      {"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.146 Safari/537.36"},
    "Accept":          {"text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"},
    "Accept-Charset":  {"UTF-8,*;q=0.5"},
    "Accept-Encoding": {"gzip,deflate,sdch"},
    "Accept-Language": {"en-US,en;q=0.8"},
    "Referer":         {"http://www.iqiyi.com/v_19rrc654uc.html"},
}

http://data.video.qiyi.com/videos/v0/20180417/2e/db/1fef815a82a926b007169418a43924be.265ts?qdv=1&qypid=999353000_04022000001000000000_17&start=4072268&end=4726132&contentlength=653864&sd=35560&qd_uid=&qd_vip=0&qd_src=3_31_312&qd_tm=1527944018308&qd_ip=3df22a5a&qd_p=3df22a5a&qd_k=968250d4f014dcd4795ffc047ca3021d&sgti=&dfp=&qd_sc=047351398e5a0a6235d4fff038150911
 102.76 KiB / 904.43 MiB [>---------------------------------------------------------------]   0.01% 527.78 KiB/s 27m34sMethod:      URL:         Status Code: GET
http://data.video.qiyi.com/videos/v0/20180417/2e/db/1fef815a82a926b007169418a43924be.265ts?qdv=1&qypid=999353000_04022000001000000000_17&start=2150156&end=2988824&contentlength=838668&sd=20200&qd_uid=&qd_vip=0&qd_src=3_31_312&qd_tm=1527944018308&qd_ip=3df22a5a&qd_p=3df22a5a&qd_k=968250d4f014dcd4795ffc047ca3021d&sgti=&dfp=&qd_sc=047351398e5a0a6235d4fff038150911
Headers:     Method:      http.Header{
    "Referer":         {"http://www.iqiyi.com/v_19rrc654uc.html"},
    "Accept":          {"text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"},
    "Accept-Charset":  {"UTF-8,*;q=0.5"},
    "Accept-Encoding": {"gzip,deflate,sdch"},
    "Accept-Language": {"en-US,en;q=0.8"},
    "User-Agent":      {"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.146 Safari/537.36"},
}
200
GET
 182.35 KiB / 904.43 MiB [>---------------------------------------------------------------]   0.02% 886.41 KiB/s 17m23sHeaders:     200
http.Header{
    "Accept-Encoding": {"gzip,deflate,sdch"},
    "Accept-Language": {"en-US,en;q=0.8"},
    "User-Agent":      {"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.146 Safari/537.36"},
    "Accept":          {"text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"},
    "Accept-Charset":  {"UTF-8,*;q=0.5"},
    "Referer":         {"http://www.iqiyi.com/v_19rrc654uc.html"},
}
Status Code: 200

**Comment by iawia002** [comment]
你传的文件我也能正常播放

<img width="1314" alt="screen shot 2018-06-02 at 21 18 03" src="https://user-images.githubusercontent.com/9134003/40875038-939f19d6-66aa-11e8-9648-80bdd2cec531.png">

**Comment by selewu** [comment]
那我是不是欠缺了什么环境，奇怪了，用mac也是不行呢...全部都是只有音频

**Comment by iawia002** [comment]
你多试两个播放器，应该是播放器的解码有问题

**Comment by selewu** [comment]
我用win/mac自带播放器，mpv QQ播放器，全部都试过了

**Comment by selewu** [comment]
应该是我本地环境有问题，在线转码之后确实能正常播放
