### ISSUE TITLE
下载出现错误

### ISSUE THREAD

**Issue by 9dtman** [iawia002/annie#16]
Type:    video
Quality:    高清 1080P
   Size:    177.54 MiB (186162839 Bytes)

 159.20 MiB / 177.54 MiB [======================================================================================>---------]  89.67% 1.59 MiB/s 10s
2018/03/18 12:40:23 Error while downloading: http://cn-jsnt-dx-v-03.acgvideo.com/vg0/c/61/34219071-2-80.flv?expires=1521354900&platform=pc&ssig=wFbUO0UouG_OrdSSKw_oew&oi=3070288114&nfa=ZGlYLwTu0dW3o1gJGPmYTQ==&dynamic=1&hfa=2023672908&hfb=Yjk5ZmZjM2M1YzY4ZjAwYTMzMTIzYmIyNWY4ODJkNWI=, net/http: request canceled (Client.Timeout exceeded while reading body)**

**Comment by iawia002** [comment]
正常的，再执行一次命令就好了，有断点记录的，会从断的地方开始下
