### ISSUE TITLE
exec: "ffmpeg": executable file not found in %PATH%

### ISSUE THREAD

**Issue by starl1ghtx** [iawia002/annie#162]
这个路径问题怎么解决?

**Comment by iawia002** [comment]
https://github.com/iawia002/annie#prerequisites

你需要单独安装 [ffmpeg](https://www.ffmpeg.org/download.html)

**Comment by fnscar** [comment]
可否支持在annie.exe所在目录寻找ffmpeg.exe，就像youtube-dl那样？
自己平时用的电脑因为各种各样的原因不能改环境变量。。。

**Comment by climboy1** [comment]
是的，改变环境变量对于不熟悉系统的人确实不方便，如果不是难以突破的困难还是建议优化代码。感谢你，你的软件对我的帮助很大。

**Comment by JohnWins** [comment]
> 这个路径问题怎么解决?

you can add user variables temp, in this case,

`ffmpeg=D:\Program Files\ffmpeg\bin\ffmpeg.exe`
