### ISSUE TITLE
自动下载特定分辨率的视频

### ISSUE THREAD

**Issue by jiagengliu** [iawia002/annie#163]
希望添加一个简单功能：自动下载`-i`的结果中`Quality`含有某个词（比如720p）对应的视频，而不需要手动输入`-f`+对应的代码

**Comment by jiagengliu** [comment]
希望能在下载 playlist 的时候用。

**Comment by iawia002** [comment]
我没太懂你的意思，你不用 `-f`，它默认下载的就是最高清晰度的。如果你需要其他清晰度的，就只能先用 `-i` 看一下有哪些可选清晰度，再用 `-f` 来选择，基本每个网站的清晰度的定义都不一样，所以必须要自己指定

**Comment by jiagengliu** [comment]
对，我的意思是说我知道清晰度定义里有什么（比如YouTube都是1080p, 720p这样），那么希望能指定自动下载指定清晰度的。

**Comment by iawia002** [comment]
你的意思是 `-f 720p` 这样？

**Comment by jiagengliu** [comment]
@iawia002 是的，-f 已经被用了，可以换个字母。

**Comment by iawia002** [comment]
那和现在的 `-f xxx` 有什么区别呢，盲选？

**Comment by jiagengliu** [comment]
是的，感觉 `-f xx`不是很直观。

**Comment by iawia002** [comment]
每个网站的清晰度的定义都不一样，我不想统一它们
