### ISSUE TITLE
Bilibili 的cookie问题

### ISSUE THREAD

**Issue by sqliuchang** [iawia002/annie#164]
刚开始我设置好之后可以正常下载1080p+的视频，今天用的时候突然就显示  Cookie error: 账号未登录  …
然后我用chrome重新提取了cookie还是没用。
过了一阵子又可以用了，现在又不能用了，不是很清楚为什么。

**Comment by iawia002** [comment]
> Cookie error: 账号未登录

我是直接带上你的 Cookie 访问 B 站的一个 API，这是 B 站的 API 返回给我的结果

B 站好像对 IP 的校验比较严，以前我挂个代理网页上都要重新登录的，你先打开网页刷新一下 B 站，看网页上登录没有，再重新获取一下

实在不行就退出重新登录一下，再拿新的 Cookie

**Comment by glenlance** [comment]
https://github.com/iawia002/annie/issues/430 

重新登录了,也没用.我用的chrome editthiscookie 获取的cookie
