### ISSUE TITLE
[weibo]下载清晰度太低，建议尽量用PC端的地址解析

### ISSUE THREAD

**Issue by beifengle** [iawia002/annie#165]
目前这微博都是通过转换成手机端上的URL来获取视频地址的，但这影响清晰度，而且手机上的解析得到的最高清晰度与电脑还是有差别，如下这个视频，手机上最高清晰度下载完文件为9.5M，而在电脑上直接打开下载则有15M大

**Comment by luhy118** [comment]
https://weibo.com/1642592432/GjWoO0WP2?from=page_1002061642592432_profile&wvr=6&mod=weibotime&type=comment

**Comment by iawia002** [comment]
怎么把这个关了，我最近没时间处理这个

**Comment by luhy118** [comment]
@iawia002 我看到没人处理就关了，免得堆积得太多问题刷屏

**Comment by luhy118** [comment]
@iawia002 为什么我这样执行会报错：
`D:\go_workspace>annie -i https://weibo.com/tv/v/abc?fid=1034:4255266544534450
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/iawia002/annie/extractors.Weibo(0xc04205aa00, 0x1d, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        C:/Users/admin/go/src/github.com/iawia002/annie/extractors/weibo.go:18 +0x59f
main.download(0xc042080040, 0x34)
        C:/Users/admin/go/src/github.com/iawia002/annie/main.go:80 +0x4f1
main.main()
        C:/Users/admin/go/src/github.com/iawia002/annie/main.go:121 +0xe7
`

**Comment by iawia002** [comment]
@luhy118 不用关，有时间的话要处理的

报错那个应该是个 bug

**Comment by luhy118** [comment]
@iawia002 微博的我好像试了没有一个是成功的，

**Comment by iawia002** [comment]
@luhy118 不会吧，地址贴上来看看

**Comment by zhz1237ok** [comment]
@luhy118 微博视频只有一种清晰度吧，你加 -i 干啥

**Comment by luhy118** [comment]
@zhz1237ok 你怎么看的？我二楼贴出的地址不是就有两种清晰度了吗

**Comment by lovecn** [comment]
weibo 用 you-get ，一直可以的
