### ISSUE TITLE
[weibo]解析异常

### ISSUE THREAD

**Issue by luhy118** [iawia002/annie#168]
如下链接：
https://weibo.com/1809436135/Glo1x6hHD

**Comment by iawia002** [comment]
最新版本没问题

```console
$ annie https://weibo.com/1809436135/Glo1x6hHD

 Site:      微博 weibo.com
 Title:     2018世界杯A组第1轮：俄罗斯队右路突破后斜射被门将扑出（詹俊、李元魁）
 Type:      video
 Stream:
     [default]  -------------------
     Size:            2.64 MiB (2767594 Bytes)
     # download with: annie -f default "URL"

 2.64 MiB / 2.64 MiB [===================================] 100.00% 4.12 MiB/s 0s
```

**Comment by luhy118** [comment]
为什么我这还是报错：
`D:\go_workspace\annie>annie https://weibo.com/1809436135/Glo1x6hHD
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/iawia002/annie/extractors.Weibo(0xc04206e090, 0x26, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        C:/Users/admin/go/src/github.com/iawia002/annie/extractors/weibo.go:14 +0x5a6
main.download(0xc04206e090, 0x26)
        C:/Users/admin/go/src/github.com/iawia002/annie/main.go:80 +0x4f1
main.main()
        C:/Users/admin/go/src/github.com/iawia002/annie/main.go:121 +0xe7

D:\go_workspace\annie>`

@iawia002

**Comment by iawia002** [comment]
你什么版本

**Comment by iawia002** [comment]
😂 我的锅，我改了还没发版本，0.7.4 可以了

**Comment by luhy118** [comment]
@iawia002 原来如此，那快点发吧

**Comment by iawia002** [comment]
发了，0.7.4
