### ISSUE TITLE
[iqiyi]请教一个问题，iqiyi移动网络播放很慢

### ISSUE THREAD

**Issue by sweord** [iawia002/annie#174]
在解析出m3u8的情况下，比如得到一个分段：
http://dx.data.video.qiyi.com/videos/v0/20150326/36/0b/1b88259f56d483fe91b7dcfa6da3b824.ts?qdv=1&qypid=356083700_04022000001000000000_4&start=0&end=2579069&hsize=99505&tag=0&v=&contentlength=2255248&qd_uid=&qd_vip=0&qd_src=3_31_312&qd_tm=1530599248545&qd_ip=72fdfee2&qd_p=72fdfee2&qd_k=afb4e5f677f2d3ba428a8c25d8c627dc&sgti=&dfp=&qd_sc=50143ca151a57105c32a512d225cb30b

播放这个分段时，如果使用联通网络，会比较正常。但是如果在移动网络下，播放会特别卡，速率大约只有十几K。

我用curl查了下，这个地址会先跳转一次，经常跳转到IP：61.240.130.139，这是河北联通的IP。
偶尔能跳转到移动的CDN IP，那么速率也会正常。

请问，是否有办法，在移动网络时，让这个地址正确使用移动的CDN，能跳转到移动的CDN？

谢谢！

**Comment by iawia002** [comment]
URL 贴上来看看

**Comment by iawia002** [comment]
这个最终解析出来的 URL 具体是从哪个地方的 CDN 下载不是我控制的呀

**Comment by sweord** [comment]
解析的这个URL： http://www.iqiyi.com/v_19rrnnoe54.html

在联通网络下正常，在移动网络下就会特别慢。感觉是CDN选择的问题。

**Comment by sweord** [comment]
嗯，是的。我也感觉是网络问题，跟这个软件没什么关系。

谢谢！
