### ISSUE TITLE
[bilibili]Download return error (Win 64)

### ISSUE THREAD

**Issue by Liaune** [iawia002/annie#181]
http://cn-zjhz-cu-v-01.acgvideo.com/upgcxcode/49/35/31453549/31453549-1-64.flv?expires=1531022400&platform=pc&ssig=Qb0azMGBMjUs-7ja00giOA&oi=1899606197&nfa=VTtnXeacAlS5k6cLdWuWIA==&dynamic=1&hfa=2037535727&hfb=Yjk5ZmZjM2M1YzY4ZjAwYTMzMTIzYmIyNWY4ODJkNWI=&trid=31d26739c9644bfd844db8789b6c7cdc&nfc=1
2018/07/08 10:02:28 [31mHTTP error: 454[0m

**Comment by iawia002** [comment]
下载地址贴一下

**Comment by iawia002** [comment]
any response?

**Comment by jiqing112** [comment]
> any response?

我现在也遇到了这个问题，返回错误是http的454和403

我有一个国内的主机和一个国外的主机。国内的主机是用Annie无法现在任何一个网站视频。国外的主机可以下载b站，不能下载腾讯视频。
安装是直接在 Releases页面直接下载的可执行文件复制到bin目录的，因为go get一直安装失败。


拿这两个视频为例：
https://www.bilibili.com/video/av27427435

https://v.qq.com/x/cover/ohnqsa724don14o/m00293knfax.html

国内主机报错如下，返回错误454和403：

![snipaste_2019-01-03_16-06-10](https://user-images.githubusercontent.com/17674011/50628095-8181cf80-0f71-11e9-8fd9-ab5d68b1ba90.png)

![snipaste_2019-01-03_16-06-44](https://user-images.githubusercontent.com/17674011/50628112-93fc0900-0f71-11e9-97ec-39a6384c9cd7.png)

国外的主机可以下载b站视频，腾讯视频不能下载，腾讯视频的报错是403
![snipaste_2019-01-03_16-07-40](https://user-images.githubusercontent.com/17674011/50628142-bb52d600-0f71-11e9-93ad-1c254c9ad0cd.png)

**Comment by jiqing112** [comment]
没事了，解决了，万能的重装大发好
