### ISSUE TITLE
bilibili 批量下载

### ISSUE THREAD

**Issue by sqliuchang** [iawia002/annie#183]
annie -c cookie.txt -p https://www.bilibili.com/bangumi/play/ep50734
annie -c cookie.txt -p https://www.bilibili.com/bangumi/media/md2271
这两个都没反应，但是单独下载某一集没问题

**Comment by iawia002** [comment]
下个版本会修复，不要用 `https://www.bilibili.com/bangumi/media/md2271` 这种地址，下载 `ep...` 这种
