### ISSUE TITLE
[miaopai] error while downloading from miaopai 

### ISSUE THREAD

**Issue by leoliu-centrality** [iawia002/annie#185]
annie -d http://www.miaopai.com/show/jgQhqCZaXT7ZBfkw2FXPXb1w2mvB3LFSh1CIIQ__.htm                                                                                                                                                             

annie: version 0.7.6, A fast, simple and clean video downloader.

URL:         http://www.miaopai.com/show/jgQhqCZaXT7ZBfkw2FXPXb1w2mvB3LFSh1CIIQ__.htm
Method:      GET
Headers:     http.Header{
    "Accept-Encoding": {"gzip,deflate,sdch"},
    "Accept-Language": {"en-US,en;q=0.8"},
    "User-Agent":      {"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.146 Safari/537.36"},
    "Accept":          {"text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"},
    "Accept-Charset":  {"UTF-8,*;q=0.5"},
    "Referer":         {"http://www.miaopai.com/show/jgQhqCZaXT7ZBfkw2FXPXb1w2mvB3LFSh1CIIQ__.htm"},
}
Status Code: 200
2018/07/09 14:56:57 https://gslb.miaopai.com/stream/jgQhqCZaXT7ZBfkw2FXPXb1w2mvB3LFSh1CIIQ__.mp4?ssig=586d3363f82239df3331958dba0ed304&time_stamp=1531108612159&cookie_id=&vend=1&os=3&partner=1&platform=2&cookie_id=&refer=miaopai&scid=jgQhqCZaXT7ZBfkw2FXPXb1w2mvB3LFSh1CIIQ__
panic: Get https://txycdn.miaopai.com/stream/jgQhqCZaXT7ZBfkw2FXPXb1w2mvB3LFSh1CIIQ___16.mp4?ssig=1a58973e9cc5120fd8b2b0c59da71dad&time_stamp=1531108616828: x509: certificate is valid for *.cdn.myqcloud.com, *.2144.com, *.dpfile.com, *.duba.com, *.flash.2144.com, *.flash.cn, *.sogoucdn.com, *.zhaopin.cn, *.zhaopin.com, not txycdn.miaopai.com

goroutine 1 [running]:
github.com/iawia002/annie/request.Request(0x13236a7, 0x3, 0xc42026a274, 0xfe, 0x0, 0x0, 0xc4201cf968, 0xc4201fc460)
	/private/tmp/annie-20180708-4272-jsdnj9/annie-0.7.6/src/github.com/iawia002/annie/request/request.go:97 +0xb74
github.com/iawia002/annie/request.Headers(0xc42026a274, 0xfe, 0x7ffeefbffaf1, 0x48, 0x2)
	/private/tmp/annie-20180708-4272-jsdnj9/annie-0.7.6/src/github.com/iawia002/annie/request/request.go:149 +0x110
github.com/iawia002/annie/request.Size(0xc42026a274, 0xfe, 0x7ffeefbffaf1, 0x48, 0x1)
	/private/tmp/annie-20180708-4272-jsdnj9/annie-0.7.6/src/github.com/iawia002/annie/request/request.go:155 +0x4d
github.com/iawia002/annie/extractors.Miaopai(0x7ffeefbffaf1, 0x48, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/private/tmp/annie-20180708-4272-jsdnj9/annie-0.7.6/src/github.com/iawia002/annie/extractors/miaopai.go:17 +0x171
main.download(0x7ffeefbffaf1, 0x48)
	/private/tmp/annie-20180708-4272-jsdnj9/annie-0.7.6/src/github.com/iawia002/annie/main.go:84 +0x712
main.main()
	/private/tmp/annie-20180708-4272-jsdnj9/annie-0.7.6/src/github.com/iawia002/annie/main.go:129 +0xe0

**Comment by iawia002** [comment]
CI 上也出现这个问题了，但是我本地复现不了，你是什么网络环境

```console
$ annie http://www.miaopai.com/show/jgQhqCZaXT7ZBfkw2FXPXb1w2mvB3LFSh1CIIQ__.htm

 Site:      秒拍 miaopai.com
 Title:     大师的修养：详细讨论莫德里奇在世界杯1 4决赛中的这次-足球带我奔跑的秒拍
 Type:      video
 Stream:
     [default]  -------------------
     Size:            9.63 MiB (10102179 Bytes)
     # download with: annie -f default "URL"

 9.63 MiB / 9.63 MiB [===================================] 100.00% 7.12 MiB/s 1s
```

**Comment by leoliu-centrality** [comment]
oops, I am using the wrong Github account, but nevermind. T^T
I have installed the latest version of annie on a Linux machine at home and a Mac OS X machine at work, and tried on both of them, got the same issue recently and repeatedly, for every single miaopai video. It looks more like a miaopai problem to me. 
I am living in Auckland, New Zealand. 
Awesome work by the way. Thank you for your time.

**Comment by leoliu-centrality** [comment]
yeah sure, but I think it is due to Miaopai is using an invalid certificate. Would you mind implementing an optional argument to bypass security check for https requests? Something like `requests.get('https://foobar.com', verify=False)` in python.

That could be a temporary solution used when the same thing happens to other websites.

**Comment by iawia002** [comment]
yeah, for now, this is the right way
