### ISSUE TITLE
小白求问如何安装

### ISSUE THREAD

**Issue by weidongzhou1994** [iawia002/annie#196]
各位大佬，为什么Windows 10输入安装命令后不能安装，显示‘go’不是内部或外部命令，另外下载的安装包（exe程序）也无法直接使用，求问如何安装啊。

**Comment by wuping24** [comment]
这显然不适合你用朋友，都是基于命令行的。
go语言要单独安装.F建议你用vdm

**Comment by iawia002** [comment]
把 `annie.exe` 所在路径加入到环境变量里，就可以在终端里 `annie ...` 使用了
