### ISSUE TITLE
安装后为什么无法使用

### ISSUE THREAD

**Issue by weidongzhou1994** [iawia002/annie#197]
![image](https://user-images.githubusercontent.com/40510496/42932018-c66ebf18-8b73-11e8-8af8-b962c446d6b9.png)

**Comment by wuping24** [comment]
youtube打不开是你没开代理，bilibili网址不用输单引号 可直接输ep231153
建议你多看下说明

**Comment by weidongzhou1994** [comment]
开代理了

**Comment by iqinqin** [comment]
代理没写进命令里啊

**Comment by iawia002** [comment]
代理要写进命令里面，https://github.com/iawia002/annie#proxy

URL 的引号错了，要么就不加，要么就英文的引号

**Comment by weidongzhou1994** [comment]
不加引号也无法下载啊，而且我之前使用shadowsocks时开全局模式可以下载，不知道为什么现在就不能下载了

**Comment by iawia002** [comment]
有些 URL 有特殊字符，加英文单引号 `'`，代理要写到命令里面，类似：`annie -s 127.0.0.1:1080`，具体的可以看文档：https://github.com/iawia002/annie#proxy

**Comment by weidongzhou1994** [comment]
我看了一下，you-get 在全局模式下可以下载，annie 必须在下载时要添加代理地址是吗？如果是这样的话为什么annie不能像you-get 一样直接在全局模式下就能下载呢？
