### ISSUE TITLE
代理问题

### ISSUE THREAD

**Issue by weidongzhou1994** [iawia002/annie#198]
您好，对于ShadowsocksR-dotnet4.0 的代理也是使用-s 命令吗？为什么我的无法使用，
![image](https://user-images.githubusercontent.com/40510496/42987909-650c44ba-8c2d-11e8-864b-7999b9c936d3.png)

**Comment by iawia002** [comment]
一般本地都是 `127.0.0.1:1080` 这个地址，你试试这个

**Comment by weidongzhou1994** [comment]
ok,可以了

**Comment by weidongzhou1994** [comment]
现在不能解析优酷视频了吗？

**Comment by iawia002** [comment]
其他问题单独提 issue 吧，把 URL，报错信息什么的都写详细
