### ISSUE TITLE
优酷视频无法下载

### ISSUE THREAD

**Issue by weidongzhou1994** [iawia002/annie#199]
我分别用了yuou-get, annie 和youtube-dl 三种方法下载，只有youtube-dl 能下载，annie 和you-get 都无法下载![image](https://user-images.githubusercontent.com/40510496/43035235-c6b2a2d0-8d1e-11e8-8585-b1979784a69d.png)

**Comment by zhangzujian** [comment]
+1，报错信息一样。

**Comment by iawia002** [comment]
ccode 的问题，我从 0500 试到了 0599，只有 0503 0510 0516 0517 0590 可以，但是都不能下最高清晰度的（有些视频只能下前几分钟）

**Comment by lim0513** [comment]
带上cookies,用 P_gck，P_pck_rm两个参数即可。
![image](https://user-images.githubusercontent.com/8295174/43057107-b57d8944-8e72-11e8-84ae-4a428419a792.png)

**Comment by weidongzhou1994** [comment]
小白求问，这些命令行程序要用的cookies是需要自己手动下载，还是直接使用命令加载，另外上面那个大佬，能接一个命令的图片吗？方便我自己再去模仿。多谢了!

**Comment by lim0513** [comment]
annie.exe -c youku.txt -F Download.txt
youku.txt 文件里记录cookies，具体内容用浏览器查看cookies信息可得到，格式如下:
`P_gck=NA%7CkIhR2NyFxJZ....;P_pck_rm=t4y2HIaXk...;`
Download.txt文件里记录要下载的视频文件地址即可

**Comment by weidongzhou1994** [comment]
小白再次求问，Download.txt文件里记录的地址怎么分开呢？是直接用 ; 分开吗，视频地址要加单引号吗？

**Comment by lim0513** [comment]
一行一个即可，不用引号。。。

**Comment by sunyue1380** [comment]
@lim0513  该cookie有有效期吧?能问一下从哪个链接返回的这个cookie呢？

**Comment by lim0513** [comment]
随意浏览一个优酷的视频地址即可。

**Comment by iawia002** [comment]
0.7.10，#202 解决了这个问题
