### ISSUE TITLE
解决#94 给出乐视网解析算法

### ISSUE THREAD

**Issue by sunyue1380** [iawia002/annie#200]
本人是一位Java程序员，不会Go语言,但可以给出乐视网解析算法，解决issue  #94 .
乐视网算法如下:
url:http://www.le.com/ptv/vplay/31419123.html
1. 提取vid:31419123
`String vid = RegexUtil
				.extract("http://www.le(tv)?.com/ptv/vplay(/)?(_)?(?<vid>\\d+)\\.html.*",
						"vid", url);`
2. 访问api ,vtype= 后面可以跟参数也不可以不跟，不跟的话返回所有清晰度的视频
* vtype=21 标清
* vtype=13 高清
* vtype=22 超清
* vtype=52 1080P
`
String api = "http://tvepg.letv.com/apk/data/common/security/playurl/geturl/byvid.shtml?vid=31419123&key=&vtype=";
`
`
definition.put("21","标清");
		definition.put("13","高清");
		definition.put("22","超清");
		definition.put("52","1080P");
`
`
GET http://tvepg.letv.com/apk/data/common/security/playurl/geturl/byvid.shtml?vid=31419123&key=&vtype=13 HTTP/1.1
Accept-Encoding: gzip
User-Agent: Java/1.8.0_144
Host: tvepg.letv.com
Accept: text/html, image/gif, image/jpeg, *; q=.2, */*; q=.2
Connection: keep-alive
`
本人测试直接访问该url链接不返回有效信息,不知道为什么,不过我java程序访问是可以的。原始http头部如代码所示.
3. 提取m3u8链接  data-->infos-->mainUrl
JSONObject info = result.getJSONArray("data").getJSONObject(0).getJSONArray("infos").getJSONObject(0);
				videoMap.put(analyzeParam.getPrefer(),info.getString("mainUrl"));

**Comment by iqinqin** [comment]
vtype后必须跟清晰度参数才能返回
不加headers也可以返回

**Comment by sunyue1380** [comment]
@iqinqin  那看来是我之前搞错了吧。我记得很久之前是可以不加vtype的，直接会返回所有清晰度信息。现在可能服务器那边变了吧。

**Comment by iqinqin** [comment]
@sunyue1380 还有一个问题 获取的m3u8只有几分钟，不完整

**Comment by sunyue1380** [comment]
@iqinqin  没有啊，我这边测试都是ok的，是完整的啊。

**Comment by sunyue1380** [comment]
@iqinqin  我这边IE直接打开m3u8，都是20多分钟的视频啊。。

**Comment by iqinqin** [comment]
@sunyue1380 
测试网站：[http://www.le.com/ptv/vplay/28915612.html](http://www.le.com/ptv/vplay/28915612.html)
[获取的链接：](http://play.g3proxy.lecloud.com/vod/v2/MjY4LzUvMzQvbGV0di11dHMvMTQvdmVyXzAwXzIyLTEwOTc2MDEzNzgtYXZjLTI5OTQ4NjgtYWFjLTEyODAwMC0yNzA5OTIwLTEwNjE5NzUzMTUtNGM5NjEwZDUxYjdhYWIzYjllYTY1MGM2MmY3ZjBlZTctMTQ5MjUxNzMyMDM5NS5tcDQ=?b=3135&mmsid=64268604&tm=1532340429&key=bc910484e5e9e7ad9ac721d5df4dda61&platid=6&splatid=602&orifrom=aHR0cDovL3R2ZXBnLmxldHYuY29tL2Z0bC9hcGsvZGF0YS9jb21tb24vc2VjdXJpdHkvcGxheXVybC9nZXR1cmwvYnl2aWQ=&orivid=28915612&clientIp01=111.20.226.19&clientIp02=10.110.140.165&playid=0&tss=tvts&vtype=52&cvid=800705518804&payff=0&pip=71dcd7c18affb6b2a52003c006ba9f28)
