### ISSUE TITLE
下载视频列表中断后再次下载出错

### ISSUE THREAD

**Issue by weidongzhou1994** [iawia002/annie#203]
annie在下载视频列表时，如果中断后再次下载总会出现下述错误。
![image](https://user-images.githubusercontent.com/40510496/43117393-22375c50-8f3f-11e8-8ffd-76514514742e.png)

**Comment by iawia002** [comment]
annie 的版本和报错的视频地址贴上来

**Comment by weidongzhou1994** [comment]
![image](https://user-images.githubusercontent.com/40510496/43119355-a7a3e436-8f48-11e8-87f2-50d54677fa3e.png)

**Comment by iawia002** [comment]
你别发图片啊，你这个我怎么测试

**Comment by weidongzhou1994** [comment]
annie 的版本应该是最新的，我前几天才开始用，视频地址是：https://www.youtube.com/watch?v=zFe2zdHOetE&list=PLop03KZMlBVfVH4WlRN15h8ujGaErlc2t

**Comment by iawia002** [comment]
看上去像是网络问题，我这里可以正常下载，你单独下第 40 集会报错吗

```console
$ annie -s 127.0.0.1:1080 https://www.youtube.com/watch\?v\=myd2ZiOIea4\&list\=PLop03KZMlBVfVH4WlRN15h8ujGaErlc2t\&index\=40

 Site:      YouTube youtube.com
 Title:     大宋提刑官 40
 Type:      video
 Stream:
     [default]  -------------------
     Quality:         720p video/mp4; codecs="avc1.4d401f"
     Size:            220.29 MiB (230991061 Bytes)
     # download with: annie -f default "URL"

 220.29 MiB / 220.29 MiB [============================] 100.00% 3.02 MiB/s 1m12s
Merging video parts into 大宋提刑官 40.mp4
```

**Comment by iawia002** [comment]
我用列表模式下也可以：

```console
$ annie -p -start 40 -end 41 -s 127.0.0.1:1080 https://www.youtube.com/watch\?v\=myd2ZiOIea4\&list\=PLop03KZMlBVfVH4WlRN15h8ujGaErlc2t\&index\=40

 Site:      YouTube youtube.com
 Title:     大宋提刑官 40
 Type:      video
 Stream:
     [default]  -------------------
     Quality:         720p video/mp4; codecs="avc1.4d401f"
     Size:            220.29 MiB (230991061 Bytes)
     # download with: annie -f default "URL"

 50.72 MiB / 220.29 MiB [======>---------------------]  23.02% 6.36 MiB/s 00m26s
```

**Comment by iawia002** [comment]
实在不行就单独下 40 集，再用列表模式下，40 集单独下了会跳过的

**Comment by weidongzhou1994** [comment]
主要不是第40集的问题，而是第40集已经下过了，但是重新下载视频列表时跳过不成功，没有办法继续下载。

**Comment by iawia002** [comment]
你把报错信息贴上来，别截图，完整的。列表可以选起点的：`annie -start 41 ...` 这样可以从 41 项开始下载

https://github.com/iawia002/annie#download-playlist

**Comment by weidongzhou1994** [comment]
报错信息：2018/07/24 11:28:25 https://r5---sn-n4v7sn76.googlevideo.com/videoplayback?initcwndbps=820000&c=WEB&dur=2737.911&keepalive=yes&source=youtube&pl=24&ei=yZxWW-DbC8-j_AP15aHQBg&id=o-AF5mEL7rlUnK5kitl9ZZVL_MMXxZx8OdImnotHYMF-n1&ms=au%2Crdu&mt=1532402804&mv=m&mm=31%2C29&signature=AB9DE6A8AB5519921C41849160915787DAA08FAC.386CC6F339199B9E22A2CCA9701B0539842DC7CB&mn=sn-n4v7sn76%2Csn-n4v7knll&sparams=clen%2Cdur%2Cei%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Crequiressl%2Csource%2Cexpire&key=yt6&ip=104.192.80.177&gir=yes&fvip=5&itag=140&expire=1532424489&lmt=1521168905077203&ipbits=0&clen=43485252&requiressl=yes&mime=audio%2Fmp4&ratebypass=yes
panic: Get https://r2---sn-ug5onuxaxjvh-3i8e.googlevideo.com/videoplayback?c=WEB&dur=2737.911&keepalive=yes&source=youtube&pl=22&ei=yZxWW-DbC8-j_AP15aHQBg&id=o-AF5mEL7rlUnK5kitl9ZZVL_MMXxZx8OdImnotHYMF-n1&signature=427E2B658AD12775864D7BF940D43785328E3A5F.669A6188FC534B2C475EA555CF11386EBC98DFCF&sparams=clen,dur,ei,expire,gir,id,ip,ipbits,ipbypass,itag,keepalive,lmt,mime,mip,mm,mn,ms,mv,pl,requiressl,source&key=cms1&ip=104.192.80.177&gir=yes&fvip=5&itag=140&expire=1532424489&lmt=1521168905077203&ipbits=0&clen=43485252&requiressl=yes&mime=audio%2Fmp4&ratebypass=yes&redirect_counter=1&rm=sn-n4ved76&req_id=2490a193fb4a3ee&cms_redirect=yes&ipbypass=yes&mip=92.38.130.139&mm=31&mn=sn-ug5onuxaxjvh-3i8e&ms=au&mt=1532402804&mv=m: EOF

goroutine 1 [running]:
github.com/iawia002/annie/request.Request(0x71a621, 0x3, 0xc042e92b00, 0x2a4, 0x0, 0x0, 0xc0427bf530, 0x2a4)
        /Users/mac/iawia002/go/src/github.com/iawia002/annie/request/request.go:99 +0xbb7
github.com/iawia002/annie/request.Headers(0xc042e92b00, 0x2a4, 0xc042cd1380, 0x53, 0x0)
        /Users/mac/iawia002/go/src/github.com/iawia002/annie/request/request.go:151 +0x117
github.com/iawia002/annie/request.Size(0xc042e92b00, 0x2a4, 0xc042cd1380, 0x53, 0x29)
        /Users/mac/iawia002/go/src/github.com/iawia002/annie/request/request.go:157 +0x54
github.com/iawia002/annie/extractors/youtube.extractVideoURLS(0xc0430ad320, 0x12, 0xc04326e000, 0x3f34, 0xc0430fb900, 0x113d, 0xc042e7e540, 0x29, 0xc042cd1380, 0x53, ...)
        /Users/mac/iawia002/go/src/github.com/iawia002/annie/extractors/youtube/youtube.go:162 +0x2d7
github.com/iawia002/annie/extractors/youtube.youtubeDownload(0xc042cd1380, 0x53, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /Users/mac/iawia002/go/src/github.com/iawia002/annie/extractors/youtube/youtube.go:112 +0x2cd
github.com/iawia002/annie/extractors/youtube.Download(0xc042046060, 0x53)
        /Users/mac/iawia002/go/src/github.com/iawia002/annie/extractors/youtube/youtube.go:87 +0x3a1
main.download(0xc042046060, 0x53)
        /Users/mac/iawia002/go/src/github.com/iawia002/annie/main.go:71 +0x43b
main.main()
        /Users/mac/iawia002/go/src/github.com/iawia002/annie/main.go:130 +0xe7
