### ISSUE TITLE
[YouKu]优酷下载提示 客户端无权播放,201

### ISSUE THREAD

**Issue by iqinqin** [iawia002/annie#204]
版本：0.7.10

测试链接：[给我一个十八岁：第1集](https://v.youku.com/v_show/id_XMzcwNDkyMTk5Ng==.html?spm=a2h0j.11185381.listitem_page1.5~A&&s=4a17cebeefbfbdefbfbd)

> annie -i https://v.youku.com/v_show/id_XMzcwNDkyMT
> k5Ng==.html?spm=a2h0j.11185381.listitem_page1.5~A&&s=4a17cebeefbfbdefbfbd

2018/07/24 18:57:03 客户端无权播放,201

**Comment by iawia002** [comment]
不行的话还是用 https://github.com/iawia002/annie/issues/199#issuecomment-406934747 这个方法吧，退回到 0.7.9

**Comment by iawia002** [comment]
ping @jpacg，你是从哪个网站看到的这个 ccode，能不能贴上来看看他们更新没有

**Comment by iqinqin** [comment]
@iawia002 换回0.7.9加载Cookies可以下载

**Comment by jpacg** [comment]
@iawia002 这次是从优酷分享视频到微博找到的ccode，不知道什么时候会失效，目前测试是可以的。

**Comment by iqinqin** [comment]
@iawia002 releases 0.7.11?

**Comment by iawia002** [comment]
等会儿，我更新一下文档

**Comment by iawia002** [comment]
还有，现在这个只能下 720P 的，先将就用着吧

**Comment by BearChu** [comment]
优酷的1080P 希望加快修复~ 感谢
