### ISSUE TITLE
[iqiyi]爱奇艺视频解析问题

### ISSUE THREAD

**Issue by gaoyanghao** [iawia002/annie#206]
视频地址：http://www.iqiyi.com/v_19rr7b7r24.html
下载到一半就报错了：
2018/07/27 10:15:19 rename 外科风云: 第39集 患者家属质问晨曦[5].ts.download 外科
风云: 第39集 患者家属质问晨曦[5].ts: The parameter is incorrect.

**Comment by iawia002** [comment]
更新一下最新版，解决了这个问题的
