### ISSUE TITLE
[bilibili]多个视频无法下载

### ISSUE THREAD

**Issue by clzls** [iawia002/annie#208]
在成功下载多个番剧视频（ep4xxxxxx）后发现无法下载av2xxxxxx视频，看起来解析不到视频地址。尝试传Cookie使用旧版播放器也无效。

PS D:\TmpDl> annie -d -C av2456943

annie version 0.7.11, A fast, simple and clean video downloader.

URL:         https://www.bilibili.com/video/av2456943
Method:      GET
Headers:     http.Header{
    "Accept":          {"text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"},
    "Accept-Charset":  {"UTF-8,*;q=0.5"},
    "Accept-Encoding": {"gzip,deflate,sdch"},
    "Accept-Language": {"en-US,en;q=0.8"},
    "User-Agent":      {"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.146 Safari/537.36"},
    "Referer":         {"https://www.bilibili.com"},
}
Status Code: 200
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/iawia002/annie/extractors/bilibili.Download(0xc04208a270, 0x28)
        /Users/mac/iawia002/go/src/github.com/iawia002/annie/extractors/bilibili/bilibili.go:142 +0xa0e
main.download(0xc04208a270, 0x28)
        /Users/mac/iawia002/go/src/github.com/iawia002/annie/main.go:64 +0x804
main.main()
        /Users/mac/iawia002/go/src/github.com/iawia002/annie/main.go:131 +0xe7

**Comment by iawia002** [comment]
我在网页端试了一下，这个视频不登录看不了，不知道是不是和 B 站最近的内容整改有关。你带上登录之后的 Cookie 就能下载了

```console
$ annie -c ~/Desktop/cookies.txt -i av2456943

 Site:      哔哩哔哩 bilibili.com
 Title:     【720P BDrip】官方恶搞+鬼畜 某科学的超电磁炮S 特典OVA2【青空字幕组 熟肉 超清】
 Type:      video
 Streams:   # All available quality
     [64]  -------------------
     Quality:         高清 720P
     Size:            83.88 MiB (87954474 Bytes)
     # download with: annie -f 64 "URL"

     [default]  -------------------
     Quality:         高清 1080P
     Size:            80.96 MiB (84896137 Bytes)
     # download with: annie -f default "URL"

     [15]  -------------------
     Size:            33.03 MiB (34637430 Bytes)
     # download with: annie -f 15 "URL"

     [32]  -------------------
     Size:            33.03 MiB (34637430 Bytes)
     # download with: annie -f 32 "URL"
```

**Comment by clzls** [comment]
在我电脑的测试时未登录也可以进入页面观看视频（仅仅多出一个“登陆以发送弹幕”），从而没有考虑Cookie的影响，疏忽了。谢谢解答。
