### ISSUE TITLE
下载路径parse -o: invalid URI for request

### ISSUE THREAD

**Issue by yiny0liuyin** [iawia002/annie#212]
我想下载到/Volumes/Untitled 用了-o /Volumes/Untitled 然后报parse -o: invalid URI for request

**Comment by iawia002** [comment]
下载完整命令贴上来看看

**Comment by yiny0liuyin** [comment]
annie -p http://地址 -o /v/u 抱歉身边没电脑

**Comment by iawia002** [comment]
命令写错了，`annie [OPTIONS] URL [URL...]`，这种格式，对应你的就应该是：

```
annie -p -o /v/u 抱歉身边没电脑 http://地址
```
