### ISSUE TITLE
[bilibili] 如何下载港澳台地区番剧 已挂sock5

### ISSUE THREAD

**Issue by yiny0liuyin** [iawia002/annie#216]
annie -c ~/Desktop/cookies -s 127.0.0.1:1086 -p https://www.bilibili.com/bangumi/play/ep65871 

 Site:      哔哩哔哩 bilibili.com
 Title:     沒有黃段子的無聊世界（僅限港澳台地區）：第1话 公序良俗是为了谁
 Type:      video
 Stream:   
     [default]  -------------------
     Size:            0.12 MiB (124627 Bytes)
     # download with: annie -f default "URL"

 0 B / 121.71 KiB [----------------------------------------------------]   0.00%2018/08/02 19:14:17 http://cn-zjjh4-dx-v-06.acgvideo.com/upgcxcode/43/69/8986943/8986943-1-16.mp4?expires=1533215400&platform=ios&ssig=FTcDTHaClSLkezR4-RHCZw&oi=3078818617&nfa=7VMUDqBQpI8VGBbhQ1faUQ==&dynamic=1&hfa=2035403398&hfb=ZWI2ODUxMTI1YmRhNTcxZjcwNTFjMTUwOTdkZTc0ZDM=&trid=0f94938f0ec44e29822a79030bd3ebb4&nfc=1
2018/08/02 19:14:17 HTTP error: 465

**Comment by iawia002** [comment]
感觉是你网络的问题

```console
$ annie -c ~/Desktop/cookies.txt -s 127.0.0.1:1080 ep63842

 Site:      哔哩哔哩 bilibili.com
 Title:     沒有黃段子的無聊世界（僅限港澳台地區）：第1话 公序良俗是为了谁
 Type:      video
 Stream:
     [default]  -------------------
     Quality:         高清 720P
     Size:            215.59 MiB (226059913 Bytes)
     # download with: annie -f default "URL"

 13.11 MiB / 215.59 MiB [==>------------------------------]   6.08% 1.39 MiB/s 02m24s
```

**Comment by iawia002** [comment]
有没有网络稳定一点的线路再试试

**Comment by yiny0liuyin** [comment]
换了好几个都是这样 我用的ssr

**Comment by iawia002** [comment]
我知道原因了，应该是代理没生效，你的 socks5 地址确定一下有没有写错

**Comment by iawia002** [comment]
@yiny0liuyin，还有回复吗？

**Comment by yiny0liuyin** [comment]
已经放弃下载 可能是我的vps有问题。

**Comment by yiny0liuyin** [comment]
感谢

**Comment by iawia002** [comment]
一般没有单独配过的，代理地址都是 `127.0.0.1:1080`

**Comment by yiny0liuyin** [comment]
mac的ssr默认1086.
