### ISSUE TITLE
[youku]带cookie下载优酷视频报错

### ISSUE THREAD

**Issue by KFC0803** [iawia002/annie#217]
`PS D:\> annie -c "f12抓到的cookie" -i http://v.youku.com/v_show/id_XMzU0NzgwNDAxMg==.html
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/iawia002/annie/extractors.youkuUps(0xc04207c0dd, 0x11, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /Users/mac/iawia002/go/src/github.com/iawia002/annie/extractors/youku.go:81 +0x5f7
github.com/iawia002/annie/extractors.Youku(0xc04207c0c0, 0x33, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /Users/mac/iawia002/go/src/github.com/iawia002/annie/extractors/youku.go:155 +0xdf
main.download(0xc04207c0c0, 0x33)
        /Users/mac/iawia002/go/src/github.com/iawia002/annie/main.go:70 +0x44e
main.main()
        /Users/mac/iawia002/go/src/github.com/iawia002/annie/main.go:131 +0xe7` # @

- [ ]

**Comment by iawia002** [comment]
先给你个临时解决方案，把 cookies 里面的 `cna=...;` 那部分去掉。我可能明天有空的时候修复一下这个
