### ISSUE TITLE
[mgtv]按照list文件批量下载报错

### ISSUE THREAD

**Issue by iqinqin** [iawia002/annie#218]
命令如下：
```
G:\Code\python\PyQt\Vdownload>annie -o G:/Code/python/PyQt/Vdownload/a -F list.t
xt
```

错误：

>  109.94 MiB / 334.78 MiB [========>-----------------]  32.84% 5.84 MiB/s 00m38s2
> 018/08/04 10:56:02 file copy error: read tcp 115.154.215.239:8810->183.235.255.1
> 71:80: wsarecv: An existing connection was forcibly closed by the remote host

.

**Comment by iawia002** [comment]
应该是连接被芒果 TV 那边拒了，试试只用一个线程下载 `-n 1`

**Comment by iqinqin** [comment]
@iawia002 改了之后没出现上述问题，
但是又有个新问题：

> 132.91 MiB / 323.80 MiB [==========>---------------]  41.05% 3.39 MiB/s 00m56s2
> 018/08/04 17:05:22 file copy error: unexpected EOF

**Comment by iawia002** [comment]
这个应该也是芒果 TV 服务器拒了这个连接，多重试一下看看。还有能把这个地址发出来吗，我看下我能不能稳定复现

**Comment by iqinqin** [comment]
重试了一下 `-n 5` 速度也不错，再没有报错，谢谢@iawia002
