### ISSUE TITLE
[youtube] 文件过大，下载后只有声音无图像

### ISSUE THREAD

**Issue by githubmin** [iawia002/annie#219]
我下载了 3 个文件，最小的 587M 最大的 1.65G 都出现只有声音无图像的现象

播放器使用的是 MPlayerX 1.1.4 (1920) 的版本，MacOS 自带的 QuickTime 无法解析

ffmpeg version 4.0.2 Copyright (c) 2000-2018 the FFmpeg developers

可测试的地址如下:
https://www.youtube.com/watch?v=8M90t0KvEDY

**Comment by iawia002** [comment]
用 mpv 播放器试一下

**Comment by githubmin** [comment]
mpv 0.29.0 可以正常播放
