### ISSUE TITLE
下载B站视频超时 在我的VPS上经常出现

### ISSUE THREAD

**Issue by RootSir** [iawia002/annie#220]
panic: Get https://interface.bilibili.com/v2/playurl?appkey=84956560bc028eb7&cid=49605674&otype=json&qn=15&quality=15&type=&sign=6f15acbe924791f0eb4b7c1b042ce0cd&utoken=YWlkPTI4NjQ1NTM3JmNpZD00OTYwNTY3NCZmcm9tPXBjJm1pZD0zNTE2NDgyMDQmb3duZXI9MCZzdmlwPTAmdHM9MTUzMzUzNDU1OCZ2aXA9MCZmY3M9MjBjZTdiMDcwYzhiNTk5ZDg3ZDJjYTRmYjhiMWVmMTU=: net/http: TLS handshake timeout

goroutine 1 [running]:
github.com/iawia002/annie/request.Request(0x71e14a, 0x3, 0xc4201d48c0, 0x13e, 0x0, 0x0, 0xc42018f450, 0x600000001)
	/Users/mac/iawia002/go/src/github.com/iawia002/annie/request/request.go:98 +0xaf7
github.com/iawia002/annie/request.Get(0xc4201d48c0, 0x13e, 0x72947b, 0x18, 0xc42018f450, 0x0, 0x0)
	/Users/mac/iawia002/go/src/github.com/iawia002/annie/request/request.go:129 +0xb7
github.com/iawia002/annie/extractors/bilibili.bilibiliDownload(0x7ffe220fe891, 0x29, 0x0, 0x1, 0xc4201de820, 0xd, 0xc4201de648, 0x8, 0xc4201de8b8, 0x8, ...)
	/Users/mac/iawia002/go/src/github.com/iawia002/annie/extractors/bilibili/bilibili.go:221 +0x21e
github.com/iawia002/annie/extractors/bilibili.Download(0x7ffe220fe891, 0x29)
	/Users/mac/iawia002/go/src/github.com/iawia002/annie/extractors/bilibili/bilibili.go:152 +0x862
main.download(0x7ffe220fe891, 0x29)
	/Users/mac/iawia002/go/src/github.com/iawia002/annie/main.go:64 +0x82c
main.main()
	/Users/mac/iawia002/go/src/github.com/iawia002/annie/main.go:133 +0xe0

**Comment by iawia002** [comment]
网络问题，重试一下
