### ISSUE TITLE
菜鸟求助：“下载的exe文件打开没反应。“

### ISSUE THREAD

**Issue by CuzImTough** [iawia002/annie#221]
第一次用GitHub，下载了“annie_0.7.13_Windows_64-bit.zip”这个文件，解压出来的exe文件闪一下就没反应了。
求解答。

**Comment by iawia002** [comment]
这是命令行程序，你要把 Annie 所在的目录加到环境变量里去，然后就可以像 README 里那样在终端里运行了

**Comment by CuzImTough** [comment]
@iawia002  学会了学会了，大佬牛逼，喝冰阔落！
