### ISSUE TITLE
Comparison to youtube-dl - table for wiki / README?

### ISSUE THREAD

**Issue by jm3** [iawia002/annie#224]
I'm curious to hear how annie's goals and usage differ from [youtube-dl](https://github.com/rg3/youtube-dl). As mentioned previously in #57, a short comparison table on the README or wiki would be awesome, especially as both programs have a somewhat long list of options and features. I'd be willing to help tackle this if anyone can point me to any further documentation or roadmap of the project.

Based  on the README and the supported sites list, my impression is that the main difference between the two, besides the implementation language of Go vs Python, is that annie focuses mostly on supporting Chinese sites — is that right?

**Comment by iawia002** [comment]
> is that annie focuses mostly on supporting Chinese sites

For now, yes, this may be a big difference between annie and youtube-dl. youtube-dl supports a lot of sites, and annie only supports a few sites (mostly Chinese sites).

The reason why I choose Go as implementation language is that Go is statically-compiled language, it's fast, maintainable, easy to use (compile once, run everywhere, no need to config other environments).

And about the roadmap, I haven’t thought about this yet. Now I'm just constantly improving the stability of download, and other core things (like error handling. etc) and maintaining existing sites.

Maybe I can try to write some further documentation about development and roadmap thing (maybe takes a few days).

**Comment by conphi** [comment]
Some site fails when using youtube-dl, so I think annie is better performance addressing 'bilibili.com'. 
That's annie's goal.
