### ISSUE TITLE
Run annie -f 278 "URL" failed

### ISSUE THREAD

**Issue by llgoer** [iawia002/annie#227]
Use the latest version of annie,run `./annie -s 127.0.0.1:1080 -f 242 https://www.youtube.com/watch?v=...`,not download the video.

show error like `2018/08/15 17:02:47 No format named 242`

but run `./annie -i ...` has this format.

**Comment by iawia002** [comment]
`https://www.youtube.com/watch?v=...` I need this full URL

**Comment by llgoer** [comment]
./annie -f 278 -s 127.0.0.1:1080 https://www.youtube.com/watch?v=LBLJt9MOLVE
