### ISSUE TITLE
视频下载完成后报错！！！

### ISSUE THREAD

**Issue by EndlessJY** [iawia002/annie#228]
annie -f 3gphd-guoyu https://v.youku.com/v_show/id_XMzc1OTA1MjE1Ng==.html?spm=a2h0j.11185381.listitem_page1.5!2~A&s=69efbfbdefbfbd343a00
“”'s' 不是内部或外部命令，也不是可运行的程序
或批处理文件。“”
![_20180816121214](https://user-images.githubusercontent.com/33413681/44186726-a8b83b80-a14d-11e8-839c-2b61350467d4.png)
求解答，谢谢！！

**Comment by EndlessJY** [comment]
好像是ffmpeg的原因，但是我ffmpeg安装的没问题，报这个错误的时候视频已经下载合成完毕了.倒是没什么影响，就是看着很难受！求解答，谢谢！

**Comment by EndlessJY** [comment]
好吧，貌似也不是ffmpeg的问题
![_20180816121214](https://user-images.githubusercontent.com/33413681/44188650-4eb97500-a151-11e8-85cc-a910ba71743f.png)

**Comment by iawia002** [comment]
这是你 URL 的问题，URL 有特殊字符，用引号引起来 `annie "url"`
