### ISSUE TITLE
[腾讯]为什么下载速度只有400kb左右？

### ISSUE THREAD

**Issue by tea1111980** [iawia002/annie#232]
![image](https://user-images.githubusercontent.com/16295097/44306341-259e1c00-a3bf-11e8-8ae5-19d717049fef.png)

用Lulu、You-get、annie 这几个下载视频都达不到满速。Why？是对方的服务商限制了吗？
我是100M的宽带，不能达到满速下载，这是怎么肥事？

**Comment by iawia002** [comment]
这是 annie 能达到的最大速度了，这应该是腾讯的限制
