### ISSUE TITLE
Twitter视频如何下载？

### ISSUE THREAD

**Issue by zhz1237ok** [iawia002/annie#234]
annie https://twitter.com/FreeMemesKids/status/1031175277156724737
还是 annie https://twitter.com/7bfab1f5-f9cd-4038-af38-750dc14ab796

S:\Annie>annie -s 127.0.0.1:1080 https://twitter.com/FreeMemesKids/status/1031175277156724737
2018/08/20 14:58:05 {Twitter twitter.com Dank Memes 💎💎💎 on Twitter 1031175277156724737 video map[]}
2018/08/20 14:58:05 No format named default

**Comment by Justsoos** [comment]
```
λ annie.exe -s 127.0.0.1:1080 "https://twitter.com/ailoysl/status/1036839724155985922"

 Site:      Twitter twitter.com
 Title:     yslailo on Twitter 1036839724155985922
 Type:      video
 Stream:
     [default]  -------------------
     Quality:         400x400
     Size:            2.57 MiB (2696484 Bytes)
     # download with: annie "URL"

 2.57 MiB / 2.57 MiB [==================================================================] 100.00% 288.33 KiB/s 9s Merging video parts into yslailo on Twitter 1036839724155985922.mp4
```
楼主这个，并没有问题，可能是你没在地址上加引号。

不过我到是遇到另一个问题，拿到了 twitter 的 m3u8 地址，想要用 annie 下载，却只下到 一个 m3u8 文件的尴尬。如果 annie 能直接解析m3u8 和 TS url 就好了
比如：
`https://video.twimg.com/ext_tw_video/1036839536997752832/pu/pl/400x400/JEWRJ15P5wjtCoyh.m3u8`
