### ISSUE TITLE
[Youku]客户端无权播放,201

### ISSUE THREAD

**Issue by leeming0513** [iawia002/annie#235]
C:\Users\Administrator>annie https://v.youku.com/v_show/id_XMzE0ODM1ODg1Ng==.htm
l
2018/08/20 05:33:04 客户端无权播放,201

想请作者帮忙测试一下能不能解决这个问题呢? 　youtube-dl，you-get，现在都不能正常下载优酷，个人尝试改了多个ccode都无法解决。

**Comment by BearChu** [comment]
嗯 我这也201了 其他软件也都失效 麻烦作者修复 感谢~

**Comment by iawia002** [comment]
ping @jpacg，有新 ccode 吗

**Comment by jpacg** [comment]
@iawia002 0590可用

**Comment by iawia002** [comment]
0590 不行，我昨天试过，只能下前几分钟的

**Comment by iawia002** [comment]
@Justsoos 这是什么原理

**Comment by SeaHOH** [comment]
>使用到的开源项目
libmpv danmaku2ass you-get ykdl

没看见所谓“使用了youku终端模拟器规避检查”。
资源插件是通过 python 脚本爬取媒体信息，再通过 API 显示到播放器媒体库。
播放时通过 you-get 和 ykdl 获取媒体地址，特色功能是支持弹幕。

**Comment by vcan** [comment]
优酷好烦啊，怎么又改动了。同样适用0808失效。

**Comment by vcan** [comment]
0515 0519测试可用。
但是问题在于并不像之前用0808那样返回的是完整的数据。。
@iawia002

**Comment by jpacg** [comment]
@iawia002 新提交了一个pr，增加了一个生成utid方法，代码有点乱哈。

**Comment by iawia002** [comment]
@jpacg 感谢，我晚点看一下

**Comment by iawia002** [comment]
0.7.17，没有 1080，但是能下完整的

**Comment by xiebruce** [comment]
我更新到最新还是同样的问题：you-get: 客户端无权播放,201，要我自己加什么参数吗？我是直接 you-get http://xxxxx 这样下载的

**Comment by jpacg** [comment]
@xiebruce 走错片场了，是用annie下载，不是you-get
