### ISSUE TITLE
能请教下B站下载的实现吗

### ISSUE THREAD

**Issue by a747368836** [iawia002/annie#239]
`{
    "from": "local",
    "result": "suee",
    "quality": 64,
    "format": "flv720",
    "timelength": 466000,
    "accept_format": "flv,flv720,flv480,flv360",
    "accept_quality": [
        80,
        64,
        32,
        16
    ],
    "video_codecid": 7,
    "video_project": true,
    "seek_param": "start",
    "seek_type": "offset",
    "durl": [
        {
            "order": 1,
            "length": 466000,
            "size": 124402262,
            "ahead": "EZBW5QA=",
            "vhead": "AWQAH//hABlnZAAfrNlAUAW6EAAAAwAQAAADAyDxgxlgAQAFaOvs8jw=",
            "url": "http://upos-hz-mirrorkodo.acgvideo.com/upgcxcode/56/03/32810356/32810356-1-64.flv?e=ig8euxZM2rNcNbKBhbNVhoMHhwKMhwdEto8g5X10ugNcXBlqNCNEto8g5gNvNE3DN0B5tZlqNxTEto8BTrNvN05fqx6S5ahE9IMvXBvE2ENvNCImNEVEK9GVqJIwqa80WXIekXRE9IB5QK==&deadline=1534966104&dynamic=1&gen=playurl&oi=1912330591&os=kodo&platform=android&rate=452200&trid=6326abea7383400f9a31ce814615e56a&uipk=5&uipv=5&um_deadline=1534966104&um_sign=f9b7a06d5f3909ec3fecdb626c4f987f&upsig=10f95686983860a195ef8de5eedd7e83",
            "backup_url": [
                "http://upos-hz-mirrorcos.acgvideo.com/upgcxcode/56/03/32810356/32810356-1-64.flv?um_deadline=1534966104&platform=android&rate=452200&oi=1912330591&um_sign=f9b7a06d5f3909ec3fecdb626c4f987f&gen=playurl&os=cos&trid=6326abea7383400f9a31ce814615e56a"
            ]
        }
    ]
}`

得到这段json以后，里面的url直接打开会返回http 456 或者460  请问下这是不是和 ahead 和 vhead 这两个参数有关呢，这又是怎么处理的。。

**Comment by iawia002** [comment]
我记得 B 站要校验 Referer 这些

**Comment by Justsoos** [comment]
`#!/bin/bash
mpv --quiet --no-ytdl --user-agent="Mozilla/5.0 (Windows NT 10.0; WOW64; rv:51.0) Gecko/20100101 Firefox/51.0" --referrer="https://www.bilibili.com/" $@`
我用mpv看B站视频脚本，供参考
