### ISSUE TITLE
download video from bilibili.com which url not end with av+id will not exit after downloading.

### ISSUE THREAD

**Issue by tonyxyl** [iawia002/annie#24]
as the title says, tests below:
```
tony@tony-VirtualBox:~/下载$ 
   Site:   哔哩哔哩 bilibili.com
  Title:   【Perfume】 Music Station （2018.02.23） 无限未来
   Type:   video
Quality:   高清 720P
   Size:   52.13 MiB (54661154 Bytes)

 52.13 MiB / 52.13 MiB [============================] 100.00% 540.23 KiB/s 1m38s

[1]+  已完成               annie https://www.bilibili.com/video/av19976437?from=search
```
after downloading, the process will not exit, you should enter the "enter" key to exit.

**Comment by iawia002** [comment]
你是放到后台下载的？这和 URL 没有关系的

**Comment by iawia002** [comment]
稳定复现吗，我试了一下你这个视频，我能正常的下完哎

**Comment by tonyxyl** [comment]
![hashiqi](https://user-images.githubusercontent.com/12979723/37636603-f3d1ebfa-2c3d-11e8-970d-0f7e41c156c3.png)

**Comment by tonyxyl** [comment]
下载完了，就一直这个状态，没有退出进程。

**Comment by iawia002** [comment]
@tonyxyl 是不是卡在 100%，速度一直降就是不退出？所有视频都这样吗？我以前遇到过一次这种情况，我删了再下载又好了，现在还不知道原因

**Comment by tonyxyl** [comment]
我试过很多次b站的视频，因为我都是先搜索再下载的，url会带上from=search之类的尾巴, 从来没有下载完了会自动退出进程的情况。从下载结果来看，视频是已经完全下载好了的，不是临时文件的状态。

**Comment by iawia002** [comment]
@tonyxyl 后缀还是 .download 吗？

**Comment by tonyxyl** [comment]
不是啊，已经是flv了

**Comment by iawia002** [comment]
哦你这个不是我以前遇到过的那种情况，临时文件改名已经是最后一步了，做完这个它就应该退出了

**Comment by iawia002** [comment]
@tonyxyl 那你下载下来的视频文件是正常的吧

**Comment by tonyxyl** [comment]
这个问题可以暂时留给我，下午研究下，看能否提个PR，小小贡献一点。

**Comment by iawia002** [comment]
@tonyxyl 可以，非常感谢，先拉最新的代码，在这个基础上来调试

**Comment by tonyxyl** [comment]
其实倒是有个简单的解决办法，就是接收url后做下处理，过滤掉不需要的参数

**Comment by iawia002** [comment]
@tonyxyl 我好像知道了哎，你把你的 URL 打上引号，linux 把 URL 里面的 `$` 当作后台下载了吧，你试试呢

**Comment by iawia002** [comment]
`annie 'https://...'`

**Comment by tonyxyl** [comment]
试了下，确实可行。

**Comment by tonyxyl** [comment]
要不在文档里备注下这种情况？

**Comment by iawia002** [comment]
其实你说的针对 B 站过滤掉不需要的参数也是个解决方案，你有兴趣的话可以提个 PR，或者我来写

**Comment by iawia002** [comment]
@tonyxyl 可以，文档我来更新
