### ISSUE TITLE
release 0.7.17  优酷下载失败

### ISSUE THREAD

**Issue by Steven2131** [iawia002/annie#242]
annie https://v.youku.com/v_show/id_XMjI2ODA4MTQw.html
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x63da17]

goroutine 22 [running]:
github.com/iawia002/annie/request.Request(0x71eef5, 0x3, 0x0, 0x0, 0x0, 0x0, 0xc04232bd28, 0x0)
        /Users/mac/iawia002/go/src/github.com/iawia002/annie/request/request.go:97 +0xb47
github.com/iawia002/annie/downloader.writeFile(0x0, 0x0, 0xc04235c030, 0xc04232bd28, 0xc0420bf1e0, 0x0, 0x0, 0x0)
        /Users/mac/iawia002/go/src/github.com/iawia002/annie/downloader/downloader.go:91 +0x92
github.com/iawia002/annie/downloader.Save(0x0, 0x0, 0x2ee99a9, 0x0, 0x0, 0xc0420440c0, 0x56, 0xc04230d850, 0xf, 0xc0420bf1e0)
        /Users/mac/iawia002/go/src/github.com/iawia002/annie/downloader/downloader.go:181 +0x989
github.com/iawia002/annie/downloader.VideoData.Download.func1(0xc0420478e0, 0x0, 0x0, 0x2ee99a9, 0x0, 0x0, 0xc0420440c0, 0x56, 0xc04230d850, 0xf, ...)
        /Users/mac/iawia002/go/src/github.com/iawia002/annie/downloader/downloader.go:329 +0xba
created by github.com/iawia002/annie/downloader.VideoData.Download
        /Users/mac/iawia002/go/src/github.com/iawia002/annie/downloader/downloader.go:327 +0x3b9
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x63da17]

goroutine 23 [running]:
github.com/iawia002/annie/request.Request(0x71eef5, 0x3, 0x0, 0x0, 0x0, 0x0, 0xc042325d28, 0x0)
        /Users/mac/iawia002/go/src/github.com/iawia002/annie/request/request.go:97 +0xb47
github.com/iawia002/annie/downloader.writeFile(0x0, 0x0, 0xc042004088, 0xc042325d28, 0xc0420bf1e0, 0x0, 0x0, 0x0)
        /Users/mac/iawia002/go/src/github.com/iawia002/annie/downloader/downloader.go:91 +0x92
github.com/iawia002/annie/downloader.Save(0x0, 0x0, 0x302f3f1, 0x0, 0x0, 0xc0420440c0, 0x56, 0xc04230d870, 0xf, 0xc0420bf1e0)
        /Users/mac/iawia002/go/src/github.com/iawia002/annie/downloader/downloader.go:181 +0x989
github.com/iawia002/annie/downloader.VideoData.Download.func1(0xc0420478e0, 0x0, 0x0, 0x302f3f1, 0x0, 0x0, 0xc0420440c0, 0x56, 0xc04230d870, 0xf, ...)
        /Users/mac/iawia002/go/src/github.com/iawia002/annie/downloader/downloader.go:329 +0xba
created by github.com/iawia002/annie/downloader.VideoData.Download
        /Users/mac/iawia002/go/src/github.com/iawia002/annie/downloader/downloader.go:327 +0x3b9

**Comment by wen2006953** [comment]
你这个地址有问题吧，直接访问都打不开

**Comment by monofish** [comment]
是不是ccode什么的又变了，我用you-get和youtube-dl都报201，annie和楼主一样

**Comment by iawia002** [comment]
这个视频优酷只返回了 m3u8 的 URL，我要先解析 m3u8 得到真正的分片地址才能开始下载，但是现在在处理小片段的时候有点问题，只能访问前几十个片段，我测了一下一般从 80 多开始就要 timeout 了（这个视频大概有 200 多个片段），不清楚这是优酷的什么机制

**Comment by iawia002** [comment]
ccode 不一样接口返回的东西不一样吧，我这边 0511 都用不了的

**Comment by SeaHOH** [comment]
0515 也可以

**Comment by iawia002** [comment]
0515 确实可以，我明天更新一下默认的，现在可以 `annie -ccode 0515 ...` 直接用
