### ISSUE TITLE
爱奇艺的cookie怎么加载啊

### ISSUE THREAD

**Issue by weidongzhou1994** [iawia002/annie#248]
爱奇艺的cookie 里面需要加载哪些数据？
![image](https://user-images.githubusercontent.com/40510496/44645614-cf5a5a00-aa0a-11e8-99e6-5b0a60a75d20.png)

**Comment by iawia002** [comment]
一般不知道加载哪个就全写上

你是要下 VIP 相关的吗，爱奇艺现在还不支持， #50
