### ISSUE TITLE
优酷有些视频有密码怎么破？？

### ISSUE THREAD

**Issue by lssb** [iawia002/annie#249]
没有见到可以输入密码的参数。。。

**Comment by iawia002** [comment]
现在还不支持

**Comment by icerleer** [comment]
在浏览器登陆之后，获取 Cookie 信息，然后使用挂在  Cookie 的参数 -c  应该就可以下载了吧，我没有VIP账户，没有尝试

**Comment by lssb** [comment]
> 在浏览器登陆之后，获取 Cookie 信息，然后使用挂在 Cookie 的参数 -c 应该就可以下载了吧，我没有VIP账户，没有尝试

不不不，不是这个意思，， 是有些视频有单独的密码。。 例如
http://v.youku.com/v_show/id_XMzA5OTAzMzMxMg==.html?spm=a2h3j.8428770.3416059.1

**Comment by tea1111980** [comment]
@icerleer Cookie 有那么多参数，到底是取哪一个参数啊。

**Comment by tea1111980** [comment]
@airdge  请指教，我不是程序员，所以不能理解你所说的 ups/acs是什么。具体的操作步骤是怎么样的。

**Comment by SeaHOH** [comment]
意思就是现在不行。

**Comment by tea1111980** [comment]
@airdge  我已经找到了，谢谢

**Comment by iawia002** [comment]
0.9.3 `-password` 参数
