### ISSUE TITLE
[youtube] can not download 4K video.

### ISSUE THREAD

**Issue by fuchanghao** [iawia002/annie#250]
$ annie -i https://www.youtube.com/watch?v=vjF9GgrY9c0

panic: runtime error: index out of range

goroutine 1 [running]:
github.com/iawia002/annie/extractors/youtube.youtubeDownload(0xc04200a270, 0x2b, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /Users/mac/iawia002/go/src/github.com/iawia002/annie/extractors/youtube/youtube.go:107 +0x452
github.com/iawia002/annie/extractors/youtube.Download(0xc04200a270, 0x2b)
        /Users/mac/iawia002/go/src/github.com/iawia002/annie/extractors/youtube/youtube.go:69 +0x447
main.download(0xc04200a270, 0x2b)
        /Users/mac/iawia002/go/src/github.com/iawia002/annie/main.go:75 +0x441
main.main()
        /Users/mac/iawia002/go/src/github.com/iawia002/annie/main.go:134 +0xe7

**Comment by iqinqin** [comment]
G:\Code\python\PyQt\Vdownload>annie -i https://www.youtube.com/watch?v=vjF9GgrY9
c0

 Site:      YouTube youtube.com
 Title:     Cyberpunk 2077 Gameplay Reveal — 48-minute walkthrough
 Type:      video
 Streams:   # All available quality
     [default]  -------------------
     Quality:         2160p video/webm; codecs="vp9"
     Size:            5085.11 MiB (5332127522 Bytes)
     # download with: annie "URL"

     [271]  -------------------
     Quality:         1440p video/webm; codecs="vp9"
     Size:            2028.72 MiB (2127269200 Bytes)
     # download with: annie -f 271 "URL"

     [137]  -------------------
     Quality:         1080p video/mp4; codecs="avc1.640028"
     Size:            816.15 MiB (855794253 Bytes)
     # download with: annie -f 137 "URL"

     [248]  -------------------
     Quality:         1080p video/webm; codecs="vp9"
     Size:            781.05 MiB (818992784 Bytes)
     # download with: annie -f 248 "URL"

     [136]  -------------------
     Quality:         720p video/mp4; codecs="avc1.4d401f"
     Size:            474.73 MiB (497790379 Bytes)
     # download with: annie -f 136 "URL"

     [247]  -------------------
     Quality:         720p video/webm; codecs="vp9"
     Size:            455.05 MiB (477158023 Bytes)
     # download with: annie -f 247 "URL"

     [135]  -------------------
     Quality:         480p video/mp4; codecs="avc1.4d401f"
     Size:            271.39 MiB (284570870 Bytes)
     # download with: annie -f 135 "URL"

     [244]  -------------------
     Quality:         480p video/webm; codecs="vp9"
     Size:            247.61 MiB (259635583 Bytes)
     # download with: annie -f 244 "URL"

     [243]  -------------------
     Quality:         360p video/webm; codecs="vp9"
     Size:            157.46 MiB (165113388 Bytes)
     # download with: annie -f 243 "URL"

     [134]  -------------------
     Quality:         360p video/mp4; codecs="avc1.4d401e"
     Size:            155.42 MiB (162973551 Bytes)
     # download with: annie -f 134 "URL"

     [242]  -------------------
     Quality:         240p video/webm; codecs="vp9"
     Size:            104.11 MiB (109168798 Bytes)
     # download with: annie -f 242 "URL"

     [133]  -------------------
     Quality:         240p video/mp4; codecs="avc1.4d4015"
     Size:            85.56 MiB (89716256 Bytes)
     # download with: annie -f 133 "URL"

     [278]  -------------------
     Quality:         144p video/webm; codecs="vp9"
     Size:            75.45 MiB (79111862 Bytes)
     # download with: annie -f 278 "URL"

     [160]  -------------------
     Quality:         144p video/mp4; codecs="avc1.4d400c"
     Size:            64.78 MiB (67927903 Bytes)
     # download with: annie -f 160 "URL"

     [251]  -------------------
     Quality:         audio/webm; codecs="opus"
     Size:            44.47 MiB (46625322 Bytes)
     # download with: annie -f 251 "URL"

     [140]  -------------------
     Quality:         audio/mp4; codecs="mp4a.40.2"
     Size:            43.96 MiB (46098183 Bytes)
     # download with: annie -f 140 "URL"

     [171]  -------------------
     Quality:         audio/webm; codecs="vorbis"
     Size:            39.87 MiB (41804637 Bytes)
     # download with: annie -f 171 "URL"

     [250]  -------------------
     Quality:         audio/webm; codecs="opus"
     Size:            22.52 MiB (23618218 Bytes)
     # download with: annie -f 250 "URL"

     [249]  -------------------
     Quality:         audio/webm; codecs="opus"
     Size:            17.07 MiB (17901079 Bytes)
     # download with: annie -f 249 "URL"

**Comment by iawia002** [comment]
Try the latest version

```console
$ annie -i https://www.youtube.com/watch\?v\=vjF9GgrY9c0

 Site:      YouTube youtube.com
 Title:     Cyberpunk 2077 Gameplay Reveal — 48-minute walkthrough
 Type:      video
 Streams:   # All available quality
     [default]  -------------------
     Quality:         2160p video/webm; codecs="vp9"
     Size:            5085.11 MiB (5332127522 Bytes)
     # download with: annie "URL"

     [271]  -------------------
     Quality:         1440p video/webm; codecs="vp9"
     Size:            2028.72 MiB (2127269200 Bytes)
     # download with: annie -f 271 "URL"

     [137]  -------------------
     Quality:         1080p video/mp4; codecs="avc1.640028"
     Size:            816.15 MiB (855794253 Bytes)
     # download with: annie -f 137 "URL"
```

**Comment by iawia002** [comment]
any response?
