### ISSUE TITLE
youku 大部分免费视频都提示客户端无法播放了

### ISSUE THREAD

**Issue by xiongzhenglong** [iawia002/annie#256]
应该算法升级了 ，大佬看下

**Comment by xukongop** [comment]
`客户端无权播放,201`

**Comment by ochriste** [comment]
+1

**Comment by YuetAu** [comment]
-ccode 0590 Just died.

**Comment by YuetAu** [comment]
Any solution?
有解決方案嗎?

**Comment by ochriste** [comment]
im using -ccode 0590 right now, but maybe it doesnt work for new videos.
do you have an example of video where it doesnt work ?

**Comment by YuetAu** [comment]
-ccode 0590 can activate the download but it lag (or stop downloading) after downloaded the first 5 minutes or sth

**Comment by ochriste** [comment]
isnt that more like a network/routing issue ?
I just finished a 985Mb/1h51 movie without problem

you know you can restart a download and it will skip all the parts already downloaded, yes ?

**Comment by piaoyunsoft** [comment]
你们用什么客户端播放啊？ 我下载回来直接网页播放挺好的啊

**Comment by iawia002** [comment]
我试了一下 0590 可以

```console
$ annie -ccode 0590 -i http://v.youku.com/v_show/id_XMzUzMjE3NDczNg\=\=.html

 Site:      优酷 youku.com
 Title:     车事儿：智能汽车已经不在遥远 东风风光iX5发布
 Type:      video
 Streams:   # All available quality
     [default]  -------------------
     Quality:         mp4hd2v2 1280x720
     Size:            21.64 MiB (22692900 Bytes)
     # download with: annie "URL"
```

**Comment by ochriste** [comment]
@YuetAu I am now seeing the same behavior you noticed:
` 73.80 MiB / 131.70 MiB [=================================================================================>----------------------------------------------------------------]  56.04% 452.47 KiB/s 2m47s
Merging video parts into ?? ???? 21 ????.mp4`
the parts merge happens before all parts have been downloaded

**Comment by ochriste** [comment]
mmm, the listed video pieces mismatch the total size:
```
        "default": {
            "URLs": [
                {
                    "URL": "http://vali.cp31.ott.cibntv.net/6774451A5853F719392393B78/03000B07005ADE4329FDD9E50AE6C1784FE034-6D4E-939C-AA08-1E44D7E8A147.mp4?ccode=0590\u0026duration=195\u0026expire=18
000\u0026psid=481a1efc8b7a7e9a5daa43e588ea585d\u0026sp=1000\u0026ups_client_netip=59d96d53\u0026ups_ts=1535715971\u0026ups_userid=\u0026utid=gRgQFH5eq1oCAVnZbVOaLCWX\u0026vid=XMzQxNzM4NDM1Ng%3D%3D\u00
26vkey=B5e8fa6fe822a69c3f4c94534185c62de\u0026s=16efbfbd6defbfbd066d",
                    "Size": 21113152,
                    "Ext": "mp4"
                },
                {
                    "URL": "http://vali.cp31.ott.cibntv.net/697667A78F93D71868D822E26/03000B07015ADE4329FDD9E50AE6C1784FE034-6D4E-939C-AA08-1E44D7E8A147.mp4?ccode=0590\u0026duration=197\u0026expire=18
000\u0026psid=481a1efc8b7a7e9a5daa43e588ea585d\u0026sp=1000\u0026ups_client_netip=59d96d53\u0026ups_ts=1535715971\u0026ups_userid=\u0026utid=gRgQFH5eq1oCAVnZbVOaLCWX\u0026vid=XMzQxNzM4NDM1Ng%3D%3D\u00
26vkey=B3e479f3a6b29dba4be94fa7fdba9db81\u0026s=16efbfbd6defbfbd066d",
                    "Size": 19359506,
                    "Ext": "mp4"
                },
                {
                    "URL": "http://vali.cp31.ott.cibntv.net/6574451A57338716601B743D9/03000B07025ADE4329FDD9E50AE6C1784FE034-6D4E-939C-AA08-1E44D7E8A147.mp4?ccode=0590\u0026duration=195\u0026expire=18
000\u0026psid=481a1efc8b7a7e9a5daa43e588ea585d\u0026sp=1000\u0026ups_client_netip=59d96d53\u0026ups_ts=1535715971\u0026ups_userid=\u0026utid=gRgQFH5eq1oCAVnZbVOaLCWX\u0026vid=XMzQxNzM4NDM1Ng%3D%3D\u00
26vkey=B6091b6b18fb8386a61a2f8bc375264c4\u0026s=16efbfbd6defbfbd066d",
                    "Size": 21422890,
                    "Ext": "mp4"
                },
                {
                    "URL": "http://vali.cp31.ott.cibntv.net/6574FB49A6132713EF390669A/03000B07035ADE4329FDD9E50AE6C1784FE034-6D4E-939C-AA08-1E44D7E8A147.mp4?ccode=0590\u0026duration=193\u0026expire=18
000\u0026psid=481a1efc8b7a7e9a5daa43e588ea585d\u0026sp=1000\u0026ups_client_netip=59d96d53\u0026ups_ts=1535715971\u0026ups_userid=\u0026utid=gRgQFH5eq1oCAVnZbVOaLCWX\u0026vid=XMzQxNzM4NDM1Ng%3D%3D\u00
26vkey=B20504c82884ddfb32d90ae6c25098e03\u0026s=16efbfbd6defbfbd066d",
                    "Size": 15488663,
                    "Ext": "mp4"
                }
            ],
            "Quality": "mp4hd2v2 1280x720",
            "Size": 138096715
```
4 pieces listed: 21113152 + 19359506 + 21422890 + 15488663 = 77384211
which is not equal to total size: 138096715

either the parsing of the metadata returned from youku is wrong, or something is broken on youku side directly.

**Comment by iawia002** [comment]
@ochriste Youku only returned the first few minutes of data

**Comment by ochriste** [comment]
@iawia002 you mean in the "Formats" URLs list ?
then it's either a bug in youku side, or they intentionally cut the pieces list, like they do with VIP videos when the user is not authenticated.

**Comment by iawia002** [comment]
> or they intentionally cut the pieces list, like they do with VIP videos when the user is not authenticated.

yep

**Comment by ochriste** [comment]
:(

**Comment by zhengjiudiqiu** [comment]
-ccode 0590，不能下载完整的优酷视频。普通视频也只能下载视频的前几分钟，后面的部分无法下载。

**Comment by ochriste** [comment]
this problem doesnt occur with all videos.
I just successfully donwloaded a 210Mb file:
```
 Site:      ?? youku.com
 Title:     ???? ??? 02 ?????
 Type:      video
 Stream:
     [default]  -------------------
     Quality:         mp4hd2v2 1280x720 ??
     Size:            210.44 MiB (220658938 Bytes)
     # download with: annie "URL"

 210.44 MiB / 210.44 MiB [============...=================] 100.00% 813.14 KiB/s 4m25s
Merging video parts into ???? ??? 02 ?????.mp4
```
which make me think it's just something broken on some youku servers

**Comment by ochriste** [comment]
more specifically: 
all videos which are 4 pieces or less are downloading OK,
all video which are more than 4 pieces are broken because the pieces listing only list the first 4 pieces.

**Comment by iqinqin** [comment]
现在加载cookies都没用了，提示客户端无权播放201

**Comment by ochriste** [comment]
try with option "-n 1"

**Comment by iawia002** [comment]
@jpacg 你有新 ccode 吗

**Comment by SeaHOH** [comment]
0517

**Comment by ochriste** [comment]
@iqinqin "-n" will solve the error 201, it will not solve the partial download.
The partial download is caused by the fact the number of pieces listed in the pieces list at the start of the download is wrong,
you can easily see that when using the "-i -j" options, the "get.json" query request the details of the streams to youku server, but in the json data returned by youku, the pieces list (as "segs" in the returned json) are incomplet.
to solve the current problem, it is required to understand why youku server return an incomplet pieces list for the requested video.

**Comment by iawia002** [comment]
0.7.20

have a try, thanks to @jpacg
