### ISSUE TITLE
no such file or directory

### ISSUE THREAD

**Issue by retiredhide** [iawia002/annie#259]
annie: version 0.7.20, A fast, simple and clean video downloader.

請問影片看到但下載不到怎辦？

$ annie -i 'https://v.youku.com/v_show/id_XNDUwMDQ3NTI=.html'

 Site:      优酷 youku.com
 Title:     暗夜边缘 01
 Type:      video
 Streams:   # All available quality
     [default]  -------------------
     Quality:         flvhd 384x294
     Size:            124.51 MiB (130560203 Bytes)
     # download with: annie "URL"

$ annie 'https://v.youku.com/v_show/id_XNDUwMDQ3NTI=.html'

 Site:      优酷 youku.com
 Title:     暗夜边缘 01
 Type:      video
 Stream:   
     [default]  -------------------
     Quality:         flvhd 384x294
     Size:            124.51 MiB (130560203 Bytes)
     # download with: annie "URL"

 0 B / 124.51 MiB [----------------------------------------------------]   0.00%2018/09/04 01:58:46 open 暗夜边缘 01[9].net/player/getFlvPath/sid/05359975261321274ca46/st/flv/fileid/0300020B004C5CF36B8BB800DA1A7EC3270A50-680C-D3DB-D7E0-193CE296C337.download: no such file or directory
2018/09/04 01:58:46 open 暗夜边缘 01[1].net/player/getFlvPath/sid/05359975261321274ca46/st/flv/fileid/0300020B004C5CF36B8BB800DA1A7EC3270A50-680C-D3DB-D7E0-193CE296C337.download: no such file or directory

$ annie -d 'https://v.youku.com/v_show/id_XNDUwMDQ3NTI=.html'

annie: version 0.7.20, A fast, simple and clean video downloader.

URL:         http://log.mmstat.com/eg.js
Method:      GET
Headers:     http.Header{
    "Accept-Language": {"en-US,en;q=0.8"},
    "User-Agent":      {"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.146 Safari/537.36"},
    "Accept":          {"text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"},
    "Accept-Charset":  {"UTF-8,*;q=0.5"},
    "Accept-Encoding": {"gzip,deflate,sdch"},
    "Referer":         {"https://v.youku.com"},
}
Status Code: 200

URL:         https://ups.youku.com/ups/get.json?vid=XNDUwMDQ3NTI=&ccode=0103010102&client_ip=192.168.1.1&client_ts=1535997&utid=W40GZU1lgiEDAI0%2Bq2GfImN%2B&ckey=7B19C0AB12633B22E7FE81271162026020570708D6CC189E4924503C49D243A0DE6CD84A766832C2C99898FC5ED31F3709BB3CDD82C96492E721BDD381735026
Method:      GET
Headers:     http.Header{
    "Accept-Encoding": {"gzip,deflate,sdch"},
    "Accept-Language": {"en-US,en;q=0.8"},
    "User-Agent":      {"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.146 Safari/537.36"},
    "Accept":          {"text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"},
    "Referer":         {"https://v.youku.com"},
    "Accept-Charset":  {"UTF-8,*;q=0.5"},
}
Status Code: 200

 Site:      优酷 youku.com
 Title:     暗夜边缘 01
 Type:      video
 Stream:   
     [default]  -------------------
     Quality:         flvhd 384x294
     Size:            124.51 MiB (130560203 Bytes)
     # download with: annie "URL"

 0 B / 124.51 MiB [----------------------------------------------------]   0.00%2018/09/04 02:01:09 open 暗夜边缘 01[0].net/player/getFlvPath/sid/053599766918112ffd44f/st/flv/fileid/0300020B004C5CF36B8BB800DA1A7EC3270A50-680C-D3DB-D7E0-193CE296C337.download: no such file or directory
2018/09/04 02:01:09 open 暗夜边缘 01[3].net/player/getFlvPath/sid/053599766918112ffd44f/st/flv/fileid/0300020B004C5CF36B8BB800DA1A7EC3270A50-680C-D3DB-D7E0-193CE296C337.download: no such file or directory
2018/09/04 02:01:09 open 暗夜边缘 01[4].net/player/getFlvPath/sid/053599766918112ffd44f/st/flv/fileid/0300020B004C5CF36B8BB800DA1A7EC3270A50-680C-D3DB-D7E0-193CE296C337.download: no such file or directory
2018/09/04 02:01:09 open 暗夜边缘 01[2].net/player/getFlvPath/sid/053599766918112ffd44f/st/flv/fileid/0300020B004C5CF36B8BB800DA1A7EC3270A50-680C-D3DB-D7E0-193CE296C337.download: no such file or directory

**Comment by jpacg** [comment]
我这里测试是可以的，你看一下是不是优酷地区限制了
```
➜  Downloads annie https://v.youku.com/v_show/id_XNDUwMDQ3NTI\=.html

 Site:      优酷 youku.com
 Title:     暗夜边缘 01
 Type:      video
 Stream:
     [default]  -------------------
     Quality:         flvhd 384x294
     Size:            124.51 MiB (130560203 Bytes)
     # download with: annie "URL"

 124.51 MiB / 124.51 MiB [====================================================================================================] 100.00% 3.63 MiB/s 34s
Merging video parts into 暗夜边缘 01.mp4
```

**Comment by retiredhide** [comment]
用proxy解決了謝謝！
