### ISSUE TITLE
优酷和b站vip视频无法正常下载

### ISSUE THREAD

**Issue by yukiii3104** [iawia002/annie#260]
优酷上需要vip才能看的视频不管用不用cookies都显示“欲看此视频请先登录”
b站大会员的1080p+有同样的问题
不知是否跟cookies有关
求助！谢谢！

**Comment by iawia002** [comment]
你 cookie 不对吧，你怎么操作的，命令贴上来看一下

**Comment by yukiii3104** [comment]
我是之前看别人的教程说可以用annie -c 读取保存到本地的cookies.txt 我的txt文档是chrome插件直接下载的 不知道是不是那个txt的原因？
命令就是 annie -c cookies.txt http://.......

**Comment by iawia002** [comment]
确实可以读文件中的 cookies

你的 cookie 是什么格式的？如果是 key value 格式的，文件只能有一行，如果是 Netscape Cookie 就无所谓

**Comment by iawia002** [comment]
优酷我没有会员，不能确定只加载 VIP cookie 能不能工作，但是 B 站我是单独适配过的，这个肯定可以的

**Comment by yukiii3104** [comment]
有没有什么提取netscape cookie的方法呢 我直接用的chrome插件下载我也不知道那个cookies是什么格式

**Comment by yukiii3104** [comment]
[cookies.txt](https://github.com/iawia002/annie/files/2348762/cookies.txt)
这个是我直接chrome插件下载的 或许是这个cookie不合适的原因？

**Comment by jpacg** [comment]
这个ccode是优酷TV版的，不支持用Cookie下载VIP。

**Comment by SeaHOH** [comment]
赶快删除吧，居然公开展示。

**Comment by yukiii3104** [comment]
删了删了

**Comment by yukiii3104** [comment]
@jpacg 哪个的ccode？所以是？

**Comment by iawia002** [comment]
你的就是 Netscape 格式的

@jpacg 的意思是下不了 VIP 的

**Comment by yukiii3104** [comment]
所以是优酷vip的视频下不了？

**Comment by SeaHOH** [comment]
@jpacg 是 TV 版啊，是我记混了吗？请问这个 ccode 和移动版有没有关系？

**Comment by iawia002** [comment]
@jpacg bug 是 `index out of range` 那个吗，我刚才试的时候注意到已经改了 2cd3ce1

**Comment by yukiii3104** [comment]
@iawia002 我需要更新annie吗 试着用-ccode 0590还是显示index out of range

**Comment by jpacg** [comment]
@iawia002 是的，改完那就没问题了

**Comment by iawia002** [comment]
@yukiii3104 还没发版本，应该要等到周末发，你如果有 go 环境的话可以直接安装最新的代码

**Comment by iawia002** [comment]
@yukiii3104 不会的话就等下个版本吧

**Comment by jpacg** [comment]
@SeaHOH 0103010102是从TV版里找的，手机版也是这种长的，TV版比手机版的简单，优酷感觉最近好难弄了，以后可能要完整的分析优酷解析了。

**Comment by yukiii3104** [comment]
@iawia002 好的好的！！谢谢！！！

**Comment by SeaHOH** [comment]
@jpacg 谢谢讲解，感觉你们好厉害。我只会简单分析下，一混淆的厉害就看不懂了。

**Comment by SeaHOH** [comment]
> 指定cookie下载VIP视频可以使用ccode: 0590

**Comment by jsnjycwyz** [comment]
@SeaHOH 还是不行，刚刚有一下成功下载了，之后再输同样的命令还是报错：客户端无权播放,201 ，已经用了-ccode 0590了

**Comment by SeaHOH** [comment]
> 指定cookie下载VIP视频

你光说 ccode，其它呢？我看 jpacg 的结果挺正常的。

**Comment by jsnjycwyz** [comment]
就是用chrome插件下的cookie啊，刚刚有一次成功了，然后我取消了，后面就算复制的一样的命令都下不了

**Comment by SeaHOH** [comment]
不是成功过嘛，再试试其它 ccode 吧。

**Comment by jsnjycwyz** [comment]
05开头的全试过了。。。

**Comment by jpacg** [comment]
@jsnjycwyz 等一等，代码还有Bug，加cookie时utid没设置上

**Comment by jsnjycwyz** [comment]
@jpacg 感谢大佬！辛苦了

**Comment by jsnjycwyz** [comment]
@jpacg 完美，感谢！！依然需要加ccode，加了就满速下载了！

**Comment by jpacg** [comment]
@jsnjycwyz 那就没问题了，程序默认的ccode是TV版的，如果是优酷的酷喵VIP会员，不指定ccode也能下载。

```
➜  ~ annie -c ~/cookies.txt https://v.youku.com/v_show/id_XMzgxMDY4Njk2OA\=\=.html

 Site:      优酷 youku.com
 Title:     香蜜沉沉烬如霜 TV版 香蜜沉沉烬如霜 63
 Type:      video
 Stream:
     [default]  -------------------
     Quality:         mp4hd3 1920x1080 国语
     Size:            761.17 MiB (798141401 Bytes)
     # download with: annie "URL"

 761.17 MiB / 761.17 MiB [==============================================================================] 100.00% 7.07 MiB/s 1m47s
Merging video parts into 香蜜沉沉烬如霜 TV版 香蜜沉沉烬如霜 63.mp4
```

**Comment by iawia002** [comment]
0.8.0
