### ISSUE TITLE
YOUTUBE视频解析异常

### ISSUE THREAD

**Issue by zhz1237ok** [iawia002/annie#264]
annie -s 127.0.0.1:1080 https://www.youtube.com/watch?v=jyHwxu6WVIg
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/iawia002/annie/extractors/youtube.youtubeDownload(0xc042086030, 0x2b, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /Users/mac/iawia002/go/src/github.com/iawia002/annie/extractors/youtube/youtube.go:107 +0x452
github.com/iawia002/annie/extractors/youtube.Download(0xc042086030, 0x2b)
        /Users/mac/iawia002/go/src/github.com/iawia002/annie/extractors/youtube/youtube.go:69 +0x447
main.download(0xc042086030, 0x2b)
        /Users/mac/iawia002/go/src/github.com/iawia002/annie/main.go:75 +0x441
main.main()
        /Users/mac/iawia002/go/src/github.com/iawia002/annie/main.go:134 +0xe7

不知道什么原因

**Comment by iqinqin** [comment]
请登录，以便我们确认您的年龄
本视频可能不适合某些用户观看。
必须加载Cookies才能下载

**Comment by zhz1237ok** [comment]
那么该如何用annie加载cookies呢

**Comment by iawia002** [comment]
可以用 Chrome 上的插件把 cookie 下载到本地，然后 `-c "cookie 的路径"` 就行了
