### ISSUE TITLE
The system cannot find the path specified

### ISSUE THREAD

**Issue by BearChu** [iawia002/annie#267]
http://v.youku.com/v_show/id_XMzYzNDA0OTIyOA==.html?spm=a2hzp.8244740.0.0

 Site:      优酷 youku.com
 Title:     WAVEYA 最新热舞 - 爱莉安娜·格兰德《No Tears Left to Cry》
 Type:      video
 Stream:
     [default]  -------------------
     Quality:         mp4hd3 1920x1080
     Size:            27.05 MiB (28366251 Bytes)
     # download with: annie "URL"

 0 B / 27.05 MiB [--------------------------------------------------------------------------------------------]   0.00%Downloading [36mhttp://v.youku.com/v_show/id_XMzYzNDA0OTIyOA==.html?spm=a2hzp.8244740.0.0[0m error:
[31mopen WAVEYA 最新热舞 - 爱莉安娜·格兰德《No Tears Left to Cry》.net\player\getFlvPath\sid\0536495088967127a9d60\st\mp4\fileid\03000C01005B0E288A448392F278B91D07C10C-B1B0-4AA8-A3B8-01938F01646A.download: The system cannot find the path specified.[0m

之前一直都能用,现在突然多了这个错误,其他github的没这问题,请教怎么修复~

**Comment by jpacg** [comment]
我这里下载没问题，你检查一下是不是中文目录之类的问题，把临时文件删除重试。
```
➜  ~ annie http://v.youku.com/v_show/id_XMzYzNDA0OTIyOA\=\=.html

 Site:      优酷 youku.com
 Title:     WAVEYA 最新热舞 - 爱莉安娜·格兰德《No Tears Left to Cry》
 Type:      video
 Stream:
     [default]  -------------------
     Quality:         mp4hd3 1920x1080
     Size:            27.05 MiB (28366251 Bytes)
     # download with: annie "URL"

 27.05 MiB / 27.05 MiB [==================================================================================] 100.00% 1.32 MiB/s 20s
➜  ~
```

**Comment by BearChu** [comment]
我用exe的,英文目录,放到桌面也是The system cannot find the path specified

**Comment by iawia002** [comment]
这个很奇怪，想不通是什么原因，之前也出过一次类似的问题 #259

**Comment by BearChu** [comment]
没有代理

**Comment by BearChu** [comment]
我下载其他网站的视频 就无此错误 应该就优酷才有的
 Site:      YouTube youtube.com
 Title:     G.E.M.【倒數 TIK TOK】Official MV [HD] 鄧紫棋
 Type:      video
 Stream:
     [default]  -------------------
     Quality:         1080p video/mp4; codecs="avc1.640028"
     Size:            64.02 MiB (67129892 Bytes)
     # download with: annie "URL"

 64.02 MiB / 64.02 MiB [=======================================================================] 100.00% 28.74 MiB/s 2s
Merging video parts into G.E.M.【倒數 TIK TOK】Official MV [HD] 鄧紫棋.mp4

**Comment by iawia002** [comment]
@jpacg 可以，破案了
