### ISSUE TITLE
b站批量下载问题

### ISSUE THREAD

**Issue by gq20110204** [iawia002/annie#271]
b站批量下载有1080+清晰度的视频时，只有第一个视频能下载到1080+的清晰度，往后都只能下载到1080清晰度

**Comment by iawia002** [comment]
这个问题很奇怪，一般是访问 1080+ 的 API 的时候出了什么奇怪的错导致的。我会尝试修复这个问题

**Comment by gq20110204** [comment]
感谢回复。我现在的处理方法就是含有1080+的单独进行下载。

**Comment by iawia002** [comment]
更新一下 0.8.1，尝试一下把重试次数 `-retry` 设置地大一点（默认是 100）

不行的话就先看一下最高清晰度是什么，然后用 `annie -f ` 来指定只下载最高清晰度的，如果出现类似的错会跳过下载而不是下载一个低清晰度的
