### ISSUE TITLE
希望增加参数，下载 B站 视频 flv 可以自动转 mp4

### ISSUE THREAD

**Issue by conphi** [iawia002/annie#276]

**Comment by iawia002** [comment]
你可以尝试用第三方的视频转换工具

**Comment by conphi** [comment]
我自己针对B站写了一个循环sh，可以批量转化，速度快（安装ffmpeg）
代码如下：for f in *.flv;do ffmpeg -i "$f" -c copy ${f%flv}mp4;done
PS（这个软件如何下载某个用户的全部B站视频呢，现在好像只能下载全部列表）

**Comment by iawia002** [comment]
现在还不支持

**Comment by conphi** [comment]
不知道目前有没有可以下载B站某个用户全部视频的工具呢？

**Comment by bigbear1024** [comment]
我自己用這個方式下載全部視頻
https://www.bilibili.com/video/av38492390
