### ISSUE TITLE
[bug] 1-11 are ok, but 12 are wrong

### ISSUE THREAD

**Issue by terriblegod** [iawia002/annie#277]
annie -i https://www.bilibili.com/video/av32108283/
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/iawia002/annie/extractors/bilibili.Download(0x7ffeefbffbd1, 0x2a, 0x133f3c4, 0x8)
	/private/tmp/annie-20180916-64042-1uurlwu/annie-0.8.1/src/github.com/iawia002/annie/extractors/bilibili/bilibili.go:148 +0xb0e
main.download(0x7ffeefbffbd1, 0x2a, 0xc0000b1de0, 0x25dc86930d5be3b3)
	/private/tmp/annie-20180916-64042-1uurlwu/annie-0.8.1/src/github.com/iawia002/annie/main.go:74 +0x895
main.main()
	/private/tmp/annie-20180916-64042-1uurlwu/annie-0.8.1/src/github.com/iawia002/annie/main.go:155 +0x11c
meikongdeMacBook-Pro:Downloads terriblegod$ annie -i -p https://www.bilibili.com/bangumi/play/ep232338/

 Site:      哔哩哔哩 bilibili.com
 Title:     异界少女召唤术：第1话 魔王演技
 Type:      video
 Streams:   # All available quality
     [80]  -------------------
     Quality:         高清 1080P
     Size:            372.88 MiB (390991480 Bytes)
     # download with: annie -f 80 ...

     [64]  -------------------
     Quality:         高清 720P
     Size:            287.96 MiB (301946621 Bytes)
     # download with: annie -f 64 ...

     [32]  -------------------
     Quality:         清晰 480P
     Size:            147.91 MiB (155098500 Bytes)
     # download with: annie -f 32 ...

     [16]  -------------------
     Quality:         流畅 360P
     Size:            72.91 MiB (76446865 Bytes)
     # download with: annie -f 16 ...

 Site:      哔哩哔哩 bilibili.com
 Title:     异界少女召唤术：第2话 最强新人
 Type:      video
 Streams:   # All available quality
     [80]  -------------------
     Quality:         高清 1080P
     Size:            335.98 MiB (352301653 Bytes)
     # download with: annie -f 80 ...

     [64]  -------------------
     Quality:         高清 720P
     Size:            259.66 MiB (272271218 Bytes)
     # download with: annie -f 64 ...

     [32]  -------------------
     Quality:         清晰 480P
     Size:            137.69 MiB (144381246 Bytes)
     # download with: annie -f 32 ...

     [16]  -------------------
     Quality:         流畅 360P
     Size:            72.44 MiB (75954966 Bytes)
     # download with: annie -f 16 ...

 Site:      哔哩哔哩 bilibili.com
 Title:     异界少女召唤术：第3话 魔族袭来
 Type:      video
 Streams:   # All available quality
     [80]  -------------------
     Quality:         高清 1080P
     Size:            381.06 MiB (399566406 Bytes)
     # download with: annie -f 80 ...

     [64]  -------------------
     Quality:         高清 720P
     Size:            294.34 MiB (308633288 Bytes)
     # download with: annie -f 64 ...

     [32]  -------------------
     Quality:         清晰 480P
     Size:            150.47 MiB (157781869 Bytes)
     # download with: annie -f 32 ...

     [16]  -------------------
     Quality:         流畅 360P
     Size:            79.82 MiB (83694650 Bytes)
     # download with: annie -f 16 ...

 Site:      哔哩哔哩 bilibili.com
 Title:     异界少女召唤术：第4话 迫击乱舞
 Type:      video
 Streams:   # All available quality
     [80]  -------------------
     Quality:         高清 1080P
     Size:            358.87 MiB (376302222 Bytes)
     # download with: annie -f 80 ...

     [64]  -------------------
     Quality:         高清 720P
     Size:            277.21 MiB (290679594 Bytes)
     # download with: annie -f 64 ...

     [32]  -------------------
     Quality:         清晰 480P
     Size:            151.06 MiB (158396627 Bytes)
     # download with: annie -f 32 ...

     [16]  -------------------
     Quality:         流畅 360P
     Size:            74.89 MiB (78530472 Bytes)
     # download with: annie -f 16 ...

 Site:      哔哩哔哩 bilibili.com
 Title:     异界少女召唤术：第5话 国家骑士
 Type:      video
 Streams:   # All available quality
     [80]  -------------------
     Quality:         高清 1080P
     Size:            376.48 MiB (394766513 Bytes)
     # download with: annie -f 80 ...

     [64]  -------------------
     Quality:         高清 720P
     Size:            290.64 MiB (304753649 Bytes)
     # download with: annie -f 64 ...

     [32]  -------------------
     Quality:         清晰 480P
     Size:            145.29 MiB (152345919 Bytes)
     # download with: annie -f 32 ...

     [16]  -------------------
     Quality:         流畅 360P
     Size:            76.82 MiB (80555690 Bytes)
     # download with: annie -f 16 ...

 Site:      哔哩哔哩 bilibili.com
 Title:     异界少女召唤术：第6话 隶从市场
 Type:      video
 Streams:   # All available quality
     [80]  -------------------
     Quality:         高清 1080P
     Size:            129.80 MiB (136100744 Bytes)
     # download with: annie -f 80 ...

     [64]  -------------------
     Quality:         高清 720P
     Size:            94.23 MiB (98810997 Bytes)
     # download with: annie -f 64 ...

     [32]  -------------------
     Quality:         清晰 480P
     Size:            75.23 MiB (78879796 Bytes)
     # download with: annie -f 32 ...

     [16]  -------------------
     Quality:         流畅 360P
     Size:            54.85 MiB (57517285 Bytes)
     # download with: annie -f 16 ...

 Site:      哔哩哔哩 bilibili.com
 Title:     异界少女召唤术：第7话 人心变幻
 Type:      video
 Streams:   # All available quality
     [80]  -------------------
     Quality:         高清 1080P
     Size:            161.22 MiB (169053179 Bytes)
     # download with: annie -f 80 ...

     [64]  -------------------
     Quality:         高清 720P
     Size:            113.91 MiB (119441645 Bytes)
     # download with: annie -f 64 ...

     [32]  -------------------
     Quality:         清晰 480P
     Size:            89.90 MiB (94267319 Bytes)
     # download with: annie -f 32 ...

     [16]  -------------------
     Quality:         流畅 360P
     Size:            66.78 MiB (70020648 Bytes)
     # download with: annie -f 16 ...

 Site:      哔哩哔哩 bilibili.com
 Title:     异界少女召唤术：第8话 英雄猛进
 Type:      video
 Streams:   # All available quality
     [80]  -------------------
     Quality:         高清 1080P
     Size:            202.73 MiB (212574353 Bytes)
     # download with: annie -f 80 ...

     [64]  -------------------
     Quality:         高清 720P
     Size:            141.06 MiB (147914375 Bytes)
     # download with: annie -f 64 ...

     [32]  -------------------
     Quality:         清晰 480P
     Size:            109.90 MiB (115239668 Bytes)
     # download with: annie -f 32 ...

     [16]  -------------------
     Quality:         流畅 360P
     Size:            77.22 MiB (80976247 Bytes)
     # download with: annie -f 16 ...

 Site:      哔哩哔哩 bilibili.com
 Title:     异界少女召唤术：第9话 圣骑士传
 Type:      video
 Streams:   # All available quality
     [80]  -------------------
     Quality:         高清 1080P
     Size:            174.97 MiB (183472183 Bytes)
     # download with: annie -f 80 ...

     [64]  -------------------
     Quality:         高清 720P
     Size:            124.77 MiB (130830389 Bytes)
     # download with: annie -f 64 ...

     [32]  -------------------
     Quality:         清晰 480P
     Size:            99.14 MiB (103956048 Bytes)
     # download with: annie -f 32 ...

     [16]  -------------------
     Quality:         流畅 360P
     Size:            72.55 MiB (76071355 Bytes)
     # download with: annie -f 16 ...

 Site:      哔哩哔哩 bilibili.com
 Title:     异界少女召唤术：第10话 魔王复活
 Type:      video
 Streams:   # All available quality
     [80]  -------------------
     Quality:         高清 1080P
     Size:            322.78 MiB (338454716 Bytes)
     # download with: annie -f 80 ...

     [64]  -------------------
     Quality:         高清 720P
     Size:            249.06 MiB (261159981 Bytes)
     # download with: annie -f 64 ...

     [32]  -------------------
     Quality:         清晰 480P
     Size:            125.39 MiB (131476420 Bytes)
     # download with: annie -f 32 ...

     [16]  -------------------
     Quality:         流畅 360P
     Size:            64.27 MiB (67391208 Bytes)
     # download with: annie -f 16 ...

 Site:      哔哩哔哩 bilibili.com
 Title:     异界少女召唤术：第11话 少女觉醒
 Type:      video
 Streams:   # All available quality
     [80]  -------------------
     Quality:         高清 1080P
     Size:            380.96 MiB (399466362 Bytes)
     # download with: annie -f 80 ...

     [64]  -------------------
     Quality:         高清 720P
     Size:            294.37 MiB (308671849 Bytes)
     # download with: annie -f 64 ...

     [32]  -------------------
     Quality:         清晰 480P
     Size:            136.44 MiB (143067305 Bytes)
     # download with: annie -f 32 ...

     [16]  -------------------
     Quality:         流畅 360P
     Size:            71.57 MiB (75049983 Bytes)
     # download with: annie -f 16 ...

panic: runtime error: index out of range

goroutine 1 [running]:
github.com/iawia002/annie/downloader.VideoData.Download(0x13476ae, 0x19, 0xc000648810, 0x2d, 0x133cfa2, 0x5, 0xc0006b2810, 0x0, 0x0, 0x0, ...)
	/private/tmp/annie-20180916-64042-1uurlwu/annie-0.8.1/src/github.com/iawia002/annie/downloader/downloader.go:285 +0xe1f
github.com/iawia002/annie/extractors/bilibili.bilibiliDownload(0xc0006f6ea0, 0x2e, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/private/tmp/annie-20180916-64042-1uurlwu/annie-0.8.1/src/github.com/iawia002/annie/extractors/bilibili/bilibili.go:298 +0x80f
github.com/iawia002/annie/extractors/bilibili.Download(0x7ffeefbffbc4, 0x2f, 0x133f3c4, 0x8)
	/private/tmp/annie-20180916-64042-1uurlwu/annie-0.8.1/src/github.com/iawia002/annie/extractors/bilibili/bilibili.go:173 +0x3f8
main.download(0x7ffeefbffbc4, 0x2f, 0xc0000cfde0, 0x2b96d511274b50f3)
	/private/tmp/annie-20180916-64042-1uurlwu/annie-0.8.1/src/github.com/iawia002/annie/main.go:74 +0x895
main.main()
	/private/tmp/annie-20180916-64042-1uurlwu/annie-0.8.1/src/github.com/iawia002/annie/main.go:155 +0x11c

**Comment by iawia002** [comment]
12 集需要大会员的 Cookie 才能下载
