### ISSUE TITLE
无法下载b站含有分p的1080p视频

### ISSUE THREAD

**Issue by forestbullet** [iawia002/annie#278]
其他网站视频下载正常，但是部分最高画质为1080p的视频（并不是番剧，没有含有bangumi的地址）无法下载，流量一直要么为接收0mb，要么只接收100b左右流量。下载失败后出现这一行

Unsolicited response received on idle HTTP channel starting with ".acgvideo.com/upgcxcode/66/14/2361466/2361466-10-80.flv?expires=1537981800&platform=pc&ssig=iIbwtNlnjruaQNeGM_m7gg&oi=3708035111&nfa=VTtnXeacAlS5k6cLdWuWIA==&dynamic=1&hfb=Yjk5ZmZjM2M1YzY4ZjAwYTMzMTIzYmIyNWY4ODJkNWI=&trid=9e4773aa6aae422582dad4cffbd3b0e1&nfc=1\r\n\r\n"; err=<nil>
2018/09/26 23:40:08 Unsolicited response received on idle HTTP channel starting with ".acgvideo.com/upgcxcode/66/14/2361466/2361466-9-80.flv?expires=1537981800&platform=pc&ssig=4e-Bl5tBK2oREjc5i2gX4w&oi=3708035111&nfa=BpfiWF+i4mNW8KzjZFHzBQ==&dynamic=1&hfb=Yjk5ZmZjM2M1YzY4ZjAwYTMzMTIzYmIyNWY4ODJkNWI=&trid=9e4773aa6aae422582dad4cffbd3b0e1&nfc=1\r\n\r\n"; err=<nil>

只要是最高画质为1080p的视频都是如此，只有部分可以正常下载。最高画质为720p的视频却都可以下载，不知道什么情况，麻烦解答一下，谢谢。

**Comment by iawia002** [comment]
B 站地址贴一下，还有，有没有挂代理

**Comment by iawia002** [comment]
any response?

**Comment by forestbullet** [comment]
不好意思一直忘了回，因为找到另外一个专门下b站视频的所以最近没有怎么试用annie的效果，但记忆中还是on and off的状态。另外，有用代理

Sent from my iPhone

On Oct 24, 2018, at 13:52, Xinzhao Xu <notifications@github.com<mailto:notifications@github.com>> wrote:


any response?
