### ISSUE TITLE
QQ panic: runtime error: index out of range

### ISSUE THREAD

**Issue by apt425410** [iawia002/annie#283]
annie -i https://v.qq.com/x/cover/7xoocndx1w8g085.html
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/iawia002/annie/extractors.QQ(0xc0000102a0, 0x2d, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /Users/mac/iawia002/go/src/github.com/iawia002/annie/extractors/qq.go:155 +0x735
main.download(0xc0000102a0, 0x2d, 0xc000079de0, 0x4206d323cbecf015)
        /Users/mac/iawia002/go/src/github.com/iawia002/annie/main.go:104 +0x32f
main.main()
        /Users/mac/iawia002/go/src/github.com/iawia002/annie/main.go:155 +0x123

**Comment by iawia002** [comment]
更新到最新版本

```console
$ annie https://v.qq.com/x/cover/7xoocndx1w8g085.html

 Site:      腾讯视频 v.qq.com
 Title:     夜天子_01
 Type:      video
 Stream:
     [fhd]  -------------------
     Quality:         蓝光;(1080P)
     Size:            663.24 MiB (695461502 Bytes)
     # download with: annie -f fhd ...

 646.00 KiB / 663.24 MiB [>--------------------------------------------------]   0.10% 215.87 KiB/s 52m12s
```

**Comment by apt425410** [comment]
annie -d https://v.qq.com/x/cover/7xoocndx1w8g085.html

[36mannie[0m: version [34m0.8.1[0m, A fast, simple and clean video downloader.


URL:         https://v.qq.com/x/cover/7xoocndx1w8g085.html
Method:      GET
Headers:     http.Header{
    "Accept-Language": {"en-US,en;q=0.8"},
    "User-Agent":      {"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.81 Safari/537.36"},
    "Accept":          {"text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"},
    "Referer":         {"https://v.qq.com/x/cover/7xoocndx1w8g085.html"},
    "Accept-Charset":  {"UTF-8,*;q=0.5"},
    "Accept-Encoding": {"gzip,deflate,sdch"},
}
Status Code: 200

URL:         http://vv.video.qq.com/getinfo?otype=json&platform=11&defnpayver=1&appver=3.2.19.333&defn=shd&vid=a0027jaob76
Method:      GET
Headers:     http.Header{
    "Accept-Language": {"en-US,en;q=0.8"},
    "User-Agent":      {"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.81 Safari/537.36"},
    "Accept":          {"text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"},
    "Accept-Charset":  {"UTF-8,*;q=0.5"},
    "Referer":         {"https://v.qq.com/x/cover/7xoocndx1w8g085.html"},
    "Accept-Encoding": {"gzip,deflate,sdch"},
}
Status Code: 200
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/iawia002/annie/extractors.QQ(0xc0000102a0, 0x2d, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /Users/mac/iawia002/go/src/github.com/iawia002/annie/extractors/qq.go:155 +0x735
main.download(0xc0000102a0, 0x2d, 0xc000079de0, 0xbc53d9824f52601b)
        /Users/mac/iawia002/go/src/github.com/iawia002/annie/main.go:104 +0x32f
main.main()
        /Users/mac/iawia002/go/src/github.com/iawia002/annie/main.go:155 +0x123

C:\Users\apt\Downloads\Compressed\annie_0.8.1_Windows_64-bit>

**Comment by iawia002** [comment]
你用浏览器打开这个地址 http://vv.video.qq.com/getinfo?otype=json&platform=11&defnpayver=1&appver=3.2.19.333&defn=shd&vid=a0027jaob76 把结果贴上来

**Comment by apt425410** [comment]
txminiplayerJsonpCallBack_getinfo_205648({"dltype":1,"exem":0,"fl":{"cnt":1,"fi":[{"id":2,"name":"mp4","lmt":0,"sb":1,"cname":"高清;(480P)","br":62,"profile":1,"drm":0,"video":1,"audio":1,"fs":353182,"sl":1}]},"hs":0,"ip":"119.76.175.254","ls":0,"preview":5,"s":"o","sfl":{"cnt":0},"tm":1538731584,"vl":{"cnt":1,"vi":[{"br":62,"ch":0,"cl":{"fc":0,"keyid":"q1722mgihrv.2"},"ct":21600,"drm":0,"dsb":0,"fmd5":"923c29d34ac451bcd68fdee2bd4d629f","fn":"q1722mgihrv.mp4","fs":353182,"fst":5,"fvkey":"F1CCEAD63C0287B091FBF32010C67FDA4CCDC8DE11BDA4BF03E25A4FE87248B0F9D80DA3A217E9855ECADED7DF2B31C143DC4E5BE19F5D63ADE363AE0A381598C828D05F4DFEA4F97BD9F6A62A6B0D001E70CDCEF90FE115","head":0,"hevc":0,"iflag":0,"level":0,"lnk":"q1722mgihrv","logo":1,"mst":8,"pl":null,"share":1,"sp":0,"st":2,"tail":0,"td":"5.55","ti":"星辰变 第1季 第01话","tie":0,"type":4612,"ul":{"ui":[{"url":"http://video.dispatch.tc.qq.com/AhpJNgVh9T_-BZG67D5z5d670kWX1d1d9KFFgRQZ6LE8/","vt":0,"dtc":0,"dt":2},{"url":"http://video.dispatch.tc.qq.com/AhpJNgVh9T_-BZG67D5z5d670kWX1d1d9KFFgRQZ6LE8/","vt":0,"dtc":0,"dt":2}]},"vh":486,"vid":"q1722mgihrv","videotype":0,"vr":0,"vst":5,"vw":864,"wh":1.7777778,"wl":{"wi":[]},"uptime":1538709211,"fvideo":0,"fvpint":0,"swhdcp":0}]}})

**Comment by iawia002** [comment]
这不对，正常的应该是这样的：

```
QZOutputJson={"dltype":1,"exem":2,"fl":{"cnt":4,"fi":[{"id":10203,"name":"sd","lmt":0,"sb":1,"cname":"标清;(270P)","br":111,"profile":1,"drm":0,"video":1,"audio":1,"fs":102559927,"sl":0},{"id":10212,"name":"hd","lmt":0,"sb":1,"cname":"高清;(480P)","br":116,"profile":1,"drm":0,"video":1,"audio":1,"fs":239628063,"sl":0},{"id":10201,"name":"shd","lmt":0,"sb":1,"cname":"超清;(720P)","br":136,"profile":1,"drm":0,"video":1,"audio":1,"fs":377363544,"sl":1},{"id":10209,"name":"fhd","lmt":1,"sb":1,"cname":"蓝光;(1080P)","br":141,"profile":1,"drm":0,"video":1,"audio":1,"fs":692699028,"sl":0}]},"fp2p":2,"hs":0,"ip":"117.149.19.162","ls":0,"preview":180,"s":"o","sfl":{"cnt":0},"tm":1538736907,"vl":{"cnt":1,"vi":[{"br":136,"ch":0,"cl":{"fc":9,"ci":[{"idx":1,"cs":46013162,"cd":"300","cmd5":"43858a661571fda27defecf625a394f7","vkey":"","urllist":[],"keyid":"a0027jaob76.10201.1"},{"idx":2,"cs":38836502,"cd":"300","cmd5":"0369077acbe8cac80a892b5622530833","vkey":"","urllist":[],"keyid":"a0027jaob76.10201.2"},{"idx":3,"cs":34604854,"cd":"300","cmd5":"55307fec129d73d13723f9719cfc559e","vkey":"","urllist":[],"keyid":"a0027jaob76.10201.3"},{"idx":4,"cs":46582863,"cd":"300.032","cmd5":"0171e3df2195d5c51469bd71284beb1e","vkey":"","urllist":[],"keyid":"a0027jaob76.10201.4"},{"idx":5,"cs":35350464,"cd":"300","cmd5":"1922ef81d42871838603b1b2b7b4eb98","vkey":"","urllist":[],"keyid":"a0027jaob76.10201.5"},{"idx":6,"cs":36124655,"cd":"300","cmd5":"11bf576be6df8b2b6b3b5acbdf91c853","vkey":"","urllist":[],"keyid":"a0027jaob76.10201.6"},{"idx":7,"cs":46220761,"cd":"300","cmd5":"41a473e3a629cf2d4c18de2742a8c3cb","vkey":"","urllist":[],"keyid":"a0027jaob76.10201.7"},{"idx":8,"cs":39671710,"cd":"300.032","cmd5":"1c2f4ab62fc3a3b882db02a0d03d82b4","vkey":"","urllist":[],"keyid":"a0027jaob76.10201.8"},{"idx":9,"cs":55006451,"cd":"300.073","cmd5":"bd08eb9f9299e778ac006b139400dd1b","vkey":"","urllist":[],"keyid":"a0027jaob76.10201.9"}]},"ct":21600,"drm":0,"dsb":0,"fclip":1,"fmd5":"4b83b693464498a7d3917326f2ecce2a","fn":"a0027jaob76.p201.mp4","fs":377363544,"fst":5,"fvkey":"E903E67D48456D3831B037AFC39AD526ED018ABF179506934D4215A68DD7B053CC284F128A4613C4E0C302B76B6CE9EF040BE006752DB282BEAC3565790F402E6E400621D2DB9E3E5B68798123DCD6A277675591C8EA67BA84E5475DD074945DD375495D6F26D6E3","head":0,"hevc":0,"iflag":0,"level":0,"lnk":"a0027jaob76","logo":1,"mst":8,"pl":[{"cnt":3,"pd":[{"cd":10,"h":45,"w":80,"r":10,"c":10,"fmt":40001,"fn":"q1","url":"http://puui.qpic.cn/video_caps/0/"},{"cd":10,"h":90,"w":160,"r":5,"c":5,"fmt":40002,"fn":"q2","url":"http://puui.qpic.cn/video_caps/0/"},{"cd":10,"h":135,"w":240,"r":5,"c":5,"fmt":40003,"fn":"q3","url":"http://puui.qpic.cn/video_caps/0/"}]}],"share":1,"sp":0,"st":2,"tail":92,"td":"2700.07","ti":"夜天子_01","tie":0,"type":1036,"ul":{"ui":[{"url":"http://111.29.8.24/vlive.qqvideo.tc.qq.com/Adr7fVAU5KeOAxJycSSBJZFD7DcPt772BzVRkEg-11sE/uwMRJfz-r5jAYaQXGdGnC2_ppdhgmrDlPaRvaV7F2Ic/","vt":203,"dtc":0,"dt":2},{"url":"http://111.29.8.12/vlive.qqvideo.tc.qq.com/Adr7fVAU5KeOAxJycSSBJZFD7DcPt772BzVRkEg-11sE/uwMRJfz-r5jAYaQXGdGnCtD0ZkRh8BgOUQePMGh65cs/","vt":203,"dtc":0,"dt":2},{"url":"http://111.29.8.13/vlive.qqvideo.tc.qq.com/Adr7fVAU5KeOAxJycSSBJZFD7DcPt772BzVRkEg-11sE/uwMRJfz-r5jAYaQXGdGnCdPSIuBiT-Ez5OOv2zO7oh4/","vt":203,"dtc":0,"dt":2},{"url":"http://video.dispatch.tc.qq.com/","vt":0,"dtc":0,"dt":2}]},"vh":720,"vid":"a0027jaob76","videotype":2,"vr":0,"vst":2,"vw":1280,"wh":1.7777778,"wl":{"wi":[]},"uptime":1533451923,"fvideo":0,"fvpint":0,"swhdcp":0}]}};
```

你挂了什么代理吗，网络环境是怎样的

**Comment by apt425410** [comment]
home network  http://trueonline.truecorp.co.th/

**Comment by iawia002** [comment]
you're not Chinese?

**Comment by apt425410** [comment]
yes ykdl recomment me to know about annie

**Comment by apt425410** [comment]
https://github.com/zhangn1985/ykdl/issues/333

**Comment by SeaHOH** [comment]
User can load the cookies of a paid account, is that right?

**Comment by iawia002** [comment]
@SeaHOH that's right, but I'm not sure Tencent video needs to be adapted separately

**Comment by apt425410** [comment]
it seem i can't download vip video anymore // long time ago i download v.qq.com  vip with you-get but not  work anymore

**Comment by SeaHOH** [comment]
Just try via a chinese proxy to break regional restriction, and you must pay if need to downloads VIP videos.

**Comment by apt425410** [comment]
why i can download vip video with annie at youku but not v.qq.com

**Comment by apt425410** [comment]
and normal link like this annie downloader not work //////////////////////////////////////////////////////////////////////annie https://v.qq.com/x/cover/29ydp7xrml13rxk.html
Downloading [36mhttps://v.qq.com/x/cover/29ydp7xrml13rxk.html[0m error:
[31mhttp://video.dispatch.tc.qq.com/b00273ouw97.p203.2.mp4?vkey=B504CFB5BE1926039D31DD328B04BB9EB7FBFF73AE0A75D4A964D69DB5414A4E59F0C1C7C6E6300F6CA2BE90A72C590FBDF95C4A17EC2F8D2A2FCE66D9262415645E3AE824B41E0CFB5B85637CD8BA9207617EF424ABBC52F51B5B4D99BB028625A4A20A770DBBBE request error: HTTP 403[0m

**Comment by SeaHOH** [comment]
> why i can download vip video with annie at youku but not v.qq.com

U can show the youku video link, i think it is not trues.

**Comment by SeaHOH** [comment]
That is a trial time, few minutes.

**Comment by apt425410** [comment]
um it seem can download just not more 14% Site:      优酷 youku.com
 Title:     颤抖吧，阿部 03
 Type:      video
 Stream:
     [mp4hd3-guoyu]  -------------------
     Quality:         mp4hd3 1920x1080 国语
     Size:            501.40 MiB (525754198 Bytes)
     # download with: annie -f mp4hd3-guoyu ...

 70.99 MiB / 501.40 MiB [==========>-------------------------------------------------------------]  14.16% 162.37 KiB/s

**Comment by apt425410** [comment]
URL: | http://45.112.215.74/657452AC7BA30815EA10182AAB/03000C130059ACF6B84628011BA6A9DB12AE47-0E66-39BC-EF84-00DAF928A199.mp4?ccode=0103010102\u0026duration=136\u0026expire=18000\u0026psid=a7422012736b8f03c1411863cecf5143\u0026ups_client_netip=3a0b6bc2\u0026ups_ts=1538748642\u0026ups_userid=\u0026utid=W7cAhE1lgiEDAI0%2Bq2G8sTbt\u0026vid=XMjk0NTUzOTMwNA%3D%3D\u0026vkey=A63e43d6cdfe34f921b9268325974fc0a\u0026sp=
-- | --
Server: | c04.squid.hongkong.cdn.yoqoo
Date: | 2018/10/05 22:11:37

**Comment by SeaHOH** [comment]
This download will not be completd if U are not pay.
U paid it?

**Comment by apt425410** [comment]
no i just try

**Comment by SeaHOH** [comment]
Ok, enjoy the free videos, or pay for it.

**Comment by zed2021** [comment]
panic: runtime error: index out of range [0] with length 0 any updates for this
