### ISSUE TITLE
求助：解析爱奇艺出现如下错误提示

### ISSUE THREAD

**Issue by climboy1** [iawia002/annie#290]
$ annie https://www.iqiyi.com/v_19rr6cf7uw.html

 Site:      爱奇艺 iqiyi.com
 Title:     中国好声音：纯享：周杰伦 张神儿 宿涵《屋顶》
 Type:      video
 Stream:   
     [4]  -------------------
     Quality:         1280x720
     Size:            60.52 MiB (63464664 Bytes)
     # download with: annie -f 4 ...

 60.52 MiB / 60.52 MiB [================================] 100.00% 2.30 MiB/s 26s
Merging video parts into 中国好声音：纯享：周杰伦 张神儿 宿涵《屋顶》.mp4
Downloading https://www.iqiyi.com/v_19rr6cf7uw.html error:
exec: "ffmpeg": executable file not found in $PATH

**Comment by iawia002** [comment]
ffmpeg 这个软件要单独安装

https://github.com/iawia002/annie#prerequisites
