### ISSUE TITLE
B站下载视频卡住了

### ISSUE THREAD

**Issue by aizya** [iawia002/annie#291]
RT, 我试了下annie -p URL, 以及单集下载,都失败了,卡着没有任何反映,资源是正常的.

`
annie https://www.bilibili.com/video/av32733073/?p=11

 Site:      哔哩哔哩 bilibili.com
 Title:     Java8新特性及实战视频教程完整版 11_supplier与函数式接口总结
 Type:      video
 Stream:   
     [default]  -------------------
     Quality:         高清 1080P
     Size:            83.04 MiB (87072593 Bytes)
     # download with: annie -f default "URL"

 0 B / 83.04 MiB [---------------------------------------------------------------------------------------------------------------------------]   0.00% 0 B / 83.04 MiB [---------------------------------------------------------------------------------------------------------------------------]   0.00% 0 B / 83.04 MiB [---------------------------------------------------------------------------------------------------------------------------]   0.00% 0 B / 83.04 MiB [---------------------------------------------------------------------------------------------------------------------------]   0.00%`

![image](https://user-images.githubusercontent.com/22078443/46912282-adf60300-cfa3-11e8-80ce-876f76136ca3.png)

**Comment by iawia002** [comment]
尝试带上登录过的 Cookie 试试

```console
$ annie -c ~/Downloads/cookies.txt https://www.bilibili.com/video/av32733073/\?p\=11

 Site:      哔哩哔哩 bilibili.com
 Title:     Java8新特性及实战视频教程完整版 11_supplier与函数式接口总结
 Type:      video
 Stream:
     [64]  -------------------
     Quality:         高清 720P
     Size:            83.08 MiB (87113735 Bytes)
     # download with: annie -f 64 ...

 720.00 KiB / 83.08 MiB [=>--------------------------------------------]   0.85% 81.44 KiB/s 16m35s
```

**Comment by aizya** [comment]
@iawia002  请问使用document.cookie获取的cookie信息,提示了账号未登录.. 我已经重新登录了B站的帐号,还是不行. 请问您的cookie是怎么获取的? 是我使用方式有问题么?

![image](https://user-images.githubusercontent.com/22078443/46924837-d7be3100-d05a-11e8-9e78-b1a5092d0b2d.png)

**Comment by aizya** [comment]
可以了. 谢谢
