### ISSUE TITLE
GOOD JOB!

### ISSUE THREAD

**Issue by hobmgcode** [iawia002/annie#3]
支持列表还是有点少啊

**Comment by iawia002** [comment]
@hobmgcode 感谢你的关注

annie 才刚刚开始，我还在不断思考和完善底层的一些东西（函数、接口的设计等，我也只是一个 Go 语言的初学者），所以现在支持的都是我平常用的比较多的网站（其实我基本只用 B 站 😂），以后有精力会慢慢完善的。欢迎 Pull Requests！

**Comment by Justsoos** [comment]
可以考虑作各个取 流 软件的下载，拼接的底层。感觉go 的底层协议实现要比 python 好很多。
比如you-get + lulu + youtuble-dl 生成流地址 -> annie 下载 -> ffmpeg 拼接 这三件事，三个专业合作。

go 处理字符方面不如 python，也用不着所有网站都自己造轮子，能作个非常棒的底层下载，会很快铺开用户使用量。

**Comment by iawia002** [comment]
you-get 和 lulu 很多网站都不支持只返回提取的流地址的，youtube-dl 应该是支持的，它的代码要规范一些

**Comment by Justsoos** [comment]
没关系啊，可以 用 annie 取代掉 common.py 里负责下载的语句。嘿嘿，测试之后，可能会发现 python 底层有大问题的证据呢，那就是大热闹了。

**Comment by mashirozx** [comment]
请问是缺了什么 lib 吗？😂
![image](https://user-images.githubusercontent.com/16148054/37553319-aadff8fe-2a00-11e8-98a9-726b8134cb0d.png)

**Comment by iawia002** [comment]
@mashirozx 应该没问题呀，go 什么版本，不行就下 https://github.com/iawia002/annie/releases 里面的二进制

**Comment by mashirozx** [comment]
@iawia002  go version go1.8.3 linux/amd64

**Comment by iawia002** [comment]
@mashirozx 我知道了，你的 `GOPATH` 没有环境变量里面吧

```
export GOPATH=~/go
export PATH=$PATH:$GOPATH/bin
```

**Comment by mashirozx** [comment]
原来如此！可以用了，速度飞起😂

**Comment by ginhton** [comment]
66666
