### ISSUE TITLE
【iqiyi】MACOS下载完都是小片段，无法自动合并

### ISSUE THREAD

**Issue by climboy1** [iawia002/annie#303]
mac系统 爱奇艺下载完都是小片段存放在根目录下，提示error:exec: "ffmpeg": executable file not found in $PATH 。已经安装ffmpeg。是设置的问题吗？

Hyper fast Audio and Video encoder
usage: ffmpeg [options] [[infile options] -i infile]... {[outfile options] outfile}...

Use -h to get full help or, even better, run 'man ffmpeg'
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.
Deleting expired sessions...1 completed.

[进程已完成]

还是FFmpeg没有安装正确？
希望得到回复，谢谢。

**Comment by iawia002** [comment]
你的环境变量不对吧，`ffmpeg` 可执行文件地址没在你的 PATH 里面，你改一下环境变量或者把这个可执行文件放到 `/usr/local/bin` 这种目录下

**Comment by climboy1** [comment]
现在下载视频地址是/users/user，可以把PATH也改到根目录吗？这个操作容易吗？望得到指点^_^

**Comment by iawia002** [comment]
环境变量的去网上搜一下相关的比较好
