### ISSUE TITLE
解析爱奇艺视频只出现第一段视频，后续的没有

### ISSUE THREAD

**Issue by jinjfy** [iawia002/annie#304]
完整视频大小有几个G，解析和下载只下了第一块视频
D:\a>annie -c cookies.txt -i https://www.iqiyi.com/v_19rra81684.html

 Site:      爱奇艺 iqiyi.com
 Title:     野性新西兰 ：第1集 随波捕鱼
 Type:      video
 Streams:   # All available quality
     [5]  -------------------
     Quality:         1920x1080
     Size:            127.31 MiB (133496168 Bytes)
     # download with: annie -f 5 ...

     [4]  -------------------
     Quality:         1280x720
     Size:            68.54 MiB (71872400 Bytes)
     # download with: annie -f 4 ...

     [18]  -------------------
     Quality:         1920x1080
     Size:            64.17 MiB (67284448 Bytes)
     # download with: annie -f 18 ...

     [17]  -------------------
     Quality:         1280x720
     Size:            38.91 MiB (40802956 Bytes)
     # download with: annie -f 17 ...

     [2]  -------------------
     Quality:         896x504
     Size:            28.23 MiB (29603796 Bytes)
     # download with: annie -f 2 ...

     [21]  -------------------
     Quality:         896x504
     Size:            22.94 MiB (24055728 Bytes)
     # download with: annie -f 21 ...

     [1]  -------------------
     Quality:         640x360
     Size:            19.47 MiB (20412476 Bytes)
     # download with: annie -f 1 ...

     [96]  -------------------
     Quality:         384x216
     Size:            10.18 MiB (10675392 Bytes)
     # download with: annie -f 96 ...

**Comment by iawia002** [comment]
这是会员才能看的，免费的只有前几分钟

**Comment by jinjfy** [comment]
可是我已经加载我的会员cookies了。

**Comment by iawia002** [comment]
爱奇艺还不支持 VIP 视频下载，#50
