### ISSUE TITLE
 Youku download error

### ISSUE THREAD

**Issue by liuyintongxue** [iawia002/annie#31]
`   Site:   优酷 youku.com
  Title:   圆桌派 第三季：第十一集 烂片：怎样算烂？为何会烂？
   Type:   video
Quality:   mp4hd2 1280x720
   Size:   322.98 MiB (338664257 Bytes)

 39.60 MiB / 322.98 MiB [===>--------------------------]  12.26% 27.53 MiB/s 1s
Merging video parts into 圆桌派 第三季：第十一集 烂片：怎样算烂？为何会烂？.mp4`

我看你用的方法和 http://www.maoyun.tv/mdparse/index.php?id=http://v.youku.com/v_show/id_XMzQ2NjUyNjYwNA==.html 是一样的，没区别，但是他能获取到正确的地址并且播放。

我建议可以从这种解析接口里获取下载地址。

**Comment by liuyintongxue** [comment]
还是因为程序原因？ 没有下载完就开始合并了？

**Comment by liuyintongxue** [comment]
不过使用这种接口的话失去乐趣了，这个解析接口基本支持国内所有视频站点。

**Comment by iawia002** [comment]
你用的哪个版本？这个应该是下载其中一个链接的时候优酷返回 403 之类的，但是我现在对这种情况的处理是直接报错，会直接结束程序，不会走到合并那里去

**Comment by iawia002** [comment]
不会又是并发太高被优酷 ban 了吧，芒果tv 就是这样的，还搞得我强行把下载芒果tv 改成了单线程

**Comment by iawia002** [comment]
你用最新版的下所有优酷视频都这样吗？我空了调试一下看看具体原因是什么？

**Comment by liuyintongxue** [comment]
我用的最新版，他没有报错，直接合并了6分钟，我和这个解析作者聊过，他后端好像用的是c，然后切代理，做了地址缓存，解析服务器负载不小。

**Comment by iawia002** [comment]
@liuyintongxue 我自己也试了一下，不是网络的问题，应该是其他哪里出问题了

**Comment by iawia002** [comment]
@liuyintongxue 问题的原因是这样的，优酷 API 返给我的总大小是 300 多 MB，但是它返回了两个片段，每个的大小只有 10 多 MB，

**Comment by iawia002** [comment]
优酷 0503 这个 ccode 只返回前几分钟的数据，其他的 ccode 都用不了

**Comment by liuyintongxue** [comment]
那用我发给你的这个在线接口咯，应该没问题。

**Comment by iawia002** [comment]
@liuyintongxue 我倾向于直接对接优酷的 API。我重新提了一个 issue #43，我把这个关了
