### ISSUE TITLE
刚刚brew 更新了下go好像到1.11.1了，然后编译不了了。。

### ISSUE THREAD

**Issue by jsnjycwyz** [iawia002/annie#315]
go get -u github.com/iawia002/annie，全都显示：
compile: version "go1.11" does not match go tool version "go1.11.1"

**Comment by iawia002** [comment]
这是你环境的问题，你的电脑上有多个版本的 go 吧，比如 `/usr/local/bin` 和 brew 的目录有不同版本的 go 就会这样

**Comment by piaoyunsoft** [comment]
别用brew安装Go  估计环境冲突了




| |
飘飘
邮箱：piaoyunsoft@163.com
|

签名由 网易邮箱大师 定制

在2018年11月07日 22:05，Xinzhao Xu 写道：

Closed #315.

**Comment by jsnjycwyz** [comment]
果然是有两个，删了一个改了下环境路径就好了
