### ISSUE TITLE
爱奇艺的视频无法下载，一直定在这里不动了。

### ISSUE THREAD

**Issue by tea1111980** [iawia002/annie#316]
一直是这样，看下图：
![image](https://user-images.githubusercontent.com/16295097/48253278-dc032180-e441-11e8-9b00-042e64d36bdd.png)

怎么肥事？之前都是用的好好的。

**Comment by iawia002** [comment]
网络问题？重试一下，我随便下了一个可以

```console
$ annie http://www.iqiyi.com/v_19rrbdmaj0.html

 Site:      爱奇艺 iqiyi.com
 Title:     新一轮降水将至 冷空气影响中东部地区
 Type:      video
 Stream:
     [2]  -------------------
     Quality:         896x504
     Size:            2.98 MiB (3122304 Bytes)
     # download with: annie -f 2 ...

 970.65 KiB / 2.98 MiB [=======>---------------------]  31.83% 390.82 KiB/s 00m05s
```

**Comment by tea1111980** [comment]
你就下我的那个，地址：http://www.iqiyi.com/v_19rr5vxe6o.html

**Comment by iawia002** [comment]
也没问题，你更新到最新版了吗

```console
$ annie http://www.iqiyi.com/v_19rr5vxe6o.html

 Site:      爱奇艺 iqiyi.com
 Title:     财经郎眼：聚焦2018新鲜出炉的诺贝尔奖 诺贝尔奖的秘密
 Type:      video
 Stream:
     [4]  -------------------
     Quality:         1280x720
     Size:            502.09 MiB (526479900 Bytes)
     # download with: annie -f 4 ...

 6.28 MiB / 502.09 MiB [=>--------------------------------------------------------]   1.25% 1.18 MiB/s 07m00s
```

**Comment by tea1111980** [comment]
更了 最新版
![image](https://user-images.githubusercontent.com/16295097/48303294-8f077400-e543-11e8-8b2f-14dff99d0f4d.png)

**Comment by tea1111980** [comment]
我是移动的宽带，跟这个有关系吗？ 但是之前我一直用的蛮好的。

**Comment by iawia002** [comment]
下 B 站这些试试呢
你有代理吗，你可以挂代理下载试试

**Comment by airdge** [comment]
![default](https://user-images.githubusercontent.com/7813960/48311337-4bf7e000-e5d9-11e8-9f30-d4be98870360.png)
网络问题吧

**Comment by SeaHOH** [comment]
可能 DNS 有问题，建议用 114 测试下。

**Comment by tea1111980** [comment]
@iawia002  代理我也试过，上面的网站都不能下。B站的还没试。明天试试再来反馈吧。

**Comment by tea1111980** [comment]
> 可能 DNS 有问题，建议用 114 测试下。

我用的就是114 还有其它的DNS 我也试过，不行。以前都是好好的，就这几天出问题。

**Comment by tea1111980** [comment]
> 下 B 站这些试试呢
> 你有代理吗，你可以挂代理下载试试

代理我也试过，上面的网站都不能下。B站的还没试。明天试试再来反馈吧。

**Comment by songouyang** [comment]
同样的情况，不过我的链接是 w 开头的id，<http://www.iqiyi.com/w_19s1s2a4s1.html>
![2018-11-13 13 44 37](https://user-images.githubusercontent.com/16632254/48393418-67362d00-e74a-11e8-9267-2407b3b3649d.png)
![2018-11-13 13 45 07](https://user-images.githubusercontent.com/16632254/48393428-761cdf80-e74a-11e8-82dc-ca03611599cd.png)

**Comment by airdge** [comment]
上面这个视频确实不行,应该是otv算法(dx.data.qiyi.com)出问题了

![default](https://user-images.githubusercontent.com/7813960/48395135-34436780-e751-11e8-851f-20007257ea7f.png)

cmd5x算法没事

![default](https://user-images.githubusercontent.com/7813960/48395169-550bbd00-e751-11e8-9547-ef5219920d87.png)

**Comment by qbabe** [comment]
爱奇艺的问题到现在有解吗?目前爱奇艺的视频还是都无法下载的情况该怎麽办

**Comment by qbabe** [comment]
> 上面这个视频确实不行,应该是otv算法(dx.data.qiyi.com)出问题了
> 
> ![default](https://user-images.githubusercontent.com/7813960/48395135-34436780-e751-11e8-851f-20007257ea7f.png)
> 
> cmd5x算法没事
> 
> ![default](https://user-images.githubusercontent.com/7813960/48395169-550bbd00-e751-11e8-9547-ef5219920d87.png)

爱奇艺的问题到现在有解吗?目前爱奇艺的视频还是都无法下载的情况该怎麽办

**Comment by r17171709** [comment]
@iawia002 请问下，爱奇艺的会员视频是不是都不能下载了？

**Comment by xmoer** [comment]
同问，爱奇艺最近更新的视频都不能下载，老的视频却可以

**Comment by xmoer** [comment]
> > 下B站这些试试呢
> > 你有代理吗，你可以挂代理下载试试
> 
> 谜底解开了，就是被墙了。以前是正常的。也不是DNS的事。
> 
> @qbabe @airdge @SeaHOH @sououyang @ iawia002 谢谢各位..！
> 
> 谜底：
> 挂代理是可以正常下载以上这些链接的。怎么回事？
> 
> ![图片](https://user-images.githubusercontent.com/16295097/49491925-115c2d00-f891-11e8-82c7-cf8636fc3270.png)

这个视频不用代理也能下载的，所以是你之前的网络有问题。
而爱奇艺新发布的那些视频依然不能下载（代理也无效），故障时间大概是从2周半以前开始的？

**Comment by xmoer** [comment]
经过测试，我比较赞成上面 @airdge 的看法。
实际可以ping通，但是返回报错，同时抓包发现都是 0字节 返回，可见是爱奇艺又升级了。
随便测试一部番剧，比如：https://www.iqiyi.com/a_19rrgytq5h.html
发现01-18集测试下载正常，19-20集则失败，出问题的时间点和最早反馈问题的时间高度契合。

**Comment by tea1111980** [comment]
@xmoer   是的，你说的不错。我刚才试了一下，确实是 就算是使用了代理也无法下载。
我觉得这不是代理本身的问题，这是另外一个问题。

**Comment by klmmlk** [comment]
爱奇艺确实下载不了了。

**Comment by iawia002** [comment]
已经换了新的算法（感谢 @SeaHOH），有 Go 环境的可以用 go get 更新 master 的代码，没有的可以等下个版本，有问题再反馈

**Comment by SeaHOH** [comment]
这个算法是 @zhangn1985 提交的，我只是提醒下而已。

**Comment by iawia002** [comment]
恩，都很感谢
