### ISSUE TITLE
爱奇艺更改了编码?完全无法下载

### ISSUE THREAD

**Issue by qbabe** [iawia002/annie#319]
这两天爱奇艺更新的视频都无法下载
请问是爱奇艺方更改了编码吗?
上周的视频还可以下载的
本周更新的视频卻都完全不能下载
都会显示0B / 309.25MiB [---------------------------------------------------]   0.00%
等了好几个小时都没有办法下载
如图那样
用的是最新版本的annie
也试了其他本周更新的视频
都一样是0.00%完全不会动
等了好几个小时也完全都没有办法下载
本周更新的视频現在几乎都不能下载该怎麽办
请求回复帮忙 谢谢
![0](https://user-images.githubusercontent.com/38503091/48663488-fbe2b700-eacb-11e8-8bf2-65f11065a78e.PNG)

**Comment by iawia002** [comment]
估计和 #316 一个原因，我把这个 issue 关了，有问题到那里去反馈
