### ISSUE TITLE
建议使用gox发布arm相关版本

### ISSUE THREAD

**Issue by 805447391** [iawia002/annie#32]
不要小看ARM党啦~
修改gox代码，把arm放开即可。
还有aarch64么么哒~

**Comment by iawia002** [comment]
现在就是用的 gox，以前的版本是有 arm 的，后来我觉得太小众了，就没再编译了，现在有需求的话下个版本我可以加上

**Comment by 805447391** [comment]
android能跑跑，树莓派能跑跑，美滋滋~
