### ISSUE TITLE
能否加一个选项，以最低分辨率下载

### ISSUE THREAD

**Issue by daniel4git** [iawia002/annie#320]
在下载视频列表的时候，能否加一个选项，以最低或最高分辨率下载。
在下载视频列表的时候，有的最低分辨率代码是15、有的最低分辨率代码是16，导致下载列表终止：
如annie -f 15 -p https://www.bilibili.com/video/av3471472
有的最低分辨率代码是16，会显示
no stream named 15

谢谢！

**Comment by iawia002** [comment]
这个需求太少见了，你只有自己处理一下，一个一个下这样

**Comment by ClericPy** [comment]
我感觉实际上这并不是一个稀有需求

1. 似乎默认使用最高分辨率, 但是有的 4K 视频并不需要那么高清, 因为我电脑只是 14 寸的显示器, 为此下载更多内容非常浪费资源. 有时候我的网络非常差, 下载太高清的要很长时间
2. 是否能有一个相对索引的方式选择清晰度, 主要问题是不同网站的呃 stream 名字不一样, B 站可能是 16-12, 别的网站可能是 1080p, 是否能有一个归一化的参数可以选择 best / median / lowest / -1 / -2 之类的统一定位索引. 虽然可以先 -i / -j 获取一次, 但这样子每个视频都要额外请求一次, 比较浪费, 而且数量如果多了, 不确定会不会触发反爬


不知道是否难搞, 相比第一条, 实际上因为每次都是命令行一次执行完毕的, 所以没法更好地定制化出现多个 stream 时候让我手动选择(有可能支持 stdin 么)
