### ISSUE TITLE
Petition to change the example in the README, to Never Gonna Give You Up, by Rick Astley

### ISSUE THREAD

**Issue by Aniket-Pradhan** [iawia002/annie#326]
It's more of a useless issue, but, it's a great song/meme. I hope you get it.

I'll be happy to do that, if you agree to the change. :P

**Comment by iawia002** [comment]
Sure, you can change the first example https://github.com/iawia002/annie#download-a-video, keep the others

**Comment by Aniket-Pradhan** [comment]
Got it!

Will send a PR soon.
