### ISSUE TITLE
小白问题求助，关于优酷下载的问题

### ISSUE THREAD

**Issue by r17171709** [iawia002/annie#334]
![cookies](http://bmob-cdn-22620.b0.upaiyun.com/2018/11/28/eb96d88940c64178800a3fc06f8573a1.png)
> 我这个cookies取值应该没问题吧，应该是这个位置去取吧
![实际结果](http://bmob-cdn-22620.b0.upaiyun.com/2018/11/28/509b2249401560c18055a18425c79055.png)
但是优酷会员视频下载不完整就结束了，这是ccode问题吗？我用的是0590

**Comment by iawia002** [comment]
你登录你的优酷会员账号，打开任意优酷的页面，拿那个页面的请求的所有 cookie
或者直接用 chrome 这些的下载 cookie 的插件把优酷的保存到文件中使用
