### ISSUE TITLE
youku使用cookie仍然201错误

### ISSUE THREAD

**Issue by Refarin** [iawia002/annie#335]
`annie -d -c c.txt http://v.youku.com/v_show/id_XMzU3MzMwNzk5Mg==.html?spm=a2hzp.8250547.0.0
annie: version 0.8.5, A fast, simple and clean video downloader.

URL:         http://log.mmstat.com/eg.js
Method:      GET
Headers:     http.Header{
    "Cookie":          {"P_gck*=;P_pck_rm=*;"},
    "Accept":          {"text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"},
    "Accept-Charset":  {"UTF-8,*;q=0.5"},
    "Accept-Encoding": {"gzip,deflate,sdch"},
    "Accept-Language": {"en-US,en;q=0.8"},
    "User-Agent":      {"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.81 Safari/537.36"},
    "Referer":         {"https://v.youku.com"},
}
Status Code: 200

URL:         https://ups.youku.com/ups/get.json?vid=XMzU3MzMwNzk5Mg==&ccode=0103010102&client_ip=192.168.1.1&client_ts=1543384&utid=W%2F27vU1lgiEDAI0%2Bq2HI2ulJ&ckey=7B19C0AB12633B22E7FE81271162026020570708D6CC189E4924503C49D243A0DE6CD84A766832C2C99898FC5ED31F3709BB3CDD82C96492E721BDD381735026
Method:      GET
Headers:     http.Header{
    "Accept-Encoding": {"gzip,deflate,sdch"},
    "Accept-Language": {"en-US,en;q=0.8"},
    "User-Agent":      {"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.81 Safari/537.36"},
    "Accept":          {"text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"},
    "Referer":         {"https://v.youku.com"},
    "Cookie":          {"P_gck=*;P_pck_rm=*;"},
    "Accept-Charset":  {"UTF-8,*;q=0.5"},
}
Status Code: 200
Downloading http://v.youku.com/v_show/id_XMzU3MzMwNzk5Mg==.html?spm=a2hzp.8250547.0.0 error:
客户端无权播放,201`

是cookies格式的问题吗

**Comment by iawia002** [comment]
试试 `-ccode 0590`

**Comment by iawia002** [comment]
如果还不行，看看 #296 里面的其它 ccode 行不行

**Comment by Refarin** [comment]
> 如果还不行，看看 #296 里面的其它 ccode 行不行

可以了，感谢
