### ISSUE TITLE
能否增加python支持

### ISSUE THREAD

**Issue by weilining** [iawia002/annie#337]
大佬，从lulu过来的，之前那个没有维护了，希望这个能支持python，you-get 以及youtube-dl都不支持https://www.bilibili.com/bangumi/play/ep257264，lulu支持，所以大佬你的产品靠谱啊，如果能支持python的pip3,那使用起来方便点，感谢。

**Comment by iawia002** [comment]
不行的，pip 是 python 的包才能用的，安装可选方法如下：https://github.com/iawia002/annie#installation
