### ISSUE TITLE
B站视频下载不了

### ISSUE THREAD

**Issue by FFFcat** [iawia002/annie#338]
< 

0 B / 71.54 MiB [--------------------------------------------------------------------------------------------]   0.00%Downloading [36mhttps://www.bilibili.com/video/av37356097[0m error:
http://cn-jxnc-cmcc-v-11.acgvideo.com/upgcxcode/00/72/65657200/65657200-1-15.flv?expires=1543996500&platform=pc&ssig=YYAq7-RqV8_uWXkxgnfpbQ&oi=3085848328&nfa=ZGlYLwTu0dW3o1gJGPmYTQ==&dynamic=1&hfa=2117379897&hfb=Yjk5ZmZjM2M1YzY4ZjAwYTMzMTIzYmIyNWY4ODJkNWI=&trid=367a6c5d3eb946128db1e8b8ea04317e&nfc=1 request error: HTTP 464[0m
> 
请问这是怎么回事？

**Comment by iawia002** [comment]
你网络有问题吧，重试一下

```console
$ annie https://www.bilibili.com/video/av37356097

 Site:      哔哩哔哩 bilibili.com
 Title:     【嘻咦啊看】你偷看过别人的日记吗？ 日记
 Type:      video
 Stream:
     [64]  -------------------
     Quality:         高清 720P
     Size:            313.97 MiB (329220724 Bytes)
     # download with: annie -f 64 ...

 2.70 MiB / 313.97 MiB [=>-------------------------------------------]   0.86% 711.05 KiB/s 07m25s
```
