### ISSUE TITLE
bilibili: request canceled

### ISSUE THREAD

**Issue by Constannnnnt** [iawia002/annie#34]
annie https://www.bilibili.com/video/av17748345

   Site:   哔哩哔哩 bilibili.com
  Title:   【Aimer】Aimer Live in BUDOKAN "blanc et noir" 【中日双语字幕】
   Type:   video
Quality:   高清 1080P
   Size:   1807.59 MiB (1895391009 Bytes)

 829.44 MiB / 1.77 GiB [====================================>-------------------------------------------]  45.89% 8.29 MiB/s 1m56s2018/03/21 18:23:10 Error while downloading: http://hk-hkbn7.acgvideo.com/vg7/6/de/28975875-5-80.flv?expires=1521634800&platform=pc&ssig=UqtWX_k7xdW6BizHsphstQ&oi=2946464944&nfa=ZGlYLwTu0dW3o1gJGPmYTQ==&dynamic=1&hfa=2021724512&hfb=Yjk5ZmZjM2M1YzY4ZjAwYTMzMTIzYmIyNWY4ODJkNWI=&trid=806ca226c0bf4373a9ace3a79c1f11ed, net/http: request canceled (Client.Timeout exceeded while reading body)

尝试下载两次但都是在同一个地方失败。好像是链接超时, 但不知道具体原因。（啊再一次沉迷于go的并发机制，决心好好学一下。

**Comment by iawia002** [comment]
这就是网络问题，连接中断了，你再重试一下一般就好了

**Comment by iawia002** [comment]
反正有断点记录的

**Comment by Constannnnnt** [comment]
原来如此，那这个issue还是关了吧。这个proj真的太棒了, 称赞你

**Comment by iawia002** [comment]
这个问题我还是把它写到 readme 里面吧

**Comment by Constannnnnt** [comment]
okay okay，十分感谢！这样的话就清晰许多～
