### ISSUE TITLE
不管从哪个网站上下载视频 速度过一会就变的很慢了

### ISSUE THREAD

**Issue by dspaladin** [iawia002/annie#341]
不管从哪个网站上下载视频 速度过一会就变的很慢了

**Comment by prokiller1199** [comment]
> 不管从哪个网站上下载视频 速度过一会就变的很慢了

是的 我的是腾讯过了一会变很慢

**Comment by dspaladin** [comment]
造成这个问题的原因是什么呢？服务器的判定？直接在网页上播放的时候是没有这个问题的。

**Comment by aunhappy** [comment]
我也遇到了这个问题，下载https://v.youku.com/v_show/id_XMTU4NjAyMjU3Mg.html
到88.13%的时候，速度开始往下掉，本来速度是500k/s左右，一直到慢慢的减少。下载进度不再变化了，还是88.13%
@iawia002

**Comment by levixie** [comment]
@iawia002 the issue is when we download the whole file in one shot, those cdn will throttle the connection. For example qq.com, we just need to follow request smaller chunk, it will work.
do you want my PR? - I only test for qq, so didn't make it as a param as cmd

**Comment by iawia002** [comment]
@levixie PRs are welcome, I will review it when I have free time.
