### ISSUE TITLE
youku 客户端无权播放,201

### ISSUE THREAD

**Issue by vcan** [iawia002/annie#342]
看了下源码，尝试了很多CCODE还是不行，一直提示客户端无权播放

**Comment by lleeopen** [comment]
![qq 20181215194237](https://user-images.githubusercontent.com/35162785/50042704-ba7d0180-00a1-11e9-9ee6-48c1f3f26dcc.jpg)

目前加cookie可以解决下载问题~~~~把cookie复到一个txt文本里，用 -c 参数加载。

**Comment by iawia002** [comment]
https://github.com/iawia002/annie#%E4%BC%98%E9%85%B7

带上登录过的 cookie 可以解决许多 ccode 的问题，类似问题到 #296 去反馈

**Comment by vcan** [comment]
> https://github.com/iawia002/annie#%E4%BC%98%E9%85%B7
> 
> 带上登录过的 cookie 可以解决许多 ccode 的问题，类似问题到 #296 去反馈

请问这个cookie怎么获取？我再Chrome下找到的cookie好像无法使用。

**Comment by iawia002** [comment]
https://github.com/iawia002/annie#cookies

chrome 有插件可以直接下载整个 site 的 cookie 到一个文件，直接 -c filepath 就行了
