### ISSUE TITLE
部分爱奇艺下载不了

### ISSUE THREAD

**Issue by wen2006953** [iawia002/annie#343]
annie -i "https://www.iqiyi.com/v_19rrb5h8kw.html"
Downloading [36mhttps://www.iqiyi.com/v_19rrb5h8kw.html[0m error:
[31mcan't play this video[0m

**Comment by iawia002** [comment]
这种是爱奇艺的接口不返数据的，现在解决不了

**Comment by SeaHOH** [comment]
https://github.com/zhangn1985/ykdl/commit/0bfd0a0cece6f982df641337325862175602cae4#diff-5f7f459abf17b98d5275a80eb3baa0ae
http://cache.video.qiyi.com/vps 能用，ykdl 已经用很久了。

**Comment by iawia002** [comment]
@SeaHOH #316 的问题能解决吗

**Comment by SeaHOH** [comment]
全部试过一遍，只有一个收费的无法播放，估计加上付费的 cookies 就能用。

**Comment by iawia002** [comment]
我空了看一下那个算法

BTW：iqiyi 的会员好像要单独适配

**Comment by SeaHOH** [comment]
嗯，ykdl 没有支持 会员/VIP/cookies 的打算。
