### ISSUE TITLE
油管上的一个视频下载转码出错

### ISSUE THREAD

**Issue by jiqing112** [iawia002/annie#345]
https://www.youtube.com/watch?v=ldb0y-Q7L9I

是这个漂亮妹子的舞蹈视频，好东西大家一起看看....
用annie下载之后，路径下有一个webm视频，一个m4a音频文件，和一个转码出错的mp4文件。
貌似是调用ffmpeg视频转码阶段的错误。
youtube-dl顺利下载，转换完是一个webm文件。

![snipaste_2018-12-18_16-49-25](https://user-images.githubusercontent.com/17674011/50142562-68c4b900-02e5-11e9-8bd8-a3f951e39f9e.png)
![snipaste_2018-12-18_16-50-18](https://user-images.githubusercontent.com/17674011/50142576-6f533080-02e5-11e9-9154-0b62581b7b63.png)

**Comment by jiqing112** [comment]
感觉更像是我的环境问题，下载视频转码偶尔出错，不清楚怎么回事

**Comment by jiqing112** [comment]
用当前版本的ffmpeg做了好多定制开发，还不敢升级。问题先放着吧，如果别人那里没有相似的问题就是我这里的环境了

**Comment by liunianbanbo** [comment]
同样的问题
