### ISSUE TITLE
[bilibili]解析异常 https://www.bilibili.com/video/av14325037

### ISSUE THREAD

**Issue by benqktc** [iawia002/annie#352]
Z:\>annie -v

[36mannie[0m: version [34m0.9.0[0m, A fast, simple and clean video downloader.

Z:\>annie https://www.bilibili.com/video/av14325037
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/iawia002/annie/extractors/bilibili.Download(0xc000072030, 0x29, 0xc00007203c, 0x8, 0x0, 0x0, 0x0)
        /Users/mac/iawia002/go/src/github.com/iawia002/annie/extractors/bilibili/bilibili.go:145 +0xf27
main.download(0xc000072030, 0x29)
        /Users/mac/iawia002/go/src/github.com/iawia002/annie/main.go:107 +0xb95
main.main()
        /Users/mac/iawia002/go/src/github.com/iawia002/annie/main.go:211 +0x121

Z:\>annie -i https://www.bilibili.com/video/av14325037
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/iawia002/annie/extractors/bilibili.Download(0xc000072030, 0x29, 0xc00007203c, 0x8, 0x0, 0x0, 0x0)
        /Users/mac/iawia002/go/src/github.com/iawia002/annie/extractors/bilibili/bilibili.go:145 +0xf27
main.download(0xc000072030, 0x29)
        /Users/mac/iawia002/go/src/github.com/iawia002/annie/main.go:107 +0xb95
main.main()
        /Users/mac/iawia002/go/src/github.com/iawia002/annie/main.go:211 +0x121

Z:\>

**Comment by iawia002** [comment]
你这个视频有点奇怪，要登录才能看，你带上登录过的 cookie 就能下载了

```console
$ annie -i -c cookies.txt av14325037

 Site:      哔哩哔哩 bilibili.com
 Title:     BBC 弗洛伊记录片 BBC 弗洛伊德的外甥
 Type:      video
 Streams:   # All available quality
     [16]  -------------------
     Quality:         流畅 360P
     Size:            185.94 MiB (194970085 Bytes)
     # download with: annie -f 16 ...

     [64]  -------------------
     Quality:         高清 720P
     Size:            107.32 MiB (112531211 Bytes)
     # download with: annie -f 64 ...

     [32]  -------------------
     Quality:         清晰 480P
     Size:            107.32 MiB (112531211 Bytes)
     # download with: annie -f 32 ...

     [80]  -------------------
     Quality:         高清 1080P
     Size:            107.32 MiB (112531211 Bytes)
     # download with: annie -f 80 ...
```

**Comment by benqktc** [comment]
谢谢
