### ISSUE TITLE
B站外挂字幕无法下载

### ISSUE THREAD

**Issue by afeizh** [iawia002/annie#353]
B站外挂字幕无法下载
比如:https://www.bilibili.com/video/av34936698/?spm_id_from=333.788.videocard.17
下载下来的只有视频,没有字幕
请问如何解决

**Comment by sqliuchang** [comment]
有些转载up主不再压制内嵌字幕的视频了，只有外挂的CC字幕
希望能够添加自动下载cc字幕的功能

**Comment by misdake** [comment]
我顺着网络请求摸索了一下方法，步骤如下：
1. 下载播放网页的源代码
2. 找到<script>window.__INITIAL_STATE__ = {。。。。。。}</script>
3. 找到window.__INITIAL_STATE__.videoData.subtitle.list
4. 这是个数组，每个元素都是一种语言的字幕，元素包含语言和一个url，url指向一个json文件，文件内容就是字幕
5. 把字幕json转换成播放器可用的格式

**Comment by snylonue** [comment]
请求支持 cc 字幕解析

**Comment by huntwin** [comment]
希望能实现b站外挂字幕的下载，现在b站上很多视频都是外挂字幕的
