### ISSUE TITLE
优酷视频下载不完整

### ISSUE THREAD

**Issue by jarwin123** [iawia002/annie#355]
你好：
  我用annie -ccode 0590 -d  https://v.youku.com/v_show/id_XMzk1NjM2OTAw.html?spm=a2h0j.11185381.listitem_page1.5!3~A&&s=cc003400962411de83b1下载的时候，内容只有12分钟，但是视频是有24分钟的，我哪里使用的有问题吗？

**Comment by iawia002** [comment]
尝试带上登录过的 cookies 来下载，这样能下完整的

```console
$ annie -c ~/Downloads/youku.txt https://v.youku.com/v_show/id_XMzk1NjM2OTAw.html

 Site:      优酷 youku.com
 Title:     名侦探柯南 第003话 偶像密室杀人事件
 Type:      video
 Stream:
     [mp4hd-guoyu]  -------------------
     Quality:         mp4hd 576x432 国语
     Size:            97.69 MiB (102440509 Bytes)
     # download with: annie -f mp4hd-guoyu ...

 97.69 MiB / 97.69 MiB [==========================================] 100.00% 1.85 MiB/s 52s
Merging video parts into 名侦探柯南 第003话 偶像密室杀人事件.mp4
```

**Comment by jarwin123** [comment]
![default](https://user-images.githubusercontent.com/8475971/52844588-d8b5bb00-313f-11e9-9ad9-7cfae73d45ff.png)

我的浏览器cookies:
  __ysuid=1544893918981EpW; cna=4COcFKCO9xACAXEupD7U2H/S; juid=01cupdl32b1fth; gray_mark=75; l=aB0nMjIZyFZ4VSsKyMaO8SCNu7076CZPjOAY1MwL-TEhNPVo8XUYx9tvCzsINjNCfqOIuEmV505j0; ycid=0; __ayft=1549956960105; __aysid=1549956960105Xa6; __ayscnt=1; yseid=1550213115118HHvKeH; yseidcount=14; P_ck_ctl=8C6E0C0EF1D077C755D704F7DE75FE6D; __arycid=dz-3-00; __arcms=dz-3-00; seid=01d3o31mn01ivm; referhost=https%3A%2F%2Fv.youku.com; __arpvid=1550219483222DLJl0V-1550219483237; __aypstp=23; __ayspstp=23; seidtimeout=1550221287354; ypvid=1550219490359R6OtV9; ysestep=8; yseidtimeout=1550226690361; ystep=58; _m_h5_tk=dbee6612f65228c389513db85be22bf1_1550223091040; _m_h5_tk_enc=4907181a51f6443b7fcb2b91f0c5a9b3; __ayvstp=147; __aysvstp=147; isg=BJGRzWVRqcZmAcWh1dRQpiEPoJ2H7mHinn5CF3MmeNh3GrFsu0pvQc18vK5ZEp2o

url是：https://v.youku.com/v_show/id_XNTI4NjIyNDI0.html

总是提示我的cookies有错误，我应该怎么获取我的cookies呢？谢谢

**Comment by iawia002** [comment]
@jarwin123 不要直接把完整的 cookie 写在评论里，我先帮你把评论删了

你那个 cookie 文件多了一行空行，删了就好了

**Comment by jarwin123** [comment]
我这个文件就一行呀，怎么会多一行呀

**Comment by iawia002** [comment]
后面有一个 `\n` 的，有一个空的换行，你用文本编辑器打开看一下就知道了

**Comment by jarwin123** [comment]
刚试了，添加上cookie还是不能下载完

**Comment by jarwin123** [comment]
![default](https://user-images.githubusercontent.com/8475971/52846090-ab6b0c00-3143-11e9-9b43-dd958566e807.png)

**Comment by iawia002** [comment]
这个视频是会员才能看的吗？

**Comment by jarwin123** [comment]
不是，谁都可以看

**Comment by iawia002** [comment]
发一下这个视频的链接，我空了调试一下

**Comment by jarwin123** [comment]
https://v.youku.com/v_show/id_XNTI4NjIyNDI0.html?spm=a2h0j.11185381.listitem_page1.5!25~A&s=cc001f06962411de83b1

**Comment by jarwin123** [comment]
![default](https://user-images.githubusercontent.com/8475971/52849077-2daafe80-314b-11e9-9803-313459ec3e82.png)
请教下，我安装了cookies.txt插件，他的cookies会存放在哪里？

**Comment by iawia002** [comment]
`click here` 下载当前站的 cookies，它会弹窗让你选保存在哪的

**Comment by iawia002** [comment]
更新最新版了吗，我也能下载完整的啊，23 分钟多

```console
$ annie -ccode 0502 -c ~/Downloads/youku.txt https://v.youku.com/v_show/id_XNTI4NjIyNDI0.html

 Site:      优酷 youku.com
 Title:     火影忍者 第025话 决定胜负 进退两难的第十题
 Type:      video
 Stream:
     [mp4hd3]  -------------------
     Quality:         mp4hd3 1920x1080
     Size:            211.00 MiB (221251487 Bytes)
     # download with: annie -f mp4hd3 ...

 211.00 MiB / 211.00 MiB [==================================================================================================================================================================] 100.00% 3.92 MiB/s 53s
Merging video parts into 火影忍者 第025话 决定胜负 进退两难的第十题.mp4
```

**Comment by jarwin123** [comment]
但是下载的文件内容跟图片的内容是一样一样的，也不是name=value；name2=value2这种格式，想问下有qq群或者微信群吗？我想加进去，谢谢@iawia002

**Comment by iawia002** [comment]
对，这是另一种格式的 cookie，也支持的
暂时没有交流群

**Comment by jarwin123** [comment]
你可以截个你的cookies片段吗？我想看看到底是什么样的，另外你的cookies是会员的cookies吗？

**Comment by iawia002** [comment]
就是你图上那种，key=value 那种格式的也行，我是会员

**Comment by jarwin123** [comment]
我试了，用保存了的cookies.txt，还是不行
![default](https://user-images.githubusercontent.com/8475971/52860474-8211a680-316a-11e9-95fb-216440bf366f.png)

**Comment by jarwin123** [comment]
你可以试下不是会员的cookies吗？看看是不是跟我的症状一样

**Comment by xpsviewer** [comment]
我也一样, 非会员cookie不行.
![default](https://user-images.githubusercontent.com/23251507/52902447-d93b7800-324b-11e9-9844-e4d2f725718e.PNG)

**Comment by iawia002** [comment]
我就一个优酷的号

@jarwin123 @xpsviewer 你们的 cookies 不对吧，确定是网页上登录了才下载的？或者换个 ccode，0590

**Comment by jarwin123** [comment]
cookies是用插件cookies.txt保存下来的，应该没问题的

**Comment by jarwin123** [comment]
@iawia002 你可以试下非会员的cookies，如果你的可以，那证明我们的cookies有问题，你弄一个其他浏览器的，其他的ccode也试了，0590的下载不完整

**Comment by xpsviewer** [comment]
@jarwin123 
好像得cookie结合ccode 0502 一起就可以, 而且必须登录一个帐号, 昨天没有登录.
![3](https://user-images.githubusercontent.com/23251507/52910529-b654a680-32d3-11e9-9f74-d2895d7a1fe9.PNG)
![5](https://user-images.githubusercontent.com/23251507/52910535-bc4a8780-32d3-11e9-9da0-be945ae8e208.PNG)

我的cookie用扩展抓的
![cookies](https://user-images.githubusercontent.com/23251507/52910545-df753700-32d3-11e9-98ec-db4d74eb757e.PNG)

**Comment by jarwin123** [comment]
好像会员的不行
我按你的方法不收费的是可以下载完整的，vip的视频还不行
@xpsviewer

**Comment by jarwin123** [comment]
![default](https://user-images.githubusercontent.com/8475971/52996691-5982f880-3459-11e9-849f-5edb26caa1cb.png)
annie -ccode 0502 -c new.txt https://v.youku.com/v_show/id_XNTI4NjIyNDI0.html（非vip片，可以下载）
annie -ccode 0502 -c new.txt https://v.youku.com/v_show/id_XNDA2MTg3NzQwMA==.html（vip片，下载不完整）

**Comment by xpsviewer** [comment]
你不是vip账号的cookie本来就只能下15分钟的试看吧，我也不太清楚，没下过vip视频
