### ISSUE TITLE
爱奇艺解析失效。。。。。。。HTTP405

### ISSUE THREAD

**Issue by AmyRose1288** [iawia002/annie#356]
PS C:\Users\Amy Rose\Desktop\工具包> ./annie.exe https://www.iqiyi.com/v_19rr5bqof0.html
Downloading [36mhttps://www.iqiyi.com/v_19rr5bqof0.html[0m error:
[31mhttp://data.video.qiyi.com/videos/v0/20181005/88/e4/955eb363f55a720aec8c8da8df07bb38.f4v?qd_tvid=1397222000&qd_vipres=2&qd_index=1&qd_aid=229180501&qd_stert=0&qd_scc=cd71240fb531601f765a6efea558dd46&qd_sc=abfb9ef0dc153fb539c1cb2f8a862162&qd_p=3b4220be&qd_ip=3b4220be&qd_k=d15a022bcf92eb2d86d88103d4b76dd4&qd_src=01012001010000000000&qd_vipdyn=2&qd_uid=0&qd_tm=1546862394137&qd_vip=0 request error: HTTP 405[0m

**Comment by lishubing** [comment]
貌似是vps接口不给用了？vps接口里的url都用不了了。。
换别的接口的话……vf值的md5盐是不是也不一样了……

**Comment by iawia002** [comment]
VIP 视频下载不了

**Comment by lizhaojing** [comment]
> VIP 视频下载不了

目前是使用cookies还报http405，期待支持。

**Comment by bergyu2020** [comment]
> > VIP 视频下载不了
> 
> 目前是使用cookies还报http405，期待支持。

你的cookie是怎么拼的啊？
