### ISSUE TITLE
請問優酷的聲道可以選擇嗎?

### ISSUE THREAD

**Issue by maaxthou** [iawia002/annie#357]
我想下載粵語的,但好像只能下載國語,在網頁中是可以選擇聲道的,謝謝
https://v.youku.com/v_show/id_XMTQyMTY2MzM3Mg==.html?spm=a2h0k.11417342.soresults.dplaybutton&lang=%E7%B2%A4%E8%AF%AD&_time=11.153

**Comment by maaxthou** [comment]
原來用-i 就可以了,不好意思我不是學電腦的所以不太懂

**Comment by iawia002** [comment]
恩用 `-i` 可以看到一个列表，选一个就行了
