### ISSUE TITLE
有什么方便获取cookies的方法吗？我看了#37没啥卵用

### ISSUE THREAD

**Issue by xiaoliu2012** [iawia002/annie#362]
![Uploading 1.png…]()
![Uploading 2.png…]()
![Uploading 3.png…]()
annie -c cookies.txt http://v.youku.com/v_show/id_XMzQ0MzAyNzk1Mg==.html?spm=a2h1n.8261147.reload_1.1~3!3~A&s=3074efbfbdefbfbdefbf

**Comment by xiaoliu2012** [comment]
https://i.bmp.ovh/imgs/2019/01/112702d5c6b9fd34.png
https://i.bmp.ovh/imgs/2019/01/d8e7f8a2c7372714.png
https://i.bmp.ovh/imgs/2019/01/675e0b325a79e787.png

**Comment by iawia002** [comment]
Chrome 用 cookies.txt 这个插件可以直接下载 cookies
