### ISSUE TITLE
Is there a way to use annie as a library?

### ISSUE THREAD

**Issue by lherman-cs** [iawia002/annie#364]
I want to use annie a video url extractor for my application. But, from what I see is that annie is strongly integrated with "config" that is specified as cli arguments. I could definitely use annie as cli and just use it as a subprocess. But, it seems very hacky and not reliable.

What I want is something like:
```go
package main

import "github.com/iawia002/annie"

func main(){
    url := "https://www.youtube.com/watch?v=jF0kD7lxTTw"
    extractor := annie.New()
    data := extractor.Extract(url)
    // Use the data for my program
}
```

**Comment by iawia002** [comment]
Theoretically, yes, you can use annie as a library, here is an example:

```go
package main

import (
	"fmt"

	"github.com/iawia002/annie/config"
	"github.com/iawia002/annie/extractors/youtube"
)

func main() {
	url := "https://www.youtube.com/watch?v=jF0kD7lxTTw"
	config.ThreadNumber = 20
	fmt.Println(youtube.Extract(url))
}
```
