### ISSUE TITLE
爱奇艺vip视频无法下载

### ISSUE THREAD

**Issue by HeavenWatsons** [iawia002/annie#369]
刚试了下，普通视频正常下载，但是vip视频下载不了（附上vip账号的cookies也下载不了）

你们能下么？

**Comment by HeavenWatsons** [comment]
https://www.iqiyi.com/v_19rqrb717g.html#curid=1858273200_e49787a049ec2c2b1bbec79a9112dfcd


C:\Users\yfyan>annie -c C:\Users\yfyan\iqiyicookies.txt https://www.iqiyi.com/v_19rqrb717g.html#curid=1858273200_e49787a049ec2c2b1bbec79a9112dfcd
Downloading [36mhttps://www.iqiyi.com/v_19rqrb717g.html#curid=1858273200_e49787a049ec2c2b1bbec79a9112dfcd[0m error:
[31mhttp://data.video.iqiyi.com/videos/v0/20190117/0b/be/ad417afea40baf795ccd535554892bf8.f4v?qd_tvid=1858273200&qd_vipres=2&qd_index=1&qd_aid=216260801&qd_stert=0&qd_scc=27d07d46cfdc08939e6c289da517d051&qd_sc=163c831f6d20996bac7b3a4f5845248e&qd_p=718c0b05&qd_ip=718c0b05&qd_k=2d0b6a8a4e1ae450fe8148ec1ef63844&qd_src=01012001010000000000&qd_vipdyn=2&qd_uid=0&qd_tm=1547989983779&qd_vip=0 request error: HTTP 405[0m

**Comment by iawia002** [comment]
爱奇艺暂不支持 VIP 视频

**Comment by FngvGe** [comment]
> 爱奇艺暂不支持 VIP 视频



> 爱奇艺暂不支持 VIP 视频

大佬，可否支持一下，除了不能下爱奇艺的vip视频，其他都完美了！感谢大佬！

**Comment by FngvGe** [comment]
> 爱奇艺暂不支持 VIP 视频
大佬，可否支持一下，除了不能下爱奇艺的vip视频，其他都完美了！感谢大佬！

**Comment by FngvGe** [comment]
> 爱奇艺暂不支持 VIP 视频
大佬，可否支持一下，除了不能下爱奇艺的vip视频，其他都完美了！感谢大佬！

**Comment by FngvGe** [comment]
大佬，可否支持一下，除了不能下爱奇艺的vip视频，其他都完美了！感谢大佬！
