### ISSUE TITLE
请问cookies.txt如何获取，具体如何使用~~

### ISSUE THREAD

**Issue by lleeopen** [iawia002/annie#37]
请问cookies.txt如何获取，具体如何使用~~

我从IE导出的cookies.txt不能用，出错~~

**Comment by iawia002** [comment]
@lleeopen cookies 的格式是这样的 `name=value; name2=value2; ...`，具体可以看 https://github.com/iawia002/annie#cookies

也不用非要放到文件里面，直接 `-c` 加 cookies 字符串也可以

一般可以在 Chrome 的 network 里面的 request headers 里面找到

**Comment by lleeopen** [comment]
F:\annie>annie -c cookies.txt http://www.iqiyi.com/v_19rrbl81hc.html

   Site:   爱奇艺 iqiyi.com
  Title:   齐木楠雄的灾难 第2季 第10集
   Type:   video
Quality:   1920x1080
   Size:   63.11 MiB (66176564 Bytes)

 63.11 MiB / 63.11 MiB [========================================================================] 100.00% 9.94 MiB/s 6s
Merging video parts into 齐木楠雄的灾难 第2季 第10集.mp4

我在在 Chrome 的 network 里面的 request headers 里面找到cookies代码复制到文本，加载没有用，我有爱奇艺的vip账号~~

**Comment by lleeopen** [comment]
我的用的annie.exe下载的，cookies到底是怎么弄的，我真搞不懂，还有优酷只下载一半就开始合并了~~·

**Comment by iawia002** [comment]
@lleeopen 可能爱奇艺的 VIP 鉴权不是用的 cookies，是用其他类似于签名的东西，这个要单独适配，目前单独适配的只有 B 站

优酷有些视频确实有问题，目前还未找到解决方法 #43

**Comment by lleeopen** [comment]
非常感谢您在百忙之中回答我的问题，目前爱奇艺的用户量也是比较大的，大部分的视频没有水印，很多人都比较喜欢下载，手中有vip账号却无法实现用软件下载，遗憾啊~~~

**Comment by iawia002** [comment]
@lleeopen 我提了个新 issue #50，没调研过爱奇艺这方面的接口，我会尝试适配的
