### ISSUE TITLE
[bilibili] B站港澳台番剧只有第一集

### ISSUE THREAD

**Issue by Funky-ovo** [iawia002/annie#373]
已挂梯子，之前用单文件版整个番剧下载下来都是第一集，换了安装版之后就直接下载不了了，求解

annie -c C:/Users/Desktop/cookies.txt -s 127.0.0.1:1080 -p https://www.bilibili.com/bangumi/play/ep199859
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/iawia002/annie/extractors/bilibili.bilibiliDownload(0xc0000862a0, 0x2
e, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        C:/Users/go/src/github.com/iawia002/annie/extractors/bilibili/bilib
ili.go:215 +0xd9f
github.com/iawia002/annie/extractors/bilibili.Download(0xc0000862a0, 0x2e)
        C:/Users/go/src/github.com/iawia002/annie/extractors/bilibili/bilib
ili.go:152 +0x870
main.download(0xc0000862a0, 0x2e)
        C:/Users/go/src/github.com/iawia002/annie/main.go:67 +0x7aa
main.main()
        C:/Users/go/src/github.com/iawia002/annie/main.go:134 +0xfb

**Comment by iawia002** [comment]
重新登录一下 B 站，用新的 cooike 试试

**Comment by Funky-ovo** [comment]
> 重新登录一下 B 站，用新的 cookie 试试

重新登录，分别试了Chrome和firefox两个浏览器导出的cookies，以及-c "sid=****; DedeUserID=12345678; DedeUserID__ckMd5=123456789abcdf; SESSDATA=e123456f%2C1234567822%2Cabcde45;"这种格式，还是同样出现之前的问题
