### ISSUE TITLE
安装失败，go get 没反应

### ISSUE THREAD

**Issue by hqin2013** [iawia002/annie#376]
Debian 7 64位操作系统，已经安装Go和 FFmpeg 。运行安装命令` go get github.com/iawia002/annie`，没有反应，不熟悉Go语言，不知道该咋整？

尝试下载.gz包，解压缩后就一个文件，直接运行 `annie https://www.youtube.com/watch?v=dQw4w9WgXcQ` 也没有反应。

有什么建议吗？谢谢

**Comment by iawia002** [comment]
想确认安装成功与否的话，直接运行 `annie -v`，有输出就成功了

```console
$ annie -v

annie: version 0.9.1, A fast, simple and clean video downloader.
```
