### ISSUE TITLE
能否增加腾讯  优酷 乐视 tv接口

### ISSUE THREAD

**Issue by 1422384664** [iawia002/annie#377]
腾讯云试听极光接口：http://tv.aiseet.atianqi.com/openqq/getvinfo?otype=json&platform=10503&sdtfrom=v6133&vid=n0029iv6xsm&hevclv=16&spwm=2&encryptVer=4.2&defn=dolby&appVer=3.3.1.5216&otype=json&cKey=--01dFK_hGFJMKpf5dFxaFBbgxmjrVaVY6ABtO3SC2L57Xx6Gx6CT0xLyuR2BpdvjF8ryct-OpC3YQhuidBVpfSLz-Y3Fd18kJBbeuCRi8eFxgAvhp1IfHmOLbLuj5KCqBEmpxVHTcug88YMgqe_Y7uKc6KJsxkB3WluNOg7eRv7B99kgyF5Y0gHGrTHJ-X3nWE_1TjWXQ&defnpayver=5&dtype=3

优酷酷喵接口：http://ups.cp31.ott.cibntv.net/ups/get.json?ckey=7B19C0AB12633B22E7FE81271162026020570708D6CC189E4924503C49D243A0DE6CD84A766832C2C99898FC5ED31F3709BB3CDD82C96492E721BDD381735026&vid=XMzk4NDE2Njc4OA==&password=&ccode=0103010102&client_ip=192.168.1.1&utid=WzrpFLQIjvQDAGaLEM4dJn2N&client_ts=1547882204&h265=1&ptoken=&stoken=&atoken=

乐视tv接口:http://api.itv.cp21.ott.cibntv.net/iptv/api/new/video/play/get.json?&token=&userId=&timestamp=1549193445138&client=android&stream=4k&supportStream=1_1_1&broadcastId=2&sig=E43F6FF96FA44E386F7987E1B16E3549&videoid=1902138&mac=&username=

http://api.itv.cp21.ott.cibntv.net/iptv/api/new/video/play/get.json?&token=&userId=&timestamp=1549193495346&client=android&stream=4k&supportStream=1_1_1&broadcastId=2&sig=458FE230A0BDFD43ECB50F3ADFF31B30&videoid=29621310&mac=&username=

**Comment by iawia002** [comment]
现在没有精力适配新的接口

**Comment by HuShanquan3** [comment]
这个不好解析弄
