### ISSUE TITLE
MGTV 无法下载

### ISSUE THREAD

**Issue by wellos99** [iawia002/annie#379]
Downloading [36mhttps://www.mgtv.com/b/327938/5119678.html[0m error:
[31mhttp://210.22.60.20/c1/2019/02/06_0/B59D841DAE84F4AC52F4B92137038B96_20190206_1_1_189_mp4/E4114CEFA62101FC2B13150BAC81286D.m3u8?arange=0&pm=M1abFUxdJsB7UL4GIMsBQBECJUjgNceget8rIybKzVbche60tPk_6cfB5PqdbgxvxH3xHvdtbJ1CsearRFGOQryHEdoR54c2mEl1MIQXws41hn7jJrBwBGuzAdAEdSSgRU_XeRhcwc5a5ds_V4~zOIqzpG2pMovZvCisCuQCLBEFGG7tRW0DB_iC9uuipwHpSrXhgQdqM36KIdsJCWKytyunJLCVe~xdxa~2DJ3odkEMCY4lYer0yXDuB7QrLbFNBovJkeq4mY_5rjEiIkXiBKR9lRJja~dd7JBoehbO_5doMf9mWJyWZYKwF9BdIohczTh4ivrmAax6qSFmeKZQTrZQbwcGliq1i5osYZPjnG2Nm8QG01Kt5G2~AjgSOib9BmmKUAQvG8_~HJ~G5wlLYzcvhQhCF~vTHbBbyhQTqNeMrcSaWr5223onI0Q-&mr=eyd~Jc79iOuBiZrvArXPVP5FcvS7xs0YsR6xIxtnLt0YX79m2_mLFhhj78hLZGNr7YQkTXU0P6DgACVNuoTyFkO~VhY-&vcdn=0&scid=273 request error: HTTP 405[0m

**Comment by prokiller1199** [comment]
是的 不能下了 几个礼拜了

**Comment by iawia002** [comment]
网络问题？我这里复现不了

```console
$ annie https://www.mgtv.com/b/327938/5119678.html

 Site:      芒果TV mgtv.com
 Title:     众王驾到 洛夕被混沌附身陷入昏迷
 Type:      video
 Stream:
     [3]  -------------------
     Quality:         超清
     Size:            165.41 MiB (173442784 Bytes)
     # download with: annie -f 3 ...

 7.80 MiB / 165.41 MiB [=======>---------------------------------------------------------------------------------------------------------------------------------------------------------]   4.72% 1.42 MiB/s 01m51s
```

**Comment by wellos99** [comment]
VIP视频下载不了。

**Comment by iawia002** [comment]
VIP 视频本来就不支持
