### ISSUE TITLE
Select and download available YouTube video formats

### ISSUE THREAD

**Issue by lamg** [iawia002/annie#38]
A feature similar to `youtube-dl -F` which gives a list of available formats, and then allows downloading a specific one using  `youtube-dl -f number_that_identifies_format`

**Comment by iawia002** [comment]
hi @lamg, Actually, more than one person asked me about this, but Annie wanted to be simple at the beginning of the design, so Annie's approach is to download the highest quality video that can be obtained, I mean, now the internet gets faster, so why not download the best.

These are just my personal opinions, I left this open to see what others thought about this.

**Comment by arpit1997** [comment]
@iawia002 why not both the options? Give users the capability of choosing as well as a default behavior of getting best video. Let me know your thoughts.

**Comment by lamg** [comment]
@iawia002 Simplicity is very important, but there are ways of managing complexity without breaking a design. Probably keeping `annie` simple for the user and for the programmer, while making it more useful, is a challenge of the kind that should be taken. This is very general, you're the one who knows the design, therefore the you have the last word on this issue. But if your design is formally stated maybe more people can have a word on that. I'm available for helping you with it (I will tell you later what I understand about your code). Besides, "the internet gets faster" isn't true in my case.

**Comment by iawia002** [comment]
@arpit1997 @lamg 
At the very beginning, I only considered my own situation (I like high definition video), and only one option is simpler from code implementation, but now I realize that this seems too 'arbitrary', you are right, we should give users the capability of choosing.

So,  here are my thoughts, download the highest definition video by default, and support downloading other formats

**Comment by iawia002** [comment]
I'll start on this, as soon as I've made a progress, I'll submit a PR, you can help review.

**Comment by iawia002** [comment]
```go
// URLData data struct of single URL
type URLData struct {
	URL  string
	Size int64
	Ext  string
}

// VideoData data struct of video info
type VideoData struct {
	Site  string
	Title string
	// [URLData: {URL, Size, Ext}, ...]
	// Some video files have multiple fragments
	// and support for downloading multiple image files at once
	URLs    []URLData
	Size    int64
	Type    string
	Quality string
}
```
this is the data struct for now, and I think it shoude be changed to:

```go
// URLData data struct of single URL
type URLData struct {
	URL  string
	Size int64
	Ext  string
}

// FormatData data struct of every format
type FormatData struct {
	// [URLData: {URL, Size, Ext}, ...]
	// Some video files have multiple fragments
	// and support for downloading multiple image files at once
	URLs    []URLData
	Quality string
	Size    int64
}

// VideoData data struct of video info
type VideoData struct {
	Site  string
	Title string
	Type  string
	// each format has it's own URLs and Quality
	Formats map[string]FormatData
}
```
any thoughts about this? By the way, if you got any suggestion about naming, just say it, feel free

**Comment by lamg** [comment]
The type `map[string]FormatData` seems fine for storing the information about available video formats, but if the user is going to select the format by typing that map's keys, then they should be easy to type. `youtube-dl` identifies formats using numbers, but I don't know if that is due some internal processing or if it's just the way YouTube returns data.

Example `youtube-dl -F` output:

```
[info] Available formats for $VIDEO_ID:
format code  extension  resolution note
249          webm       audio only DASH audio   57k , opus @ 50k, 21.81MiB
250          webm       audio only DASH audio   85k , opus @ 70k, 28.24MiB
140          m4a        audio only DASH audio  131k , m4a_dash container, mp4a.40.2@128k, 55.98MiB
171          webm       audio only DASH audio  135k , vorbis@128k, 54.15MiB
251          webm       audio only DASH audio  161k , opus @160k, 56.07MiB
160          mp4        192x144    144p   28k , avc1.4d400c, 30fps, video only, 5.67MiB
133          mp4        320x240    240p   53k , avc1.4d400d, 30fps, video only, 9.81MiB
278          webm       192x144    144p   73k , webm container, vp9, 15fps, video only, 12.79MiB
134          mp4        480x360    360p  113k , avc1.4d401e, 30fps, video only, 18.38MiB
242          webm       320x240    240p  133k , vp9, 30fps, video only, 21.64MiB
135          mp4        640x480    480p  190k , avc1.4d401e, 30fps, video only, 29.09MiB
243          webm       480x360    360p  224k , vp9, 30fps, video only, 35.65MiB
136          mp4        960x720    720p  316k , avc1.4d401f, 30fps, video only, 47.99MiB
244          webm       640x480    480p  357k , vp9, 30fps, video only, 56.50MiB
137          mp4        1440x1080  1080p  492k , avc1.640028, 30fps, video only, 78.33MiB
247          webm       960x720    720p  697k , vp9, 30fps, video only, 104.54MiB
248          webm       1440x1080  1080p 1346k , vp9, 30fps, video only, 185.69MiB
17           3gp        176x144    small , mp4v.20.3, mp4a.40.2@ 24k
36           3gp        320x240    small , mp4v.20.3, mp4a.40.2
18           mp4        480x360    medium , avc1.42001E, mp4a.40.2@ 96k
43           webm       640x360    medium , vp8.0, vorbis@128k
22           mp4        960x720    hd720 , avc1.64001F, mp4a.40.2@192k (best)
```

**Comment by MurtadhaS** [comment]
@lamg  It is the way youtube returns data, you can check that using "stats for nerds" in youtube.

**Comment by iawia002** [comment]
> The type map[string]FormatData seems fine for storing the information about available video formats, but if the user is going to select the format by typing that map's keys, then they should be easy to type. 

If I'm not misunderstood, you mean that the optional format should be something like `HD` `720p`, these more intuitive strings, right?

> but I don't know if that is due some internal processing or if it's just the way YouTube returns data.

@MurtadhaS is right, It is the way youtube returns data, maybe Annie will do it the same way, like `annie -f 22 URL` etc.

> Maybe a field in FormatData with a video format description would be useful from the user perspective.

the `Quality` is the video format description field, it's value is like `720p`, `HD`.

**Comment by lamg** [comment]
@iawia002 In YouTube's case, would `Quality` store a string like `audio only DASH audio   57k , opus @ 50k, 21.81MiB`?

**Comment by iawia002** [comment]
@lamg maybe in next version? Now I have done some basic functions

```
 Site:      YouTube youtube.com
 Title:     Multifandom Mashup 2017
 Type:      video
 Streams:   # All available quality
     [43]  -------------------
     Quality:         medium
     Size:            31.95 MiB (33505824 Bytes)
     # download with: annie -f 43 "URL"

     [18]  -------------------
     Quality:         medium
     Size:            24.81 MiB (26011062 Bytes)
     # download with: annie -f 18 "URL"
......
```
