### ISSUE TITLE
速度计算方法即显示可能有误？

### ISSUE THREAD

**Issue by colemanlee** [iawia002/annie#381]
我的网速下载最大都没有超过2MB过，一直都是1.4兆左右，这里显示10.01MiB不对，而且实际下载速度也没有那么大。
``` 
2.13 GiB / 2.36 GiB [=======================================================>-----]  90.33% 10.01 MiB/s 00m23s
```

**Comment by misdake** [comment]
有一种可能是这样的：
显示的速度据我观察是总下载量除以本次下载时间，如果是恢复了之前ctrl+c中断的下载就会出现显示速度大于实际速度的情况。
参考：https://github.com/iawia002/annie/issues/160

**Comment by colemanlee** [comment]
非常感谢。
