### ISSUE TITLE
B站 ep下载的都是第一集

### ISSUE THREAD

**Issue by sxyazi** [iawia002/annie#382]
**版本：**
```
~/Desktop> annie -v
annie: version 0.9.1, A fast, simple and clean video downloader.
```

**B站剧集地址：**
https://www.bilibili.com/bangumi/play/ep130934
……
https://www.bilibili.com/bangumi/play/ep130973

**使用的下载指令：**

```bash
annie -c cookies.txt 'https://www.bilibili.com/bangumi/play/ep130938'
annie -c cookies.txt 'https://www.bilibili.com/bangumi/play/ep130939'
annie -c cookies.txt 'https://www.bilibili.com/bangumi/play/ep130940'
annie -c cookies.txt 'https://www.bilibili.com/bangumi/play/ep130941'
annie -c cookies.txt 'https://www.bilibili.com/bangumi/play/ep130942'
annie -c cookies.txt 'https://www.bilibili.com/bangumi/play/ep130943'
```

**打印出的内容：**
![1.png](https://i.loli.net/2019/02/09/5c5ee22846c34.png)
（观察发现 5-7 集大小都一样，实际播放内容为 第一集 `ep130934`）

类似的 issues 有 #370 ，看过发现其中可能使用了代理，增加了问题还原的复杂度，故重新发了一个（这个是没有使用代理的例子）。

**Comment by sxyazi** [comment]
补充：可能和登录状态（这里就是 Cookies ）没有关系，去掉 `-c cookies.txt` 指令后依然如此。

**Comment by iawia002** [comment]
已经解决这个问题了，我还没发新版本，如果有 go 环境的话，可以 go get 更新，没有的话等一下下个版本吧（最近一两周）
