### ISSUE TITLE
B站av号下载runtime error，番剧下载OK

### ISSUE THREAD

**Issue by asdhubin** [iawia002/annie#384]
尝试过很多av号都无法下载，但是同时番剧可以正常下载。
 .\annie.exe -d  av43570877
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/iawia002/annie/downloader.Download(0x745841, 0x19, 0xc000290150, 0x70, 0x73a0e0, 0x5, 0xc0001cc0f0, 0x0, 0x0, 0x0, ...)
        /Users/mac/iawia002/go/src/github.com/iawia002/annie/downloader/downloader.go:189 +0x1631
main.download(0xc00008a2a0, 0x29)
        /Users/mac/iawia002/go/src/github.com/iawia002/annie/main.go:163 +0x44f
main.main()
        /Users/mac/iawia002/go/src/github.com/iawia002/annie/main.go:217 +0x121

————————————番剧——————————————
 .\annie.exe  https://www.bilibili.com/bangumi/play/ss26283/

 Site:      哔哩哔哩 bilibili.com
 Title:     五等分的新娘
 Type:      video
 Stream:
     [80]  -------------------
     Quality:         高清 1080P
     Size:            222.86 MiB (233683104 Bytes)
     # download with: annie -f 80 ...

 5.65 MiB / 222.86 MiB [=>------------------------------------------------------------------]   2.53% 2.03 MiB/s 01m39s

**Comment by iawia002** [comment]
似乎是现在用的 appkey 不行了

**Comment by SeaHOH** [comment]
https://www.bilibili.com/video/av40391547
https://www.bilibili.com/bangumi/play/ep259083
感觉是页面结构问题，使用 av 号就好了。

**Comment by zpkosmos** [comment]
我也是，话说这annie如何更新那？

**Comment by Yesterday17** [comment]
这篇博客里的是可以用的：https://blog.kaaass.net/archives/947

`AppKey`: `iVGUTjsxvpLeuDCf`
`SecretKey`: `aHRmhWMLkdeMuILqORnYZocwMBpMEOdt`

**Comment by zpkosmos** [comment]
> 这篇博客里的是可以用的：https://blog.kaaass.net/archives/947
> 
> `AppKey`: `iVGUTjsxvpLeuDCf`
> `SecretKey`: `aHRmhWMLkdeMuILqORnYZocwMBpMEOdt`

您好，能在打搅你下你是如何修改AppKey和SecretKey的那？我安装annie时候下载下来的也只有一个exe文件，不太清楚在哪里能修改，控制台好像没找到AppKey的修改指令

**Comment by Yesterday17** [comment]
> > 这篇博客里的是可以用的：https://blog.kaaass.net/archives/947
> > `AppKey`: `iVGUTjsxvpLeuDCf`
> > `SecretKey`: `aHRmhWMLkdeMuILqORnYZocwMBpMEOdt`
> 
> 您好，能在打搅你下你是如何修改AppKey和SecretKey的那？我安装annie时候下载下来的也只有一个exe文件，不太清楚在哪里能修改，控制台好像没找到AppKey的修改指令

我是`go get`之后重新`go build`的...改的话是下面两行：

https://github.com/iawia002/annie/blob/705ee1ae23187a265155acfe373c3791fcc5144d/extractors/bilibili/bilibili.go#L26-L27

**Comment by zpkosmos** [comment]
> > > 这篇博客里的是可以用的：https://blog.kaaass.net/archives/947
> > > `AppKey`: `iVGUTjsxvpLeuDCf`
> > > `SecretKey`: `aHRmhWMLkdeMuILqORnYZocwMBpMEOdt`
> > 
> > 
> > 您好，能在打搅你下你是如何修改AppKey和SecretKey的那？我安装annie时候下载下来的也只有一个exe文件，不太清楚在哪里能修改，控制台好像没找到AppKey的修改指令
> 
> 我是`go get`之后重新`go build`的...改的话是下面两行：
> 
> [annie/extractors/bilibili/bilibili.go](https://github.com/iawia002/annie/blob/705ee1ae23187a265155acfe373c3791fcc5144d/extractors/bilibili/bilibili.go#L26-L27)
> 
> Lines 26 to 27 in [705ee1a](/iawia002/annie/commit/705ee1ae23187a265155acfe373c3791fcc5144d)
> 
>  appKey = "84956560bc028eb7" 
>  secKey = "94aba54af9065f71de72f5508f1cd42e"

是先用go get下载后，然后修改\src\github.com\iawia002\annie\extractors\bilibili下的bilibili.go文件，修改完后go build bilibili.go这个文件吗？不好意思，第一次用go，我这样做好像还是不能下载，我已经把修改了之前annie的PATH到我用go get 下载的annie所在路径了

**Comment by Yesterday17** [comment]
go build github.com/iawia002/annie

**Comment by zpkosmos** [comment]
> `go build github.com/iawia002/annie`

哇，成功了，多谢指导，涨知识了！

**Comment by iawia002** [comment]
我也今晚发个新版本

**Comment by lovecn** [comment]
go get -u github.com/iawia002/annie
 annie.exe -v

annie: version 0.9.2, A fast, simple and clean video downloader.
