### ISSUE TITLE
panic: runtime error: index out of range

### ISSUE THREAD

**Issue by NoString** [iawia002/annie#385]
Why is that? Annie 9.1 has been installed

root@host ~]# annie av43539789
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/iawia002/annie/downloader.Download(0x74995d, 0x19, 0xc000053260, 0x5c, 0x73edad, 0x5, 0xc00017d830, 0x0, 0x0, 0x0, ...)
        /Users/mac/iawia002/go/src/github.com/iawia002/annie/downloader/downloader.go:189 +0x162a
main.download(0xc000016270, 0x29)
        /Users/mac/iawia002/go/src/github.com/iawia002/annie/main.go:163 +0x448
main.main()
        /Users/mac/iawia002/go/src/github.com/iawia002/annie/main.go:217 +0x11a
[root@host ~]#

**Comment by iawia002** [comment]
和 #384 重复了，还在找解决方法，我把这个关了
