### ISSUE TITLE
如何获取B站视频名称，标签等属性？

### ISSUE THREAD

**Issue by NoString** [iawia002/annie#388]
我试了-j，感觉扒的东西太少，既然视频都能扒，为什么不连标题，标签，视频类别，视频简介，封面也一起扒下来呢？保存成json岂不美哉？🌝🌝🌝当然，我这只是提个意见

**Comment by iawia002** [comment]
因为我只需要标题和视频文件的地址，所以也没（也没必要）提取其他信息了，你有需要的话可以考虑一下其他的工具
