### ISSUE TITLE
哔哩哔哩无法解析，用了cookies也没用

### ISSUE THREAD

**Issue by DiangGen** [iawia002/annie#389]
annie -i https://www.bilibili.com/video/av42172030/
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/iawia002/annie/downloader.Download(0x745825, 0x19, 0xc0002a2140, 0x9e, 0x73a0dc, 0x5, 0xc0002b6150, 0x0, 0x0, 0x0, ...)
        /Users/mac/iawia002/go/src/github.com/iawia002/annie/downloader/downloader.go:189 +0x1631
main.download(0xc00007c030, 0x2a)
        /Users/mac/iawia002/go/src/github.com/iawia002/annie/main.go:157 +0x44f
main.main()
        /Users/mac/iawia002/go/src/github.com/iawia002/annie/main.go:211 +0x121

**Comment by iawia002** [comment]
已经修复了，0.9.2
