### ISSUE TITLE
youku解析不了，这项目好像问题多

### ISSUE THREAD

**Issue by beifengle** [iawia002/annie#390]
https://v.youku.com/v_show/id_XMjk4ODQ2NzU4OA==.html?spm=a2hzp.8253869.0.0

**Comment by goxofy** [comment]
你都不看ReadMe的吗

**Comment by beifengle** [comment]
> 你都不看ReadMe的吗

真的没有去看，只有当初第一次看到这项目时看了下，已经习惯了，麻烦指教下

**Comment by goxofy** [comment]
![image](https://user-images.githubusercontent.com/1695416/52943710-b1155b80-33a8-11e9-95bb-96f9ee565c32.png)

**Comment by beifengle** [comment]
@goxofy 3Q，能再问下你的cookie文件里是什么格式的吗，我在文件里是按name=value; name2=value2  格式写的，结果还是报错 
`D:\codes_go\annie>annie -c "youkucookie.txt" "https://v.youku.com/v_show/id_XMjk4ODQ2NzU4OA==.html"
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/iawia002/annie/extractors.youkuUps(0xc04200c19e, 0x11, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        C:/Users/lhy/go/src/github.com/iawia002/annie/extractors/youku.go:93 +0x71c
github.com/iawia002/annie/extractors.Youku(0xc04200c180, 0x34, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        C:/Users/lhy/go/src/github.com/iawia002/annie/extractors/youku.go:198 +0xde
main.download(0xc04200c180, 0x34)
        C:/Users/lhy/go/src/github.com/iawia002/annie/main.go:73 +0x454
main.main()
        C:/Users/lhy/go/src/github.com/iawia002/annie/main.go:134 +0xe7`

**Comment by Tokeyman** [comment]
出现这个就是你cookies文件的格式有问题了，从浏览器直接复制过来覆盖掉你的txt文件内容

**Comment by iawia002** [comment]
更新到最新版，用 cookies.txt 之类的浏览器插件来下载 cookies

**Comment by beifengle** [comment]
> 更新到最新版，用 cookies.txt 之类的浏览器插件来下载 cookies

麻烦介绍一个可以下载到 cookies.txt的插件好吗，实在没办法了

**Comment by Tokeyman** [comment]
> > 更新到最新版，用 cookies.txt 之类的浏览器插件来下载 cookies
> 
> 麻烦介绍一个可以下载到 cookies.txt的插件好吗，实在没办法了

chrome浏览器F12-->network,刷新一下优酷，过滤XHR，找带cookies的header，复制就行，或者百度搜一下浏览器插件

**Comment by iawia002** [comment]
@beifengle 就叫 `cookies.txt`，chrome 搜一下

**Comment by beifengle** [comment]
> > > 更新到最新版，用 cookies.txt 之类的浏览器插件来下载 cookies
> > 
> > 
> > 麻烦介绍一个可以下载到 cookies.txt的插件好吗，实在没办法了
> 
> chrome浏览器F12-->network,刷新一下优酷，过滤XHR，找带cookies的header，复制就行，或者百度搜一下浏览器插件

按你这样直接复制的内容放cookies.txt格式没有问题吗？不是文件的话只支持Netscape Cookie format这种格式吗，我现在就是不知怎么由KV转换成Netscape Cookie format这种文件格式

**Comment by Tokeyman** [comment]
@beifengle 额，一直这么用，没问题呀...

**Comment by beifengle** [comment]
> @beifengle 额，一直这么用，没问题呀...

可以直接把下面这堆放到cookie.txt文件可以用？
`Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3
Accept-Encoding: gzip, deflate, br
Accept-Language: zh-CN,zh;q=0.9
Cache-Control: max-age=0
Connection: keep-alive
Cookie: stardustvideo=1; CURRENT_FNVAL=16; sid=8u3d0963; rpdid=kwmoosslxkdospimlixww; _uuid=F7E4461A-95E2-F6E3-05D3-1D87C433BCD268630infoc; LIVE_BUVID=AUTO3115452853724542; fts=1545285385; CURRENT_QUALITY=32; buvid3=ACA59533-4F79-451D-9FD6-A1781AC0FD6F65936infoc
Host: www.bilibili.com
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36`

**Comment by Tokeyman** [comment]
@beifengle 我是只复制Cookie:后面的内容，保存到txt然后-c调用的
