### ISSUE TITLE
腾讯视频不能下载吗

### ISSUE THREAD

**Issue by goxofy** [iawia002/annie#395]

**Comment by iawia002** [comment]
不能下载的 URL 来一个

**Comment by prokiller1199** [comment]
https://v.qq.com/x/cover/1bav7atk48laen2/p0022corr7u.html

**Comment by iawia002** [comment]
@prokiller1199 你这个是需要 VIP 的肯定下不了啊，普通的视频有没有

**Comment by prokiller1199** [comment]
> @prokiller1199 你这个是需要 VIP 的肯定下不了啊，普通的视频有没有

哦哦 知道了 谢谢 那应该是可以了！

**Comment by redstoneleo** [comment]
这个不能下载 https://v.qq.com/x/cover/wussyc1mi5f6fkx/a00145qg0he.html
