### ISSUE TITLE
Bilibili视频没下载完整，请求帮助

### ISSUE THREAD

**Issue by hubs** [iawia002/annie#401]
https://www.bilibili.com/video/av17629439 您好，这个视频有共331分钟，下载到本机只有800多M，32分钟。是什么原因没下载完呢？谢谢。

**Comment by iawia002** [comment]
这个问题我也不知道原因，B 站 API 只返回了 800 多 M 的数据

**Comment by xhlove** [comment]
> [flv @ 000002831ed53980] Auto-inserting h264_mp4toannexb bitstream filter
>     Last message repeated 2 times
> [flv @ 000002831f03bec0] Auto-inserting h264_mp4toannexb bitstream filter5kbits/s speed=2.05e+03x
> [flv @ 000002831ed27800] Auto-inserting h264_mp4toannexb bitstream filter
> [NULL @ 000002831e7bfdc0] Invalid NAL unit size (0 > 11532).
> [NULL @ 000002831e7bfdc0] missing picture in access unit with size 11536
> [NULL @ 000002831e7bfdc0] Invalid NAL unit size (0 > 482).
> [NULL @ 000002831e7bfdc0] missing picture in access unit with size 486
> [concat @ 000002831e75aa80] h264_mp4toannexb filter failed to receive output packet
> concat.txt: Invalid argument

用ffmpeg合并有可以看到错误，是有文件损坏/或有错误数据了。具体损坏是第30和第32个分段。去除这两个分段合并可以得到正常的800M+的文件。
要忽略这个错误可以先将flv分段转ts，然后通过 cat/copy这样的命令将ts分段合并为完整的一个文件，最后使用ffmpeg -i copy.ts -c copy out.mp4这样的ffmpeg命令无损转换文件格式。
这是最终文件的mediainfo，大小时长都是对的：

> General
> Complete name                  : out.mp4
> Format                         : MPEG-4
> Format profile                 : Base Media
> Codec ID                       : isom (isom/iso2/avc1/mp41)
> File size                      : 837 MiB
> Duration                       : 5h 31mn
> Overall bit rate               : 353 Kbps
> Writing application            : Lavf58.23.102
> 
> Video
> ID                             : 1
> Format                         : AVC
> Format/Info                    : Advanced Video Codec
> Format profile                 : Baseline@L3.1
> Format settings, CABAC         : No
> Format settings, ReFrames      : 3 frames
> Format settings, GOP           : M=1, N=120
> Codec ID                       : avc1
> Codec ID/Info                  : Advanced Video Coding
> Duration                       : 5h 31mn
> Bit rate                       : 271 Kbps
> Width                          : 1 280 pixels
> Height                         : 720 pixels
> Display aspect ratio           : 16:9
> Frame rate mode                : Variable
> Frame rate                     : 14.985 (14985/1000) fps
> Minimum frame rate             : 0.119 fps
> Maximum frame rate             : 15.152 fps
> Original frame rate            : 15.000 fps
> Color space                    : YUV
> Chroma subsampling             : 4:2:0
> Bit depth                      : 8 bits
> Scan type                      : Progressive
> Bits/(Pixel*Frame)             : 0.020
> Stream size                    : 643 MiB (77%)
> Color range                    : Limited
> 
> Audio
> ID                             : 2
> Format                         : AAC
> Format/Info                    : Advanced Audio Codec
> Format profile                 : LC
> Codec ID                       : 40
> Duration                       : 5h 31mn
> Bit rate mode                  : Constant
> Bit rate                       : 77.6 Kbps
> Channel(s)                     : 2 channels
> Channel positions              : Front: L R
> Sampling rate                  : 44.1 KHz
> Frame rate                     : 43.066 fps (1024 spf)
> Compression mode               : Lossy
> Stream size                    : 184 MiB (22%)
> Default                        : Yes
> Alternate group                : 1

**Comment by xhlove** [comment]
补充一个样本，第30个flv分段 http://tmp.link/f/5d034dd6d8b7d
(用这个命令可以看到很多错误 ffmpeg -i 30.flv -c copy 30out.mp4)
另外这个视频请求480返回结果的实际文件是720p的。。

**Comment by hubs** [comment]
> 补充一个样本，第30个flv分段 http://tmp.link/f/5d034dd6d8b7d
> (用这个命令可以看到很多错误 ffmpeg -i 30.flv -c copy 30out.mp4)
> 另外这个视频请求480返回结果的实际文件是720p的。。
大佬可以提供一下flv 转 ts 的命令吗？谢谢。ffmpeg 试了几个都不行。

**Comment by xhlove** [comment]
> > 补充一个样本，第30个flv分段 http://tmp.link/f/5d034dd6d8b7d
> > (用这个命令可以看到很多错误 ffmpeg -i 30.flv -c copy 30out.mp4)
> > 另外这个视频请求480返回结果的实际文件是720p的。。
> 
> 大佬可以提供一下flv 转 ts 的命令吗？谢谢。ffmpeg 试了几个都不行。

ffmpeg -i in.flv -c copy out.ts

**Comment by hubs** [comment]
> > > 补充一个样本，第30个flv分段 http://tmp.link/f/5d034dd6d8b7d
> > > (用这个命令可以看到很多错误 ffmpeg -i 30.flv -c copy 30out.mp4)
> > > 另外这个视频请求480返回结果的实际文件是720p的。。
> > 
> > 
> > 大佬可以提供一下flv 转 ts 的命令吗？谢谢。ffmpeg 试了几个都不行。
> 
> ffmpeg -i in.flv -c copy out.ts

可以了，感谢。

1、ffmpeg -i in.flv -c copy out.ts （把所有的flv转成ts)
2、将ts放入一个文件中(比如ts.txt),好打包一起转载。
3、ffmpeg -y -f concat -safe -1 -i  ts.txt -c copy -bsf:a aac_adtstoasc ok.mp4
