### ISSUE TITLE
youku VIP视频不能下载

### ISSUE THREAD

**Issue by wellos99** [iawia002/annie#402]
https://v.youku.com/v_show/id_XNDAzNDE0ODI2OA==.html
Downloading [36mhttps://v.youku.com/v_show/id_XNDAzNDE0ODI2OA==.html[0m error:
[31m客户端无权播放,201[0m

**Comment by lim0513** [comment]
![image](https://user-images.githubusercontent.com/8295174/54102748-a462b100-4404-11e9-8b04-eea307caa9d4.png)
需要cookie携带登陆信息。

**Comment by wellos99** [comment]
之前带着ccode 和完整cookies可以下载，但是从3月9日起就无法下载了。

**Comment by kukugmy** [comment]
尝试了ccode 0590 可以下载VIP视频

**Comment by wellos99** [comment]
换了账号，用0590可以下载了

**Comment by scegg** [comment]
优酷的cookie有生存期。虽然cna是不会变，但是里面其他的值是有时间限制的。在过期后需要重新登录再获取一次cookie。
