### ISSUE TITLE
B站下载列表问题

### ISSUE THREAD

**Issue by Pmc8090** [iawia002/annie#405]
批量下载时，比如这个链接，https://www.bilibili.com/video/av37669351，下载的时候输入 
annie -p https://www.bilibili.com/video/av37669351   下载列表里某一个单集的时候，好像是自动选择查看清晰度的时候的第一个，但是某些单集返回的清晰的不是按照清晰度高低来排序的，比如这个
annie -i "https://www.bilibili.com/video/av37669351/?p=28" 

但是下面这个单集返回的就是按照清晰度高低排序的
annie -i "https://www.bilibili.com/video/av37669351/?p=31"

目前的解决方法是
annie -f 80 -p https://www.bilibili.com/video/av37669351

那如果某个单集没有返回80的这个清晰度，执行的时候估计会报错，所以希望返回清晰度的时候能高低排序，或者最高清晰度就是默认的，不需要特别指定

**Comment by iawia002** [comment]
现在就是按清晰度排序的，默认选择的是视频大小最大的那个（清晰度最高的），B 站有些视频 720P 和 480P 这些视频大小都一样，就可能出现你说的那种情况，你要是实在在意的话，遇到这种视频就手工选一下

```console
$ annie -i https://www.bilibili.com/video/av37669351/\?p\=28

 Site:      哔哩哔哩 bilibili.com
 Title:     黑马程序员 2018 千集 Python 教程 28-文件和目录命令-10-rm命令的扩展
 Type:      video
 Streams:   # All available quality
     [32]  -------------------
     Quality:         清晰 480P
     Size:            23.79 MiB (24943399 Bytes)
     # download with: annie -f 32 ...

     [64]  -------------------
     Quality:         高清 720P
     Size:            23.78 MiB (24938367 Bytes)
     # download with: annie -f 64 ...

     [80]  -------------------
     Quality:         高清 1080P
     Size:            23.78 MiB (24936248 Bytes)
     # download with: annie -f 80 ...

     [16]  -------------------
     Quality:         流畅 360P
     Size:            21.86 MiB (22922431 Bytes)
     # download with: annie -f 16 ...
```
