### ISSUE TITLE
annie exit codes are bad

### ISSUE THREAD

**Issue by alkorsan** [iawia002/annie#406]
Hi,
the exit codes of the last versions of annie return bad exit codes:
```
$ annie http://v.youku.com/v_show/id_XNDAtesttttttttttt==.html
Downloading http://v.youku.com/v_show/id_XNDAtesttttttttttt==.html error:
vid参数错误

$ echo $?
0
```
the exit code must be 1.
most of errors now return 0 , the old versions was fine!
thank you

**Comment by iawia002** [comment]
will fix it later
