### ISSUE TITLE
part download

### ISSUE THREAD

**Issue by TomokaMinato** [iawia002/annie#410]
I'd like to download some videoes on iqiyi for some segments, but not the whole, which argument should be used?
For example:
download file is [title][0],[title][1],[title][2],etc
but only [title][1] is necessary.
Thank you.

**Comment by TomokaMinato** [comment]
使用 -p 参数 下载合集 速度网速进度异常（有时出现无速度，ctrl+c，再重新下载会出现网速进度异常）
—
But there's only one video in an URL, not a playlist.
For example:
I've downloaded one like:
aaaa[0].f4v
aaaa[1].f4v
aaaa[2].f4v
....
All parts would be download, but only aaaa[1].f4v is what I want.
I think that '-p' is not fit.
Thank you.

**Comment by iawia002** [comment]
没这个功能的，`-p` 是用来下载列表的，不是分段，你可以尝试用视频编辑工具截取你想要的片段

**Comment by TomokaMinato** [comment]
ok.Thanks。
