### ISSUE TITLE
annie网速进度异常

### ISSUE THREAD

**Issue by Unlash** [iawia002/annie#411]
![Snipaste_2019-03-23_18-03-50](https://user-images.githubusercontent.com/32661990/54865858-fd3c2d00-4da6-11e9-999b-b018587a0984.png)

使用 -p 参数 下载合集 速度网速进度异常（有时出现无速度，ctrl+c，再重新下载会出现网速进度异常）

**Comment by iawia002** [comment]
这个是因为前面的已经下完了，你再下载是直接跳过的，所以速度显示这样，但是只是速度显示不准确，不影响其它的
