### ISSUE TITLE
How to easily download 2P in 哔哩哔哩

### ISSUE THREAD

**Issue by reov** [iawia002/annie#416]
E:\> annie https://www.bilibili.com/video/av6945785

 Site:      哔哩哔哩 bilibili.com
 Title:     【咬人猫】PPAP❤没错我也中毒了！2P=͟͟͞͞(๑•̀д•́๑) 合体版
 Type:      video
 Stream:
     [80]  -------------------
     Quality:         高清 1080P
     Size:            20.13 MiB (21106505 Bytes)
     # download with: annie -f 80 ...

 20.13 MiB / 20.13 MiB [=====================================================================] 100.00% 729.82 KiB/s 28s
PS E:\>
Can you only change the url manually? 
https://www.bilibili.com/video/av6945785/?p=2

**Comment by iawia002** [comment]
annie -p https://www.bilibili.com/video/av6945785
