### ISSUE TITLE
騰訊視頻不能完全下載

### ISSUE THREAD

**Issue by hlc67** [iawia002/annie#417]
C:\Users\flora>annie -x http://117.191.11.103:80 https://v.qq.com/x/cover/xv941e
sz2kogn60/k0021uy3gt1.html

 Site:       Title:      Type:      video
 Stream:
     [fhd]  -------------------
     Quality:              Size:            666.29 MiB (698655008 Bytes)
     # download with: annie -f fhd ...

 339.32 MiB / 666.29 MiB [=============>------------]  50.93% 5.43 MiB/s 00m59s

一開始下載速度非常快，之後速度就一直往下降，下載進度也一直停留在50.93%，請問騰訊視頻都會有這情況嗎?如何才能順利下載? 謝謝

**Comment by wansqh** [comment]
腾讯最新的视频好像需要提交8.1的ckey才能返回正确的fkey

**Comment by hlc67** [comment]
> 
> 
> 腾讯最新的视频好像需要提交8.1的ckey才能返回正确的fkey

請問要如何提交ckey? 這我不會用 
謝謝。

**Comment by iawia002** [comment]
没速度了中断再下载试试

**Comment by hlc67** [comment]
> 
> 
> 没速度了中断再下载试试

試過好幾次中斷再下載，都是到一半就會變成沒速度。

**Comment by ZELINK35** [comment]
好幾次中斷再下載，都是到一半就會變成沒速度。我下載時也是這樣，一直要中斷再下載，好麻煩啊

**Comment by iawia002** [comment]
对了，不用手动中断，忘了这个了，用 `-cs` 参数指定一个 http chunk 的大小（单位 MB），例如 `-cs 10`，下 10 MB 就会重新请求下载（相当于中断再恢复）

文档：https://github.com/iawia002/annie#download
