### ISSUE TITLE
twitter下载请求返回429错误

### ISSUE THREAD

**Issue by kickpanda1** [iawia002/annie#420]
twitter下载返回了429错误：
刚开始下载别的视频还是正常的，大概下载了7-8个视频后，再下载视频就出现了429的错误（网上查说这个错误是“请求太多”），之前的下载频率大概为4-5分钟一个

错误如下：
root@vultr:~# ./annie -d https://twitter.com/Train494593086/status/1119317860747239424/video/1

annie: version 0.8.5, A fast, simple and clean video downloader.

URL:         https://twitter.com/Train494593086/status/1119317860747239424/video/1
Method:      GET
Headers:     http.Header{
    "Accept":          {"text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"},
    "Accept-Charset":  {"UTF-8,*;q=0.5"},
    "Accept-Encoding": {"gzip,deflate,sdch"},
    "Accept-Language": {"en-US,en;q=0.8"},
    "User-Agent":      {"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.81 Safari/537.36"},
    "Referer":         {"https://twitter.com/Train494593086/status/1119317860747239424/video/1"},
}
Status Code: 200
Downloading https://twitter.com/Train494593086/status/1119317860747239424/video/1 error:
**https://api.twitter.com/1.1/videos/tweet/config/1119317860747239424.json request error: HTTP 429**

已经尝试过的解决方法：
1、等待15分钟重试，仍然是该错误。
2、换一台不同ip的vps重试，仍然是该错误。

希望各位大大能帮忙解决，或者提供个debug的方法，万分感谢！

**Comment by kickpanda1** [comment]
第二天又正常了，暂时关闭掉

**Comment by redstoneleo** [comment]
我也是这个问题
