### ISSUE TITLE
YouTube下载异常，有网络占用，但终端无进度，本地不会生成文件。

### ISSUE THREAD

**Issue by Unlash** [iawia002/annie#424]
![Snipaste_2019-04-22_22-08-48](https://user-images.githubusercontent.com/32661990/56504510-47056800-654b-11e9-918c-1e4bfeb3e957.png)

**Comment by Unlash** [comment]
长时间保持这个状态
有网速占用，但是没有文件生成，annie终端无进度显示，也没有硬盘占用。

**Comment by Unlash** [comment]
![图片](https://user-images.githubusercontent.com/32661990/56504632-bbd8a200-654b-11e9-9acb-1d1bdc65a0a1.png)
国内正常

**Comment by iawia002** [comment]
这个视频的地址发一下，我来试试

**Comment by Unlash** [comment]
> 
> 
> 这个视频的地址发一下，我来试试

https://www.youtube.com/watch?v=Bey4XXJAqS8
你的网站证书过期了
然后我强行访问 一直卡在 logo哪里。  Loading 然后一直播放logo

**Comment by iawia002** [comment]
> 你的网站证书过期了

感谢提醒

下载 youtube 感觉是你代理有问题

```
 Site:      YouTube youtube.com
 Title:     4K VIDEO ultrahd hdr sony 4K VIDEOS demo test nature relaxation movie for 4k oled tv
 Type:      video
 Stream:
     [313]  -------------------
     Quality:         2160p video/webm; codecs="vp9"
     Size:            2854.50 MiB (2993159978 Bytes)
     # download with: annie -f 313 ...

 2.62 MiB / 2.79 GiB [>--------------------------------------------------------------------------------------------------------------------------------------------------------------]   0.09% 290.57 KiB/s 2h47m27s
```

你用 annie -d -retry 1 ... 试试，然后把那个 log 贴上来

**Comment by Unlash** [comment]
> 
> 
> > 你的网站证书过期了
> 
> 感谢提醒
> 
> 下载 youtube 感觉是你代理有问题
> 
> ```
>  Site:      YouTube youtube.com
>  Title:     4K VIDEO ultrahd hdr sony 4K VIDEOS demo test nature relaxation movie for 4k oled tv
>  Type:      video
>  Stream:
>      [313]  -------------------
>      Quality:         2160p video/webm; codecs="vp9"
>      Size:            2854.50 MiB (2993159978 Bytes)
>      # download with: annie -f 313 ...
> 
>  2.62 MiB / 2.79 GiB [>--------------------------------------------------------------------------------------------------------------------------------------------------------------]   0.09% 290.57 KiB/s 2h47m27s
> ```
> 
> 你用 annie -d -retry 1 ... 试试，然后把那个 log 贴上来

如果是代理问题，web youtube 也会看不了 但是web youtube 正常
![Snipaste_2019-04-28_12-29-18](https://user-images.githubusercontent.com/32661990/56858714-78e65680-69b1-11e9-9b97-feb1885c3cf6.png)

**Comment by iawia002** [comment]
搞不太懂了，我试着下了这么多都没问题

```console
$ annie  https://www.youtube.com/watch\?v\=Bey4XXJAqS8

 Site:      YouTube youtube.com
 Title:     4K VIDEO ultrahd hdr sony 4K VIDEOS demo test nature relaxation movie for 4k oled tv
 Type:      video
 Stream:
     [313]  -------------------
     Quality:         2160p video/webm; codecs="vp9"
     Size:            2854.50 MiB (2993159978 Bytes)
     # download with: annie -f 313 ...

 918.85 MiB / 2.79 GiB [===================================================>-------------------------------------------------------------------------------------------------------------]  32.19% 1.04 MiB/s 30m55s
```

实在不行就试试其他工具吧

**Comment by Unlash** [comment]
> 
> 
> 搞不太懂了，我试着下了这么多都没问题
> 
> ```
> $ annie  https://www.youtube.com/watch\?v\=Bey4XXJAqS8
> 
>  Site:      YouTube youtube.com
>  Title:     4K VIDEO ultrahd hdr sony 4K VIDEOS demo test nature relaxation movie for 4k oled tv
>  Type:      video
>  Stream:
>      [313]  -------------------
>      Quality:         2160p video/webm; codecs="vp9"
>      Size:            2854.50 MiB (2993159978 Bytes)
>      # download with: annie -f 313 ...
> 
>  918.85 MiB / 2.79 GiB [===================================================>-------------------------------------------------------------------------------------------------------------]  32.19% 1.04 MiB/s 30m55s
> ```
> 
> 实在不行就试试其他工具吧

你是用scoop 安装的 还是 用二进制文件

**Comment by iawia002** [comment]
二进制文件（我直接在本地编译的），但是理论上你用其他方式安装的也没差

**Comment by Unlash** [comment]
> 
> 
> 二进制文件（我直接在本地编译的），但是理论上你用其他方式安装的也没差

玄学问题
