### ISSUE TITLE
annie -c .\cookie.txt -f 80 -p -start 64 "https:// ..."  cookie error 账号未登录

### ISSUE THREAD

**Issue by glenlance** [iawia002/annie#430]
Downloading [36mhttps://www.bilibili.com/video/av30099487/?p=1[0m error:
[31mcookie error: 账号未登录[0m
Downloading [36mhttps://www.bilibili.com/video/av30099487/?p=1[0m error:
[31mcookie error: 账号未登录[0m
Downloading [36mhttps://www.bilibili.com/video/av30099487/?p=1[0m error:
[31mcookie error: 账号未登录[0m
Downloading [36mhttps://www.bilibili.com/video/av30099487/?p=1[0m error:
[31mcookie error: 账号未登录[0m
Downloading [36mhttps://www.bilibili.com/video/av30099487/?p=1[0m error:
[31mcookie error: 账号未登录[0m
Downloading [36mhttps://www.bilibili.com/video/av30099487/?p=1[0m error:
[31mcookie error: 账号未登录[0m
Downloading [36mhttps://www.bilibili.com/video/av30099487/?p=1[0m error:
[31mcookie error: 账号未登录[0m
Downloading [36mhttps://www.bilibili.com/video/av30099487/?p=1[0m error:
[31mcookie error: 账号未登录[0m
Downloading [36mhttps://www.bilibili.com/video/av30099487/?p=1[0m error:
[31mcookie error: 账号未登录[0m
Downloading [36mhttps://www.bilibili.com/video/av30099487/?p=1[0m error:
[31mcookie error: 账号未登录[0m

**Comment by iawia002** [comment]
我试了没问题啊，感觉还是你 cookies 的问题，chrome cookies.txt 直接下载，然后用 -c 参数

**Comment by Oaroyal** [comment]
chrome cookies.txt 插件 作为扩展现在没发添加了，能否给个bilibili cookie参考？哪些是必须的？
