### ISSUE TITLE
Error while opening encoder for output stream #0:1 - maybe incorrect parameters such as bit_rate, rate, width or height

### ISSUE THREAD

**Issue by orangeff** [iawia002/annie#432]
Site:      YouTube youtube.com
 Title:     BJ서아 | Dalshabet(달샤벳) _ JOKER | BJ SEOA SEXY DANCE (official)
 Type:      video
 Stream:   
     [248]  -------------------
     Quality:         1080p video/webm; codecs="vp9"
     Size:            26.98 MiB (28287357 Bytes)
     # download with: annie -f 248 ...

 26.98 MiB / 26.98 MiB [======================================================================] 100.00% 252.78 KiB/s 1m49s
Merging video parts into BJ서아 - Dalshabet(달샤벳) _ JOKER - BJ SEOA SEXY DANCE (official).mp4
Downloading https://www.youtube.com/watch?v=phsst31eFOM error:
exit status 1
ffmpeg version 2.7.1 Copyright (c) 2000-2015 the FFmpeg developers
  built with gcc 4.9.3 (crosstool-NG 1.20.0) 20150311 (prerelease)
  configuration: --prefix=/usr --incdir='${prefix}/include/ffmpeg' --arch=i686 --target-os=linux --cross-prefix=/usr/local/x86_64-pc-linux-gnu/bin/x86_64-pc-linux-gnu- --enable-cross-compile --enable-optimizations --enable-pic --enable-gpl --enable-shared --disable-static --enable-version3 --enable-nonfree --enable-libfaac --enable-encoders --enable-pthreads --disable-bzlib --disable-protocol=rtp --disable-muxer=image2 --disable-muxer=image2pipe --disable-swscale-alpha --disable-ffserver --disable-ffplay --disable-devices --disable-bzlib --disable-altivec --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libmp3lame --disable-vaapi --disable-decoder=amrnb --disable-decoder=ac3 --disable-decoder=ac3_fixed --disable-encoder=zmbv --disable-encoder=dca --disable-encoder=ac3 --disable-encoder=ac3_fixed --disable-encoder=eac3 --disable-decoder=dca --disable-decoder=eac3 --disable-decoder=truehd --cc=/usr/local/x86_64-pc-linux-gnu/bin/x86_64-pc-linux-gnu-ccache-gcc --enable-yasm --enable-libx264 --enable-encoder=libx264
  libavutil      54. 27.100 / 54. 27.100
  libavcodec     56. 41.100 / 56. 41.100
  libavformat    56. 36.100 / 56. 36.100
  libavdevice    56.  4.100 / 56.  4.100
  libavfilter     5. 16.101 /  5. 16.101
  libswscale      3.  1.101 /  3.  1.101
  libswresample   1.  2.100 /  1.  2.100
  libpostproc    53.  3.100 / 53.  3.100
Input #0, matroska,webm, from 'BJ서아 - Dalshabet(달샤벳) _ JOKER - BJ SEOA SEXY DANCE (official)[0].webm':
  Metadata:
    encoder         : google/video-file
  Duration: 00:02:22.52, start: 0.000000, bitrate: 1458 kb/s
    Stream #0:0(eng): Video: vp9 (Profile 0), yuv420p(tv, bt709/unknown/unknown), 1920x1080, SAR 1:1 DAR 16:9, 23.98 fps, 23.98 tbr, 1k tbn, 1k tbc (default)
Input #1, mov,mp4,m4a,3gp,3g2,mj2, from 'BJ서아 - Dalshabet(달샤벳) _ JOKER - BJ SEOA SEXY DANCE (official)[1].m4a':
  Metadata:
    major_brand     : dash
    minor_version   : 0
    compatible_brands: iso6mp41
    creation_time   : 2018-11-07 03:21:31
  Duration: 00:02:22.57, start: 0.000000, bitrate: 129 kb/s
    Stream #1:0(eng): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 128 kb/s (default)
    Metadata:
      creation_time   : 2018-11-07 03:21:31
      handler_name    : ISO Media file produced by Google Inc. Created on: 11/06/2018.
Output #0, mp4, to 'BJ서아 - Dalshabet(달샤벳) _ JOKER - BJ SEOA SEXY DANCE (official).mp4':
  Metadata:
    encoder         : google/video-file
    Stream #0:0(eng): Video: vp9, yuv420p, 1920x1080 [SAR 1:1 DAR 16:9], q=2-31, 23.98 fps, 23.98 tbr, 1k tbn, 1k tbc (default)
    Stream #0:1(eng): Audio: aac, 0 channels, 128 kb/s (default)
    Metadata:
      creation_time   : 2018-11-07 03:21:31
      handler_name    : ISO Media file produced by Google Inc. Created on: 11/06/2018.
      encoder         : Lavc56.41.100 aac
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #1:0 -> #0:1 (aac (native) -> aac (native))
Error while opening encoder for output stream #0:1 - maybe incorrect parameters such as bit_rate, rate, width or height

**Comment by iawia002** [comment]
我试了没问题

```console
$ annie -s 127.0.0.1:1080 https://www.youtube.com/watch\?v\=phsst31eFOM

 Site:      YouTube youtube.com
 Title:     BJ서아 | Dalshabet(달샤벳) _ JOKER | BJ SEOA SEXY DANCE (official)
 Type:      video
 Stream:
     [248]  -------------------
     Quality:         1080p video/webm; codecs="vp9"
     Size:            26.98 MiB (28287357 Bytes)
     # download with: annie -f 248 ...

 26.98 MiB / 26.98 MiB [================================================================================================================================================================] 100.00% 392.50 KiB/s 1m10s
Merging video parts into BJ서아 - Dalshabet(달샤벳) _ JOKER - BJ SEOA SEXY DANCE (official).mp4
```

ffmpeg 更新到最新版再试试
