### ISSUE TITLE
希望把网页的爱奇艺VIP视频解析加入进来

### ISSUE THREAD

**Issue by xwlcn** [iawia002/annie#433]
[https://github.com/ZSAIm/iqiyi-parser/blob/master/%E7%88%B1%E5%A5%87%E8%89%BA%E8%A7%86%E9%A2%91H5%E8%A7%A3%E6%9E%90%E5%88%86%E6%9E%90%E8%BF%87%E7%A8%8B.pdf](url)
可以参考这个链接，这个是可以解析下载的。

**Comment by iawia002** [comment]
链接挂了，也暂不考虑加这个功能
