### ISSUE TITLE
希望能添加支持跳过错误下载的命令

### ISSUE THREAD

**Issue by kooton** [iawia002/annie#434]
你好，作者大大，由于批量下载视频时候，常常因为其中一个地址无法下载导致整个下载任务终止，能否添加一个功能，类似youtube-dl里的--ignore-errors命令，遇到错误时可以跳过，继续下载其他的视频地址，感谢！辛苦！

**Comment by iawia002** [comment]
现在就是这样的，一般的错误是直接跳过的，但是有些时候遇到 `panic: runtime error:` 这种错误就会中断程序。遇到这种错的时候再提 issue 吧
