### ISSUE TITLE
youtoube下载挂了吗？

### ISSUE THREAD

**Issue by maxiaohong-m** [iawia002/annie#435]
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/iawia002/annie/extractors/youtube.decipherTokens(0xc0003b4100, 0x9, 0x10, 0x0, 0x0, 0x0, 0x0)
        /Users/mac/iawia002/go/src/github.com/iawia002/annie/extractors/youtube/signature.go:126 +0x3e2
github.com/iawia002/annie/extractors/youtube.getSig(0x0, 0x0, 0xc0001e2030, 0x2d, 0

**Comment by AiDres** [comment]
估计是的。我也下载不了

**Comment by iawia002** [comment]
视频地址贴一下，我这边随便试了一个可以

**Comment by AiDres** [comment]
解决了，主要升级一下：youtube-dl -U

**Comment by maxiaohong-m** [comment]
现在可以下载了

**Comment by gohomo** [comment]
怎么解决的，能提供下方法吗？我现在也是下载不了，错误提示一致
