### ISSUE TITLE
下载playlist的时候是否可以默认总下载最清晰的版本？

### ISSUE THREAD

**Issue by skywoodlin** [iawia002/annie#436]
如题， 下载playlist的时候是否可以指定总是下载最清晰的版本？

**Comment by iawia002** [comment]
现在就是这样的，下载都是默认最高清晰度的（文件最大），遇到什么问题了吗

**Comment by skywoodlin** [comment]
> 现在就是这样的，下载都是默认最高清晰度的（文件最大），遇到什么问题了吗

没问题， 是我自己搞错了
