### ISSUE TITLE
更新annie 时提示错误

### ISSUE THREAD

**Issue by weidongzhou1994** [iawia002/annie#441]
怎么进行更新呢？使用 go get github.com/iawia002/annie命令更新时总是失败，提示too many errors
![image](https://user-images.githubusercontent.com/40510496/58140311-50304480-7c71-11e9-8a5b-2ae05a1e84d9.png)

**Comment by iawia002** [comment]
这看起来像是你 go 环境的问题，不行就直接在 https://github.com/iawia002/annie/releases 下载二进制文件直接用
