### ISSUE TITLE
下载视频时出现下面的提示 爱奇艺、优酷都出现

### ISSUE THREAD

**Issue by wansqh** [iawia002/annie#443]
019/05/28 17:23:17 Unsolicited response received on idle HTTP channel starting with "\x00\x00\x00 ftypisom\x00\x00\x02\x00isomiso2avc1mp41\x00\x00\x00\byqoo\x00\x01\xaa\xf7moov\x00\x00\x00lmvhd\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x03\xe8\x00\x02\x0f\xb6\x00\x01\x00\x00\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00@\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x03\x00\x00\xc0\xc0trak\x00\x00\x00\\tkhd\x00\x00\x00\x03\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01\x00\x00\x00\x00\x00\x02\x0f\xa8\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00@\x00\x00\x00\a\x80\x00\x00\x048\x00\x00\x00\x00\x00$edts\x00\x00\x00\x1celst\x00\x00\x00\x00\x00\x00\x00\x01\x00\x02\x0f\xa8\x00\x00\x04\x00\x00\x01\x00\x00\x00\x00\xc08mdia\x00\x00\x00 mdhd\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x002\x00\x00\x1ab\x00U\xc4\x00\x00\x00\x00\x00-hdlr\x00\x00\x00\x00\x00\x00\x00\x00vide\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00VideoHandler\x00\x00\x00\xbf\xe3minf\x00\x00\x00\x14vmhd\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00$dinf\x00\x00\x00\x1cdref\x00\x00\x00\x00\x00\x00\x00\x01\x00\x00\x00\furl \x00\x00\x00\x01\x00\x00\xbf\xa3stbl\x00\x00\x00\xabstsd\x00\x00\x00\x00\x00\x00\x00\x01\x00\x00\x00\x9bavc1\x00\x00\x00\x00\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\a\x80\x048\x00H\x00\x00\x00H\x00\x00\x00\x00\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x18\xff\xff\x00\x00\x005avcC\x01d\x00(\xff\xe1\x00\x1egd\x00(\xac\xd9@x\x02'\xe5\xc0Z\x80\x80\x80\xa0\x00\x00\x03\x00 \x00\x00\x06A\xe3\x062\xc0\x01\x00\x04h\xeb\xe7\xcb\x00\x00\x00\x10pasp\x00\x00\x00\x01\x00\x00\x00\x01\x00\x00\x00\x18stts\x00\x00\x00\x00\x00\x00\x00\x01\x00\x00\r1\x00\x00\x02\x00\x00\x00\x00xstss\x00\x00\x00\x00\x00\x00\x00\x1a\x00\x00\x00\x01\x00\x00\x00T\x00\x00\x00\xd6\x00\x00\x01N\x00\x00\x01\xad\x00\x00\x02.\x00\x00\x02\xc4\x00\x00\x03Z\x00\x00\x03\xec\x00\x00\x04\x82\x00\x00\x05\x00\x00\x00\x05V\x00\x00\x05\xec\x00\x00\x06\x82\x00\x00\x06\xd2\x00\x00\ah\x00\x00\a\xfe\x00\x00\bS\x00\x00\b\xa9\x00\x00\t?\x00\x00\t\xd5\x00\x00\nc\x00\x00\n\xf9\x00\x00\v\x8f\x00\x00\f\x1b\x00\x00\f\x9c\x00\x00T\x98ctts\x00\x00\x00\x00\x00\x00\n\x91\x00\x00\x00\x01\x00\x00\x04\x00\x00\x00\x00\x01\x00\x00\x06\x00\x00\x00\x00\x01\x00\x00\x02\x00\x00\x00\x00\x01\x00\x00\x06\x00\x00\x00\x00\x01\x00\x00\x02\x00\x00\x00\x00\x01\x00\x00\x06\x00\x00\x00\x00\x01\x00\x00\x02\x00\x00\x00\x00\x01\x00\x00\x06\x00\x00\x00\x00\x01\x00\x00\x02\x00\x00\x00\x00\x01\x00\x00\x04\x00\x00\x00\x00\x01\x00\x00\x06\x00\x00\x00\x00\x01\x00\x00\x02\x00\x00\x00\x00\x01\x00\x00\x06\x00\x00\x00\x00\x01\x00\x00\x02\x00\x00\x00\x00\x01\x00\x00\x06\x00\x00\x00\x00\x01\x00\x00\x0

**Comment by iawia002** [comment]
下载的 URL 贴一下
