### ISSUE TITLE
下载bilibili视频都会报错

### ISSUE THREAD

**Issue by stonemakers** [iawia002/annie#446]
```
annie https://www.bilibili.com/video/av53847589\?spm_id_from\=333.334.b_686f6d655f706f70756c6172697a65.5
```

macos

报错信息：
goroutine 1 [running]:
github.com/iawia002/annie/downloader.Download(0x134c488, 0x19, 0xc00015c360, 0x8d, 0x1341c3a, 0x5, 0xc0002788d0, 0x0, 0x0, 0x0, ...)
	/private/tmp/annie-20181124-53134-rlcpgc/annie-0.8.5/src/github.com/iawia002/annie/downloader/downloader.go:189 +0x1578
main.download(0x7ffeefbffa96, 0x60)
	/private/tmp/annie-20181124-53134-rlcpgc/annie-0.8.5/src/github.com/iawia002/annie/main.go:157 +0x448
main.main()
	/private/tmp/annie-20181124-53134-rlcpgc/annie-0.8.5/src/github.com/iawia002/annie/main.go:211 +0x11a

**Comment by weiyongsheng** [comment]
建议可以升级到最新版后再试试，我用的0.9.3表示没有问题

```
➜  annie -v                                             

annie: version 0.9.3, A fast, simple and clean video downloader.

➜  annie https://www.bilibili.com/video/av53847589\?spm_id_from\=333.334.b_686f6d655f706f70756c6172697a655.5
 

 Site:      哔哩哔哩 bilibili.com
 Title:     心要化了，养猫时最暖的时刻，张开爪爪软软的撒娇
 Type:      video
 Stream:   
     [80]  -------------------
     Quality:         高清 1080P
     Size:            33.95 MiB (35598335 Bytes)
     # download with: annie -f 80 ...

 2.79 MiB / 33.95 MiB [======>--------------------------------------------------------------------------]   8.21% 1.79 MiB/s 00m17s^C

```

**Comment by stonemakers** [comment]
> 建议可以升级到最新版后再试试，我用的0.9.3表示没有问题
> 
> ```
> ➜  annie -v                                             
> 
> annie: version 0.9.3, A fast, simple and clean video downloader.
> 
> ➜  annie https://www.bilibili.com/video/av53847589\?spm_id_from\=333.334.b_686f6d655f706f70756c6172697a655.5
>  
> 
>  Site:      哔哩哔哩 bilibili.com
>  Title:     心要化了，养猫时最暖的时刻，张开爪爪软软的撒娇
>  Type:      video
>  Stream:   
>      [80]  -------------------
>      Quality:         高清 1080P
>      Size:            33.95 MiB (35598335 Bytes)
>      # download with: annie -f 80 ...
> 
>  2.79 MiB / 33.95 MiB [======>--------------------------------------------------------------------------]   8.21% 1.79 MiB/s 00m17s^C
> ```

homebrew 默认安装低版本的。。更新了就好了。。。谢谢
