### ISSUE TITLE
刚开始下载腾讯视频速度快后面基本不动

### ISSUE THREAD

**Issue by FFFcat** [iawia002/annie#449]
用服务器下载，一开始能有10M/S，十几秒过后就是0了，关掉程序再开的话继续10M/S，如此反复。。

**Comment by iawia002** [comment]
试试 `-cs 10` 参数，相当于下载 10M 后自动断开重新下

https://github.com/iawia002/annie#download

**Comment by FFFcat** [comment]
好

**Comment by FFFcat** [comment]
试了下，还是会卡住的，并不会一直下去，还是需要手动停止。

**Comment by FFFcat** [comment]
看来是我的问题，我换另一台服务器下就正常了。
