### ISSUE TITLE
error is So dry

### ISSUE THREAD

**Issue by chinanf-boy** [iawia002/annie#45]
https://github.com/iawia002/annie/blob/master/main.go#L34

``` go
	if len(args) < 1 {
		fmt.Println("error") // so dry
		return
	}
```

may be you could Add same like `annie -h` etc, not just `error`

**Comment by iawia002** [comment]
Nice catch! This is the code that was written at the beginning of this project and I forgot to update it when I finished the basic functions

**Comment by arpit1997** [comment]
@iawia002 Can I work on this issue?

**Comment by iawia002** [comment]
@arpit1997 Sure! About the error message, you got any suggestion?

**Comment by arpit1997** [comment]
@iawia002, In general, we show error (too few/many args) and the help that how to use and supported args. We can do same for this also

**Comment by iawia002** [comment]
@arpit1997 how about
```
too few args to call Annie

Use "annie -h" for more information
```

**Comment by arpit1997** [comment]
@iawia002, Can we just show them the help here itself? Because user have to type `annie -h` to see available commands. If he/she did enter too few/many args then we should show them the help directly.

**Comment by iawia002** [comment]
@arpit1997 cool!

```
too few args to call Annie

Usage of annie:
...
```

**Comment by arpit1997** [comment]
Will be doing the above. Will submit a PR by tonight. @iawia002

**Comment by iawia002** [comment]
@arpit1997 cool, thanks!

**Comment by chinanf-boy** [comment]
#49 ok!
seem like that error message is 可以的
