### ISSUE TITLE
panic: runtime error: index out of range

### ISSUE THREAD

**Issue by abshammeri** [iawia002/annie#452]
Steps:

use http proxy such as cntlm on port 3328 

```
brew install annie 
annie -x http://localhost:3328 -i https://www.youtube.com/watch?v=ZtgzKBrU1GY

```

Result:
```
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/iawia002/annie/extractors/youtube.decipherTokens(0xc00015e100, 0x5, 0x8, 0x0, 0x0, 0x0, 0x0)
	/private/tmp/annie-20190302-78152-y6yc8f/annie-0.9.3/src/github.com/iawia002/annie/extractors/youtube/signature.go:126 +0x3f7
github.com/iawia002/annie/extractors/youtube.getSig(0x0, 0x0, 0xc0001e80f0, 0x2d, 0x1659640, 0xc0004160de, 0x13805b1, 0x3)
	/private/tmp/annie-20190302-78152-y6yc8f/annie-0.9.3/src/github.com/iawia002/annie/extractors/youtube/youtube.go:50 +0x11e
github.com/iawia002/annie/extractors/youtube.genSignedURL(0xc000422400, 0x3a0, 0xc0001d73a8, 0xc0001e80f0, 0x2d, 0xc0001fa450, 0x3, 0x3, 0x1d)
	/private/tmp/annie-20190302-78152-y6yc8f/annie-0.9.3/src/github.com/iawia002/annie/extractors/youtube/youtube.go:66 +0x181
github.com/iawia002/annie/extractors/youtube.extractVideoURLS(0xc0001e8120, 0x27, 0xc000416000, 0x947c, 0xc000406000, 0xbfc, 0xc0001e80f0, 0x2d, 0x7ffeefbff7ca, 0x2b, ...)
	/private/tmp/annie-20190302-78152-y6yc8f/annie-0.9.3/src/github.com/iawia002/annie/extractors/youtube/youtube.go:192 +0x6be
github.com/iawia002/annie/extractors/youtube.youtubeDownload(0x7ffeefbff7ca, 0x2b, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/private/tmp/annie-20190302-78152-y6yc8f/annie-0.9.3/src/github.com/iawia002/annie/extractors/youtube/youtube.go:143 +0x33a
github.com/iawia002/annie/extractors/youtube.Extract(0x7ffeefbff7ca, 0x2b, 0x13835be, 0x7, 0x0, 0xc000120660, 0x3)
	/private/tmp/annie-20190302-78152-y6yc8f/annie-0.9.3/src/github.com/iawia002/annie/extractors/youtube/youtube.go:83 +0x69d
main.download(0x7ffeefbff7ca, 0x2b)
	/private/tmp/annie-20190302-78152-y6yc8f/annie-0.9.3/src/github.com/iawia002/annie/main.go:125 +0x699
main.main()
	/private/tmp/annie-20190302-78152-y6yc8f/annie-0.9.3/src/github.com/iawia002/annie/main.go:221 +0x156
```

**Comment by s1oz** [comment]
panic: runtime error: index out of range                                                                                                                                                                    
                                                                                                                                                                                                            
goroutine 9 [running]:                                                                                                                                                                                      
github.com/iawia002/annie/extractors/youtube.decipherTokens(0xc0000797c0, 0x3, 0                                                                                                                            
x4, 0x0, 0x0, 0x0, 0x0)                                                                                                                                                                                     
        /Users/mac/iawia002/go/src/github.com/iawia002/annie/extractors/youtube/                                                                                                                            
signature.go:126 +0x3db                                                                                                                                                                                     
github.com/iawia002/annie/extractors/youtube.getSig(0x0, 0x0, 0xc0001e4390, 0x2d                                                                                                                            
, 0x9c5620, 0x4114b1, 0xc0003ecb3a, 0x73ffaf)                                                                                                                                                               
        /Users/mac/iawia002/go/src/github.com/iawia002/annie/extractors/youtube/                                                                                                                            
youtube.go:50 +0x13e                                                                                                                                                                                        
github.com/iawia002/annie/extractors/youtube.genSignedURL(0xc00019a380, 0x35b, 0                                                                                                                            
xc000252420, 0xc0001e4390, 0x2d, 0xc0002524e0, 0x3, 0x3, 0x440471)                                                                                                                                          
        /Users/mac/iawia002/go/src/github.com/iawia002/annie/extractors/youtube/                                                                                                                            
youtube.go:66 +0x181                                                                                                                                                                                        
github.com/iawia002/annie/extractors/youtube.extractVideoURLS(0xc00028e400, 0x17                                                                                                                            
, 0xc0003eca80, 0x64c2, 0xc000194c00, 0xba0, 0xc0001e4390, 0x2d, 0xc000058180, 0                                                                                                                            
x53, ...)                                                                                                                                                                                                   
        /Users/mac/iawia002/go/src/github.com/iawia002/annie/extractors/youtube/                                                                                                                            
youtube.go:192 +0x54a                                                                                                                                                                                       
github.com/iawia002/annie/extractors/youtube.youtubeDownload(0xc000058180, 0x53,                                                                                                                            
 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)                                                                                                                                                               
        /Users/mac/iawia002/go/src/github.com/iawia002/annie/extractors/youtube/                                                                                                                            
youtube.go:143 +0x2fb                                                                                                                                                                                       
github.com/iawia002/annie/extractors/youtube.Extract.func1(0xc00005a2f0, 0x0, 0x                                                                                                                            
c000058180, 0x53, 0xc0000f4c80, 0x1c, 0x1c)                                                                                                                                                                 
        /Users/mac/iawia002/go/src/github.com/iawia002/annie/extractors/youtube/                                                                                                                            
youtube.go:109 +0x7a                                                                                                                                                                                        
created by github.com/iawia002/annie/extractors/youtube.Extract                                                                                                                                             
        /Users/mac/iawia002/go/src/github.com/iawia002/annie/extractors/youtube/                                                                                                                            
youtube.go:107 +0x63e

**Comment by vishen** [comment]
I am also getting this without proxies or anything.

```
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/iawia002/annie/extractors/youtube.decipherTokens(0xc00028a180, 0x5, 0x8, 0x0, 0x0, 0x0, 0x0)
        /home/pentecostjonathan/go/src/github.com/iawia002/annie/extractors/youtube/signature.go:126 +0x3f7
github.com/iawia002/annie/extractors/youtube.getSig(0x0, 0x0, 0xc00028c030, 0x2d, 0xa5bc80, 0xc000446041, 0x78540d, 0x3)
        /home/pentecostjonathan/go/src/github.com/iawia002/annie/extractors/youtube/youtube.go:50 +0x11e
github.com/iawia002/annie/extractors/youtube.genSignedURL(0xc00044a400, 0x38b, 0xc000195398, 0xc00028c030, 0x2d, 0xc000278480, 0x3, 0x3, 0xd)
        /home/pentecostjonathan/go/src/github.com/iawia002/annie/extractors/youtube/youtube.go:66 +0x181
github.com/iawia002/annie/extractors/youtube.extractVideoURLS(0xc0002820a0, 0x4c, 0xc000446000, 0x3fe6, 0xc000430000, 0xc6a, 0xc00028c030, 0x2d, 0x7ffc8d1a1d4a, 0x2b, ...)
        /home/pentecostjonathan/go/src/github.com/iawia002/annie/extractors/youtube/youtube.go:192 +0x6c1
github.com/iawia002/annie/extractors/youtube.youtubeDownload(0x7ffc8d1a1d4a, 0x2b, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/pentecostjonathan/go/src/github.com/iawia002/annie/extractors/youtube/youtube.go:143 +0x33a
github.com/iawia002/annie/extractors/youtube.Extract(0x7ffc8d1a1d4a, 0x2b, 0x787ffe, 0x7, 0x1, 0xc0000873b0, 0x3)
        /home/pentecostjonathan/go/src/github.com/iawia002/annie/extractors/youtube/youtube.go:83 +0x69d
main.download(0x7ffc8d1a1d4a, 0x2b, 0x7a2c08)
        /home/pentecostjonathan/go/src/github.com/iawia002/annie/main.go:127 +0x6c0
main.main()
        /home/pentecostjonathan/go/src/github.com/iawia002/annie/main.go:233 +0x165
```

**Comment by zhz1237ok** [comment]
annie -s 127.0.0.1:1080 youtube视频地址
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/iawia002/annie/extractors/youtube.decipherTokens(0xc0001e8180, 0x5, 0x8, 0x0, 0x0, 0x0, 0x0)
        /Users/mac/iawia002/go/src/github.com/iawia002/annie/extractors/youtube/signature.go:126 +0x3e2
github.com/iawia002/annie/extractors/youtube.getSig(0x0, 0x0, 0xc0001ea030, 0x2d, 0x9b5d40, 0x411a48, 0xc0003840c5, 0x73c2c6)
        /Users/mac/iawia002/go/src/github.com/iawia002/annie/extractors/youtube/youtube.go:50 +0x145
github.com/iawia002/annie/extractors/youtube.genSignedURL(0xc000390380, 0x340, 0xc0001cc360, 0xc0001ea030, 0x2d, 0xc0001cc420, 0x3, 0x3, 0x43f828)
        /Users/mac/iawia002/go/src/github.com/iawia002/annie/extractors/youtube/youtube.go:66 +0x188
github.com/iawia002/annie/extractors/youtube.extractVideoURLS(0xc0001da240, 0x18, 0xc000384000, 0x5820, 0xc00038ac00, 0xb6e, 0xc0001ea030, 0x2d, 0xc000086030, 0x2b, ...)
        /Users/mac/iawia002/go/src/github.com/iawia002/annie/extractors/youtube/youtube.go:192 +0x551
github.com/iawia002/annie/extractors/youtube.youtubeDownload(0xc000086030, 0x2b, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /Users/mac/iawia002/go/src/github.com/iawia002/annie/extractors/youtube/youtube.go:143 +0x302
github.com/iawia002/annie/extractors/youtube.Extract(0xc000086030, 0x2b, 0x73f269, 0x7, 0x0, 0x0, 0x0)
        /Users/mac/iawia002/go/src/github.com/iawia002/annie/extractors/youtube/youtube.go:83 +0x6ee
main.download(0xc000086030, 0x2b)
        /Users/mac/iawia002/go/src/github.com/iawia002/annie/main.go:125 +0x6e1
main.main()
        /Users/mac/iawia002/go/src/github.com/iawia002/annie/main.go:221 +0x121

**Comment by schollz** [comment]
The tests are also failing.

```
$ go test -v -cover
=== RUN   TestYoutube
=== RUN   TestYoutube/normal_test
panic: runtime error: index out of range [recovered]
        panic: runtime error: index out of range

goroutine 7 [running]:
testing.tRunner.func1(0x1812320)
        /usr/local/go/src/testing/testing.go:830 +0x364
panic(0x2ac668, 0x51b280)
        /usr/local/go/src/runtime/panic.go:522 +0x1a0
github.com/iawia002/annie/test.Check(0x1812320, 0x2ef2ca, 0x2b, 0x2e7852, 0x17, 0x2eca37, 0x24, 0x0, 0x0, 0x2e60a5, ...)
        /home/zns/go/src/github.com/iawia002/annie/test/utils.go:33 +0x3f8
github.com/iawia002/annie/extractors/youtube.TestYoutube.func1(0x1812320)
        /home/zns/go/src/github.com/iawia002/annie/extractors/youtube/youtube_test.go:102 +0x1ac
testing.tRunner(0x1812320, 0x18107d8)
        /usr/local/go/src/testing/testing.go:865 +0xa4
created by testing.(*T).Run
        /usr/local/go/src/testing/testing.go:916 +0x2b8
exit status 2
FAIL    github.com/iawia002/annie/extractors/youtube    18.635s
```

The algorithm may have changed as there are also errors reported in https://github.com/rylio/ytdl/issues/69. 

There may be a possible fix here: https://github.com/ytdl-org/youtube-dl/pull/18927

**Comment by arieller** [comment]
same here, 
annie -f 134 https://www.youtube.com/watch?v=ucZemSXcjtM
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/iawia002/annie/extractors/youtube.decipherTokens(0xc00010a100, 0x5, 0x8, 0x0, 0x0, 0x0, 0x0)
        /Users/mac/iawia002/go/src/github.com/iawia002/annie/extractors/youtube/signature.go:126 +0x3e2
github.com/iawia002/annie/extractors/youtube.getSig(0x0, 0x0, 0xc00000ccf0, 0x2d, 0x9b5d40, 0x411a48, 0xc00036e03d, 0x73c2c6)
        /Users/mac/iawia002/go/src/github.com/iawia002/annie/extractors/youtube/youtube.go:50 +0x145
github.com/iawia002/annie/extractors/youtube.genSignedURL(0xc00007aa80, 0x36a, 0xc0001a0480, 0xc00000ccf0, 0x2d, 0xc0001a0540, 0x3, 0x3, 0x43f828)
        /Users/mac/iawia002/go/src/github.com/iawia002/annie/extractors/youtube/youtube.go:66 +0x188
github.com/iawia002/annie/extractors/youtube.extractVideoURLS(0xc000014380, 0x64, 0xc00036e000, 0x4861, 0xc0000a9200, 0x436, 0xc00000ccf0, 0x2d, 0xc00000c2d0, 0x2b, ...)
        /Users/mac/iawia002/go/src/github.com/iawia002/annie/extractors/youtube/youtube.go:192 +0x551
github.com/iawia002/annie/extractors/youtube.youtubeDownload(0xc00000c2d0, 0x2b, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /Users/mac/iawia002/go/src/github.com/iawia002/annie/extractors/youtube/youtube.go:143 +0x302
github.com/iawia002/annie/extractors/youtube.Extract(0xc00000c2d0, 0x2b, 0x73f269, 0x7, 0x0, 0x0, 0x0)
        /Users/mac/iawia002/go/src/github.com/iawia002/annie/extractors/youtube/youtube.go:83 +0x6ee
main.download(0xc00000c2d0, 0x2b)
        /Users/mac/iawia002/go/src/github.com/iawia002/annie/main.go:125 +0x6e1
main.main()
        /Users/mac/iawia002/go/src/github.com/iawia002/annie/main.go:221 +0x121

**Comment by iawia002** [comment]
0.9.4
