### ISSUE TITLE
-ccode选项无法选择吗？为什么我使用不了

### ISSUE THREAD

**Issue by weidongzhou1994** [iawia002/annie#453]
![image](https://user-images.githubusercontent.com/40510496/59323172-21573c80-8d0c-11e9-8f6b-66a40f20d595.png)

**Comment by xhlove** [comment]
好像是你版本的问题... 你的提示里面没有出现ccode

**Comment by weidongzhou1994** [comment]
https://github.com/iawia002/annie/issues/453#issuecomment-501992421

**Comment by weidongzhou1994** [comment]
![image](https://user-images.githubusercontent.com/40510496/59489529-0411a200-8eb5-11e9-9a6e-be82474e3abb.png)

**Comment by iawia002** [comment]
更新到最新版就有了
