### ISSUE TITLE
国内下载不了youtube(can‘t download video from youtube)

### ISSUE THREAD

**Issue by ixiangwang** [iawia002/annie#462]
![image](https://user-images.githubusercontent.com/52265150/60226673-d66a2700-98be-11e9-8f6e-7573bba641b8.png)

用的翻墙软件，但是下载不了，提示：no connection could be made because the target machine actively refused it.
所以，这个软件是被youtube封锁了吗？(so,does it mean that Annie.exe is banned by youtube? )

**Comment by SeaHOH** [comment]
https://github.com/iawia002/annie#proxy

**Comment by jiqing112** [comment]
看返回的错误是无连接，肯定是没有走代理。
