### ISSUE TITLE
iqiyi下载失败，访问拒绝。

### ISSUE THREAD

**Issue by hoogeek** [iawia002/annie#471]
PS C:\> annie http://www.iqiyi.com/w_19s7iwi6d9.html

 Site:      爱奇艺 iqiyi.com
 Title:     《拾年》——纪念中国建国70周年-片花-高清完整版视频在线观看–爱奇艺
 Type:      video
 Stream:
     [4]  -------------------
     Quality:         1280x720
     Size:            106.37 MiB (111540347 Bytes)
     # download with: annie -f 4 ...

 0 B / 106.37 MiB [-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------]   0.00%Downloading [36mhttp://www.iqiyi.com/w_19s7iwi6d9.html[0m error:
[31mopen 《拾年》——纪念中国建国70周年-片花-高清完整版视频在线观看–爱奇艺[0].f4v.download: Access is denied.[0m

**Comment by hoogeek** [comment]
使用 ytdl 成功了。

**Comment by iawia002** [comment]
并没有复现

```console
$ annie http://www.iqiyi.com/w_19s7iwi6d9.html

 Site:      爱奇艺 iqiyi.com
 Title:     《拾年》——纪念中国建国70周年-片花-高清完整版视频在线观看–爱奇艺
 Type:      video
 Stream:
     [4]  -------------------
     Quality:         1280x720
     Size:            106.37 MiB (111540347 Bytes)
     # download with: annie -f 4 ...

 17.92 MiB / 106.37 MiB [==========================>-------------------------------------------------------------------------------------------------------------------------------------]  16.85% 9.77 MiB/s 00m08s
```
