### ISSUE TITLE
能否通过传递cooki来下载iqiyi的收费视频

### ISSUE THREAD

**Issue by sbw983** [iawia002/annie#472]
RT
我有iqiyi的会员账号，能否通过传递浏览器的cooki来下载收费视频？下载参数如何设置，谢谢

**Comment by sbw983** [comment]
我用EditThisCookie这个插件导出的cooki文件，但是用annie -c这个参数导入了cooki还是失败

**Comment by iawia002** [comment]
暂不支持，#50
