### ISSUE TITLE
请问如何下载网易云音乐的曲子

### ISSUE THREAD

**Issue by hairuo** [iawia002/annie#482]
比如想下载https://music.163.com/#/song?id=405079650

```annie -i https://music.163.com/#/song?id=405079650```

提示:
Downloading [36mhttps://music.163.com/#/song?id=405079650[0m error:
[31minvalid url for netease music[0m

**Comment by hairuo** [comment]
好的，谢谢回复。

**Comment by haroldyong** [comment]
请问为何不将Lulu 与 annie 功能合在一起了？
