### ISSUE TITLE
shell使用zsh的时候无法使用，必须要用bash

### ISSUE THREAD

**Issue by ydq** [iawia002/annie#483]
如题：将MacOS的终端从bash切换至zsh之后
使用-v查看版本号可以正常显示，但是使用annie下载的时候，总是会提示
> zsh: no matches found: xxxx

![image222](https://user-images.githubusercontent.com/8097340/62831143-14dc5b00-bc4d-11e9-996c-ce0a6a7b9ca5.png)

切换成bash却可以正常下载，看看能否兼容一下 zsh，因为据说macOS Catalina 会使用zsh取代bash，成为新版操作系统中的默认 shell

**Comment by iawia002** [comment]
URL 有特殊字符，用引号引起来
