### ISSUE TITLE
Pornhub视频无法下载

### ISSUE THREAD

**Issue by netsonicyxf** [iawia002/annie#487]
https://www.pornhub.com/view_video.php?viewkey=ph5ab5b8cd2ede0

> Downloading [36mhttps://www.pornhub.com/view_video.php?viewkey=ph5ab5b8cd2ede0[0m error:
[31mrequest error: Get https://www.pornhub.com/view_video.php?viewkey=ph5ab5b8cd2ede0: read tcp 10.19.18.41:57615->66.254.114.41:443: wsarecv: An existing connection was forcibly closed by the remote host.[0m``

**Comment by Phencxl** [comment]
> https://www.pornhub.com/view_video.php?viewkey=ph5ab5b8cd2ede0
> 
> > 正在下载 [36mhttps：//www.pornhub.com/view_video.php？viewkey =ph5ab5b8cd2ede0 [0m错误：
> > [31mrequest error：Get https://www.pornhub.com/view_video.php?viewkey=ph5ab5b8cd2ede0：read tcp 10.19.18.41:57615->66.254.114.41:443：wsarecv：远程主机强行关闭现有连接。[0m``

老铁，确认过眼神，你是个狠人~。什么issue都敢提~！
哈哈哈哈哈哈哈哈哈~!

**Comment by wzyonggege** [comment]
设置下http_proxy

**Comment by 1198632064** [comment]
> 设置下http_proxy

如何设置，求教啊，老铁

**Comment by C-racker** [comment]
是个狼人

**Comment by linshuizanghuaren** [comment]
> https://www.pornhub.com/view_video.php?viewkey=ph5ab5b8cd2ede0
> 
> > Downloading �[36mhttps://www.pornhub.com/view_video.php?viewkey=ph5ab5b8cd2ede0�[0m error:
> > �[31mrequest error: Get https://www.pornhub.com/view_video.php?viewkey=ph5ab5b8cd2ede0: read tcp 10.19.18.41:57615->66.254.114.41:443: wsarecv: An existing connection was forcibly closed by the remote host.�[0m``

pronhub能下载？我试了下也不好使呀，姿势不对？

**Comment by iawia002** [comment]
#689 fixes this
