### ISSUE TITLE
比you-get 好多了 star表扬 感谢大佬

### ISSUE THREAD

**Issue by willshion** [iawia002/annie#496]

**Comment by Vinhuan** [comment]
请教大佬，已经挂了梯子，添加了代码，还是下载不了Youtube视频，显示
a connection attempt failed bacause the connect did not properly respond agter a preiod of time

**Comment by willshion** [comment]
poxy设置吧

**Comment by Vinhuan** [comment]
> poxy设置吧

已经设置了127.000····这样的端口，还是不行，我用的是V2ray，是不是端口在变化所以不能用呢

**Comment by sbw983** [comment]
> > poxy设置吧
> 
> 已经设置了127.000····这样的端口，还是不行，我用的是V2ray，是不是端口在变化所以不能用呢

http和socks代理的参数是不一样的，确认一下类型看
