### ISSUE TITLE
go get build failed

### ISSUE THREAD

**Issue by yrong** [iawia002/annie#507]
➜  ~ go get github.com/iawia002/annie
go: finding github.com/iawia002/annie latest
go: finding github.com/MercuryEngineering/CookieMonster latest
go: finding golang.org/x/net/proxy latest
go: finding golang.org/x/net latest
go: downloading gopkg.in/mattn/go-colorable.v0 v0.1.2
go: downloading gopkg.in/mattn/go-isatty.v0 v0.0.9
build github.com/iawia002/annie: cannot load gopkg.in/mattn/go-colorable.v0: cannot find module providing package gopkg.in/mattn/go-colorable.v0

**Comment by wakhh** [comment]
+1

**Comment by yrong** [comment]
if build with go module, change the 

`
go get github.com/iawia002/annie
`
with 

`
go mod init github.com/iawia002/annie
go build -o annie main.go
`

**Comment by wakhh** [comment]
> this is a legacy godep project and if want to build with go module, change the command
> 
> `go get github.com/iawia002/annie`
> 
> with
> 
> `go mod init github.com/iawia002/annie && go build -o annie main.go`

yes, and user can fork it ,do `go mod` and commit it in self repository.Hope @iawia002 change the repository with `go mod`.
