### ISSUE TITLE
芒果TV的视频下载不全

### ISSUE THREAD

**Issue by XinyiZhu1007** [iawia002/annie#512]
从芒果tv要下载一个两个小时的超清视频，用`annie -i`查看可选择分辨率时发现解析的视频只有68Mb，下载的分段视频有30段，每个时长10秒，合并之后只有原视频的开头5分钟的部分

**Comment by wuqian9871** [comment]
我也一样  youku 的视频  也是只能下载6M  就停止了
别的网站没有试

**Comment by wansqh** [comment]
加COOKIE

**Comment by wuqian9871** [comment]
就那天不好使   后来再下载就可以用了

**Comment by XinyiZhu1007** [comment]
> 加COOKIE

問題解決了~謝謝！
