### ISSUE TITLE
downloader.Download  in a for . the cpu and memory is up to 99%

### ISSUE THREAD

**Issue by kevinmiao** [iawia002/annie#513]
main.go 

`for{
 err = downloader.Download(downloadItem, videoURL, config.ChunkSizeMB)
}`

when i go run main.go  . cup and memory is up to 99%.

what can i do to fix this problem

**Comment by bronze1man** [comment]
Maybe you should handle the case that 'err == nil' then break the for loop.

**Comment by kevinmiao** [comment]
@bronze1man thanks for you reply.  now i am not use "downloader.Download()" in my program , i think use this code will lead to some memory is not release.  so now i use "exec.Command()" in my program to run "annie" , its works well
