### ISSUE TITLE
annie 0.9.5 download youtube playlist panic: runtime error: index out of range

### ISSUE THREAD

**Issue by bronze1man** [iawia002/annie#516]
annie 0.9.5 download youtube playlist panic: runtime error: index out of range
```
annie -i -p https://www.youtube.com/playlist?list=PLlrATfBNZ98foTJPJ_Ev03o2oq3-GGOS2
```

**Comment by iawia002** [comment]
Sorry for the delay, please try [0.9.7](https://github.com/iawia002/annie/releases/tag/0.9.7)
