### ISSUE TITLE
关于“title”的问题

### ISSUE THREAD

**Issue by chinuno-usami** [iawia002/annie#526]
一开始我是遇到#451 这样的问题，多p情况下无法区分顺序，所以想看看能不能改个分p号上去。
结果看到 cbf645fac35427f6a58c81c37e43a0c3a51e3122 这个提交，加了一个文件名长度限制，并且在`title`里加了分p号
但是在https://github.com/iawia002/annie/blob/cbf645fac35427f6a58c81c37e43a0c3a51e3122/extractors/bilibili/bilibili.go#L236-L240 
这里只在`title`长度大于`80`的时候才会把分p加上去
然后想起了之前遇到过这种情况：
名字比较长的视频会变成带分p的形式，最后用省略号省略掉了，但是视频文件跟xml又不一致
像这样
视频文件：`Title 01 Subtitle[0].flv` 是完整的文件名
弹幕xml文件:`Title 01 Subti...` 连后缀都没了
跟这个相关的issue是#522
不知道这里为什么要这样处理？

**Comment by iawia002** [comment]
省略是因为文件名超长在一些系统下要报错，这里处理地不够好，你有兴趣的话可以改改，或者等我有空了来看看

**Comment by chinuno-usami** [comment]
。其实我想问的是为什么要在长度大于80的时候才把分p号加上。这边应该跟长度限制没有关系吧

**Comment by iawia002** [comment]
忘了当时咋想的。。。按理说有分 P 号就应该加上，然后超长省略这个问题也要重新考虑一下
