### ISSUE TITLE
[feature-request] start and end flags for a file

### ISSUE THREAD

**Issue by phanirithvij** [iawia002/annie#529]
Something like these
```shell
annie.exe -F list.txt -start 2 -end 20
annie.exe -F list.txt -start 2 -end 2
annie.exe -F list.txt -start 2
annie.exe -F list.txt -end 20
```
Downloads only a subset of URLs from a list.
The `-F` option didn't work with `-start` and `-end` so I'm guessing this wasn't implemented.

**Comment by Stegosawr** [comment]
You're right the feature isn't implemented. But why don't you just make a file with only the URLs you want? What a typical use case for this?

**Comment by phanirithvij** [comment]
These might be some valid use cases:
- Fetching a huge list containing many urls and downloading a subset of them. (might be useful for some properly labeled datasets)
- Creating a complete list once (which might take some time) and downloading desired videos from it later.
    - eg.
      Dumping all links form youtube playlist to a text file and downloading the last few from it.

It can also be done by just creating a file with only the desired urls. And the same idea can be directly integrated into annie.
