### ISSUE TITLE
优酷下一半出错

### ISSUE THREAD

**Issue by zouhua** [iawia002/annie#53]
···root@vagrant-ubuntu-trusty-64:/data/python# ./annie_linux_amd64 http://v.youku.com/v_show/id_XMTg2MDkwMjU2OA==.html

   Site:   优酷 youku.com
  Title:   驴得水
   Type:   video
Quality:   mp4hd2 1280x544
   Size:   1011.24 MiB (1060363118 Bytes)

 23.68 MiB / 1011.24 MiB [=>-----------------------------------------------------]   2.34% 250.36 KiB/s 1h7m18s 24.51 MiB / 1011.24 MiB [=>------------------------------------------------------]   2.42% 250.94 KiB/s 1h7m5s2018/03/23 16:08:14 Error while downloading: http://vali.cp31.ott.cibntv.net/67712A7A56F4271A343555873/0300012300584E4FFB7BBE05CF07DD5ED554FA-344E-44D9-060F-3977925FDBEC.flv?ccode=0503&duration=203&expire=18000&psid=e8c7535193b2acd84aed20dc2bb6f577&ups_client_netip=3b6c4885&ups_ts=1521793175&ups_userid=&utid=lqY7EyAiCSUCAcu7o+J2eEgs&vid=XMTg2MDkwMjU2OA%3D%3D&vkey=A8dd72981db8c7c95bbb552f14947736f&s=92d6ad9a806711e6b9bb, net/http: request canceled (Client.Timeout exceeded while reading body)
···

**Comment by iawia002** [comment]
这是网络问题，再下一次就好

**Comment by zouhua** [comment]
我试了N次都一样，

**Comment by iawia002** [comment]
注意优酷可能还有另一个问题，没下完就开始合并了，这是已知问题，不用再提 bug 了 #43

**Comment by iawia002** [comment]
只是这一个视频吗？我空了调试一下

**Comment by zouhua** [comment]
恩

**Comment by vaward** [comment]
这个还有没有可能是视频本身分片过多，下载完第一批的4片后就开始合并，后面没继续下载了。

**Comment by leopku** [comment]
昨天也遇到这个情况，基本都是重试一次，能自动续传，下完就好了

**Comment by iawia002** [comment]
@vaward 不是过多，是优酷的 API 只返回了前几分钟的数据，但是它返回的总大小是对的

**Comment by lidedongsn** [comment]
嗯，遇到了同样的问题，分多个文件下载，并且只下载前两个
