### ISSUE TITLE
Pornhub下载panic

### ISSUE THREAD

**Issue by cocobao** [iawia002/annie#540]
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/iawia002/annie/downloader.Download(0x13ae78b, 0x13, 0xc0004ae204, 0x9d, 0x13a6c41, 0x5, 0xc0000a6d20, 0x0, 0x0, 0x0, ...)
        /Users/ybz/Documents/code/gopath/src/github.com/iawia002/annie/downloader/downloader.go:196 +0x1887
main.download(0x7ffeefbff98a, 0x3e, 0x13c35d8)
        /Users/ybz/Documents/code/gopath/src/github.com/iawia002/annie/main.go:185 +0x44a
main.main()
        /Users/ybz/Documents/code/gopath/src/github.com/iawia002/annie/main.go:242 +0x168

**Comment by Cattosm** [comment]
同样的问题

annie -F /data/download/list20191101 

panic: runtime error: index out of range

goroutine 1 [running]:
github.com/iawia002/annie/extractors/youtube.youtubeDownload(0xc420016240, 0x2b, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/root/go/src/github.com/iawia002/annie/extractors/youtube/youtube.go:93 +0x665
github.com/iawia002/annie/extractors/youtube.Extract(0xc420016240, 0x2b, 0x747c96, 0x7, 0x1, 0x0, 0x0)
	/root/go/src/github.com/iawia002/annie/extractors/youtube/youtube.go:38 +0x6d3
main.download(0xc420016240, 0x2b, 0xc420016240)
	/root/go/src/github.com/iawia002/annie/main.go:127 +0x704
main.main()
	/root/go/src/github.com/iawia002/annie/main.go:233 +0x116

**Comment by joeke80215** [comment]
官方有防爬蟲機制...所以目前的邏輯抓不到資源

**Comment by mingcheng** [comment]
试试这个项目 https://github.com/mingcheng/pornhub-dl

**Comment by iawia002** [comment]
#689 fixes this
