### ISSUE TITLE
YouTube下载后只有音频

### ISSUE THREAD

**Issue by wdy3334** [iawia002/annie#543]
https://www.youtube.com/watch?v=FoRfoVCK4_U

下载后后缀是mp4，但是只有音频，没有视频

还是谢谢大佬，很好用

**Comment by cxjava** [comment]
@wdy3334  解析之后是这样的
```
annie -x http://127.0.0.1:7890 -i https://www.youtube.com/watch\?v\=FoRfoVCK4_U

 Site:      YouTube youtube.com
 Title:     Vanity tour  欢迎来到我的化妆品收纳合集
 Type:      video
 Streams:   # All available quality
     [248]  -------------------
     Quality:         1080p video/webm; codecs="vp9"
     Size:            330.62 MiB (346681533 Bytes)
     # download with: annie -f 248 ...

     [137]  -------------------
     Quality:         1080p video/mp4; codecs="avc1.640028"
     Size:            324.85 MiB (340627483 Bytes)
     # download with: annie -f 137 ...

     [247]  -------------------
     Quality:         720p video/webm; codecs="vp9"
     Size:            133.53 MiB (140013110 Bytes)
     # download with: annie -f 247 ...

。。。。。
```
默认下载的是清晰度最高的，靠前的格式`1080p video/webm; codecs="vp9"`保存为Mp4，不能播放是因为需要转码。

如果不想转码，可以下载mp4格式的`1080p video/mp4; codecs="avc1.640028"`。根据提示`# download with: annie -f 137` 加上参数` -f 137 ` 即可。

```
annie -x http://127.0.0.1:7890 -f 137 https://www.youtube.com/watch?v=FoRfoVCK4_U
```

**Comment by wdy3334** [comment]
> @ wdy3334 解析之后是这样的
> 
> ```
> annie -x http://127.0.0.1:7890 -i https://www.youtube.com/watch\?v\=FoRfoVCK4_U
> 
>  Site:      YouTube youtube.com
>  Title:     Vanity tour  欢迎来到我的化妆品收纳合集
>  Type:      video
>  Streams:   # All available quality
>      [248]  -------------------
>      Quality:         1080p video/webm; codecs="vp9"
>      Size:            330.62 MiB (346681533 Bytes)
>      # download with: annie -f 248 ...
> 
>      [137]  -------------------
>      Quality:         1080p video/mp4; codecs="avc1.640028"
>      Size:            324.85 MiB (340627483 Bytes)
>      # download with: annie -f 137 ...
> 
>      [247]  -------------------
>      Quality:         720p video/webm; codecs="vp9"
>      Size:            133.53 MiB (140013110 Bytes)
>      # download with: annie -f 247 ...
> 
> 。。。。。
> ```
> 
> 默认下载的是最高最高的，靠前的格式`1080p video/webm; codecs="vp9"`保存为Mp4，不能播放是因为需要转码。
> 
> 如果不想转码，可以下载mp4格式的`1080p video/mp4; codecs="avc1.640028"`。根据提示`# download with: annie -f 137`加上参数`-f 137`即可。
> 
> ```
> annie -x http://127.0.0.1:7890 -f 137 https://www.youtube.com/watch?v=FoRfoVCK4_U
> ```

两个办法都可以解决 谢谢大佬
