### ISSUE TITLE
json解析错误

### ISSUE THREAD

**Issue by Sesprie** [iawia002/annie#554]
json: cannot unmarshal number into Go struct field multiPage.aid of type string

**Comment by sqliuchang** [comment]
很急…b站没法下载了

**Comment by hubs** [comment]
哈哈，我以为就我....原来都一样了...急急

**Comment by Sesprie** [comment]
好速度，赞一个

**Comment by sqliuchang** [comment]
多谢了，这么快就解决了

**Comment by sqliuchang** [comment]
有的可以，有的不行
https://www.bilibili.com/video/av74911480
这个没法下载

**Comment by iawia002** [comment]
什么情况，我这边显示

<img width="312" alt="Screen Shot 2019-11-08 at 20 08 08" src="https://user-images.githubusercontent.com/9134003/68475606-82efe880-0263-11ea-917d-158018f62e77.png">

**Comment by sqliuchang** [comment]
怪不得 应该是视频被删除了…

**Comment by megabites2013** [comment]
not fix yet,  try this link it still gives the same error, 

annie https://www.bilibili.com/video/BV1px411Q7Kb?p=1
