### ISSUE TITLE
特定youtube视频无法下载？

### ISSUE THREAD

**Issue by impossible98** [iawia002/annie#577]
```
annie -x http://127.0.0.1:10086 -i "https://www.youtube.com/watch?v=D1PvIWdJ8xo"
```

```
Downloading https://www.youtube.com/watch?v=D1PvIWdJ8xo error:
url parse failed
```

**Comment by rainpenber** [comment]
丢到clipconverter里面看了一下 不能被下载的原因是包含版权音乐。这种的解决方法是，你保存一下你登陆了youtube账号以后网站的cookie（chrome可以使用editthiscookie插件），以键值对的形式保存到一个txt文档里去，然后在下载的时候加上`-c 你保存的cookie.txt`试试。有年龄或者地区限制的也可以使用cookie或者换代理线路解决

**Comment by impossible98** [comment]
@rainpenber 试了一下cookies还是不行，不过谢谢了

**Comment by rainpenber** [comment]
> @rainpenber 试了一下cookies还是不行，不过谢谢了
应该和 #585 同一个issue

**Comment by iawia002** [comment]
Sorry for the delay, please try [0.9.7](https://github.com/iawia002/annie/releases/tag/0.9.7)
