### ISSUE TITLE
Panic downloading video

### ISSUE THREAD

**Issue by lamg** [iawia002/annie#58]
With https://github.com/iawia002/annie/commit/4315740814dd81144009eb0f9fc4209dd2041dec I got the following output downloading a YouTube playlist, behind an HTTP proxy :

```
panic: Get https://www.youtube.com/watch?v=lLOvB1qFE1E&gl=US&hl=en&has_verified=1&bpctr=9999999999: Bad Gateway

goroutine 1 [running]:
github.com/iawia002/annie/request.Request(0x70a4cf, 0x3, 0xc4204a0240, 0x57, 0x0, 0x0, 0x0, 0xc4204a0240)
	/home/lamg/go/src/github.com/iawia002/annie/request/request.go:88 +0xc7b
github.com/iawia002/annie/request.Get(0xc4204a0240, 0x57, 0x0, 0x0)
	/home/lamg/go/src/github.com/iawia002/annie/request/request.go:111 +0x7b
github.com/iawia002/annie/extractors.youtubeDownload(0xc4204a01e0, 0x53, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/lamg/go/src/github.com/iawia002/annie/extractors/youtube.go:71 +0x16b
github.com/iawia002/annie/extractors.Youtube(0x7ffcacfc62d0, 0x44)
	/home/lamg/go/src/github.com/iawia002/annie/extractors/youtube.go:52 +0x21c
main.main()
	/home/lamg/go/src/github.com/iawia002/annie/main.go:60 +0x428
```

**Comment by iawia002** [comment]
@lamg I tried this `annie -i -p https://www.youtube.com/watch?v=4FE79y_JkCE&list=PLGxuz-nmYlQMO2wRhUhV_g6AN3vLN_4X7`, but everything is normal here. Can you retry this to see it still wrong?

**Comment by lamg** [comment]
The following code (from request.go) causes this error, is wrong because input/output errors shouldn't be treated as exceptional:

```Go
res, err := client.Do(req)
	if err != nil {
		log.Print(url)
		panic(err)
}
```

You should return the error value.

**Comment by iawia002** [comment]
You mean to ignore this `error`?

```
res, _ := client.Do(req)
```

But I don't understand why you got this `Bad Gateway` error

**Comment by lamg** [comment]
I mean it shouldn't be treated as something worth of a panic call. Checkout the pattern I use for handling errors in https://github.com/lamg/pmproxy/blob/master/cmd/pmproxy/main.go. Every error in internal procedures is returned, the command line interface handles them at the end, because showing messages to the user is its concern.

The `Bad Gateway` probably is a consequence of using a very busy HTTP proxy server with little bandwidth for serving its clients.

**Comment by lamg** [comment]
I mean a panic call isn't the better way of handling it. Checkout https://github.com/lamg/pmproxy/blob/master/cmd/pmproxy/main.go: internal procedures that fail with errors that should be shown to the user return them, and the correct place to handle them is in the command line interface's code. `Bad Gateway` is probably the consequence of using a very busy HTTP proxy with little bandwidth for serving its clients.

**Comment by iawia002** [comment]
@lamg I used to use the `log.Fatal`, but then I think I should use `panic`(5413cd2). The output of `log.Fatal` is too short, too similar. I don't know which request was wrong.
