### ISSUE TITLE
YouTube - url parse failed

### ISSUE THREAD

**Issue by xuxueyun** [iawia002/annie#585]
新的视频地址像 `https://www.youtube.com/watch?v=SFfpK3FoNSg` 会报错 ` url parse failed`

**Comment by yuezy3** [comment]
Same issue. please fix it,

**Comment by xuxueyun** [comment]
对比分析了一下，发现是数据格式变了，我试着修复一下，数据格式有点复杂……

**Comment by Pwera** [comment]
youtube.go line 162 returns nil
`utils.MatchOneOf(streamType, `(\w+)/(\w+);`)`

after that
```
exts := utils.MatchOneOf(streamType, `(\w+)/(\w+);`)
			if exts == nil || len(exts) < 3 {
				return nil, extractors.ErrURLParseFailed
			}
```

**Comment by fastfading** [comment]
annie https://www.youtube.com/watch?v=E2_1y_9zGQs
Downloading https://www.youtube.com/watch?v=E2_1y_9zGQs error:
url parse failed

**Comment by Stegosawr** [comment]
![image](https://user-images.githubusercontent.com/38107067/71636246-af096380-2c2d-11ea-98e5-b82d9e21bc18.png)

Something goes wrong while parsing that json

**Comment by HYLanslot** [comment]
Same issue

**Comment by Stegosawr** [comment]
There is no url_encoded_fmt_stream_map in the html string. Youtube probably changed something again

**Comment by Stegosawr** [comment]
@iawia002 
There is a problem with the youtube download. It's probably something with the signature.
Would be great if you could look into this if you have time.

Also happy New Year :)

**Comment by edwinvedder** [comment]
Same issue. Centos 8. annie 0.9.6

**Comment by fbaube** [comment]
Same issue, both from "brew install" version and from "go get; go run main.go" versions.
MacOS 10.15.3 beta 
go version go1.13.6 darwin/amd64
bash 5.0.11(1)-release (x86_64-apple-darwin18.6.0)

**Comment by w3bb** [comment]
Same issue

**Comment by kiss2u** [comment]
Same issue

**Comment by iawia002** [comment]
Sorry for the delay, please try [0.9.7](https://github.com/iawia002/annie/releases/tag/0.9.7)
