### ISSUE TITLE
部分youtube视频无法解析下载

### ISSUE THREAD

**Issue by qazber** [iawia002/annie#592]
下载地址http://www.youtube.com/watch?v=cACrCUmzMA4，下载命令：annie -s 127.0.0.1:1080 -i http://www.youtube.com/watch?v=cACrCUmzMA4。
提示Downloading [36mhttp://www.youtube.com/watch?v=cACrCUmzMA4[0m error:
[31murl parse failed[0m    
是什么原因？

**Comment by qazber** [comment]
请各位大神帮忙找找原因

**Comment by Stegosawr** [comment]
Looks like it's the same problem as #585

**Comment by iawia002** [comment]
Sorry for the delay, please try [0.9.7](https://github.com/iawia002/annie/releases/tag/0.9.7)
