### ISSUE TITLE
New Design

### ISSUE THREAD

**Issue by Yasujizr** [iawia002/annie#60]
![untitled-1](https://user-images.githubusercontent.com/36993664/37868680-9a7f2cf8-2fbb-11e8-98b6-7b4618ad3cab.jpg)

Hi I have made a icon to help you in your project and to better present the program you have developed. If you want any change, you can contact me without hesitation. I hope you use it.

**Comment by iawia002** [comment]
Thanks for doing this! They looks good, but I prefer wild style. Something like your previous work 'Steem Assistant Logo', that looks really cool!

**Comment by Yasujizr** [comment]
I will prepare a few drafts for you. we do what they like. Thank you for looking at my designs. :)

**Comment by Yasujizr** [comment]
![annie](https://user-images.githubusercontent.com/36993664/37880107-31d6fe0c-308c-11e8-9ecf-a55725762267.jpg)


Hello there,

I've tried a few options. I'd like to hear your ideas.

**Comment by iawia002** [comment]
To be honest, I like your almost all previous works, Steem Assistant Logo is my favorite, but this one, not cool enough, this graphic is not cool at all, can we try it again? Many thanks!

**Comment by Yasujizr** [comment]
I think you are right. I will work on it. Send me the designs if you like them. Let us draw a path according to him. I'll do some more work again. Thank you for your answers. :)

**Comment by Yasujizr** [comment]
![anni2elogo](https://user-images.githubusercontent.com/36993664/37923285-7246522a-3137-11e8-8fdf-467f7c07ea40.jpg)


Hi,
I've done another study, and I've also examined the logo you sent. It seems a little difficult. The same can be done. No problem. But if we're thinking of a logo that expresses your program. It will be difficult to adapt.

![anni2e](https://user-images.githubusercontent.com/36993664/37923290-7652675a-3137-11e8-8a6b-79d025377332.jpg)

**Comment by iawia002** [comment]
This looks cooooooool!
@Yasujizr I want this, I will mention your name in README, thanks for doing this!

**Comment by iawia002** [comment]
You can find my email here https://github.com/iawia002

**Comment by Yasujizr** [comment]
Thank u. :)

I sent the files to your mail. If a problem arises, you can send an e-mail.

**Comment by iawia002** [comment]
@Yasujizr Thank you very much!

One last question, this logo won't be authorized to others, right?

**Comment by iawia002** [comment]
I have mentioned your name here https://github.com/iawia002/annie#contributing

**Comment by iawia002** [comment]
Thanks @Yasujizr
