### ISSUE TITLE
解析不了Youtube

### ISSUE THREAD

**Issue by jyuan15** [iawia002/annie#600]
win10 64位系统，annie可以解析国内网站视频，但解析Youtube时一直不出来结果，一直停在这个界面，而用you-get、youtube-dl都能正常解析。

![图片](https://user-images.githubusercontent.com/12642186/72869969-c7970600-3d21-11ea-8e5b-8cf04752dd42.png)

**Comment by kybom** [comment]
程序应该打印一下错误，这样才好排查

**Comment by jyuan15** [comment]
> 
> 
> 程序应该打印一下错误，这样才好排查

debug模式也是一直没有任何内容输出。

**Comment by jyuan15** [comment]
好像变成ipv6了，而代理又不支持ipv6，所以才导致解析失败吧

`$ annie -i https://www.youtube.com/watch?v=7pDQ4ImXmRM
Downloading https://www.youtube.com/watch?v=7pDQ4ImXmRM error:
request error: Get https://www.youtube.com/watch?v=7pDQ4ImXmRM: dial tcp [2404:6800:4008:801::200e]:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.`

**Comment by chandler1142** [comment]
I got the same problem, try to add proxy option, like: annie -s 127.0.0.1:1080  <url>

**Comment by wxf4150** [comment]
不行啊
youtube.com下载 引用了 github.com/rylio/ytdl
ytdl这个模块不支持 socks5代理 .  配制的socks5 仅在annie项目这范围里有效.

**Comment by iawia002** [comment]
@wxf4150 我发现了这个问题，试试最新的 0.9.8，使用代理的方式有变化
https://github.com/iawia002/annie#proxy

**Comment by jyuan15** [comment]
最新版可以解析Youtube了，但代理命令也太长了吧，能不能精简一下？
比如http用“H”表示，socks用“S”表示，可以实现吗？

**Comment by iawia002** [comment]
Try [0.10.0](https://github.com/iawia002/annie/releases/tag/0.10.0)
