### ISSUE TITLE
关于 Win10 Youtube下载的代理问题

### ISSUE THREAD

**Issue by JulyanHe** [iawia002/annie#609]
新版本更换代理设置方式之后，在Win10 PowerShell中，如果直接套用示例中的写法就会报语法错误
>PS C:\Users\user> HTTP_PROXY="http://127.0.0.1:1080/" annie -i https://www.youtube.com/watch?v=Gnbch2osEeo

返回 
>HTTP_PROXY=http://127.0.0.1:1080/ : 无法将“HTTP_PROXY=http://127.0.0.1:1080/”项识别为 cmdlet、函数、脚本文件或可运行
程序的名称。请检查名称的拼写，如果包括路径，请确保路径正确，然后再试一次。

如果先设置好 `http_proxy` `https_proxy` 再下载，从结果上看和不做任何设置下的报错一样，换言之就是不走代理
>PS C:\Users\user> set http_proxy=http://127.0.0.1:1080
PS C:\Users\user> set https_proxy=http://127.0.0.1:1080
PS C:\Users\user> annie -i https://www.youtube.com/watch?v=Gnbch2osEeo

返回
>Downloading [36mhttps://youtu.be/QTiA1fhfkic?list=PLtGPeQrZzBXv6ijt6x6DYcZ7jwM6OgRsu[0m error:
[31mrequest failed: &{%!w(string=Get) %!w(string=https://www.youtube.com/watch?v=QTiA1fhfkic) %!w(*net.OpError=&{dial tcp <nil> 0xc00005fc80 0xc00004d220})}[0m

**Comment by iawia002** [comment]
Windows 的 shell 怎么配置环境变量我不太熟，你得保证 `HTTP_PROXY` 环境变量设置上了，然后 `http://127.0.0.1:1080/` 这个代理地址是否正确？

macOS/Linux 示例：

```console
$ HTTP_PROXY="http://127.0.0.1:1087/" annie -i https://www.youtube.com/watch?v=Gnbch2osEeo

 Site:      YouTube youtube.com
 Title:     Multifandom Mashup 2017
 Type:      video
 Streams:   # All available quality
     [136]  -------------------
     Quality:         720p video/mp4; codecs="avc1.4d401f"
     Size:            55.58 MiB (58282592 Bytes)
     # download with: annie -f 136 ...

...
```

**Comment by JulyanHe** [comment]
1. 刚才的描述确实有问题，`set`是 cmd 设置代理的方法，而 PowerShell 设置似乎要麻烦的多。
2. 你提到的代理地址是否有误，这是没有问题的，之前版本一直是通过`-s 127.0.0.1:1080`设置，是可以下载的
3. 如果在cmd中下载视频，出现了新的问题。已经通过`curl`检验过代理连通的情况下：
```shell
C:\Users\user>annie -i https://www.youtube.com/watch?v=Gnbch2osEeo

Downloading [36mhttps://www.youtube.com/watch?v=Gnbch2osEeo[0m error:
[31munexpected status code: 429[0m
```

**Comment by JulyanHe** [comment]
429报错可能是短时间内测试太频繁导致的，现在在 cmd 可以正常使用了。我先关掉这个comment。

**Comment by JulyanHe** [comment]
429 应该是短时间测试过于频繁导致的。现在已经可以正常用了。就先关掉这个issue了，感谢。
