### ISSUE TITLE
Is there any way to not include the playlist name when downloading the playlist?

### ISSUE THREAD

**Issue by Benjababe** [iawia002/annie#615]
^

**Comment by Stegosawr** [comment]
Show an example - please

**Comment by Benjababe** [comment]
When i try to download the playlist running 
> annie -p -start 2 https://www.bilibili.com/video/av50672987

All video files will be prepended with the playlist name eg. 
>Vid 2 - 【RingFinger中字】Playlist by DAY6 & Compact Live 合集（四集全） P2 [Compact Live] SECRE....flv
Vid 3 - 【RingFinger中字】Playlist by DAY6 & Compact Live 合集（四集全） P3 Playlist by DAY6 #2.flv

Is there a way to ignore the playlist name "【RingFinger中字】Playlist by DAY6 & Compact Live 合集（四集全）" from all the downloads? It cuts off the video filenames sometimes.

**Comment by Stegosawr** [comment]
Thanks for your example!

Maybe I can implement something after the title finding here:
https://github.com/iawia002/annie/blob/f3ef980c190bf458971bf739f32a1af49a7b59a5/extractors/bilibili/bilibili.go#L325

I will look into this as soon as I can

--- Note for me ---
This is the link to the get title method
https://github.com/iawia002/annie/blob/f3ef980c190bf458971bf739f32a1af49a7b59a5/parser/parser.go#L60
