### ISSUE TITLE
Couldn't extract url from format

### ISSUE THREAD

**Issue by OUZYcn** [iawia002/annie#622]
annie.exe -d https://www.youtube.com/watch?v=J6Tq3hw5SWs

annie: version 0.9.8, A fast, simple and clean video downloader.

{"level":"debug","time":"2020-02-20T18:13:28+08:00","message":"Fetching https://www.youtube.com/watch?v=J6Tq3hw5SWs"}
{"level":"debug","time":"2020-02-20T18:13:30+08:00","message":"No itag found with number: 597, skipping..."}
{"level":"debug","time":"2020-02-20T18:13:30+08:00","message":"No itag found with number: 598, skipping..."}
{"level":"debug","time":"2020-02-20T18:13:30+08:00","message":"No itag found with number: 599, skipping..."}
{"level":"debug","time":"2020-02-20T18:13:30+08:00","message":"No itag found with number: 600, skipping..."}

URL:         https://www.youtube.com/watch?v=J6Tq3hw5SWs
Method:      GET
Headers:     http.Header{
    "Accept":          {"text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"},
    "Accept-Charset":  {"UTF-8,*;q=0.5"},
    "Accept-Encoding": {"gzip,deflate,sdch"},
    "Accept-Language": {"en-US,en;q=0.8"},
    "User-Agent":      {"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.81 Safari/537.36"},
    "Referer":         {"https://www.youtube.com"},
}
Status Code: 200
Downloading https://www.youtube.com/watch?v=J6Tq3hw5SWs error:
**Couldn't extract url from format**

**Comment by iawia002** [comment]
Try [0.10.0](https://github.com/iawia002/annie/releases/tag/0.10.0)
