### ISSUE TITLE
request error: HTTP 405

### ISSUE THREAD

**Issue by Jeff-Jia** [iawia002/annie#626]
Dear Developer:
    When I try to download "叶问4" on iQiYi, I met this issue.

$: annie -i https://www.iqiyi.com/v_19rw208to0.html?vfm=2008_aldbd&fc=828fb30b722f3164&fv=p_02_01

Downloading https://www.iqiyi.com/v_19rw208to0.html?vfm=2008_aldbd error:
http://data.video.iqiyi.com/videos/v0/20200210/9f/b2/f331dc77b39ca43c6df7fce18d1ec3e5.f4v?qd_tvid=12340311900&qd_vipres=2&qd_index=1&qd_aid=12340311900&qd_stert=0&qd_scc=61674b3b07a964cba41a4bb8a8102267&qd_sc=d29e55df3b3c3424a2d63ff0903ce9de&qd_p=76cf7be5&qd_ip=76cf7be5&qd_k=87777a0494d2a5fa4bd3775b074b6560&qd_src=01012001010000000000&qd_vipdyn=2&qd_uid=0&qd_tm=1582453547161&qd_vip=0 request error: HTTP 405

Could you please help check it?
Thanks so much~

**Comment by tea1111980** [comment]
can't download on vip.

**Comment by Jeff-Jia** [comment]
Thanks a lot.
