### ISSUE TITLE
flag provided but not defined: -f

### ISSUE THREAD

**Issue by ardinusawan** [iawia002/annie#64]
Hey, when I try to download with 
```
$ annie -f default https://www.youtube.com/watch?v=x2P7nDtXg-A
```
I got message like this : flag provided but not defined: -f
And if 
```
$ annie -h
```
The message show without -f flag
```
Usage of annie:
  -c string
    	Cookie
  -d	Debug mode
  -i	Information only
  -p	Download playlist
  -r string
    	Use specified Referrer
  -s string
    	SOCKS5 proxy
  -v	Show version
  -x string
    	HTTP proxy
```

annie: version 0.5.1
MacOS High Sierra 10.13.3

**Comment by iawia002** [comment]
0.6.1

**Comment by ardinusawan** [comment]
I installed with ```go get github.com/iawia002/annie```
Why I not get latest version?

**Comment by iawia002** [comment]
@ardinusawan [0.6.0](https://github.com/iawia002/annie/releases/tag/0.6.0) released 2 days ago, when did you install it?

**Comment by ardinusawan** [comment]
@iawia002 I just installed today

**Comment by ardinusawan** [comment]
@iawia002 I installed several day ago (I forgot the day exactly). And I try to install again today with same command. Now I try to upgrade with ```go get -u all```

**Comment by ardinusawan** [comment]
Ok, my annie version now 0.6.1
Thx dude

**Comment by iawia002** [comment]
Ok then
