### ISSUE TITLE
B站改版，av号变成BV号

### ISSUE THREAD

**Issue by zhz1237ok** [iawia002/annie#651]
以下两个链接指向了同一个视频
https://www.bilibili.com/video/av98307847
https://www.bilibili.com/video/BV1JE411F741

虽然现在av号还能继续使用
但是，可以预见的是未来很有可能取消av号，全部使用BV号

**Comment by VoidxHoshi** [comment]
Annie又不是特定av号的（输网址一样可以），只是可能不能像以前一样直接输av号罢了。

**Comment by redyjq** [comment]
测试了一下，使用BV号是不能下载的

C:\Users\user\Downloads>annie https://www.bilibili.com/video/BV1aE411F7DS
Downloading [36mhttps://www.bilibili.com/video/BV1aE411F7DS[0m error:
[31mhttps://www.bilibili.com/video/BV1aE411F7DS request error: HTTP 403[0m

C:\Users\user\Downloads>annie -v
[36mannie[0m: version [34m0.9.8[0m, A fast, simple and clean video downloader.

我切换成AV号之后，是可以下载的
C:\Users\user\Downloads>annie https://www.bilibili.com/video/av98347549

 Site:      哔哩哔哩 bilibili.com
 Title:     活动作品当年“天下足球 ”好听到炸裂的BGM，满满都是回忆啊！
 Type:      video
 Stream:
     [80]  -------------------
     Quality:         高清 1080P
     Size:            219.81 MiB (230489404 Bytes)
     # download with: annie -f 80 ...

 2.94 MiB / 219.81 MiB [>-----------------------------------------------------------------]   1.34% 713.26 KiB/s 05m09s

现在通过查看网页源代码，还可以查询到视频的av号，但我估计以后有可能会慢慢取消

**Comment by VoidxHoshi** [comment]
> 测试了一下，使用BV号是不能下载的
> 
> C:\Users\user\Downloads>annie https://www.bilibili.com/video/BV1aE411F7DS
> Downloading �[36mhttps://www.bilibili.com/video/BV1aE411F7DS�[0m error:
> �[31mhttps://www.bilibili.com/video/BV1aE411F7DS request error: HTTP 403�[0m
> 
> C:\Users\user\Downloads>annie -v
> �[36mannie�[0m: version �[34m0.9.8�[0m, A fast, simple and clean video downloader.
> 
> 我切换成AV号之后，是可以下载的
> C:\Users\user\Downloads>annie https://www.bilibili.com/video/av98347549
> 
> Site: 哔哩哔哩 bilibili.com
> Title: 活动作品当年“天下足球 ”好听到炸裂的BGM，满满都是回忆啊！
> Type: video
> Stream:
> [80] -------------------
> Quality: 高清 1080P
> Size: 219.81 MiB (230489404 Bytes)
> # download with: annie -f 80 ...
> 
> 2.94 MiB / 219.81 MiB [>-----------------------------------------------------------------] 1.34% 713.26 KiB/s 05m09s
> 
> 现在通过查看网页源代码，还可以查询到视频的av号，但我估计以后有可能会慢慢取消

我可以正常使用

**Comment by mo-han** [comment]
> 
> 
> > 测试了一下，使用BV号是不能下载的
> > C:\Users\user\Downloads>annie https://www.bilibili.com/video/BV1aE411F7DS
> > Downloading �[36mhttps://www.[bilibili.com/video/BV1aE411F7DS�[0m](http://bilibili.com/video/BV1aE411F7DS�[0m) error:
> > �[31mhttps://www.[bilibili.com/video/BV1aE411F7DS](http://bilibili.com/video/BV1aE411F7DS) request error: HTTP 403�[0m
> > C:\Users\user\Downloads>annie -v
> > �[36mannie�[0m: version �[34m0.9.8�[0m, A fast, simple and clean video downloader.
> > 我切换成AV号之后，是可以下载的
> > C:\Users\user\Downloads>annie https://www.bilibili.com/video/av98347549
> > Site: 哔哩哔哩 bilibili.com
> > Title: 活动作品当年“天下足球 ”好听到炸裂的BGM，满满都是回忆啊！
> > Type: video
> > Stream:
> > [80] -------------------
> > Quality: 高清 1080P
> > Size: 219.81 MiB (230489404 Bytes)
> > # download with: annie -f 80 ...
> > 2.94 MiB / 219.81 MiB [>-----------------------------------------------------------------] 1.34% 713.26 KiB/s 05m09s
> > 现在通过查看网页源代码，还可以查询到视频的av号，但我估计以后有可能会慢慢取消
> 
> 我可以正常使用

你真的确定吗？
我也试了，同一个视频（旧稿），用av号版的URL可以正常下载，但是用BV号版本的URL就不行，同样是报HTTP 403的错误码。
你测试正常的视频地址发一下呗？

**Comment by VoidxHoshi** [comment]
> > > 测试了一下，使用BV号是不能下载的
> > > C:\Users\user\Downloads>annie https://www.bilibili.com/video/BV1aE411F7DS
> > > Downloading �[36mhttps://www.[bilibili.com/video/BV1aE411F7DS�[0m](http://bilibili.com/video/BV1aE411F7DS%EF%BF%BD%5B0m) error:
> > > �[31mhttps://www.[bilibili.com/video/BV1aE411F7DS](http://bilibili.com/video/BV1aE411F7DS) request error: HTTP 403�[0m
> > > C:\Users\user\Downloads>annie -v
> > > �[36mannie�[0m: version �[34m0.9.8�[0m, A fast, simple and clean video downloader.
> > > 我切换成AV号之后，是可以下载的
> > > C:\Users\user\Downloads>annie https://www.bilibili.com/video/av98347549
> > > Site: 哔哩哔哩 bilibili.com
> > > Title: 活动作品当年“天下足球 ”好听到炸裂的BGM，满满都是回忆啊！
> > > Type: video
> > > Stream:
> > > [80] -------------------
> > > Quality: 高清 1080P
> > > Size: 219.81 MiB (230489404 Bytes)
> > > # download with: annie -f 80 ...
> > > 2.94 MiB / 219.81 MiB [>-----------------------------------------------------------------] 1.34% 713.26 KiB/s 05m09s
> > > 现在通过查看网页源代码，还可以查询到视频的av号，但我估计以后有可能会慢慢取消
> > 
> > 
> > 我可以正常使用
> 
> 你真的确定吗？
> 我也试了，同一个视频（旧稿），用av号版的URL可以正常下载，但是用BV号版本的URL就不行，同样是报HTTP 403的错误码。
> 你测试正常的视频地址发一下呗？

$ annie https://www.bilibili.com/video/BV1aE411F7DS

 Site:      哔哩哔哩 bilibili.com
 Title:     活动作品当年“天下足球 ”好听到炸裂的BGM，满满都是回忆啊！
 Type:      video
 Stream:
     [80]  -------------------
     Quality:         高清 1080P
     Size:            219.81 MiB (230489404 Bytes)
     # download with: annie -f 80 ...

 5.97 MiB / 219.81 MiB    2.72% 715.06 KiB/s 05m05s11s
