### ISSUE TITLE
下载列表时，能不能为每个视频自动选择最高清晰度？

### ISSUE THREAD

**Issue by playgithub** [iawia002/annie#652]

**Comment by VoidxHoshi** [comment]
实际就是如此，但其实Annie是默认下载最大的视频（往往最清晰）
只是因为二次压制的问题（B站比较明显），例如上传后720P的视频大小比1080P要大，所以默认下载了720P的视频。

**Comment by playgithub** [comment]
是的，我也发现这个现象了，如果显示指定就更好了，比如可以选择文件最大或者分辨率最高。
