### ISSUE TITLE
invalid character ';' after top-level value

### ISSUE THREAD

**Issue by nu8** [iawia002/annie#658]
~~~
$ annie https://www.youtube.com/watch?v=lSOEGRl_LnE
Downloading https://www.youtube.com/watch?v=lSOEGRl_LnE error:
invalid character ';' after top-level value
~~~

<https://www.youtube.com/watch?v=lSOEGRl_LnE>

**Comment by Rishikleo** [comment]
yeah, even I'm facing this issue.
any solutions?

 https://www.youtube.com/watch?v=E5Jg4Wm9b7o

**Comment by muv1** [comment]
@Rishikleo workaround:

<https://github.com/ytdl-org/youtube-dl>

**Comment by Rishikleo** [comment]
thanks man 👍

**Comment by Rishikleo** [comment]
hey I used youtube-dl and I can't get the video along with the  audio except in 720p quality and I can't download the video with the highest quality with audio

**Comment by muv1** [comment]
@Rishikleo thats off topic.

**Comment by kimonoki** [comment]
I find you can succeed by trying more times..

**Comment by muv1** [comment]
I tried 5 times in a row, no luck.

**Comment by Rishikleo** [comment]
hey, @muv1 I suggest  " you-get " instead of youtube-dl. 
it has a similar interface to Annie

**Comment by j3g** [comment]
+1 for me. I am running the binary from this release: "annie_0.9.8_Linux_64-bit.tar.gz". Running on ubuntu 18.x.

**Comment by allochi** [comment]
I still prefer `annie` over any python solution, Go solutions are one clean binary. I hope this get fixed soon.

**Comment by mdouchement** [comment]
I've build annie from the master branch (424f8de) and the issue seems resolved.

**Comment by xbolshe** [comment]
See https://github.com/rylio/ytdl/pull/93

**Comment by duxinglangzi** [comment]
Running on Centos 8.   No more .

**Comment by BillChen2K** [comment]
Same problem here.

**Comment by iawia002** [comment]
Try [0.10.0](https://github.com/iawia002/annie/releases/tag/0.10.0)
