### ISSUE TITLE
download youtube is failed

### ISSUE THREAD

**Issue by huluBrother** [iawia002/annie#661]

**Comment by huluBrother** [comment]
`F:>annie https://www.youtube.com/watch?v=vCyD1vzKDkk
Downloading [36mhttps://www.youtube.com/watch?v=vCyD1vzKDkk[0m error:
[31minvalid character ';' after top-level value[0m`

when I download the video, it always failed. How to solve it?
the URL is https://www.youtube.com/watch?v=vCyD1vzKDkk

**Comment by zjgsamuel** [comment]
Me too

Downloading [36mhttps://www.youtube.com/watch?v=yMxPBPcdLUI[0m error:
[31minvalid character ';' after top-level value[0m

**Comment by kkdai** [comment]
youtube profile info has been changed. Need check from more detail refer to https://github.com/rylio/ytdl/pull/92
https://github.com/kkdai/youtube/issues/26

**Comment by iawia002** [comment]
Try [0.10.0](https://github.com/iawia002/annie/releases/tag/0.10.0)
