### ISSUE TITLE
Fails to compile

### ISSUE THREAD

**Issue by arsdragonfly** [iawia002/annie#664]
```
go get github.com/iawia002/annie   
# github.com/iawia002/annie/extractors/youtube
go/src/github.com/iawia002/annie/extractors/youtube/youtube.go:122:37: not enough arguments in call to ytdl.GetVideoInfo
        have (string)
        want (context.Context, interface {})
go/src/github.com/iawia002/annie/extractors/youtube/youtube.go:190:27: videoInfo.GetDownloadURL undefined (type *ytdl.VideoInfo has no field or method GetDownloadURL)
```

**Comment by AntiverX** [comment]
`[root ~] go get github.com/iawia002/annie
go: downloading github.com/iawia002/annie v0.0.0-20200408122329-90e4f8f6dc58
go: github.com/iawia002/annie upgrade => v0.0.0-20200408122329-90e4f8f6dc58
go: downloading github.com/rs/zerolog v1.16.0
go: downloading github.com/rylio/ytdl v0.6.2
go: downloading github.com/tidwall/gjson v1.3.2
go: downloading github.com/tidwall/match v1.0.1
go: downloading github.com/cheggaaa/pb v1.0.25
go: downloading github.com/tidwall/pretty v1.0.0
go: downloading github.com/kr/pretty v0.1.0
go: downloading github.com/fatih/color v1.7.0
go: downloading github.com/kr/text v0.1.0
go: downloading github.com/PuerkitoBio/goquery v1.4.1
go: downloading golang.org/x/sys v0.0.0-20191104094858-e8c54fb511f6
go: downloading github.com/MercuryEngineering/CookieMonster v0.0.0-20180304172713-1584578b3403
go: downloading github.com/mattn/go-runewidth v0.0.6
go: downloading github.com/mattn/go-colorable v0.0.9
go: downloading github.com/mattn/go-isatty v0.0.10
go: downloading github.com/andybalholm/cascadia v1.0.0`

Can you try again?

**Comment by elimisteve** [comment]
I'm having the same problem (go version 1.14) --

```
$ go get github.com/iawia002/annie
# github.com/iawia002/annie/extractors/youtube
/home/user/gocode/src/github.com/iawia002/annie/extractors/youtube/youtube.go:122:37: not enough arguments in call to ytdl.GetVideoInfo
        have (string)
        want (context.Context, interface {})
```

**Comment by elimisteve** [comment]
Upgraded to go 1.14.2 but ran into the same exact issue.

**Comment by elimisteve** [comment]
@AntiverX If you do

    go get -u -v github.com/iawia002/annie

it'll be more realistic of a user doing a fresh install. If you do ^^that^^, _then_ do you get the same error?

**Comment by mrmign** [comment]
![image](https://user-images.githubusercontent.com/1880532/79692809-bfefea80-8299-11ea-8867-563125825a82.png)
same problem on go 1.14.2

**Comment by elimisteve** [comment]
Any plans to fix the build?...

**Comment by elimisteve** [comment]
Looks like https://github.com/rylio/ytdl/pull/100 should fix this. Checking...

**Comment by elimisteve** [comment]
Hey all, I fixed it! Instead of running

    $ go get github.com/iawia002/annie

run

    $ GO111MODULE=on go get github.com/iawia002/annie

:tada: 

Does it work for you? If so, leave a comment on https://github.com/iawia002/annie/pull/671 saying to accept my PR that tweaks the installation instructions on `README.md` :slightly_smiling_face: .

**Comment by forliuyifei** [comment]
```
✘ GO111MODULE=on go get github.com/iawia002/annie
# github.com/iawia002/annie/extractors/youtube
go/pkg/mod/github.com/iawia002/annie@v0.0.0-20201215015310-abc3c9df1817/extractors/youtube/youtube.go:128:20: undefined: ytdl.DefaultClient
go/pkg/mod/github.com/iawia002/annie@v0.0.0-20201215015310-abc3c9df1817/extractors/youtube/youtube.go:196:18: undefined: ytdl.DefaultClient
✘ go get github.com/iawia002/annie
# github.com/iawia002/annie/extractors/youtube
go/pkg/mod/github.com/iawia002/annie@v0.0.0-20201215015310-abc3c9df1817/extractors/youtube/youtube.go:128:20: undefined: ytdl.DefaultClient
go/pkg/mod/github.com/iawia002/annie@v0.0.0-20201215015310-abc3c9df1817/extractors/youtube/youtube.go:196:18: undefined: ytdl.DefaultClient
```
