### ISSUE TITLE
哔哩哔哩不支持4K下载

### ISSUE THREAD

**Issue by fuchanghao** [iawia002/annie#670]
测试视频：https://www.bilibili.com/video/av412909688

命令行

> annie.exe -c cookies.txt -p https://www.bilibili.com/video/av412909688

输出信息如下：

> 
>  Site:      哔哩哔哩 bilibili.com
>  Title:     【何同学4K】3299真香？iPhone SE使用体验 P1 iPhone SE 4k 2
>  Type:      video
>  Stream:
>      [112]  -------------------
>      Quality:         高清 1080P+
>      Size:            78.21 MiB (82008936 Bytes)
>      # download with: annie -f 112 ...
> 

并未识别最高清晰度。

**Comment by kepy909** [comment]
我去看了下，现在官方返回的就是没有4k信息的，只有网页有。
![image](https://user-images.githubusercontent.com/23306503/80106872-fdf85180-85ac-11ea-8171-28cb4bfa5926.png)

**Comment by PlexPt** [comment]
you le

**Comment by obrua** [comment]
> you le

??啥意思，还是没有啊

**Comment by PlexPt** [comment]
@obrua 
![image](https://user-images.githubusercontent.com/15922823/83992462-f5a07e00-a982-11ea-96ca-dc370ef94f96.png)

**Comment by bfchengnuo** [comment]
同样解析不到。。。
``` sh
annie -c cookie.txt -i BV12D4y1D7ZY

 Site:      哔哩哔哩 bilibili.com
 Title:     「天气之子」4K 画质巅峰，你若安好，便是雨天
 Type:      video
 Streams:   # All available quality
     [112]  -------------------
     Quality:         高清 1080P+
     Size:            158.46 MiB (166154524 Bytes)
     # download with: annie -f 112 ...

     [80]  -------------------
     Quality:         高清 1080P
     Size:            74.43 MiB (78048791 Bytes)
     # download with: annie -f 80 ...

     [64]  -------------------
     Quality:         高清 720P
     Size:            51.89 MiB (54407678 Bytes)
     # download with: annie -f 64 ...

     [32]  -------------------
     Quality:         清晰 480P
     Size:            32.35 MiB (33925803 Bytes)
     # download with: annie -f 32 ...

     [16]  -------------------
     Quality:         流畅 360P
     Size:            14.67 MiB (15386695 Bytes)
     # download with: annie -f 16 ...
```

**Comment by delusionxb** [comment]
> 同样解析不到。。。
> 
> ```shell
> annie -c cookie.txt -i BV12D4y1D7ZY
> 
>  Site:      哔哩哔哩 bilibili.com
>  Title:     「天气之子」4K 画质巅峰，你若安好，便是雨天
>  Type:      video
>  Streams:   # All available quality
>      [112]  -------------------
>      Quality:         高清 1080P+
>      Size:            158.46 MiB (166154524 Bytes)
>      # download with: annie -f 112 ...
> 
>      [80]  -------------------
>      Quality:         高清 1080P
>      Size:            74.43 MiB (78048791 Bytes)
>      # download with: annie -f 80 ...
> 
>      [64]  -------------------
>      Quality:         高清 720P
>      Size:            51.89 MiB (54407678 Bytes)
>      # download with: annie -f 64 ...
> 
>      [32]  -------------------
>      Quality:         清晰 480P
>      Size:            32.35 MiB (33925803 Bytes)
>      # download with: annie -f 32 ...
> 
>      [16]  -------------------
>      Quality:         流畅 360P
>      Size:            14.67 MiB (15386695 Bytes)
>      # download with: annie -f 16 ...
> ```

同上, 最高只有1080 60p, 没有4k的

**Comment by syayys** [comment]
别提了我只能解析480P

**Comment by YangLin1998** [comment]
> 别提了我只能解析480P

我找到一个可以解析4K的下载工具
https://github.com/niuhuan/bili-cli-rs

**Comment by kepy909** [comment]
480p是因为没cookies

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Mfus ***@***.***>
发送时间: Tuesday, July 18, 2023 6:37:08 PM
收件人: iawia002/lux ***@***.***>
抄送: kepy909 ***@***.***>; Comment ***@***.***>
主题: Re: [iawia002/lux] 哔哩哔哩不支持4K下载 (#670)


别提了我只能解析480P

我找到一个可以解析4K的下载工具
https://github.com/niuhuan/bili-cli-rs

―
