### ISSUE TITLE
拜托升级一下chocolatey和homebrew的pkg 目前版本是0.9.6和0.9.3

### ISSUE THREAD

**Issue by mengx8** [iawia002/annie#680]
拜托升级一下chocolatey和homebrew的pkg 
目前版本是0.9.6和0.9.3
无法下载youtube视频

https://chocolatey.org/packages/annie

**Comment by mengx8** [comment]
homebrew版本也很老

**Comment by lakerbfs** [comment]
<a href="https://lakerbfs.co.uk">Laker Builders Merchant!</a>
<a href="https://lakerbfs.co.uk/building-supplies/">Laker Builders Merchant!</a>
<a href="https://lakerbfs.co.uk/timber-materials/">Laker Builders Merchant!</a>
<a href="https://lakerbfs.co.uk/fixings-tools/">Laker Builders Merchant!</a>
<a href="https://lakerbfs.co.uk/landscaping/">Laker Builders Merchant!</a>
<a href="https://lakerbfs.co.uk/bathrooms/">Laker Builders Merchant!</a>
<a href="https://lakerbfs.co.uk/window-doors/">Laker Builders Merchant!</a>
<a href="https://lakerbfs.co.uk/kitchens/">Laker Builders Merchant!</a>

**Comment by iawia002** [comment]
chocolatey 不是我维护的，homebrew 的一直是最新的呀，现在是 0.10.2
