### ISSUE TITLE
Youtube 视频下载失败

### ISSUE THREAD

**Issue by gelmannt** [iawia002/annie#683]
下载命令输入后会出现以下提示
Downloading [36mhttps://www.youtube.com/watch?v=KVFhaZbrOGE[0m error: [31minvalid character ';' after top-level value[0m

**Comment by Karl15926** [comment]
一样的情况……

**Comment by yueyangyang** [comment]
me too

**Comment by iawia002** [comment]
Try [0.10.0](https://github.com/iawia002/annie/releases/tag/0.10.0)
