### ISSUE TITLE
能否添加对B站DASH格式视频的支持，这样下载速度可能快一些

### ISSUE THREAD

**Issue by jiaqi61** [iawia002/annie#684]
下载B站的这个视频https://www.bilibili.com/video/BV1EE411X7HR， annie得到的信息如下
![image](https://user-images.githubusercontent.com/33590720/81764811-fd484080-9504-11ea-87cd-6b25c822a90e.png)
用you-get得到的信息如下
![image](https://user-images.githubusercontent.com/33590720/81765081-852e4a80-9505-11ea-9e85-fcf6017e5ce2.png)
说明annie好像不能发现DASH格式的视频。下载速度的话you-get默认下载DASH格式的视频，速度要快很多，能达到10MB/s
![image](https://user-images.githubusercontent.com/33590720/81765302-0685dd00-9506-11ea-91ea-242828a6e5ad.png)
而annie 下载速度一般不超过500KB/s
![image](https://user-images.githubusercontent.com/33590720/81765372-346b2180-9506-11ea-8338-8b6f3ca46a85.png)

**Comment by iawia002** [comment]
Try [0.10.3](https://github.com/iawia002/annie/releases/tag/0.10.3)
