### ISSUE TITLE
优酷是否有ip屏蔽的操作

### ISSUE THREAD

**Issue by mgr9525** [iawia002/annie#688]
annie -j http://v.youku.com/v_show/id_XNDE5OTg1OTEyNA==.html
使用本地可以正常解析，使用服务器（静态ip）不行，同样的代码编译出来的，加了COOKIE也不行。
![image](https://user-images.githubusercontent.com/9899755/82111097-17885580-9775-11ea-9e38-0298f676efbe.png)

**Comment by redstoneleo** [comment]
下载多之后好像会屏蔽

**Comment by mgr9525** [comment]
我用openvpn做隧道了，服务器请求本地树莓派解析，在返回结果 23333
