### ISSUE TITLE
request error: connection refused

### ISSUE THREAD

**Issue by w311ang** [iawia002/annie#696]
* Termux
```console
$ ./annie -i -d https://v.qq.com/x/cover/ctfk6qw188z0kcw/d002448ref9.html

annie: version 0.10.0, A fast, simple and clean video downloader.

Downloading https://v.qq.com/x/cover/ctfk6qw188z0kcw/d002448ref9.html error:
request error: Get http://vv.video.qq.com/getinfo?otype=json&platform=11&defnpayver=1&appver=3.2.19.333&defn=shd&vid=d002448ref9: dial tcp: lookup vv.video.qq.com on [::1]:53: read udp [::1]:58270->[::1]:53: read: connection refused
```

**Comment by w311ang** [comment]
![Screenshot_2020-05-30-11-21-40](https://user-images.githubusercontent.com/30381083/83318472-c2197180-a267-11ea-8f21-c1b4a4712840.png)
复制到浏览器是可以打开的

**Comment by w311ang** [comment]
结案，需要以chroot权限运行

**Comment by w311ang** [comment]
目前已尝试安装`wget`、`golang`

**Comment by w311ang** [comment]
https://github.com/termux/termux-app/issues/1138#issuecomment-493976000

**Comment by DoveBoy** [comment]
同样的问题，使用termux-chroot命令后进入root环境下，annie依旧报错，错误是一样的

**Comment by w311ang** [comment]
> 同样的问题，使用termux-chroot命令后进入root环境下，annie依旧报错，错误是一样的

resolv-conf

**Comment by DoveBoy** [comment]
> `pkg install resolv-conf`

安装完以后，`termux-chroot`进入root模式后，annie下载没有任何反应，是缺少什么操作吗？

**Comment by w311ang** [comment]
> > `pkg install resolv-conf`
> 
> 安装完以后，`termux-chroot`进入root模式后，annie下载提示`read connection time out`，是缺少什么操作吗？

是下载的油管视频吗，那也许需要挂梯？

**Comment by DoveBoy** [comment]
> 是下载的油管视频吗，那也许需要挂梯？

尝试下载bilibili视频出现的这个错误，可能网络问题，后来正常了
