### ISSUE TITLE
新版本不能下载爱奇艺的1080p了啊

### ISSUE THREAD

**Issue by RicardoQ404** [iawia002/annie#705]
非会员专享的视频上一个版本还能下载1080p，更新以后虽然进度条跑完了但是最后只留下一个f4v格式的开头六分钟。我又换回上一个版本下载的mp4格式，希望可以修复一下。另外还有没有可能重新支持cookie下载爱奇艺vip视频啊？

**Comment by iawia002** [comment]
应该和 #700 是一个问题，试试 0.10.1
