### ISSUE TITLE
Archlinux Support 

### ISSUE THREAD

**Issue by joaquingx** [iawia002/annie#71]
Hello, 

I just wrote a package build for Archlinux(https://aur.archlinux.org/packages/annie/), maybe can be useful for archusers if you mention that in README/install

Regards,
Joaquin

**Comment by iawia002** [comment]
hey @joaquingx 
I'm not a archuser, so I don't know how this work on archlinux(how to install using this package), Can you tell me more information?

**Comment by nilsocket** [comment]
Aur is known as arch user repository, only selected applications will be available in arch main repository,
Arch main repository, provides binaries which are pre-compiled for different platform architectures.
Where as Aur, is another repository where anybody can write a pkgbuild (file, stating different configurations necessary for installation) and upload it to aur.
If any pkgbuild file is written, arch users can directly install it using yaourt(package management tool), or any other other tool.
pkgbuild is a file, which basically says run this command to build this source program and after making the binary place it under this location.
If some body uses go, then its simple to install.

But if a user don't know how to get source programs , or so or any general configuration of system.

He/She can just type `yaourt -S annie`, it will download and build and place it as per pkgbuild.
As `go get` is specific to go programs,
`pkgbuild` were specific to `arch`.

**Comment by iawia002** [comment]
@nilsocket thanks for the explain

How is the document written like this?

### yaourt (for Archlinux)
You can install annie easily via:
```
yaourt -S annie
```

**Comment by nilsocket** [comment]
No,
because yaourt is just one of the tools used for package management,
There were many other tools available.
You could just mention, something like this.

Arch Linux users can install latest version from [AUR](https://aur.archlinux.org/packages/annie).

**Comment by iawia002** [comment]
@nilsocket how about this:

### Install from [AUR](https://aur.archlinux.org/packages/annie) (for Archlinux)
You can install annie from [AUR](https://aur.archlinux.org/packages/annie) like this (If you use yaourt as your package manager):
```
yaourt -S annie
```

**Comment by nilsocket** [comment]
Arch Linux users are advanced Linux users, don't mention it that way.

Simply mention this package is available in AUR.
Almost every AUR-helper uses the same command line flags as that of Pacman.



Arch users like simplicity.

**Comment by iawia002** [comment]
@nilsocket thanks for your patient explanation. Are you interested in helping write this document?

**Comment by iawia002** [comment]
Thanks! Both of you

**Comment by iawia002** [comment]
It should work, but the go.test.sh is the file for ci, I don't know if it should be in the pkgbuild

**Comment by nilsocket** [comment]
No that isn't intended for that.

**Comment by joaquingx** [comment]
Ok, Thanks for the clarification!.
