### ISSUE TITLE
无法下载B站视频

### ISSUE THREAD

**Issue by netsonicyxf** [iawia002/annie#713]

**Comment by netsonicyxf** [comment]
比如：https://www.bilibili.com/video/BV1754y1Q73a

> E:\Program Files\Network\Annie>Annie https://www.bilibili.com/video/BV1754y1Q73a

 Site:      哔哩哔哩 bilibili.com
 Title:     钢管混凝土系杆拱桥分析要点说明-李兆阳
 Type:      video
 Stream:
     [80]  -------------------
     Quality:         高清 1080P
     Size:            745.85 MiB (782081067 Bytes)
     # download with: annie -f 80 ...

 0 B / 745.85 MiB [-------------------------------------------------------------------------------------------]   0.00%Downloading [36mhttps://www.bilibili.com/video/BV1754y1Q73a[0m error:
[31mhttp://cn-jsnt-dx-v-05.bilivideo.com/upgcxcode/35/11/197911135/197911135-1-80.flv?expires=1591761600&platform=pc&ssig=KLz3KYX3jqvlf-oCrIHg5A&oi=1918113120&trid=dd9ebc8daa764683ae4bde931fb12749&nfb=maPYqpoel5MI3qOUX6YpRA==&nfc=1&mid=0 request error: HTTP 454[0m

**Comment by sunrainxyz** [comment]
试了下，现在好像是下不了B站视频了

**Comment by iawia002** [comment]
先手动设置一下 referer https://github.com/iawia002/annie/issues/697#issuecomment-640325567
下个版本修
