### ISSUE TITLE
0.10.1 版本无法下载部分 B 站链接

### ISSUE THREAD

**Issue by vcheckzen** [iawia002/annie#716]
视频链接：
https://www.bilibili.com/video/BV13z411b77M?p=18

调试信息：

```bash
➜  LOGI annie.exe -d "https://www.bilibili.com/video/BV13z411b77M?p=18"

annie: version 0.10.1, A fast, simple and clean video downloader.


URL:         https://www.bilibili.com/video/BV13z411b77M?p=18
Method:      GET
Headers:     http.Header{
    "Accept-Language": {"en-US,en;q=0.8"},
    "Referer":         {"https://www.bilibili.com"},
    "User-Agent":      {"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/6
9.0.3497.81 Safari/537.36"},
    "Accept":          {"text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"},
    "Accept-Charset":  {"UTF-8,*;q=0.5"},
    "Accept-Encoding": {"gzip,deflate,sdch"},
}
Status Code: 200

URL:         https://interface.bilibili.com/v2/playurl?appkey=iVGUTjsxvpLeuDCf&cid=172854601&otype=json&qn=15&quality=15
&type=&sign=2d2a590c9e3888ee522a4ebd5c3f4843
Method:      GET
Headers:     http.Header{
    "Accept":          {"text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"},
    "Accept-Charset":  {"UTF-8,*;q=0.5"},
    "Accept-Encoding": {"gzip,deflate,sdch"},
    "Accept-Language": {"en-US,en;q=0.8"},
    "User-Agent":      {"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/6
9.0.3497.81 Safari/537.36"},
    "Referer":         {"https://www.bilibili.com"},
}
Status Code: 200
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/iawia002/annie/downloader.(*Downloader).Download(0xc0002064d0, 0xc000391c20, 0x0, 0x0)
        /Users/mac/iawia002/go/src/github.com/iawia002/annie/downloader/downloader.go:542 +0xd55
main.download(0xc0000182a0, 0x30, 0x2, 0x3)
        /Users/mac/iawia002/go/src/github.com/iawia002/annie/main.go:183 +0x51a
main.main()
        /Users/mac/iawia002/go/src/github.com/iawia002/annie/main.go:253 +0x274
```

浏览器打开最后一个链接返回如下：

```json
{"code":10004,"result":"error","message":"Video is hidden."}
```

**Comment by vcheckzen** [comment]
经测试下面的 API 可以获取下载链接，建议作者添加进去，演示如下：
https://api.bilibili.com/x/player/playurl?bvid=BV13z411b77M&cid=172854601&qn=80

**Comment by sorakirahk** [comment]
建议换用you-get
之前用annie部分番剧直接报错
https://github.com/iawia002/annie/issues/678
换用you-get后一切正常
包括你出问题的这个

**Comment by athrunsun** [comment]
@sorakirahk 我用you-get下载 https://www.bilibili.com/video/BV1H7411y7Hh 报错说 "Unsupported URL pattern" 呢？

**Comment by sorakirahk** [comment]
> @sorakirahk 我用you-get下载 https://www.bilibili.com/video/BV1H7411y7Hh 报错说 "Unsupported URL pattern" 呢？

不知道是不是annie现在还不支持新的BV号，用you-get能正常下载你给的这个视频

**Comment by athrunsun** [comment]
> > @sorakirahk 我用you-get下载 https://www.bilibili.com/video/BV1H7411y7Hh 报错说 "Unsupported URL pattern" 呢？
> 
> 不知道是不是annie现在还不支持新的BV号，用you-get能正常下载你给的这个视频

可以给我下你用的命令行吗？谢谢。

**Comment by sorakirahk** [comment]
> > > @sorakirahk 我用you-get下载 https://www.bilibili.com/video/BV1H7411y7Hh 报错说 "Unsupported URL pattern" 呢？
> > 
> > 
> > 不知道是不是annie现在还不支持新的BV号，用you-get能正常下载你给的这个视频
> 
> 可以给我下你用的命令行吗？谢谢。

you-get不是annie里的功能，是另一个人写的下载器
https://github.com/soimort/you-get

**Comment by athrunsun** [comment]
> > > > @sorakirahk 我用you-get下载 https://www.bilibili.com/video/BV1H7411y7Hh 报错说 "Unsupported URL pattern" 呢？
> > > 
> > > 
> > > 不知道是不是annie现在还不支持新的BV号，用you-get能正常下载你给的这个视频
> > 
> > 
> > 可以给我下你用的命令行吗？谢谢。
> 
> you-get不是annie里的功能，是另一个人写的下载器
> https://github.com/soimort/you-get

我知道，你是这样下的吗：`you-get https://www.bilibili.com/video/BV1H7411y7Hh`

**Comment by sorakirahk** [comment]
> > > > > @sorakirahk 我用you-get下载 https://www.bilibili.com/video/BV1H7411y7Hh 报错说 "Unsupported URL pattern" 呢？
> > > > 
> > > > 
> > > > 不知道是不是annie现在还不支持新的BV号，用you-get能正常下载你给的这个视频
> > > 
> > > 
> > > 可以给我下你用的命令行吗？谢谢。
> > 
> > 
> > you-get不是annie里的功能，是另一个人写的下载器
> > https://github.com/soimort/you-get
> 
> 我知道，你是这样下的吗：`you-get https://www.bilibili.com/video/BV1H7411y7Hh`

对，直接用这个命令下的
你那边不行吗？

**Comment by athrunsun** [comment]
> > > > > > @sorakirahk 我用you-get下载 https://www.bilibili.com/video/BV1H7411y7Hh 报错说 "Unsupported URL pattern" 呢？
> > > > > 
> > > > > 
> > > > > 不知道是不是annie现在还不支持新的BV号，用you-get能正常下载你给的这个视频
> > > > 
> > > > 
> > > > 可以给我下你用的命令行吗？谢谢。
> > > 
> > > 
> > > you-get不是annie里的功能，是另一个人写的下载器
> > > https://github.com/soimort/you-get
> > 
> > 
> > 我知道，你是这样下的吗：`you-get https://www.bilibili.com/video/BV1H7411y7Hh`
> 
> 对，直接用这个命令下的
> 你那报错吗？

是的。不过我突然想到一个问题——我已经很久没升级过you-get的版本了。。。我先升级再试试。

**Comment by iawia002** [comment]
Try [0.10.3](https://github.com/iawia002/annie/releases/tag/0.10.3)
