### ISSUE TITLE
求助，annie下载YouTube视频时出现请求错误怎么解决？

### ISSUE THREAD

**Issue by cutecutebuild** [iawia002/annie#718]
annie -d https://www.youtube.com/watch?v=HtcBPBgI-J0

debug msg：
{"level":"debug","time":"2020-06-18T16:40:25+08:00","message":"Fetching https://www.youtube.com/watch?v=HtcBPBgI-J0"}
Downloading https://www.youtube.com/watch?v=HtcBPBgI-J0 error:
**request failed: &{%!w(string=Get) %!w(string=https://www.youtube.com/watch?v=HtcBPBgI-J0) %!w(*net.OpError=&{dial tcp <nil> 0xc0001de0c0 0xaafac0})}**

any idea？

annie: version 0.9.8, A fast, simple and clean video downloader.

**Comment by john-black-3k** [comment]
Try version 0.10.1

**Comment by Half9000** [comment]
Try set proxy.
With version 0.10.1, I am able to download the video from this URL.

**Comment by shiqqJOY** [comment]
just upgrade version ， ok！3Q
