### ISSUE TITLE
反馈一个问题

### ISSUE THREAD

**Issue by GJF2015** [iawia002/annie#719]
当我通过Telnet的方式连接远程计算机时，使用Annie下载视频，能创建下载任务，但是不走进度条，一直停留在0%。

![image](https://user-images.githubusercontent.com/46737995/85188641-d71f7880-b2da-11ea-98b4-cd9797847a2e.png)

**Comment by iawia002** [comment]
Try [0.10.2](https://github.com/iawia002/annie/releases/tag/0.10.2)
