### ISSUE TITLE
B站视频下载不了,尝试过多次

### ISSUE THREAD

**Issue by JoinGitHub427** [iawia002/annie#722]
```
PS C:\Users\anqa> annie -f 16 https://www.bilibili.com/video/BV1tC4y1a7EH

 Site:      哔哩哔哩 bilibili.com
 Title:     如果你见到一坨富得流油的发网菌，会不会想吃了它
 Type:      video
 Stream:
     [16]  -------------------
     Quality:         流畅 360P
     Size:            5.81 MiB (6092948 Bytes)
     # download with: annie -f 16 ...

 0 B / 5.81 MiB [---------------------------------------------------------------------------------------------]   0.00%Downloading [36mhttps://www.bilibili.com/video/BV1tC4y1a7EH[0m error:
[31mhttp://cn-jxnc-cmcc-bcache-12.bilivideo.com/upgcxcode/35/22/199432235/199432235-1-16.mp4?e=ig8euxZM2rNcNbRMhbUVhoM17wNBhwdEto8g5X10ugNcXBlqNxHxNEVE5XREto8KqJZHUa6m5J0SqE85tZvEuENvNC8xNEVE9EKE9IMvXBvE2ENvNCImNEVEK9GVqJIwqa80WXIekXRE9IMvXBvEuENvNCImNEVEua6m2jIxux0CkF6s2JZv5x0DQJZY2F8SkXKE9IB5QK==&deadline=1592936558&gen=playurl&nbs=1&oi=3746194221&os=bcache&platform=pc&trid=09bcaf69a15347fe96c986cb55c5866b&uipk=5&upsig=68e79e08fb1052aa05099242468bb86c&uparams=e,deadline,gen,nbs,oi,os,platform,trid,uipk&mid=0 request error: HTTP 403[0m
PS C:\Users\anqa>
```
#338 似乎也是类似的问题，“你网络有问题吧，重试一下”并不能解决问题啊！！

网络问题怎么解决呢？求方法，求步骤

**Comment by inoton** [comment]
可能不是网络问题，我这边也不能下载。

**Comment by inoton** [comment]
可能不是网络问题，我这边也不能下载
备注：Win10 64位系统，annie.exe为64位版，程序路径全英文，，已经annie.exe将手动添加到系统防火墙

`PS E:\Downloads\Softs\annie> .\annie.exe https://www.bilibili.com/video/av37356097

 Site:      哔哩哔哩 bilibili.com
 Title:     【嘻咦啊看】你偷看过别人的日记吗？
 Type:      video
 Stream:
     [64]  -------------------
     Quality:         高清 720P
     Size:            313.97 MiB (329220724 Bytes)
     # download with: annie -f 64 ...

 0 B / 313.97 MiB [-------------------------------------------------------------------------------------------]   0.00%Downloading [36mhttps://www.bilibili.com/video/av37356097[0m error:
[31mhttp://cn-hbsjz2-cmcc-bcache-07.bilivideo.com/upgcxcode/00/72/65657200/65657200-1-64.flv?e=ig8euxZM2rNcNbTj7WdVhoMj7bUVhwdEto8g5X10ugNcXBlqNxHxNEVE5XREto8KqJZHUa6m5J0SqE85tZvEuENvNC8xNEVE9EKE9IMvXBvE2ENvNCImNEVEK9GVqJIwqa80WXIekXRE9IMvXBvEuENvNCImNEVEua6m2jIxux0CkF6s2JZv5x0DQJZY2F8SkXKE9IB5QK==&deadline=1592965967&gen=playurl&nbs=1&oi=1880383930&os=bcache&platform=pc&trid=6a2dfe4c344b4c1aa478c8ad9b9cf755&uipk=5&upsig=b1681a0be6f3ef01e4308ce114065f97&uparams=e,deadline,gen,nbs,oi,os,platform,trid,uipk&mid=0 request error: HTTP 403[0m`

**Comment by iawia002** [comment]
Try [0.10.2](https://github.com/iawia002/annie/releases/tag/0.10.2)
