### ISSUE TITLE
B站VIP视频下载不了，加了cookie也不行，如何

### ISSUE THREAD

**Issue by DemonFriend** [iawia002/annie#734]

**Comment by Half9000** [comment]
哪个链接？

**Comment by DemonFriend** [comment]
随便一个电影




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"HALF9000"<notifications@github.com&gt;;
发送时间:&nbsp;2020年7月7日(星期二) 晚上10:54
收件人:&nbsp;"iawia002/annie"<annie@noreply.github.com&gt;;
抄送:&nbsp;"六日喜之郎"<522884136@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [iawia002/annie] B站VIP视频下载不了，加了cookie也不行，如何 (#734)





 
哪个链接？

**Comment by Half9000** [comment]
```
annie.exe -i -c cookies.txt https://www.bilibili.com/bangumi/play/ep280975
 Site:      哔哩哔哩 bilibili.com
 Title:     哈利·波特与魔法石
 Type:      video
 Streams:   # All available quality
     [112]  -------------------
     Quality:         高清 1080P+
     Size:            6337.25 MiB (6645089105 Bytes)
     # download with: annie -f 112 ...

     [80]  -------------------
     Quality:         高清 1080P
     Size:            2363.18 MiB (2477977654 Bytes)
     # download with: annie -f 80 ...

     [64]  -------------------
     Quality:         高清 720P
     Size:            1865.85 MiB (1956481175 Bytes)
     # download with: annie -f 64 ...

     [32]  -------------------
     Quality:         清晰 480P
     Size:            1054.07 MiB (1105271137 Bytes)
     # download with: annie -f 32 ...

     [16]  -------------------
     Quality:         流畅 360P
     Size:            479.79 MiB (503099987 Bytes)
     # download with: annie -f 16 ...
```
描述详细一点，如：系统环境，软件版本，以及最好输出 debug 信息（命令加入 -d 选项）。

**Comment by DemonFriend** [comment]
win10，版本是GitHub上的最新版，-v输出这样的


D:\video&gt;annie -v
[36mannie[0m: version [34m0.10.2[0m, A fast, simple and clean video downloader.


cookie是用EditThisCookie插件导出的
加上cookie后输出


D:\video&gt;annie -d -i -c cookie.txt https://www.bilibili.com/bangumi/play/ss28746
[36mannie[0m: version [34m0.10.2[0m, A fast, simple and clean video downloader.
Downloading [36mhttps://www.bilibili.com/bangumi/play/ss28746[0m error:
[31mrequest error: Get https://www.bilibili.com/bangumi/play/ss28746: net/http: invalid header field value "[\r\n{\r\n&nbsp; &nbsp; \"domain\": \".bilibili.com\",\r\n&nbsp; &nbsp; \"expirationDate\":&nbsp;







------------------&nbsp;原始邮件&nbsp;------------------
发件人: "HALF9000"<notifications@github.com&gt;; 
发送时间: 2020年7月8日(星期三) 下午3:55
收件人: "iawia002/annie"<annie@noreply.github.com&gt;; 
抄送: "六日喜之郎"<522884136@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [iawia002/annie] B站VIP视频下载不了，加了cookie也不行，如何 (#734)





 annie.exe -i -c cookies.txt https://www.bilibili.com/bangumi/play/ep280975  Site:      哔哩哔哩 bilibili.com  Title:     哈利·波特与魔法石  Type:      video  Streams:   # All available quality      [112]  -------------------      Quality:         高清 1080P+      Size:            6337.25 MiB (6645089105 Bytes)      # download with: annie -f 112 ...      [80]  -------------------      Quality:         高清 1080P      Size:            2363.18 MiB (2477977654 Bytes)      # download with: annie -f 80 ...      [64]  -------------------      Quality:         高清 720P      Size:            1865.85 MiB (1956481175 Bytes)      # download with: annie -f 64 ...      [32]  -------------------      Quality:         清晰 480P      Size:            1054.07 MiB (1105271137 Bytes)      # download with: annie -f 32 ...      [16]  -------------------      Quality:         流畅 360P      Size:            479.79 MiB (503099987 Bytes)      # download with: annie -f 16 ...  
描述详细一点，如：系统环境，软件版本，以及最好输出 debug 信息（命令加入 -d 选项）。

**Comment by iawia002** [comment]
Try [0.10.3](https://github.com/iawia002/annie/releases/tag/0.10.3)
