### ISSUE TITLE
无法下载优酷1080p视频

### ISSUE THREAD

**Issue by netsonicyxf** [iawia002/annie#737]
https://v.youku.com/v_show/id_XMzkzMDIyMTE2NA==.html?spm=a2h3j.8428770.3416059.1
在线看有蓝光1080选项，但用-i参数，没有看到1080的，最高只有720.

**Comment by Half9000** [comment]
可以获取到，需要添加 Cookies。
`annie -c cookies.txt -i https://v.youku.com/v_show/id_XMzkzMDIyMTE2NA==.html`
```
 Site:      优酷 youku.com
 Title:     Dynamo实现对偏离中心线的TBM盾构隧道的纠偏2——纠偏优化
 Type:      video
 Streams:   # All available quality
     [mp4hd3v2]  -------------------
     Quality:         mp4hd3v2 1916x1040
     Size:            81.32 MiB (85268918 Bytes)
     # download with: annie -f mp4hd3v2 ...

     [mp4hd2v2]  -------------------
     Quality:         mp4hd2v2 1280x694
     Size:            56.03 MiB (58750902 Bytes)
     # download with: annie -f mp4hd2v2 ...

     [mp4hd]  -------------------
     Quality:         mp4hd 960x522
     Size:            29.24 MiB (30657487 Bytes)
     # download with: annie -f mp4hd ...

     [mp4sd]  -------------------
     Quality:         mp4sd 640x348
     Size:            14.71 MiB (15429134 Bytes)
     # download with: annie -f mp4sd ...

     [3gphd]  -------------------
     Quality:         3gphd 480x260
     Size:            8.46 MiB (8866155 Bytes)
     # download with: annie -f 3gphd ...
```

**Comment by qjsdtd** [comment]
请求指导如何获取cookie

**Comment by Half9000** [comment]
> 请求指导如何获取cookie

Chrome 浏览器可以使用 [EditThisCookies](https://chrome.google.com/webstore/detail/editthiscookie/fngmhnnpilhplaeedifhccceomclgfbg)，或者 [cookies.txt](https://chrome.google.com/webstore/detail/cookiestxt/njabckikapfpffapmjgojcnbfjonfjfg) 等插件。插件商店还有很多类似的，搜一下就行。
其他浏览器不清楚，应该也有同样的插件。

**Comment by qjsdtd** [comment]
感谢您的耐心解答。全部导出并另存成cookies.txt 在程序中-c就可以直接使用吗，需要进行筛选处理或格式变更吗？

**Comment by netsonicyxf** [comment]
> > 请求指导如何获取cookie
> 
> Chrome 浏览器可以使用 [EditThisCookies](https://chrome.google.com/webstore/detail/editthiscookie/fngmhnnpilhplaeedifhccceomclgfbg)，或者 [cookies.txt](https://chrome.google.com/webstore/detail/cookiestxt/njabckikapfpffapmjgojcnbfjonfjfg) 等插件。插件商店还有很多类似的，搜一下就行。
> 其他浏览器不清楚，应该也有同样的插件。

感谢帮助！
