### ISSUE TITLE
优酷番剧一拳超人下载操作求解

### ISSUE THREAD

**Issue by kevinxYaoJiu** [iawia002/annie#738]
不知道是不是因为独播的原因，下载视频会中途中断，实际视频只有几分钟的内容而且清晰度也是很低的
我看介绍说VIP视频也可以下载，就想试试下个独播，结果可能因为自己不会设置那个什么ccode所以下不了
https://v.youku.com/v_show/id_XMTM1MTc4MDU3Ng==.html?spm=a2h0c.8166622.PhoneSokuProgramSeries_2.dposter_1

**Comment by Half9000** [comment]
新版优酷的视频基本都有加上他家自己的 DRM，目前我知道的办法是通过网页端获取解密的 key，然后在本地用工具解密。

**Comment by kevinxYaoJiu** [comment]
原来是这样，谢谢你的讲解
