### ISSUE TITLE
下载腾讯视频出现403

### ISSUE THREAD

**Issue by rchdliang** [iawia002/annie#745]
![image](https://user-images.githubusercontent.com/67943933/87324570-db018c00-c562-11ea-81e8-1c2b3c689388.png)
命令行是：annie.exe -o %dlpath% %URL% -f 128 -n 1
更新了annie.exe下载了两个腾讯的视频之后就这样了
bilibili什么的都能正常下载
求解答

**Comment by Half9000** [comment]
建议使用最新的代码构建应用：
```
annie.exe https://v.qq.com/x/page/w09305h548y.html

 Site:      腾讯视频 v.qq.com
 Title:     双语字幕TED演讲：迷茫的时候，如何重置自己的人生？
 Type:      video
 Stream:
     [shd]  -------------------
     Quality:         超清;(720P)
     Size:            65.88 MiB (69078188 Bytes)
     # download with: annie -f shd ...

 65.88 MiB / 65.88 MiB [========================================================================] 100.00% 9.49 MiB/s 6s
Merging video parts into 双语字幕TED演讲：迷茫的时候，如何重置自己的人生？.mp4
```
![image](https://user-images.githubusercontent.com/26613789/87446008-5595de80-c62b-11ea-9cf6-3c8fbf7ee806.png)
**PS:** 提问最好把相应的链接完整的给出，给张图不管是OCR或者手敲都挺麻烦的。

**Comment by rchdliang** [comment]
> 建议使用最新的代码构建应用：
> 
> ```
> annie.exe https://v.qq.com/x/page/w09305h548y.html
> 
>  Site:      腾讯视频 v.qq.com
>  Title:     双语字幕TED演讲：迷茫的时候，如何重置自己的人生？
>  Type:      video
>  Stream:
>      [shd]  -------------------
>      Quality:         超清;(720P)
>      Size:            65.88 MiB (69078188 Bytes)
>      # download with: annie -f shd ...
> 
>  65.88 MiB / 65.88 MiB [========================================================================] 100.00% 9.49 MiB/s 6s
> Merging video parts into 双语字幕TED演讲：迷茫的时候，如何重置自己的人生？.mp4
> ```
> 
> ![image](https://user-images.githubusercontent.com/26613789/87446008-5595de80-c62b-11ea-9cf6-3c8fbf7ee806.png)
> **PS:** 提问最好把相应的链接完整的给出，给张图不管是OCR或者手敲都挺麻烦的。

感谢！

**Comment by rchdliang** [comment]
腾讯的视频分成N段，因此用fvd idm一类的软件下载分片再合并实在是麻烦。希望大佬能提供一个解决方案。
感激不尽！

**Comment by Half9000** [comment]
基于**最新的代码**构建 annie, release 及其它包管理的 0.10.2 版本应该不是基于最新提交的代码构建。

**Comment by netsonicyxf** [comment]
> 建议使用最新的代码构建应用：
> 
> ```
> annie.exe https://v.qq.com/x/page/w09305h548y.html
> 
>  Site:      腾讯视频 [v.qq.com](http://v.qq.com)
>  Title:     双语字幕TED演讲：迷茫的时候，如何重置自己的人生？
>  Type:      video
>  Stream:
>      [shd]  -------------------
>      Quality:         超清;(720P)
>      Size:            65.88 MiB (69078188 Bytes)
>      # download with: annie -f shd ...
> 
>  65.88 MiB / 65.88 MiB [========================================================================] 100.00% 9.49 MiB/s 6s
> Merging video parts into 双语字幕TED演讲：迷茫的时候，如何重置自己的人生？.mp4
> ```
> 
> ![image](https://user-images.githubusercontent.com/26613789/87446008-5595de80-c62b-11ea-9cf6-3c8fbf7ee806.png)
> **PS:** 提问最好把相应的链接完整的给出，给张图不管是OCR或者手敲都挺麻烦的。

用0.10.2下还是出错：

> E:\Program Files\Network\Annie>annie.exe https://v.qq.com/x/page/w09305h548y.html
Downloading [36mhttps://v.qq.com/x/page/w09305h548y.html[0m error:
[31mhttp://video.dispatch.tc.qq.com/uwMROfz2r5zAoaQXGdGnCGdfJ6mqOYqku5Lz7Yyh2XQIczxI/w09305h548y.m701.mp4?vkey=8D11B061BDCA2624BC37D2537C531AF7153AC8345D3EFF849545E6B569C520F77EEE833CAC846CAEEA217EC6FB95FA017CC8835A2770976B0F2D26F7489C67358CDC9F1EDB07F3D99DF10CE749D9042EEF79A07716E667060B3EB1AA21B184857B44297C69807EC9AADDDC09F7796557 request error: HTTP 403[0m

**Comment by iawia002** [comment]
Try [0.10.3](https://github.com/iawia002/annie/releases/tag/0.10.3)

**Comment by snylonue** [comment]
```
annie -i -d "https://v.qq.com/x/page/x0017evzp6n.html"

[36mannie[0m: version [34m0.10.3[0m, A fast, simple and clean video downloader.


URL:         http://vv.video.qq.com/getinfo?otype=json&platform=11&defnpayver=1&appver=3.2.19.333&defn=shd&vid=x0017evzp6n
Method:      GET
Headers:     http.Header{
    "Accept":          {"text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"},
    "Accept-Charset":  {"UTF-8,*;q=0.5"},
    "Accept-Encoding": {"gzip,deflate,sdch"},
    "Accept-Language": {"en-US,en;q=0.8"},
    "User-Agent":      {"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.81 Safari/537.36"},
    "Referer":         {"https://v.qq.com/x/page/x0017evzp6n.html"},
}
Status Code: 200

URL:         http://vv.video.qq.com/getinfo?otype=json&platform=11&defnpayver=1&appver=3.2.19.333&defn=sd&vid=x0017evzp6n
Method:      GET
Headers:     http.Header{
    "User-Agent":      {"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.81 Safari/537.36"},
    "Accept":          {"text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"},
    "Accept-Charset":  {"UTF-8,*;q=0.5"},
    "Accept-Encoding": {"gzip,deflate,sdch"},
    "Accept-Language": {"en-US,en;q=0.8"},
    "Referer":         {"http://video.dispatch.tc.qq.com/uwMROfz2r5zAoaQXGdGlUmdfIu1ZXFpZPvULc1o2XzF7QVKw/"},
}
Status Code: 200

URL:         http://vv.video.qq.com/getkey?otype=json&platform=11&appver=3.2.19.333&filename=x0017evzp6n.p1203.mp4&format=11203&vid=x0017evzp6n
Method:      GET
Headers:     http.Header{
    "User-Agent":      {"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.81 Safari/537.36"},
    "Referer":         {"http://vv.video.qq.com/getkey?otype=json&platform=11&appver=3.2.19.333&filename=x0017evzp6n.p1203.mp4&format=11203&vid=x0017evzp6n"},
    "Accept":          {"text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"},
    "Accept-Charset":  {"UTF-8,*;q=0.5"},
    "Accept-Encoding": {"gzip,deflate,sdch"},
    "Accept-Language": {"en-US,en;q=0.8"},
}
Status Code: 200
Downloading [36mhttps://v.qq.com/x/page/x0017evzp6n.html[0m error:
[31mhttp://video.dispatch.tc.qq.com/uwMROfz2r5zAoaQXGdGlUmdfIu1ZXFpZPvULc1o2XzF7QVKw/x0017evzp6n.p1203.mp4?vkey=8C624B3FCA6AD9457C06C5FAF7663C54B2A5B83928B784F1844978192DD74BCBD55FC39BCB1888F345E782B7C5DC9BA2EFC57AEC69399B75BDABD50EAA5B0F1FF3060D41117442BE4CE193A62CA933A537942CCA310FF0F892FFD85FB1C2028FF9FDFCA001B184F97BF44D5C507DAE29 request error: HTTP 403[0m
```
似乎还是没有修复
