### ISSUE TITLE
视频合并问题

### ISSUE THREAD

**Issue by Oall2810** [iawia002/annie#75]
刚开始没装FFmpeg,下了个电影,无法合并,就又去下载安装了FFmpeg,那时宿舍刚好断网,没网程序报错,不能合并已下载的视频

**Comment by iawia002** [comment]
别删已经下载的文件，有网的时候再下一次（已经下载的不会再下载，只是需要网络来校验），就会合并的

**Comment by iawia002** [comment]
有问题再回复，没有问题就把这个 issue 关了哦
