### ISSUE TITLE
0.10.3 bilibili 无法解析的视频

### ISSUE THREAD

**Issue by zz5678** [iawia002/annie#750]
偶然发现
```
https://www.bilibili.com/video/BV1Hx411U7xL?p=4

https://www.bilibili.com/video/BV1Hx411U7xL?p=6

https://www.bilibili.com/video/BV1Hx411U7xL?p=7

```
有时候还会有如下错误：
`Downloading https://www.bilibili.com/video/BV1Hx411U7xL?p=6 error:
request error: Get "": unsupported protocol scheme ""`

**Comment by iawia002** [comment]
@Half9000 take a look?

**Comment by zz5678** [comment]
啥？现在 github 主要 义工，都是刚毕业的大学生了么？哈哈～ 开个玩笑，不止这里，还有 v2fly

**Comment by Half9000** [comment]
最近社畜中，忙完这一阵我尽快看看。

**Comment by iawia002** [comment]
可以，有空我也看看

**Comment by zz5678** [comment]
确实可能是 b 站没有把全部视频都转到 dash api 上来，dash api 后面的 cdn 下载速度可以达到200兆，旧 api 能到10兆巅峰速度的都很少。b 站的技术也很烂，留不住人。穷，是唯一的问题

目前也是 ykdl + annie 双接口在用。

**Comment by zz5678** [comment]
今天再测，这几个都已经有 dash api 解析结果了。关了。

顺便扔一个 shell 脚本出来，可以用 annie 结果直接播放 dash api 的：
```bash
	all=$(annie -j $url | jq -r '.[0].streams|[.[]][-1]') # url 是 bili 链接，-1 取最高分辨率
	echo $all | jq -r '.quality'  #显示分辨率
	mp4=$(echo $all | jq -r '.parts[]|select (.ext=="mp4").url')
	m4a=$(echo $all | jq -r '.parts[]|select (.ext=="m4a").url')
	para="--referrer=${u} --audio-file=${m4a} ${mp4}"
	mpv $para &
```
