### ISSUE TITLE
segmentation violation while downloading a PDF file

### ISSUE THREAD

**Issue by eatmoresushi** [iawia002/annie#760]
Command used:
`annie https://yurichev.org/b564f46f1c207b2dbc84a2bd4a41ed4c/RE4B-CN-vol1.pdf`

Error code:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x14aa05d]

goroutine 1 [running]:
github.com/iawia002/annie/extractors.Extract(0x7ffeefbffaa6, 0x46, 0x0, 0x0, 0x0, 0x1, 0x0, 0xa, 0x0, 0x0, ...)
	github.com/iawia002/annie/extractors/extractors.go:104 +0x2fd
main.download(0x7ffeefbffaa6, 0x46, 0x1, 0x1)
	github.com/iawia002/annie/main.go:131 +0x18d
main.main()
	github.com/iawia002/annie/main.go:253 +0x285
```

**Comment by Half9000** [comment]
> Annie is a fast, simple and clean video downloader built with Go.
Annie is not an universal downloader. It only supports for downloading media files from some sites.

**Comment by eatmoresushi** [comment]
That’s totally fine. I report because the following statement.
> If Annie is provided the URL of a specific resource, then it will be downloaded directly:
