### ISSUE TITLE
bilibili download error

### ISSUE THREAD

**Issue by impossible98** [iawia002/annie#763]
```
annie -c .\bilibili.txt -i "https://www.bilibili.com/bangumi/play/ep206526"
Downloading https://www.bilibili.com/bangumi/play/ep206526 error:
request error: Get : unsupported protocol scheme ""
```

**Comment by Half9000** [comment]
Please try to build the application from the `master` branch of this repo.
I think this issue has been fixed in the latest commits.

**Comment by impossible98** [comment]
@Half9000 
```
annie -v
annie: version 0.10.3, A fast, simple and clean video downloader.
```

```

**Comment by Half9000** [comment]
Read the comment carefully. 
I said, 'build the application from the `master` branch with the latest commits'.  Not the latest release.

**Comment by impossible98** [comment]
@Half9000 
Oh my god. When will we release the new? Quick.
