### ISSUE TITLE
feature request: download video from multiple url

### ISSUE THREAD

**Issue by TonyStark** [iawia002/annie#77]
Feature request:
i have video.txt file which have several video link, so is this possible to download all of video in particular format?
something like..
> 
> cat video.txt
```video_link:format_which_i_want_to_download```
> http://videosite.comm/?watch?=klfjsldkf:1080p
> http://videosite.comm/?watch?=ddsfsdf:420p
> http://videosite.comm/?watch?=aedsfc:720p

**Comment by iawia002** [comment]
> download all video links in a file

I agree with this feature.

> http://videosite.comm/?watch?=aedsfc:720p

But this, I don't know, is this really necessary?

In my opinion, just normal video links, you can use `-f` to control the format (all video links download with the same format).

**Comment by TonyStark** [comment]
okay np about that particular format...

**Comment by iawia002** [comment]
Annie now supports multiple inputs, next step will support reading URLs from a file
https://github.com/iawia002/annie#multiple-inputs
