### ISSUE TITLE
Create a telegram group for developers, to communicate and for general questions.

### ISSUE THREAD

**Issue by nilsocket** [iawia002/annie#78]

**Comment by iawia002** [comment]
Sure, what's your telegram ID, I invite you

**Comment by iawia002** [comment]
oh, I found you, I have invited you to the group. I will mention it in README later.

https://t.me/anniedev

**Comment by nilsocket** [comment]
The reason I didn't yet give my name is, I lost that sim card, I need but
new one, with same number.
I will but it today.
