### ISSUE TITLE
部分bilibili视频解析不了

### ISSUE THREAD

**Issue by WXZNJS** [iawia002/annie#794]
Url:   https://b23.tv/BV1wi4y1u7kx

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x8b8265]

goroutine 1 [running]:
github.com/iawia002/annie/extractors.Extract(0x7fffd3562a7a, 0x1b, 0x0, 0x0, 0x0, 0x1, 0x0, 0xa, 0x0, 0x0, ...)
        /Users/mac/iawia002/go/src/github.com/iawia002/annie/extractors/extractors.go:104 +0x2f5
main.download(0x7fffd3562a7a, 0x1b, 0x2, 0x2)
        /Users/mac/iawia002/go/src/github.com/iawia002/annie/main.go:131 +0x18d
main.main()
        /Users/mac/iawia002/go/src/github.com/iawia002/annie/main.go:253 +0x26d

**Comment by awei78** [comment]
问题应该出在其为短链接格式上，测试其长链接https://www.bilibili.com/video/BV1wi4y1u7kx可被正常下载

**Comment by WXZNJS** [comment]
> 问题应该出在其为短链接格式上，测试其长链接https://www.bilibili.com/video/BV1wi4y1u7kx 可被正常下载

再麻烦问下，短链接怎么转长链接呢

**Comment by snylonue** [comment]
> 
> 
> > 问题应该出在其为短链接格式上，测试其长链接https://www.bilibili.com/video/BV1wi4y1u7kx 可被正常下载
> 
> 再麻烦问下，短链接怎么转长链接呢

点开链接应该会跳转到长链接

**Comment by shawn8888** [comment]
我还发现一个小问题，如果链接当中带个/s，就无法解析，比如：
`https://www.bilibili.com/s/video/BV1c541177sZ`
把/s去掉就可以。比如上面的链接改成
`https://www.bilibili.com/video/BV1c541177sZ`
