### ISSUE TITLE
视频本身可以播放 1080P 的，但是实际下载的清晰度里面最高却只有 360P，能否直接下载到 1080P 的？

### ISSUE THREAD

**Issue by bszhct** [iawia002/annie#802]
annie -c cookie/yk.txt -i https://v.youku.com/v_show/id_XNDY4MDQwMjY0MA\=\=.html\?spm\=a2h0c.8166622.PhoneSokuProgram_1.dselectbutton_1\&showid\=dfee54c74cc240e7ba04
2020/10/12 01:46:02 net/http: invalid byte '"' in Cookie.Value; dropping invalid bytes

 Site:      优酷 youku.com
 Title:     琉璃 01
 Type:      video
 Streams:   # All available quality
     [mp4hd]  -------------------
     Quality:         mp4hd 960x540
     Size:            304.04 MiB (318807282 Bytes)
     # download with: annie -f mp4hd ...

     [mp4sd]  -------------------
     Quality:         mp4sd 640x360
     Size:            167.57 MiB (175706372 Bytes)
     # download with: annie -f mp4sd ...

     [3gphd]  -------------------
     Quality:         3gphd 480x270
     Size:            84.86 MiB (88982458 Bytes)
     # download with: annie -f 3gphd ...

**Comment by bszhct** [comment]
@iawia002 大佬有空给看下嘛？

**Comment by shuangye** [comment]
我也遇到这个问题了，我想下载 1080p HDR 版本的。
