### ISSUE TITLE
希望通过ffmpeg合成时能够调用独立显卡

### ISSUE THREAD

**Issue by HXHGTS** [iawia002/annie#819]
可以考虑在后期版本中支持nvidia和amd独立显卡参与ffmpeg的视频拼合过程吗？纯CPU感觉好慢，尤其是拼合大电影的时候，如果能让独显参与视频拼合过程就好了

**Comment by SeaHOH** [comment]
换 SSD 才能提高拼接速度。

**Comment by HXHGTS** [comment]
ffmpeg拼接默认调用的是CPU算力，但在有独立显卡的电脑上这样做有点浪费显卡算力，可以考虑添加一个参数比如--cpu-encoder --nv-encoder --amd-encoder这样的，允许用户强制调用独显加速，而且在annie调用ffmpeg将mkv或者webm转为mp4时这种情况时性能差距就更加明显了

**Comment by SeaHOH** [comment]
拼接不是转化，用再好的显卡也没用，瓶颈是硬盘。

**Comment by Nathaniel-Wu** [comment]
utils/ffmpeg.go里面可以看到拼接用的是`-c copy`，没有编码，直接复制，这已经是最快的了，近似文件复制速度
