### ISSUE TITLE
爱奇艺视频下载bug

### ISSUE THREAD

**Issue by jackychao0226** [iawia002/annie#82]
http://m.iqiyi.com/v_19rrnnoyps.html#vfrm=30-28-15-7
以前用you-get也不行，总是下载一段就错误中断

**Comment by iawia002** [comment]
```
annie http://m.iqiyi.com/v_19rrnnoyps.html\#vfrm\=30-28-15-7

 Site:      爱奇艺 iqiyi.com
 Title:     韩版隐藏的歌手第1季：隐藏的歌手之赵冠宇被模唱者震撼 遗憾错过节拍
 Type:      video
 Stream:
     [default]  -------------------
     Quality:         1280x720
     Size:            895.58 MiB (939085944 Bytes)
     # download with: annie -f default "URL"

 43.66 MiB / 895.58 MiB [=>---------------------------]   4.87% 5.63 MiB/s 2m30s
```

我试了一小段，没问题啊，你具体什么问题，你说详细一点

尝试更新一下新版本看能不能解决，现在是 0.6.4

**Comment by iawia002** [comment]
我没问题

> unexpected EOF

为什么会出现这个我现在不清楚

> read tcp 192.168.1.105:56509->211.151.156.199:80: wsarecv: An existing conection was forcibly closed by the remote host.

这个应该是你网络问题吧

**Comment by iawia002** [comment]
@jackychao0226 你下其他爱奇艺视频有没有问题

**Comment by jackychao0226** [comment]
有，而且发现优酷也有一样的问题，bilibili没有

**Comment by jackychao0226** [comment]
C:\Users\zhang>annie -o "c:\Users\zhang\Downloads\annie" https://www.bilibili.com/bangumi/play/ep173380

 Site:      哔哩哔哩 bilibili.com
 Title:     戒律的复活：第3话 神器 失落灾厄
 Type:      video
 Stream:
     [default]  -------------------
     Quality:         高清 1080P
     Size:            351.93 MiB (369026820 Bytes)
     # download with: annie -f default "URL"

 351.93 MiB / 351.93 MiB [===================================================================] 100.00% 1.27 MiB/s 4m37s
Merging video parts into c:\Users\zhang\Downloads\annie\戒律的复活：第3话 神器 失落灾厄.mp4

C:\Users\zhang>annie -o "c:\Users\zhang\Downloads\annie" http://v.youku.com/v_show/id_XMTQ2NTc4MTk1Ng==.html

 Site:      优酷 youku.com
 Title:     唐人街探案
 Type:      video
 Stream:
     [default]  -------------------
     Quality:         mp4hd3 1920x720
     Size:            2269.71 MiB (2379966165 Bytes)
     # download with: annie -f default "URL"

 88.19 MiB / 2.22 GiB [==>------------------------------------------------------------------]   3.89% 2.22 MiB/s 16m19s2018/04/02 21:03:02 Error while downloading: http://vali-dns.cp31.ott.cibntv.net/6781830A87C14271A381776868/0300803D1056B
4862F9B0805CF07DD587B39D7-A895-DA97-CFB3-71889A79A532.flv?ccode=0502&duration=146&expire=18000&psid=8d17e16b747de24599737b60e5a7639b&sp=&ups_client_netip=3afaac2d&ups_ts=1522674141&ups_userid=&utid=3RdJE7Ex3HcCATr6rC3zbnSk&vid=XMTQ2NTc4MTk1Ng%3D%3D&vkey=B269c81c4115c3e3574b8aabd8a18d170&s=eada7342708711e59e2a, unexpected EOF

**Comment by Tinywan** [comment]
爱奇艺有些下载成功，有些下载失败！
* 第一个是把所有的ts文件下载下来合并为一个mp4文件

**Comment by iawia002** [comment]
> 第一个是把所有的ts文件下载下来合并为一个mp4文件

对啊，下载完了把所有片段合成最终的视频

**Comment by iawia002** [comment]
下载失败的贴一下 debug 信息吧

**Comment by iawia002** [comment]
@Tinywan 
> Can't play this video

这个是爱奇艺接口报的错，它不让下这个

**Comment by iawia002** [comment]
@jackychao0226 你试试把临时文件全删了重新下呢

**Comment by Tinywan** [comment]
@iawia002 哈哈！下来研究下源码，挺感兴趣的

**Comment by jackychao0226** [comment]
@iawia002 试的时候一直都是清空文件夹重新下载的

**Comment by iawia002** [comment]
这个 unexpected EOF 的错应该是指这个 URL 实际大小和 Content-length 中的大小不一致，但是我又没有复现过[摊手]

**Comment by iawia002** [comment]
https://github.com/iawia002/annie/issues/108#issuecomment-381484524
@jackychao0226 现在可以指定下载线程数了，你试一下用很少的线程下载看会不会报错

https://github.com/iawia002/annie#multi-thread

**Comment by jackychao0226** [comment]
@iawia002 用两线程成功下下来一个，所以是这个问题？还有不好意思小白问一下升级命令应该是什么，每次我都删了重装

**Comment by iawia002** [comment]
可能试这个原因，你可以再试试下电影那种大文件

> 升级命令应该是什么，每次我都删了重装

现在只能删了重装，没有内置的升级，如果你是 mac 的话可以用 brew，或者直接 [`go get`](https://github.com/iawia002/annie#install-via-go-get)

**Comment by netlovehf** [comment]
you-get: [error] oops, something went wrong.
you-get: don't panic, c'est la vie. please try the following steps:
you-get:   (1) Rule out any network problem.
you-get:   (2) Make sure you-get is up-to-date.
you-get:   (3) Check if the issue is already known, on
you-get:         https://github.com/soimort/you-get/wiki/Known-Bugs
you-get:         https://github.com/soimort/you-get/issues
you-get:   (4) Run the command with '--debug' option,
you-get:       and report this issue with the full output.
