### ISSUE TITLE
bilibili/youtube都是报错no matches found

### ISSUE THREAD

**Issue by arthur-wxy** [iawia002/annie#835]
% annie -i https://www.youtube.com/watch?v=lq12qvI5Jfw
zsh: no matches found: https://www.youtube.com/watch?v=lq12qvI5Jfw

这是什么原因呢，麻烦大佬看下

**Comment by closetool** [comment]
你没翻墙? 我加了代理运行挺好
```
[closetool@closetool-desktop ~]$ http_proxy=127.0.0.1:8889 annie -i https://www.youtube.com/watch?v=lq12qvI5Jfw

 Site:      YouTube youtube.com
 Title:     200213 서영 SeoYoung 클락 Clock 'JOKER(달샤벳)' 4K 60P 직캠 @홍대 버스킹 by DaftTaengk
 Type:      video
 Streams:   # All available quality
     [315]  -------------------
     Quality:         1080p60 video/webm; codecs="vp9"
     Size:            124.94 MiB (131006978 Bytes)
     # download with: annie -f 315 ...

     [272]  -------------------
     Quality:         2160p60 video/webm; codecs="vp9"
     Size:            95.77 MiB (100423715 Bytes)
     # download with: annie -f 272 ...
...
```

**Comment by chichengsun** [comment]
> 你没翻墙? 我加了代理运行挺好
> 
> ```
> [closetool@closetool-desktop ~]$ http_proxy=127.0.0.1:8889 annie -i https://www.youtube.com/watch?v=lq12qvI5Jfw
> 
>  Site:      YouTube youtube.com
>  Title:     200213 서영 SeoYoung 클락 Clock 'JOKER(달샤벳)' 4K 60P 직캠 @홍대 버스킹 by DaftTaengk
>  Type:      video
>  Streams:   # All available quality
>      [315]  -------------------
>      Quality:         1080p60 video/webm; codecs="vp9"
>      Size:            124.94 MiB (131006978 Bytes)
>      # download with: annie -f 315 ...
> 
>      [272]  -------------------
>      Quality:         2160p60 video/webm; codecs="vp9"
>      Size:            95.77 MiB (100423715 Bytes)
>      # download with: annie -f 272 ...
> ...
> ```

请问一下，前面那个代理地址在哪儿看，我用的是V2ray

**Comment by closetool** [comment]
> > 你没翻墙? 我加了代理运行挺好
> > ```
> > [closetool@closetool-desktop ~]$ http_proxy=127.0.0.1:8889 annie -i https://www.youtube.com/watch?v=lq12qvI5Jfw
> > 
> >  Site:      YouTube youtube.com
> >  Title:     200213 서영 SeoYoung 클락 Clock 'JOKER(달샤벳)' 4K 60P 직캠 @홍대 버스킹 by DaftTaengk
> >  Type:      video
> >  Streams:   # All available quality
> >      [315]  -------------------
> >      Quality:         1080p60 video/webm; codecs="vp9"
> >      Size:            124.94 MiB (131006978 Bytes)
> >      # download with: annie -f 315 ...
> > 
> >      [272]  -------------------
> >      Quality:         2160p60 video/webm; codecs="vp9"
> >      Size:            95.77 MiB (100423715 Bytes)
> >      # download with: annie -f 272 ...
> > ...
> > ```
> 
> 请问一下，前面那个代理地址在哪儿看，我用的是V2ray

我使用了qv2ray界面, 如果你只使用v2ray, 在/etc/v2ray或者/usr/local/etc/v2ray下添加inbounds规则, 建议看文档

**Comment by chichengsun** [comment]
> > > 你没翻墙? 我加了代理运行挺好
> > > ```
> > > [closetool@closetool-desktop ~]$ http_proxy=127.0.0.1:8889 annie -i https://www.youtube.com/watch?v=lq12qvI5Jfw
> > > 
> > >  Site:      YouTube youtube.com
> > >  Title:     200213 서영 SeoYoung 클락 Clock 'JOKER(달샤벳)' 4K 60P 직캠 @홍대 버스킹 by DaftTaengk
> > >  Type:      video
> > >  Streams:   # All available quality
> > >      [315]  -------------------
> > >      Quality:         1080p60 video/webm; codecs="vp9"
> > >      Size:            124.94 MiB (131006978 Bytes)
> > >      # download with: annie -f 315 ...
> > > 
> > >      [272]  -------------------
> > >      Quality:         2160p60 video/webm; codecs="vp9"
> > >      Size:            95.77 MiB (100423715 Bytes)
> > >      # download with: annie -f 272 ...
> > > ...
> > > ```
> > 
> > 
> > 请问一下，前面那个代理地址在哪儿看，我用的是V2ray
> 
> 我使用了qv2ray界面, 如果你只使用v2ray, 在/etc/v2ray或者/usr/local/etc/v2ray下添加inbounds规则, 建议看文档

我使用的是windows，能发个文档链接吗，谢谢

**Comment by arthur-wxy** [comment]
> 你没翻墙? 我加了代理运行挺好
> 
> ```
> [closetool@closetool-desktop ~]$ http_proxy=127.0.0.1:8889 annie -i https://www.youtube.com/watch?v=lq12qvI5Jfw
> 
>  Site:      YouTube youtube.com
>  Title:     200213 서영 SeoYoung 클락 Clock 'JOKER(달샤벳)' 4K 60P 직캠 @홍대 버스킹 by DaftTaengk
>  Type:      video
>  Streams:   # All available quality
>      [315]  -------------------
>      Quality:         1080p60 video/webm; codecs="vp9"
>      Size:            124.94 MiB (131006978 Bytes)
>      # download with: annie -f 315 ...
> 
>      [272]  -------------------
>      Quality:         2160p60 video/webm; codecs="vp9"
>      Size:            95.77 MiB (100423715 Bytes)
>      # download with: annie -f 272 ...
> ...
> ```

我下载b站视频也要翻墙吗

**Comment by closetool** [comment]
> > 你没翻墙? 我加了代理运行挺好
> > ```
> > [closetool@closetool-desktop ~]$ http_proxy=127.0.0.1:8889 annie -i https://www.youtube.com/watch?v=lq12qvI5Jfw
> > 
> >  Site:      YouTube youtube.com
> >  Title:     200213 서영 SeoYoung 클락 Clock 'JOKER(달샤벳)' 4K 60P 직캠 @홍대 버스킹 by DaftTaengk
> >  Type:      video
> >  Streams:   # All available quality
> >      [315]  -------------------
> >      Quality:         1080p60 video/webm; codecs="vp9"
> >      Size:            124.94 MiB (131006978 Bytes)
> >      # download with: annie -f 315 ...
> > 
> >      [272]  -------------------
> >      Quality:         2160p60 video/webm; codecs="vp9"
> >      Size:            95.77 MiB (100423715 Bytes)
> >      # download with: annie -f 272 ...
> > ...
> > ```
> 
> 我下载b站视频也要翻墙吗

你只给了youtube, bilibili链接是哪个

**Comment by snylonue** [comment]
#483

**Comment by arthur-wxy** [comment]
> #483
> 加对引号应该就好了 ` annie -i "https://www.youtube.com/watch?v=lq12qvI5Jfw"`

雀食。
