### ISSUE TITLE
下载YouTube视频失败

### ISSUE THREAD

**Issue by chichengsun** [iawia002/annie#836]
请问下，这是什么原因
C:\Users\asus\Desktop>annie -i https://www.youtube.com/watch?v=8Q40vlfx9KI
Downloading https://www.youtube.com/watch?v=8Q40vlfx9KI error:
request failed: Get https://www.youtube.com/watch?v=8Q40vlfx9KI: dial tcp 216.58.200.238:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

**Comment by jeremyhuang123123** [comment]
一样的问题我这里

**Comment by misaka123456** [comment]
我也是报错，估计是youtube改规则了

**Comment by victor23d** [comment]
看起来像是网络问题

**Comment by chjiyun** [comment]
翻墙了也不行啊
