### ISSUE TITLE
Failed to download video from YouTube 

### ISSUE THREAD

**Issue by Anderson-Nino-Velasco** [iawia002/annie#839]
When I was trying to download a video from YouTube (https://www.youtube.com/watch?v=4iXenMW9nHA), the applications couldn't download:

`F:\ANV Programs\Apps\Annie>Annie https://www.youtube.com/watch?v=4iXenMW9nHA
{"level":"debug","time":"2020-12-09T23:25:41-05:00","message":"Unable to extract json from default url, trying embedded url"}
Downloading [36mhttps://www.youtube.com/watch?v=4iXenMW9nHA[0m error:
[31mError extracting sts from embedded url response[0m`

**Comment by john-black-3k** [comment]
Youtube made a few changes to video pages and so annie youtube extractor does not work anymore. Actually this error comes from the [ytdl](https://github.com/mihaiav/ytdl) library which annie uses to decipher video URLs. 

Until this is fixed use [youtubedr](https://github.com/kkdai/youtube):
```
youtubedr download https://www.youtube.com/watch?v=4iXenMW9nHA
```

**Comment by john-black-3k** [comment]
@iawia002 
When you have time, I would recommend switching from [https://github.com/mihaiav/ytdl](https://github.com/mihaiav/ytdl) to [https://github.com/kkdai/youtube](https://github.com/kkdai/youtube). The library offers Youtube URL decipher capability but the code is cleaner and is actively developed.

**Comment by 89z** [comment]
https://github.com/iawia002/annie/issues/815

https://github.com/iawia002/annie/issues/839
https://github.com/iawia002/annie/issues/841
https://github.com/iawia002/annie/issues/857

**Comment by 89z** [comment]
I have another option here:

https://github.com/89z/youtube

Example:

~~~
youtube -d https://www.youtube.com/watch?v=4iXenMW9nHA
~~~
