### ISSUE TITLE
youtube下载报错

### ISSUE THREAD

**Issue by sbw983** [iawia002/annie#841]
https://www.youtube.com/watch?v=iSJP53eA7D8

出错信息：
{"level":"debug","time":"2020-12-11T22:26:03+08:00","message":"Unable to extract json from default url, trying embedded url"}
Downloading https://www.youtube.com/watch?v=iSJP53eA7D8 error:
Error extracting sts from embedded url response

**Comment by victor23d** [comment]
我也是这个问题

**Comment by john-black-3k** [comment]
See #839.

**Comment by 89z** [comment]
https://github.com/iawia002/annie/issues/815
https://github.com/iawia002/annie/issues/839

https://github.com/iawia002/annie/issues/841
https://github.com/iawia002/annie/issues/857
