### ISSUE TITLE
你好，能分析一下这是什么问题吗？是被B站给屏蔽了吗？但是如果是浏览器访问的话不会有问题。

### ISSUE THREAD

**Issue by marchorse** [iawia002/annie#843]
Warning: Multi thread download is no longer supported by BiliBili, use single thread instead.
Downloading https://www.bilibili.com/video/BV1jv41147aK?spm_id_from=333.851.b_7265706f7274466972737431.8 error:
http://119-187-224-208.mcdn.bilivideo.cn:480/upgcxcode/40/64/267916440/267916440_nb2-1-30280.m4s?expires=1608291241&platform=pc&ssig=BMraj9UpBs3SDVX__ifROQ&oi=1033160474&trid=6beb454147ca4718b9e3c61c6bc52b65u&nfc=1&nfb=maPYqpoel5MI3qOUX6YpRA==&mcdnid=9000217&mid=489690390&orderid=0,3&agrr=1&logo=A0000100 request error: HTTP 400

**Comment by hcrgm** [comment]
我也遇到了这个问题，好像是请求方式的问题，应该是视频下载地址不接受HEAD请求方式，最近一个commit把获取文件大小的方法的请求方式由GET改成了HEAD，b站视频就无法下载了，用release版本就ok
