### ISSUE TITLE
mp4和m4a是分开下载的

### ISSUE THREAD

**Issue by hayuqing** [iawia002/annie#855]
下载下来的视频有2个文件，一个是mp4一个是m4a，以前不会出现这个问题

**Comment by darkerlight007** [comment]
不是会自己合并吗？你别着急呀

**Comment by C-Entropy** [comment]
装好ffmpeg，下载好后会自动调用ffmpeg合并。至于音视频分离，可能是视频网站的策略?

**Comment by giabsatoh** [comment]
i have this problem too. the audio and video files were downloaded separately regardless of whether it's a single video or the playlist download from b zhan. please advise.

**Comment by hayuqing** [comment]
I had solved this problem, What i did is update your   ffmpeg which will merage .mp4 and .m4a into  a mp4 file.   hope to helpful to you.
you can download ffmpeg from here : http://www.ffmpeg.org/


| |
Ha Yuqing
|
|
haha_hyq@163.com
|
签名由网易邮箱大师定制
在2021年1月22日 19:48，giabsatoh<notifications@github.com> 写道：

i have this problem too. the audio and video files were downloaded separately regardless of whether it's a single video or the playlist download from b zhan. please advise.

**Comment by hayuqing** [comment]
> I had solved this problem, What i did is update your ffmpeg which will merage .mp4 and .m4a into a mp4 file. hope to helpful to you. you can download ffmpeg from here : http://www.ffmpeg.org/ | | Ha Yuqing | | haha_hyq@163.com | 签名由网易邮箱大师定制 在2021年1月22日 19:48，giabsatoh<notifications@github.com> 写道： i have this problem too. the audio and video files were downloaded separately regardless of whether it's a single video or the playlist download from b zhan. please advise. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by hayuqing** [comment]
copy annie.exe and ffmpeg.exe into the C:\Windows\System32

**Comment by giabsatoh** [comment]
whoaa! it worked. thanks a lot really.
