### ISSUE TITLE
U管上视频下载不了

### ISSUE THREAD

**Issue by WittyHare** [iawia002/annie#857]
麻烦您看一下是怎么回事？
![image](https://user-images.githubusercontent.com/61578969/105948768-878e0000-60a6-11eb-82e7-6416675e1f9a.png)

**Comment by john-black-3k** [comment]
Please see #839.

**Comment by WittyHare** [comment]
知道了，谢谢！

**Comment by 89z** [comment]
https://github.com/iawia002/annie/issues/815
https://github.com/iawia002/annie/issues/839
https://github.com/iawia002/annie/issues/841

https://github.com/iawia002/annie/issues/857
