### ISSUE TITLE
抖音官方修改了逻辑，现在不再需要dytk了

### ISSUE THREAD

**Issue by LazzyFatty** [iawia002/annie#859]
分享一下思路，有时间的朋友可以写出代码来给作者pull一下
以视频https://v.douyin.com/JTBpb4L/为例
1.直接访问获得原始链接https://www.iesdouyin.com/share/video/6925270560700108032/?region=CN&mid=……（url中无关内容已省略）
2.取出videoID 6925270560700108032
3.拼接地址 https://www.iesdouyin.com/web/api/v2/aweme/iteminfo/?item_ids=6925270560700108032 访问后得到json
4.json中['item_list'][0]['video']['play_addr']['url_list'][0]为有水印地址 https://aweme.snssdk.com/aweme/v1/playwm/?video_id=v0d00f7b0000c0do1njj3ie1jhkhicfg&ratio=720p&line=0
5.将有水印地址中的playwm替换为play 即https://aweme.snssdk.com/aweme/v1/play/?video_id=v0d00f7b0000c0do1njj3ie1jhkhicfg&ratio=720p&line=0

**Comment by JeromeYangtao** [comment]
mark

**Comment by 7733012** [comment]
最后一步

好像规则变了吧，拿不到没有水印的地址了

有新的方法了吗

**Comment by LazzyFatty** [comment]
> 最后一步
> 
> 好像规则变了吧，拿不到没有水印的地址了
> 
> 有新的方法了吗

2021.7.30
刚刚测试
依然没问题

**Comment by q191995501** [comment]
mark

**Comment by iawia002** [comment]
https://github.com/iawia002/annie/pull/924
