### ISSUE TITLE
youtube certificate error

### ISSUE THREAD

**Issue by masayoshi-louis** [iawia002/annie#871]
x509: certificate is valid for *.facebook.com, *.facebook.net, *.fbcdn.net, *.fbsbx.com, *.m.facebook.com, *.messenger.com, *.xx.fbcdn.net, *.xy.fbcdn.net, *.xz.fbcdn.net, facebook.com, messenger.com, not www.youtube.com

**Comment by john-black-3k** [comment]
Please give more details about the command you are using and the exact error you are getting. What version of aniie do you use?

Please note that currently the youtube extractor does not work anymore. Please see #839 for details.
