### ISSUE TITLE
Youku issue help needed please

### ISSUE THREAD

**Issue by zed2021** [iawia002/annie#872]
annie https://v.youku.com/v_show/id_XNTEyOTUzOTYw.html?spm=a2h0c.8166622.PhoneSokuUgc_44.dtitle
Downloading https://v.youku.com/v_show/id_XNTEyOTUzOTYw.html?spm=a2h0c.8166622.PhoneSokuUgc_44.dtitle error:
客户端无权播放,201

how to get past this please

**Comment by zed2021** [comment]
@iawia002

**Comment by zed2021** [comment]
@iawia002 please help needed to get through on Mac

**Comment by john-black-3k** [comment]
I do not use Youku, but you can look at this issue here: #867.

**Comment by zed2021** [comment]
I do not know how to replace the code @john-black-3k 

> I do not use Youku, but you can look at this issue here: #867.

**Comment by john-black-3k** [comment]
The `README.md` contains info on this. Just use this command:
```
annie -ccode 0532 <youku_video_url>
```
I tested with the URL you provided and it worked.

**Comment by iawia002** [comment]
Updated in ffb34d810df408a4570ef6930813ca140a975011
