### ISSUE TITLE
youku download failed

### ISSUE THREAD

**Issue by AmyRose1288** [iawia002/annie#893]
C:\Users\Amy Rose\Desktop\工具包>annie.exe https://v.youku.com/v_show/id_XMTI2NzYzNDU2.html?spm=a2h0c.8166622.PhoneSokuThreeProgram_1.dposter_8&s=cc006a74962411de83b1
Downloading [36mhttps://v.youku.com/v_show/id_XMTI2NzYzNDU2.html?spm=a2h0c.8166622.PhoneSokuThreeProgram_1.dposter_8[0m error:
[31m客户端无权播放,201[0m
's' is not recognized as an internal or external command,
operable program or batch file.

**Comment by john-black-3k** [comment]
That URL does not seem to work anymore. Also see #872.

**Comment by AmyRose1288** [comment]
> That URL does not seem to work anymore. Also see #872.

thanks (that link only works in china mainland due to copyright problems)
