### ISSUE TITLE
release不再发布新版?怎么获取最新的二进制

### ISSUE THREAD

**Issue by HiColinn** [iawia002/annie#912]
我看到release页面最后发布的版本都是去年的了,如果电脑上没有Go get,怎么获取最新的二进制?要自己编译吗?
谢谢.

**Comment by iawia002** [comment]
你现在可以去 [Actions](https://github.com/iawia002/annie/actions/workflows/builder.yml) 页面找到最新的二进制，比如 https://github.com/iawia002/annie/actions/runs/1047923583 ，上面可以直接下载

**Comment by HiColinn** [comment]
> 你现在可以去 [Actions](https://github.com/iawia002/annie/actions/workflows/builder.yml) 页面找到最新的二进制，比如 https://github.com/iawia002/annie/actions/runs/1047923583 ，上面可以直接下载，后续也会发新版本的

谢谢
