### ISSUE TITLE
腾讯视频 VIP部份无法下载了~！

### ISSUE THREAD

**Issue by JohyC** [iawia002/annie#919]
以下是所使用的下载命令。
`
annie.exe -n 64 -c cookie.txt -i list.txt -o /d/Johy/Videos/风筝
`
[list.txt](https://github.com/iawia002/annie/files/6947303/list.txt)

vip视频部份下载报错
`Downloading https://v.qq.com/x/cover/o660llk6wfo7ncw/j00256zqohr.html error:
not pay`

**Comment by HXHGTS** [comment]
![image](https://user-images.githubusercontent.com/38959826/129473314-ad04bf7d-2c04-4bc3-b879-84e9bb5c66c9.png)
可以下载啊，看看设置是不是出问题了

**Comment by JohyC** [comment]
> ![image](https://user-images.githubusercontent.com/38959826/129473314-ad04bf7d-2c04-4bc3-b879-84e9bb5c66c9.png)
> 可以下载啊，看看设置是不是出问题了

第三集开始就没法下载了。1 2两集是不需要会员的。

**Comment by zhangguangtong** [comment]
打开对应的VIP视频。
然后按F12打开浏览器开发者工具，进入控制台 Console。
输入
document.cookie
控制台会输出cookie。
复制cookie，带引号。
然后重新下载。
annie -f fhd -c "<cookie>" <vip视频地址>

出现这种原因可能是非vip视频和vip视频的cookie不一样。

**Comment by JohyC** [comment]
> 打开对应的VIP视频。
> 然后按F12打开浏览器开发者工具，进入控制台 Console。
> 输入
> document.cookie
> 控制台会输出cookie。
> 复制cookie，带引号。
> 然后重新下载。
> annie -f fhd -c "cookie" <vip视频地址>
> 
> 出现这种原因可能是非vip视频和vip视频的cookie不一样。

这下可以了！没想到腾讯的cookie都要区分会员呀！
