### ISSUE TITLE
不知道这些算不算bug

### ISSUE THREAD

**Issue by lleeopen** [iawia002/annie#93]
![001](https://user-images.githubusercontent.com/35162785/38344767-e2fa0416-38bd-11e8-82f8-c26e4e5891e7.jpg)

**Comment by lleeopen** [comment]
F:\annie>annie https://www.bilibili.com/video/av21595634/
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/iawia002/annie/extractors/bilibili.Download(0xc042072030, 0x2a)
        /Users/mac/iawia002/go/src/github.com/iawia002/annie/extractors/bilibili/bilibili.go:131 +0x817
main.main()
        /Users/mac/iawia002/go/src/github.com/iawia002/annie/main.go:59 +0x511

B站视频不能下载吗，这是什么提示。

**Comment by lleeopen** [comment]
F:\annie>annie -i http://www.iqiyi.com/v_19rrfpwsq0.html

 Site:      爱奇艺 iqiyi.com
 Title:     齐木楠雄的灾难 第2季 第3集
 Type:      video
 Streams:   # All available quality
     [21]  -------------------
     Quality:         896x504
     Size:            125.57 MiB (131668620 Bytes)
     # download with: annie -f 21 "URL"

     [2]  -------------------
     Quality:         896x504
     Size:            118.05 MiB (123784276 Bytes)
     # download with: annie -f 2 "URL"

     [default]  -------------------
     Quality:         1280x720
     Size:            156.83 MiB (164444540 Bytes)
     # download with: annie -f default "URL"

     [4]  -------------------
     Quality:         1280x720
     Size:            188.12 MiB (197258812 Bytes)
     # download with: annie -f 4 "URL"

     [1]  -------------------
     Quality:         640x360
     Size:            71.13 MiB (74581480 Bytes)
     # download with: annie -f 1 "URL"

     [96]  -------------------
     Quality:         384x216
     Size:            34.72 MiB (36404508 Bytes)
     # download with: annie -f 96 "URL"

不能解析爱奇艺免费视频的1080P格式，还有合并完成的h265编码的视频，音频有顿挫感。

**Comment by lleeopen** [comment]
F:\annie>annie -f 4 http://www.iqiyi.com/v_19rr7ph8kw.html#vfrm=2-4-0-1

 Site:      爱奇艺 iqiyi.com
 Title:     反转人生
 Type:      video
 Stream:
     [4]  -------------------
     Quality:         1280x536
     Size:            976.19 MiB (1023607736 Bytes)
     # download with: annie -f 4 "URL"

 440.77 MiB / 976.19 MiB [==============================>-------------------------------------]  45.15% 12.62 MiB/s 42s2018/04/05 11:16:37 Error while downloading: http://dx.data.video.qiyi.com/videos/v0/20170831/4d/1b/e25f8dc64da5d41863dff7c559d0a761.ts?qdv=1&qypid=733646300_04022000001000000000_4&start=9462043&end=11643992&hsize=78356&tag=1&v=&contentlength=1315624&qd_uid=&qd_vip=0&qd_src=3_31_312&qd_tm=1522898162393&qd_ip=6550257a&qd_p=6550257a&qd_k=555b6554dcf713bbc783c91cdfd1da3b&sgti=&dfp=&qd_sc=ff43b71e71394410b4fc8977fab0fe71, unexpected EOF

一个电影下载到45%出错

**Comment by iawia002** [comment]
乱码可能是颜色显示的问题

B 站那个是 BUG，我尽快修复

爱奇艺 1080P 是会员专享吧，下一半和 #82 一样，现不知道明确原因

**Comment by lleeopen** [comment]
![qq 20180405130559](https://user-images.githubusercontent.com/35162785/38348055-1f63f628-38d2-11e8-9d84-a752e4db8ad4.jpg)
用那个猎影可以解析，1080P和4K，免费的视频

**Comment by iawia002** [comment]
B 站那个不是 BUG，这是番剧，你下 https://www.bilibili.com/bangumi/play/ep173260/ 这个地址，

**Comment by iawia002** [comment]
合并提示不知道什么意思，最后合并出来的文件有没有问题？

**Comment by lleeopen** [comment]
合并的文件没有问题，但是合并完成的h265编码的视频，音频听着有顿挫感，h264的没有问题。

**Comment by iawia002** [comment]
它原本的音频就是 h265 的吧

**Comment by lleeopen** [comment]
https://www.bilibili.com/bangumi/play/ep173260/ 确实能下载，B站不能支持这样的地址吗https://www.bilibili.com/video/av21595634/，https://www.bilibili.com/bangumi/play/ep173260/ 这样的地址是从转辑里播放的吧

**Comment by iawia002** [comment]
番剧地址必须和普通地址区分开，你最开始的那个地址也会跳转到 https://www.bilibili.com/bangumi/play/ep173260/ 的呀

**Comment by iawia002** [comment]
windows 命令行确实难用，GUI 现在没有计划。Lulu 和 Annie 是一样的，我没必要维护两个一样的工具

**Comment by lleeopen** [comment]
![qq 20180405132634](https://user-images.githubusercontent.com/35162785/38348530-fe48088c-38d4-11e8-83c0-efdd457b0175.jpg)
wwqlyparse有支持Lulu，看来以后Lulu没有更新了，Lulu某些方面比you-get好，遗憾了~~

**Comment by iawia002** [comment]
爱奇艺的问题 #82 里面要详细一些，我把这个关了
