### ISSUE TITLE
B站视频下载会出现错误

### ISSUE THREAD

**Issue by Faith-YSQ** [iawia002/annie#930]
Windows10
版本是0.11.0
链接是 https://www.bilibili.com/video/BV1cJ411h74g
错误信息如下
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/iawia002/annie/extractors/bilibili.genParts(0xc000517060, 0x40, 0xc00001c270, 0x2b, 0xc0001dad80, 0x0, 0x0, 0x6a80, 0x0)
        /Users/iawia002/go/src/github.com/iawia002/annie/extractors/bilibili/bilibili.go:79 +0x353
github.com/iawia002/annie/extractors/bilibili.bilibiliDownload(0xc00001c270, 0x2b, 0xc000400000, 0x1a81e, 0x0, 0x4d91829, 0x84bf249, 0xc00023de00, 0xc, 0x1, ...)
        /Users/iawia002/go/src/github.com/iawia002/annie/extractors/bilibili/bilibili.go:385 +0x70b
github.com/iawia002/annie/extractors/bilibili.extractNormalVideo(0xc00001c270, 0x2b, 0xc000400000, 0x1a81e, 0x0, 0x0, 0x0, 0x1, 0x0, 0x1, ...)
        /Users/iawia002/go/src/github.com/iawia002/annie/extractors/bilibili/bilibili.go:238 +0x778
github.com/iawia002/annie/extractors/bilibili.(*extractor).Extract(0x1c2a370, 0xc00001c270, 0x2b, 0x0, 0x0, 0x0, 0x1, 0x0, 0x1, 0x0, ...)
        /Users/iawia002/go/src/github.com/iawia002/annie/extractors/bilibili/bilibili.go:294 +0x25d
github.com/iawia002/annie/extractors.Extract(0xc00001c270, 0x2b, 0x0, 0x0, 0x0, 0x1, 0x0, 0xa, 0x0, 0x0, ...)
        /Users/iawia002/go/src/github.com/iawia002/annie/extractors/extractors.go:112 +0x37a
main.download(0xc000238c80, 0xc00001c270, 0x2b, 0x0, 0x0)
        /Users/iawia002/go/src/github.com/iawia002/annie/main.go:266 +0x3d8
main.main.func2(0xc000238c80, 0x0, 0x0)
        /Users/iawia002/go/src/github.com/iawia002/annie/main.go:235 +0x3fd
github.com/urfave/cli/v2.(*App).RunContext(0xc0000576c0, 0x183e4d0, 0xc000018150, 0xc00002c3e0, 0x2, 0x2, 0x0, 0x0)
        /Users/iawia002/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/app.go:322 +0x714
github.com/urfave/cli/v2.(*App).Run(...)
        /Users/iawia002/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/app.go:224
main.main()
        /Users/iawia002/go/src/github.com/iawia002/annie/main.go:254 +0x136f

**Comment by iawia002** [comment]
#933 已经修复了，可以 go get 下载最新的或者到 https://github.com/iawia002/annie/actions/runs/1202210886 这里面下载对应系统的 binary 文件来使用
