### ISSUE TITLE
优酷VIP用户如何下载VIP视频

### ISSUE THREAD

**Issue by xkser** [iawia002/annie#95]
我尝试把CKey换成vip用户的key。好像下载vip视频还是失败。能指导一下么

**Comment by iawia002** [comment]
不改代码，下载带上你的 vip 登录的 cookies，看看行不行，如果不行的话优酷的 vip 也要单独适配

**Comment by xkser** [comment]
嗯。使用cookies确实可以下载。但是cookie会失效。要是可以模拟用户登陆获取cookie就好了

**Comment by xkser** [comment]
好的。谢谢。能把把这个问题删除么？thanks
