### ISSUE TITLE
Site feature request - 8K video support for `bilibili.com`

### ISSUE THREAD

**Issue by c2xusnpq6** [iawia002/annie#977]
### Example URLs

https://www.bilibili.com/video/BV1KS4y197BN
https://www.bilibili.com/video/BV1Zr4y1Q75j

### Description

refer to: 
- https://github.com/yt-dlp/yt-dlp/issues/1878
- https://github.com/ytdl-org/youtube-dl/issues/30315
- https://github.com/yt-dlp/yt-dlp/issues/1898
- https://github.com/ytdl-org/youtube-dl/issues/30324

**Comment by LazzyFatty** [comment]
I have finished the code and created the pull request #978 . I am waiting for my code to be reviewed by iawia002.

**Comment by pukkandan** [comment]
What? why am I tagged here?

**Comment by LazzyFatty** [comment]
> > It appears anything above 1080p needs an account. Pass cookie and show verbose log of the format list (-F) @pukkandan
> 
> No. You don't.
> 
> Pick up 360p or 480p and you'll have this. There are all the details inside the request.
> 
> ![image](https://user-images.githubusercontent.com/75058881/144863366-64724eef-110e-45e0-9f14-8929243ad08e.png)
> 
> ![image](https://user-images.githubusercontent.com/75058881/144863975-7038d364-57f4-4d3b-8501-46393ea88f1d.png)
> 
> ![image](https://user-images.githubusercontent.com/75058881/144863012-ab3eb3aa-a474-4f17-9327-bcef123ac355.png)
> 
> That's from InPrivate Mode.☝🏼😁

I just verified your idea with Annie.
I put my own build of Annie.exe on my other computer. I never logged in to Bilibili on that computer, so Annie doesn't read the browser cookie with the login status either. then I managed to download the 8K video

**Comment by c2xusnpq6** [comment]
![image](https://user-images.githubusercontent.com/75058881/144880571-32456cf6-1d2f-459f-97ea-01ba96d8b6fe.png)

**Comment by c2xusnpq6** [comment]
@soimort https://github.com/soimort/you-get 👀
